<?php
/*=========================================================================
MIDAS Server
Copyright (c) Kitware SAS. 20 rue de la Villette. All rights reserved.
69328 Lyon, FRANCE.

See Copyright.txt for details.
This software is distributed WITHOUT ANY WARRANTY; without even
the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE.  See the above copyright notices for more information.
=========================================================================*/
?>
<link type="text/css" rel="stylesheet" href="<?php echo $this->coreWebroot?>/public/css/common/common.genericPage.css" />
<link type="text/css" rel="stylesheet" href="<?php echo $this->coreWebroot?>/public/css/item/item.view.css" />
<link type="text/css" rel="stylesheet" href="<?php echo $this->coreWebroot?>/public/css/common/common.browser.css" />

<?php
$this->headScript()->appendFile($this->coreWebroot.'/public/js/common/common.browser.js');
$this->headScript()->appendFile($this->webroot.'/modules/visualize/public/js/wrapper/wrapper.index.js');
?>
<div class="viewMain">
  <div class ="genericWrapperTopRight">

  </div>
</div>
<div class="viewSideBar">
  <?php
  if(count($this->sameLocation) > 1)
    {?>
  <div class='sideElementLast viewSameLocation' style='display:none;'>
    <h1><?php echo $this->t('In the same location')?></h1>
    <ul>
    <?php
    foreach($this->sameLocation as $item)
      {
      echo "<li>";
      echo "<a class='linkedcontentLink' preview='{$item->preview}' element='{$item->getKey()}' href='{$this->webroot}/item/{$item->getKey()}'>".$this->slicename($item->getName(), 45)."</a>";
      echo "</li>";
      }
    ?>
    </ul>
  </div>
  <?php
    }
    ?>
</div>
