<?php
/*=========================================================================
MIDAS Server
Copyright (c) Kitware SAS. 20 rue de la Villette. All rights reserved.
69328 Lyon, FRANCE.

See Copyright.txt for details.
This software is distributed WITHOUT ANY WARRANTY; without even
the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE.  See the above copyright notices for more information.
=========================================================================*/
?>
Translation: <?php echo $this->t("Hello world");?>
<br/>
<br/>
Module version (config file): <?php echo $this->version?>

<br/>
<br/>
Test Component (is image magick working): <?php echo $this->imageMagick[0]?>

<br/>
<br/>
Test Module Component: <?php echo $this->componentTest?>

<br/>
<br/>
Test Core Model and Dao: <?php echo $this->users->getFullName()?>

<br/>
<br/>
Test Module Model and Dao (Key): <?php echo $this->helloModel[0]->getKey()?>

<br/>
<br/>
Test Core Form: <?php echo (!empty($this->installForm)?'true':'false');?>

<br/>
<br/>
Test Module Form: <?php echo (!empty($this->indexForm)?'true':'false');?>

<br/>
<br/>
Test Public folder: <img src="<?php echo $this->moduleWebroot?>/public/images/test.png" alt="test"/>