<?php
/*=========================================================================
MIDAS Server
Copyright (c) Kitware SAS. 20 rue de la Villette. All rights reserved.
69328 Lyon, FRANCE.

See Copyright.txt for details.
This software is distributed WITHOUT ANY WARRANTY; without even
the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE.  See the above copyright notices for more information.
=========================================================================*/

$this->headScript()->appendFile($this->coreWebroot . '/public/js/jquery/jquery.form.js');
$this->headScript()->appendFile($this->apiWebroot.'/public/js/common/common.ajaxapi.js');
$this->headScript()->appendFile($this->moduleWebroot . '/public/js/config/config.index.js');
?>
<link type="text/css" rel="stylesheet" href="<?php echo $this->moduleWebroot?>/public/css/config/config.index.css" />
<link type="text/css" rel="stylesheet" href="<?php echo $this->coreWebroot?>/public/css/common/common.genericPage.css" />
<div class="viewMain">
     <div class ="genericWrapperTopRight">
         <?php
          echo '<div style="float:right;margin-right:2px;" class="genericBigButton ">';
            echo "<a  href='{$this->webroot}/admin#tabs-modules'><img style='float:left;margin-right:2px;' alt='' src='{$this->coreWebroot}/public/images/icons/back.png'/>";
            echo $this->t('Back');
            echo "</a>";
          echo '</div>';

        ?>
    </div>
    <h3>Requirements</h3>
    This module requires dcm2xml and storescp from <b>DCMTK</b> to implement a DICOM Store service (C-STORE) receiver.
    It also requires dcmqrscp and dcmqridx from <b>DCMTK</b> to implement DICOM Query/Retrieve services (C-FIND and C-MOVE).<br/>
    To install DCMTK: <a href="http://support.dcmtk.org/wiki/dcmtk/howto/start" target="_blank">http://support.dcmtk.org/wiki/dcmtk/howto/start</a><br/><br/>

    This module requires <b>Pydas</b> to upload DICOM files to Midas.<br/>
    To install Pydas: <a href="http://pydas.readthedocs.org/" target="_blank">http://pydas.readthedocs.org/</a><br/>

    <?php
      echo "
      <form class='genericForm' id='configForm' method='{$this->configForm['method']}'  action='{$this->configForm['action']}'>
      <h3>DICOM Server configuration:</h3>
            <div id='c-store_receiver'>
               <h4>DICOM Store service (C-STORE) receiver:</h4>
              <div>
                <label for='dcm2xml'>Command to run dcm2xml</label>
                {$this->configForm['dcm2xml']}
              </div>
              <br />
              <div >
                <label for='storescp'>Command to run storescp</label>
                {$this->configForm['storescp']}
              </div >
              <div >
                <label for='storescp_port'>C-STORE SCP (receiver) port</label>
                {$this->configForm['storescp_port']}
              </div >
              <div >
                <label for='storescp_study_timeout'>Storescp study_timeout (in seconds, idle period before receiving files from a study is considered complete)</label>
                {$this->configForm['storescp_study_timeout']}
              </div >
              <br />
              <br />
              <div id ='receptiondir'>
                <label for='receptiondir'>Reception directory (on local disk) for DICOM files</label>
                {$this->configForm['receptiondir']}
              </div>
              <br />
              <div>
                <label for='receptiondir'>Upload destination Midas folder</label>
                {$this->configForm['pydas_dest_folder']}
              </div>
            </div>
            <div id='c-find_c-move'>
              <h4>DICOM Query/Retrieve services (C-FIND and C-MOVE):</h4>
              <div>
                <label for='dcmqrscp'>Command to run dcmqrscp</label>
                {$this->configForm['dcmqrscp']}
              </div>
              <div>
                <label for='dcmqridx'>Command to run dcmqridx</label>
                {$this->configForm['dcmqridx']}
              </div>
              <div>
                <label for='dcmqrscp_port'>DICOM Query/Retrieve services port</label>
                {$this->configForm['dcmqrscp_port']}
              </div>
              <div>
                <label for='server_ae_title'>Server AE (Application Entity) Title</label>
                {$this->configForm['server_ae_title']}
              </div>
              <div id='peer_aes'>
              <br/>
                Peer AE (Application Entity) list allowed to use Query/Retrieve serices.</br>
                Each peer AE is defined as a 3-element tuple (3 comma-delimited elements enclosed in parentheses).
                These 3 elements are in the strict order as AETitle, HostName, PortNumber, and cannot be empty.</br>
                Different peer AEs are delimited with semicolons.
                Sample list: <b>(AE, localhost, 10001); (AE2, host2, 19530)</b>
              <br/>
              <br/>
                {$this->configForm['peer_aes']}
              </div>
            </div>
            <br/>
            <div>
              {$this->configForm['submitConfig']}
            </div>
       </form>";
       ?>

    <h3>Use this dashboard to verify current configuration:</h3>
    <?php
    echo "<table>";
    foreach($this->dashboard as $name => $status)
      {
      echo "<tr>";
      echo "  <td>$name </td>";
      if($status[0])
        {
        echo "  <td><img src='{$this->coreWebroot}/public/images/icons/ok.png' /></td>";
        }
      else
        {
        echo "  <td><img src='{$this->coreWebroot}/public/images/icons/nok.png' /></td>";
        }
      if(isset($status[1]))
        {
        echo "  <td>$status[1]</td>";
        }
      echo "</tr>";
      }
    echo "</table>";
    ?>

    <h3>Start/Stop DICOM server:</h3>
    Please restart DICOM server after each configuration change.
    <div>
      <div style="margin-right:10px;" class="genericBigButton " id="startServer">Start</div>
      <div style="margin-right:10px;" class="genericBigButton " id="stopServer">Stop</div>
      <div style="margin-right:10px;">
        <h3>Status:
          <span class="running_status" id="running_status" style="display:none">Running</span>
          <span class="only_storescp_running_status" id="only_storescp_running_status" style="display:none">C-STORE receiver is Running, but Query/Retrieve services are NOT Running</span>
          <span class="only_dcmqrscp_running_status" id="only_dcmqrscp_running_status" style="display:none">Query/Retrieve services are Running, but C-STORE receiver is NOT Running</span>
          <span class="not_running_status" id="not_running_status" style="display:none">Not Running</span>
          <span class="not_supported_status" id="not_supported_status" style="display:none">This module is currently not supported in Windows</span>
        </h3>
      </div>
      <div id="start_server_user" class="start_server_user" style="display:none">
         Midas user who started DICOM server: <span id="span_start_server_user"></span>
      </div>
      <br/>
      <div style="margin-right:10px;display:none" class="genericBigButton " id="hideError">Hide Error</div>
      <div id="apicall_failure" class="apicall_failure" style="display:none">
         <textarea id="apicall_failure_reason" rows="5" cols="80" readonly> </textarea>
      </div>
    </div>
    <div class="manualCommandsWrapper" id="manualCommandsWrapper"  style="display: none">
    In some platforms, the above start/stop buttons may not work because the web server user is lack of permissions. The following commands can be used to start/stop DICOM server in command line.
    <h3 class="sectionHeader"><a href="#">Start/Stop DICOM server in command line</a></h3>
    <ul>
      <li>
        Before start/stop DICOM server in command line, make sure the user to run the command:
      </li>
      <li>
        1) has permission to run this command: <span class="set_bold" id="dcm2xml_command"/>
      </li>
      <li>
        2) has permission to run this command: <span class="set_bold" id="storescp_command"/>
      </li>
      <li>
        3) has permission to run this command: <span class="set_bold" id="dcmqrscp_command"/>
      </li>
      <li>
        4) has permission to run this command: <span class="set_bold" id="dcmqridx_command"/>
      </li>
      <li>
        5) has write permission to this directory: <span class="set_bold" id="reception_dir"/>
      </li>
      <li>
       If all above requirements are met, copy/paste the following commands (the leading and trailing quotes are not needed) to start/stop DICOM server in command line.
       <span class="set_bold">Refresh the page to show the current running status if the DICOM server is started/stopped in command line.</span>
      </li>
      <li class="manual_start">
        <span class="set_bold" >Start DICOM server:</span> <br/>
        <span id="manual_start"></span>
      </li>
      <li class="manual_stop">
        <span class="set_bold">Stop DICOM server:</span> <br/>
        <span id="manual_stop"></span>
      </li>
    </ul>
  </div>

</div>
