<?php
/*=========================================================================
 Midas Server
 Copyright Kitware SAS, 26 rue Louis Guérin, 69100 Villeurbanne, France.
 All rights reserved.
 For more information visit http://www.kitware.com/.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

         http://www.apache.org/licenses/LICENSE-2.0.txt

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
=========================================================================*/

if (isset($this->errormessage)) {
    echo $this->escape($this->errormessage);
}
if (isset($this->statusmessage)) {
    echo $this->escape($this->statusmessage);
}
?>

<link type="text/css" rel="stylesheet"
      href="<?php echo $this->coreWebroot ?>/public/css/jquery/jquery.cluetip.min.css"/>
<div class="genericWrapperTopRight">
    <?php
    echo '<div style="margin-right:2px;" class="genericBigButton ">';
    echo "<a  href='{$this->webroot}/admin#tabs-assetstore'><img style='float:left;margin-right:2px;' alt='' src='{$this->coreWebroot}/public/images/icons/back.png'/>";
    echo $this->t('Back');
    echo "</a>";
    echo '</div>';

    ?>
</div>
<br/>
<?php
$this->headScript()->appendFile($this->coreWebroot.'/public/js/import/import.index.js');
$this->headScript()->appendFile($this->coreWebroot.'/public/js/jquery/jquery.form.js');
$this->headScript()->appendFile($this->coreWebroot.'/public/js/jquery/jquery.cluetip.js');

$this->headLink()->appendStylesheet($this->coreWebroot.'/public/css/jquery/jquery.filetree.min.css');
$this->headLink()->appendStylesheet($this->coreWebroot.'/public/css/import/import.index.css');
$this->headLink()->appendStylesheet($this->coreWebroot.'/public/css/assetstore/assetstore.add.css');

echo $this->importForm;
?>

<div id="progress" style="display:none"></div>
<div id="progress_status"></div>

<?php echo $this->element(
    'serversidefilechooser',
    array(
        'id' => 'inputdirectorybutton',
        'fileFilterErrorMsg' => 'Select the local XML directory on the server',
        'destSelector' => '#inputdirectory',
    )
)
?>

<div id="newassetstore-form" style="display:none">
    <?php echo $this->assetstoreForm; ?>
</div>

<script language="javascript">
    var midas = midas || {};
    midas.import = midas.import || {};
    midas.import.assetstores = '<?php echo str_replace('\\', '\\\\', JsonComponent::encode($this->assetstores)); ?>';
</script>
