<?php 
/*=========================================================================
MIDAS Server
Copyright (c) Kitware SAS. 20 rue de la Villette. All rights reserved.
69328 Lyon, FRANCE.

See Copyright.txt for details.
This software is distributed WITHOUT ANY WARRANTY; without even
the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE.  See the above copyright notices for more information.
=========================================================================*/
echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
  <head>

    <!-- Meta -->
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <title><?= $this->title ?></title>
    <!-- Import CSS -->
    <link rel="shortcut icon" href="<?php echo $this->coreWebroot ?>/public/images/icons/favicon.ico" />
    <?php
    if (Zend_Registry::get("configGlobal")->smartoptimizer == 1)
      {
      echo '<link type="text/css" rel="stylesheet" href="' . $this->coreWebroot . '/public/css/layout/main.css,view.css,jquery-ui.css,form.css,loginForm.css,jquery.treeTable.css,jquery.cluetip.css" />';
      }
    else
      {
      echo '<link type="text/css" rel="stylesheet" href="' . $this->coreWebroot . '/public/css/layout/main.css" />';
      echo '<link type="text/css" rel="stylesheet" href="' . $this->coreWebroot . '/public/css/layout/jquery.cluetip.css" />';
      echo '<link type="text/css" rel="stylesheet" href="' . $this->coreWebroot . '/public/css/layout/view.css" />';
      echo '<link type="text/css" rel="stylesheet" href="' . $this->coreWebroot . '/public/css/layout/jquery-ui.css" />';
      echo '<link type="text/css" rel="stylesheet" href="' . $this->coreWebroot . '/public/css/layout/form.css" />';
      echo '<link type="text/css" rel="stylesheet" href="' . $this->coreWebroot . '/public/css/layout/loginForm.css" />';
      echo '<link type="text/css" rel="stylesheet" href="' . $this->coreWebroot . '/public/css/layout/jquery.treeTable.css" />';
      }
    ?>
    <!--[if IE]>
      <?php echo  '<link type="text/css" rel="stylesheet" href="' . $this->coreWebroot . '/public/css/layout/mainIE.css" />';?>
      <?php echo '<script type="text/javascript" src="' . $this->coreWebroot . '/public/js/layout/roundCornerIE.js"></script>';?>
    <![endif]-->
    <?php echo $this->headLink();  // import the css ?>
    <?php echo $this->headStyle(); // import the css ?>
    
  </head>
  <body>
    <div class="MainDialog" style="display:none;">
      <div class="MainDialogContent">
      </div>
      <div class="MainDialogLoading">
        <img alt="" src="<?php echo  $this->coreWebroot?>/public/images/icons/loading.gif" />
      </div>
      <input type="hidden" class="DialogContentPage"/>
    </div>
    <div class="TopDynamicBar">
      <div class="TopDynamicClose">
        <a class="closeButton" href="#" ><span><?php echo $this->t('Close');?></span><img alt="" src="<?php echo $this->coreWebroot?>/public/images/icons/close.png"/> </a>
      </div>
      <div class="TopDynamicContent">
      </div>
      <div class="TopDynamicLoading">
        <img alt="" src="<?php echo  $this->coreWebroot?>/public/images/icons/loading.gif" />
      </div>
      <input type="hidden" class="DynamicContentPage"/>
    </div>
    <div class="Topbar">
      <div class="TopbarContent">
        <div class="TopbarLeft">
          <ul>
            <li class="first">
              <a href="http://www.kitware.com/products/midas.html" >MIDAS</a>
            </li>
            <li>
              <a href="http://www.kitware.com" >Kitware</a>
            </li>
          </ul>
        </div>
        <div class="TopbarRight">
          <ul>
            <li class="first">
              <?php
              if($this->logged&&isset($this->userDao))
                {
                echo '
                   <b><a id="topUserName" href="'.$this->webroot.'/user/'.$this->userDao->getUserId().'" >'.$this->userDao->getFullName().' <img class="arrowUser" src="'.$this->coreWebroot.'/public/images/icons/arrow-user.gif" alt ="" /> </a> </b>
                    <ul>
                      <li onclick="location.replace(\''.$this->webroot.'/user/userpage\');"><a>'.$this->t('My Page').'</a></li>
                      <li class="myAccountLink"><a>'.$this->t('My Account').'</a></li>
                      ';
                if($this->userDao->isAdmin())
                  {
                  echo '
                      <li onclick="location.replace(\''.$this->webroot.'/admin\');"><a>'.$this->t('Administration').'</a></li>';
                  }
                echo '
                    </ul>
                   ';
                }
              else
                {
                echo '<b><a class="loginLink" href="#" >'.$this->t('Login').'</a></b>';
                }
                ?>              
            </li>
            <li>
              <?php
              if($this->logged)
                {
                echo '<a  href="'.$this->webroot.'/user/logout" > '.$this->t('Logout').'</a>';
                }
              else
                {
                echo '<a class="registerLink" href="#" > '.$this->t('Register').'</a>';
                }
                ?>  
            </li>
            <li>
              <a href="#" > <?= $this->t('Help') ?></a>
            </li>
            <li>
              <?php if($this->lang=='fr')
                {
                echo '<a href="'.$this->webroot.'?lang=en"><img src="'.$this->coreWebroot.'/public/images/icons/english.png" alt="English"/>';
                }
              else
                {
                echo '<a href="'.$this->webroot.'?lang=fr"><img src="'.$this->coreWebroot.'/public/images/icons/french.png" alt="French"/>';
                }
                ?>
              </a>
            </li>
          </ul>
        </div>
      </div>
    </div>
    <div class="Header">
      <div class="HeaderContent">
        Hello Plugin !!!
        <div class="HeaderLogo" onclick="window.location='<?php echo $this->webroot?>';">
        </div>
        <div class="HeaderSearch">
          <input type="text" id="live_search" value="<?= $this->t('Jump to a data, folder...') ?>" autocomplete="off" autocorrect="off" autocapitalize="off" />
          <input type="hidden" id="live_search_value" value="init"  />
          <div id="searchloading" style="display:none"></div>
       </div>
        <div class="HeaderAction">
          <ul>
            <li class="uploadFile" title="Upload" rel="<?php echo $this->webroot?>/upload/simpleupload">
              <a href="#"><img src="<?= $this->coreWebroot ?>/public/images/icons/addfile.png" alt="Upload a file"/>
                Upload
              </a>
            </li>
          </ul>
        <div class="viewNotice"></div>
        </div>
      </div>
    </div>
    
    <div class="Wrapper">
      <?php
      if($this->needUpgrade)
        {
        echo '<span style="color:red;">MIDAS need to be upgraded. <a href="'.$this->webroot.'/admin/#ui-tabs-1">Upgrade</a></span><br/><br/>';
        }
      ?>
      <div class=SubWrapper">

        <div class="MainContent">
          <div class="SideBar">
            <ul>
              <li <?php if($this->activemenu=='feed') {echo 'class="active"';} ?> onclick="location.replace('<?php echo $this->webroot?>/feed');" ><a href="<?php echo $this->webroot?>/feed"><img alt="" src="<?php echo $this->coreWebroot?>/public/images/icons/feed.png" /><span> <?php echo $this->t('Feed');?></span></a></li>
              <li <?php if($this->activemenu=='browse') {echo 'class="active"';} ?> onclick="location.replace('<?php echo $this->webroot?>/browse');" ><a href="<?php echo $this->webroot?>/browse"><img alt="" src="<?php echo $this->coreWebroot?>/public/images/icons/data.png" /><span> <?php echo $this->t('Data');?></span></a></li>
              <li <?php if($this->activemenu=='community') {echo 'class="active"';} ?> onclick="location.replace('<?php echo $this->webroot?>/community');" ><a href="<?php echo $this->webroot?>/community"><img alt="" src="<?php echo $this->coreWebroot?>/public/images/icons/community.png" /><span> <?php echo $this->t('Communities');?></span></a></li>
              <li id="menuUserInfo" <?php if($this->activemenu=='user') {echo 'class="active"';} ?>  ><a href="javascript:;"><img alt="" src="<?php echo $this->coreWebroot?>/public/images/icons/upload.png" /><span> <?php echo $this->t('My Uploads');?></span></a></li>
            </ul>
            <hr/>
            <?php
            if(isset($this->recentItems)&&!empty($this->recentItems))
              {
              echo "<h1>{$this->t('Recently Viewed')}</h1>";
              $recentReverse=array_reverse($this->recentItems);
              echo '<ul>';
              foreach ($recentReverse as $item)
                {
                if(is_array($item))
                  {
                  echo "<li onclick=\"location.replace('{$this->webroot}/item/{$item['item_id']}');\" class='recentItem' title='".  str_replace("'", '"', $item['name'])." | todo'><a  href='{$this->webroot}/item/{$item['item_id']}'>".$this->slicename($item['name'],20)."</a></li>";
                  }                  
                }
              echo '</ul>';
              }
            ?>
          </div>
          <div class="SubMainContent">
            <?php
            if (isset($this->header))
              {
              echo "<div class='viewHeader'>{$this->header} </div>";
              }
            ?>
            
            <div class="viewWrapper">
              <!-- Content -->
              <?php echo $this->layout()->content ?>
              <!-- End Content -->
          
            </div>    
            <div class="clear"/>
          </div>
        </div>
        <div class="Footer"><a href="http://www.kitware.com/products/midas.html">MIDAS</a> <?php echo $this->version ?> by <a href="http://www.kitware.com">Kitware</a> © <?php echo date("Y") ?> -
         <?php
         echo $this->t('Generated in').' '.$this->generatedTimer." ms";
         ?>
        </div>
      </div>
      <hr style="display: none;"/>
    </div> 
    <?php
              if (Zend_Registry::get("configGlobal")->smartoptimizer == 1)
                {
                echo '<script type="text/javascript" src="' . $this->coreWebroot . '/public/js/layout/jquery.js,jquery-ui.js,main.js,jquery.treeTable.js,jquery.cluetip.js"></script>';
                }
              else
                {
                echo '<script type="text/javascript" src="' . $this->coreWebroot . '/public/js/layout/jquery.js"></script>';
                echo '<script type="text/javascript" src="' . $this->coreWebroot . '/public/js/layout/jquery.cluetip.js"></script>';
                echo '<script type="text/javascript" src="' . $this->coreWebroot . '/public/js/layout/jquery-ui.js"></script>';
                echo '<script type="text/javascript" src="' . $this->coreWebroot . '/public/js/layout/main.js"></script>';
                echo '<script type="text/javascript" src="' . $this->coreWebroot . '/public/js/layout/jquery.treeTable.js"></script>';
                }
    ?>
    <?php echo $this->headScript() ?>
    <input type="hidden" class="webroot" value="<?php echo $this->webroot?>" />
    <div style="display: none;" class="jsonContent">
      <?php echo $this->json?>
    </div>
  </body>
</html>