<?php
/*=========================================================================
 MIDAS Server
 Copyright (c) Kitware SAS. 26 rue Louis Guérin. 69100 Villeurbanne, FRANCE
 All rights reserved.
 More information http://www.kitware.com

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

         http://www.apache.org/licenses/LICENSE-2.0.txt

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
=========================================================================*/

$this->declareVars('coreWebroot', 'form', 'hDefaultQuota', 'hFreeSpace', 'hQuota', 'hUsedSpace', 'isAdmin', 'moduleWebroot', 'quota', 'usedSpace');
?>
<script type="text/javascript" src="<?php echo $this->coreWebroot; ?>/public/js/jquery/jquery.form.js"></script>
<script type="text/javascript" src="<?php echo $this->coreWebroot; ?>/public/js/jquery/jquery.jqplot.min.js"></script>
<script type="text/javascript" src="<?php echo $this->coreWebroot; ?>/public/js/jquery/jqplot/jqplot.pieRenderer.min.js"></script>
<script type="text/javascript" src="<?php echo $this->moduleWebroot; ?>/public/js/folder/folder.index.js"></script>
<link type="text/css" rel="stylesheet" href="<?php echo $this->moduleWebroot; ?>/public/css/folder/folder.index.css" />
<link type="text/css" rel="stylesheet" href="<?php echo $this->coreWebroot; ?>/public/css/common/common.genericPage.css" />
<link type="text/css" rel="stylesheet" href="<?php echo $this->coreWebroot; ?>/public/css/jquery/jquery.jqplot.min.css" />
<span><?php echo $this->t('Current used space:'); ?> <span id="hUsedSpaceValue"><?php echo $this->escape($this->hUsedSpace); ?></span></span>
<br />
<span><?php echo $this->t('Total space:'); ?> <span id="hQuotaValue"><?php echo $this->escape($this->hQuota); ?></span></span>
<br />
<span id="hFreeSpaceValue"><?php echo $this->escape($this->hFreeSpace); ?></span>
<span id="quotaValue"><?php echo $this->escape($this->quota); ?></span>
<span id="usedSpaceValue"><?php echo $this->escape($this->usedSpace); ?></span>
<div id="quotaChart"></div>
<?php
if ($this->isAdmin) {
    echo $this->form;
    ?>
    <br />
    <span><?php echo $this->t('Default quota:'); ?> <span id="hDefaultQuotaValue"><?php echo $this->escape($this->hDefaultQuota); ?></span></span>
<?php
}
