<?php
/*=========================================================================
 MIDAS Server
 Copyright (c) Kitware SAS. 26 rue Louis Guérin. 69100 Villeurbanne, FRANCE
 All rights reserved.
 More information http://www.kitware.com

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

         http://www.apache.org/licenses/LICENSE-2.0.txt

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
=========================================================================*/

$this->headScript()->appendFile($this->coreWebroot.'/public/js/jquery/jquery.form.js');
$this->headScript()->appendFile($this->moduleWebroot.'/public/js/config/config.index.js');
?>
<link type="text/css" rel="stylesheet" href="<?php echo $this->moduleWebroot ?>/public/css/config/config.index.css"/>
<link type="text/css" rel="stylesheet"
      href="<?php echo $this->coreWebroot ?>/public/css/common/common.genericPage.css"/>

<div class="viewMain">
    <h3>ParaViewWeb 2.0 Configuration</h3>

    <p>For this module to work, you will need to build ParaView with python enabled.</p>

    <p>Instructions are
        <a href="http://www.paraview.org/Wiki/ParaView:Build_And_Install#Build_ParaView">here</a>.
    </p>

    <p><b>Note:</b> You can turn off building with Qt when building ParaView.
    </p>

    <p><b>Important:</b> Make sure to symlink the
        <b>www</b> directory of your ParaView build
        directory as <b>modules/pvw/public/import</b>.</p>

    <form class='genericForm' id='configForm' method="<?php echo $this->configForm['method'] ?>"
          action="<?php echo $this->configForm['action'] ?>">
        <div qtip="Location of the pvpython executable on the filesystem">
            <label for='pvpython'>Location of pvpython</label>
            <?php echo $this->configForm['pvpython'] ?>
        </div>
        <div qtip="Comma separated list or range of ports (e.g. '9000, 9001' or '9000-9005') to use for ParaView instances.
               This setting also defines how many instances can be active at a time.">
            <label for='ports'>Ports</label>
            <?php echo $this->configForm['ports'] ?>
        </div>
        <div qtip="If the DISPLAY env var should be set when running ParaViewWeb, set its contents here.
               You may need to run <b>xhost +www-data@localhost</b> to allow Midas to connect to the X server.">
            <label for='displayEnv'>DISPLAY env var</label>
            <?php echo $this->configForm['displayEnv'] ?>
        </div>
        <div class="submitContainer">
            <?php echo $this->configForm['submitConfig'] ?>
        </div>
    </form>

</div>
