<?php
/*=========================================================================
MIDAS Server
Copyright (c) Kitware SAS. 20 rue de la Villette. All rights reserved.
69328 Lyon, FRANCE.

See Copyright.txt for details.
This software is distributed WITHOUT ANY WARRANTY; without even
the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE.  See the above copyright notices for more information.
=========================================================================*/

$this->headScript()->appendFile($this->coreWebroot.'/public/js/jquery/jquery.form.js');
$this->headScript()->appendFile($this->moduleWebroot.'/public/js/config/config.index.js');
?>
<link type="text/css" rel="stylesheet" href="<?php echo $this->moduleWebroot?>/public/css/config/config.index.css" />
<link type="text/css" rel="stylesheet" href="<?php echo $this->coreWebroot?>/public/css/common/common.genericPage.css" />

<div class="viewMain">
  <h3>ParaViewWeb 2.0 Configuration</h3>
  <p>For this module to work, you will need to build ParaView with python enabled.</p>
  <p>Instructions are <a href="http://paraview.org/Wiki/ParaView:Build_And_Install#Build_ParaView">here</a>.</p>
  <p><b>Note:</b> You can turn off building with Qt when building ParaView.</p>
  <p><b>Important:</b> Make sure to symlink the <b>www</b> directory of your ParaView build
    directory as <b>modules/pvw/public/import</b>.</p>
  <form class='genericForm' id='configForm' method="<?php echo $this->configForm['method']?>" action="<?php echo $this->configForm['action']?>">
    <div qtip="Location of the pvpython executable on the filesystem">
      <label for='pvpython'>Location of pvpython</label>
      <?php echo $this->configForm['pvpython']?>
    </div>
    <div qtip="Comma separated list or range of ports (e.g. '9000, 9001' or '9000-9005') to use for ParaView instances.
               This setting also defines how many instances can be active at a time.">
      <label for='ports'>Ports</label>
      <?php echo $this->configForm['ports']?>
    </div>
    <div class="submitContainer">
      <?php echo $this->configForm['submitConfig']?>
    </div>
  </form>

</div>
