<?php
/*=========================================================================
 MIDAS Server
 Copyright (c) Kitware SAS. 26 rue Louis Guérin. 69100 Villeurbanne, FRANCE
 All rights reserved.
 More information http://www.kitware.com

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

         http://www.apache.org/licenses/LICENSE-2.0.txt

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
=========================================================================*/
?>
<script type="text/javascript" src="<?php echo $this->moduleWebroot?>/public/js/config/config.status.js"></script>
<link type="text/css" rel="stylesheet" href="<?php echo $this->moduleWebroot?>/public/css/config/config.status.css" />

<div class="viewMain">
  <h3>ParaViewWeb instance list</h3>
  <?php if(count($this->instances) == 0)
    {
    echo 'There are no instances in the database at this time';
    }
  else
    { ?>
    <table class="instances">
      <thead>
        <tr><th>Id</th><th>Port</th><th>PID</th><th>Created</th><th>Status</th><th>Actions</th></tr>
      </thead>
      <tbody>
        <?php
        foreach($this->instances as $row)
          {
          $instance = $row['dao'];
          $status = $row['status'];
          echo '<tr key="'.$instance->getKey().'"><td>'.$instance->getKey().'</td><td>'.$instance->getPort().
               '</td><td>'.$instance->getPid().'</td><td>'.$instance->getCreationDate().
               '</td><td>'.($status ? '<span class="running">Running</span>' :
                                      '<span class="dead">Dead</span>');

          echo '</td><td><img qtip="Kill instance" alt="" class="killInstance" key="'.$instance->getKey().
               '" src="'.$this->coreWebroot.'/public/images/icons/close.png"/></td></tr>';
          }
        ?>
      </tbody>
    </table>
  <?php
    } ?>
</div>
