<?php
/*=========================================================================
 MIDAS Server
 Copyright (c) Kitware SAS. 26 rue Louis Guérin. 69100 Villeurbanne, FRANCE
 All rights reserved.
 More information http://www.kitware.com

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

         http://www.apache.org/licenses/LICENSE-2.0.txt

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
=========================================================================*/

/** display community agreement for users to read and accept */
echo '<script type="text/javascript" src="'.$this->moduleWebroot.'/public/js/community/community.agreementdialog.js"></script>';
?>
<link type="text/css" rel="stylesheet"
      href="<?php echo $this->moduleWebroot ?>/public/css/community/community.agreementdialog.css"/>

<div class="agreementContainer">
    <div class="agreementWarning">
        <img alt="" src="<?php echo $this->coreWebroot ?>/public/images/icons/warning.png"/>
        You must agree to the following terms before you can become a member of this community.
    </div>

    <div class="licenseDisplay">
        <?php echo $this->t(nl2br($this->agreementDao->getAgreement())); ?>
    </div>

    <input type="checkbox" id="agreementAccepted">I have read and agree to the above terms</input>
    <div class="agreementButtons">
        <form class="genericForm">
            <input type="button" id="confirmAgreement" value="Accept" disabled="disabled"/>
            <input type="button" id="declineAgreement" style="margin-left: 10px;" value="Cancel"/>
        </form>
        <div>

        </div>
