<?php
/*=========================================================================
 MIDAS Server
 Copyright (c) Kitware SAS. 26 rue Louis Guérin. 69100 Villeurbanne, FRANCE
 All rights reserved.
 More information http://www.kitware.com

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

         http://www.apache.org/licenses/LICENSE-2.0.txt

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
=========================================================================*/

echo '<script type="text/javascript" src="'.$this->coreWebroot.'/public/js/apikey/apikey.usertab.js"></script>';
?>
<h3>REST Web API</h3>
<p><b>Base URL:</b> <a href="<?php echo $this->serverURL.$this->webroot; ?>/rest"><?php echo $this->serverURL.$this->webroot; ?>/rest</a></p>

<h3><?php echo $this->t('Generated API Keys') ?></h3>
<?php if (count($this->userapiDaos) == 0) {
    echo "You do not have any API keys.<br/>";
} else {
    ?>
    <table width="100%" border="0">
        <tr bgcolor="#999999">
            <th><?php echo $this->t('Application Name') ?></th>
            <th>API Key</th>
            <th><?php echo $this->t('Default Expiration') ?></th>
            <th>Creation</th>
            <th>Action</th>
        </tr>
        <?php
        foreach ($this->userapiDaos as $userapiDao) {
            ?>
            <tr>
                <td><?php echo $this->escape($userapiDao->getApplicationName()); ?></td>
                <td><?php echo $this->escape($userapiDao->getApikey()); ?></td>
                <td><?php echo $this->escape($userapiDao->getTokenExpirationTime()); ?> minutes</td>
                <td><?php echo $this->dateago($userapiDao->getCreationDate()); ?></td>
                <td>
                    <a style='text-decoration: underline;' class='deleteApiKeyLink'
                       element='<?php echo $this->escape($userapiDao->getKey()); ?>'><?php echo $this->t('delete') ?></a>
                </td>
            </tr>
        <?php
        }
        ?>
    </table>
<?php
}
?>

<br />

<h3><?php echo $this->t('Generate New API Key') ?></h3>

<form class="genericForm" id="generateKeyForm" method="<?php echo $this->form['method']; ?>"
      action="<?php echo $this->form['action']; ?>">
    <input type="hidden" id="apiUserId" name="userId" value="<?php echo $this->escape($this->user->getKey()); ?>"/>

    <div>
        <label for="appplication_name"><?php echo $this->t('Application Name'); ?>:</label>
        <?php echo $this->form['appplication_name']; ?>
    </div>
    <div>
        <label for="expiration"><?php echo $this->t('Default Expiration'); ?> (minutes):</label>
        <?php echo $this->form['expiration']; ?>
    </div>
    <div>
        <?php echo $this->form['createAPIKey']; ?>
    </div>
</form>
