<?php
  $this->headScript()->appendFile($this->webroot.'/public/js/browse/browse.index.js');
  $this->headScript()->appendFile($this->webroot.'/public/js/common/common.browser.js');
?>
<div class="viewMain">
  <img class="tableLoading" alt="" src="<?php echo $this->webroot?>/public/images/icons/loading.gif"/>
  <table id="browseTable" class="midasTree">
    <thead>
      <tr>
        <th class="thData">Data</th>
        <th class="thSize">Size</th>
        <th class="thDate">Date</th>
      </tr>
    </thead>
    <tbody>
      <?php
      $node=1;
      foreach($this->communities as $community)
        {
        $folder=$community->getFolder();
        echo "<tr id='node--$node' class='parent' type='community' element='{$community->getCommunityId()}' ajax='{$folder->getFolderId()}'>";
        echo "  <td><span class='community'>{$community->getName()}</span></td>";
        echo "  <td><span>Test</span></td>";
        echo "  <td><span>Test</span></td>";
        echo "</tr>";
        $node++;
        }  
      ?>          
       
    </tbody>
  </table>
</div>
<div class="viewSideBar">
  <div class="sideElementFirst viewAction">
    <h1>Actions</h1>
    <ul>
      <li>
        
      </li>
    </ul>
  </div>
  <div class="sideElementLast viewInfo">
    <h1>Info</h1>    
    <img class="infoLoading" style="display:none;" alt="" src="<?php echo $this->webroot?>/public/images/icons/loading.gif"/>
    <div class="ajaxInfoElement">
    </div>
  </div>
</div>




