<?php
  $this->headScript()->appendFile($this->webroot.'/public/js/browse/browse.index.js');
  $this->headScript()->appendFile($this->webroot.'/public/js/common/common.browser.js');
?>


<link type="text/css" rel="stylesheet" href="<?php echo $this->webroot?>/public/css/common/common.browser.css" />
<link type="text/css" rel="stylesheet" href="<?php echo $this->webroot?>/public/css/browse/browse.index.css" />
<div class="viewMain">
  <img class="tableLoading" alt="" src="<?php echo $this->webroot?>/public/images/icons/loading.gif"/>
  <table id="browseTable" class="midasTree">
    <thead>
      <tr>
        <th class="thData"><?php echo $this->t('Name');?></th>
        <th class="thSize"><?php echo $this->t('Size');?></th>
        <th class="thDate"><?php echo $this->t('Modified');?></th>
        <th class="thCheckbox"></th>
      </tr>
    </thead>
    <tbody>
      <?php
      $node=1;
      foreach($this->communities as $community)
        {
        $folder=$community->getFolder();
        echo "<tr id='node--$node' class='parent' type='community' element='{$community->getCommunityId()}' ajax='{$folder->getFolderId()}'>";
        echo "  <td class='treeBrowseElement'><span class='community'>{$community->getName()}</span></td>";
        echo "  <td><img class='folderLoading'  element='{$folder->getFolderId()}' alt='' src='{$this->webroot}/public/images/icons/loading.gif'/></td>";
        echo "  <td>{$this->Date->ago($folder->getDate(),true)}</td>";
        echo "  <td><input type='checkbox' class='treeCheckbox' type='community' element='{$community->getCommunityId()}' /></td>";
        echo "</tr>";
        $node++;
        }  
      ?>        
    </tbody>
  </table>
</div>
<div class="viewSideBar">
  <div class="sideElementFirst viewAction" >
    <h1>Actions</h1>
    <ul>
      <li>
        
      </li>
    </ul>
  </div>
  <div class="sideElement viewSelected" >
    <h1><?php echo $this->t('Selected')?></h1>
    <span></span>
  </div>
  <div class="sideElementLast viewInfo" >
    <h1>Info</h1>    
    <img class="infoLoading" style="display:none;" alt="" src="<?php echo $this->webroot?>/public/images/icons/loading.gif"/>
    <div class="ajaxInfoElement">
    </div>
  </div>
  
  
  <div class="defaultSide" >
    BlaBla
    <br/>  
      <?php
    if(!empty($this->notifications))
      {
      echo   "<div class='sideElementFirst feedNotification'>
                <h1>Notifications</h1>
              </div>";
      }
      ?>
    <?php 
    if(!empty($this->itemThumbnails))
      {
      echo '<div class="'.(empty($this->notifications)?'sideElementFirst':'sideElement').' feedThumbnail">';
      echo '<h1>Thumbnails</h1>';
      foreach($this->itemThumbnails as $item)
        {
        echo "<a href='{$this->webroot}/item/{$item->getKey()}'>";
        echo "<img src='{$this->webroot}/{$item->getThumbnail()}' alt=''/>"; 
        echo "</a>";
        }
      echo '</div>';
      }
      ?>
    <div class="sideElementLast feedStats">
      <h1>Stats</h1>
      <?php
      echo "<ul>";
      echo "  <li>{$this->nUsers} user".(($this->nUsers>1)?'s':'')."</li>";
      echo "  <li>{$this->nCommunities} ".(($this->nCommunities>1)?'communities':'community')."</li>";
      echo "  <li>{$this->nItems} item".(($this->nItems>1)?'s':'')."</li>";
      echo "</ul>";
      ?>
    </div>
  </div>
</div>




