<?php
  $this->headScript()->appendFile($this->webroot.'/public/js/user/user.userpage.js');
?>
<div class="viewMain">
  <? echo $this->element('Feed'); ?>
  <img class="tableLoading" alt="" src="<?php echo $this->webroot?>/public/images/icons/loading.gif"/>
  <table id="browseTable" class="midasTree">
    <thead>
      <tr>
        <th class="thData">Data</th>
        <th class="thSize">Size</th>
        <th class="thDate">Date</th>
      </tr>
    </thead>
    <tbody>
      <?php
      $node=1;
  
      foreach($this->items as $item)
        {
        echo "<tr id='node--$node'  type='file' element='{$item->getKey()}' >";
        echo "  <td><span class='file'>{$item->getName()}</span></td>";
        echo "  <td><span>Test</span></td>";
        echo "  <td><span>Test</span></td>";
        echo "</tr>";
        $node++;
        }
      ?>          
       
    </tbody>
  </table>
</div>
<div class="viewSideBar">
  <div class="viewAction">
  </div>
</div>




