<?php
/*=========================================================================
 Midas Server
 Copyright Kitware SAS, 26 rue Louis Guérin, 69100 Villeurbanne, France.
 All rights reserved.
 For more information visit http://www.kitware.com/.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

         http://www.apache.org/licenses/LICENSE-2.0.txt

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
=========================================================================*/

echo $this->doctype().PHP_EOL;
?>
<html lang="en" xml:lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <?php
    $this->headMeta()->appendHttpEquiv('Content-Type', 'text/html; charset=UTF-8');
    echo $this->headMeta().PHP_EOL;

    $this->headTitle('Login');
    $this->headTitle()->setSeparator(' - ');
    echo $this->headTitle().PHP_EOL;

    $this->headLink()->appendStylesheet($this->baseUrl('core/public/css/layout/jquery-ui.min.css'));
    $this->headLink()->appendStylesheet($this->baseUrl('modules/oauth/public/css/authorize/authorize.index.css'));
    $this->headLink()->appendStylesheet($this->baseUrl('modules/oauth/public/css/bootstrap/bootstrap.min.css'));
    $this->headLink()->headLink(array('rel' => 'apple-touch-icon', 'href' => $this->baseUrl('apple-touch-icon-120x120.png'), 'sizes' => '60x60 120x120', 'APPEND'));
    $this->headLink()->headLink(array('rel' => 'apple-touch-icon', 'href' => $this->baseUrl('apple-touch-icon-152x152.png'), 'sizes' => '76x76 152x152', 'APPEND'));
    $this->headLink()->headLink(array('rel' => 'icon', 'href' => $this->baseUrl('favicon.ico'), 'APPEND'));
    echo $this->headLink().PHP_EOL;

    $this->headScript()->prependFile($this->baseUrl('modules/oauth/public/js/authorize//authorize.index.js'));
    $this->headScript()->prependFile($this->baseUrl('core/public/js/jquery/jquery.form.js'));
    $this->headScript()->prependFile($this->baseUrl('core/public/js/layout/jquery.js'));
    echo $this->headScript().PHP_EOL;

    echo $this->headStyle().PHP_EOL;
    ?>
</head>
<body>
<div class="loginFormContainer">
    <form class="form-login" method="POST" action="<?php echo $this->webroot ?>/oauth/authorize/submit">
        <div class="logoContainer">
            <img alt="" src="<?php echo $this->coreWebroot ?>/public/images/midas-200.png"/>
        </div>
        <div class="authorizationText">
            <img class="secureImage" alt="" src="<?php echo $this->coreWebroot ?>/public/images/icons/lock.png"/>
            By logging in, you are authorizing
            <b><?php echo $this->escape($this->client->getName()); ?></b>
            to perform the following actions:
            <ul class="scopeList">
                <?php
                foreach ($this->scopeStrings as $scopeString) {
                    echo '<li>'.$this->escape($scopeString).'</li>';
                }
                ?>
            </ul>
        </div>
        <div class="loginErrorMessage" style="display:none;">
        </div>
        <input type="text" class="input-block-level" name="login" placeholder="Login"/>
        <input type="password" class="input-block-level" name="password" placeholder="Password"/>
        <div class="buttonBar">
            <input class="btn btn-primary loginSubmit" type="submit" name="allowOrDeny" value="Allow"/>
            <input class="btn loginDeny" type="submit" name="allowOrDeny" value="Deny"/>
        </div>
        <input type="hidden" name="redirect_uri" value="<?php echo $this->escape($this->redirectUri); ?>"/>
        <input type="hidden" name="state" value="<?php echo $this->escape($this->state) ?>"/>
        <input type="hidden" name="scope" value="<?php echo $this->escape($this->scope) ?>"/>
        <input type="hidden" name="client_id" value="<?php echo $this->escape($this->client->getKey()) ?>"/>
    </form>
</div>
</body>
</html>
