<?php
/*=========================================================================
 Midas Server
 Copyright Kitware SAS, 26 rue Louis Guérin, 69100 Villeurbanne, France.
 All rights reserved.
 For more information visit http://www.kitware.com/.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

         http://www.apache.org/licenses/LICENSE-2.0.txt

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
=========================================================================*/

$this->headTitle()->append('Privacy Policy');
?>

<div class="viewMain">
    <h3 class='itemSubTitle'>Privacy Policy</h3>

    <p>We may collect information about your computer, including your IP
    address, operating system and browser type for system administration and in
    order to create reports. This is statistical data about the browsing actions
    and patterns of our visitors and does not identify any individual.</p>

    <p>We may use cookies on our site for Google Analytics. Google Analytics is
    a web analytics tool that helps website owners understand how visitors
    engage with their website. Google Analytics customers can view a variety of
    reports about how visitors interact with their website so that they can
    improve it.</p>

    <p>Like many services, Google Analytics uses first-party cookies to track
    visitor interactions as in our case, where they are used to collect
    information about how visitors use our site. We then use the information to
    compile reports and to help us improve our site.</p>

    <p>Cookies contain information that is transferred to the hard drive of your
    computer. These cookies are used to store information, such as the time that
    the current visit occurred, whether the visitor has been to the site before
    and what site referred the visitor to the web page.</p>

    <p>Google Analytics collects information anonymously. It reports website
    trends without identifying individual visitors. You can opt out of Google
    Analytics without affecting how you visit our site. For more information on
    opting out of being tracked by Google Analytics across all websites you use,
    visit
    <a href="https://www.google.com/policies/privacy/partners/">this page</a>.</p>
</div>
