<?php 
/*=========================================================================
MIDAS Server
Copyright (c) Kitware SAS. 20 rue de la Villette. All rights reserved.
69328 Lyon, FRANCE.

See Copyright.txt for details.
This software is distributed WITHOUT ANY WARRANTY; without even
the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE.  See the above copyright notices for more information.
=========================================================================*/
?>
<h2>Web API Configuration</h2>
&gt; <a href="<?php echo $this->webroot?>user">My Midas</a>
<?php if(isset($error)) {echo "<br>*".$error;} ?>
<br/><br/>
<b>Web API URL: </b><?php echo $serverURL.$this->webroot.'api/rest' ?>
<br/><br/>
<div class="separator"></div>
<h3>Generated API keys</h3>
<?php if(count($apikeys)==0)
{
 echo "You don't have any API keys";
}
else
{
?>
<table width="100%"  border="0">
 <tr bgcolor="#999999">
   <td width="20%"><center><b>Application Name</b></center></td>
   <td width="40%"><center><b>API Key</b></center></td>
   <td width="20%"><center><b>Default expiration</b></center></td>
   <td width="10%"><center><b>Date</b></center></td>
   <td width="10%"><center><b>Action</b></center></td>
 </tr>
<?php foreach($apikeys as $apikey)
 {
 ?>
 <tr>
   <td><?php echo $apikey['applicationname']; ?></td>
   <td><?php echo $apikey['key']; ?></td>
   <td><?php echo $apikey['tokenexpiration']; ?> minutes</td>
   <td><?php echo $apikey['creationdate']; ?></td>
   <td><a href="<?php echo $this->webroot ?>api/user/deletekey/<?php echo $apikey['id']; ?>">[remove]</a></td>
 </tr>
<?php } // end foreach keys ?>
</table>
<?php } // end count ?>

<div class="separator"></div>
<h3>Generate new API key</h3>
<form name="createKey" id="createKey" method="post" action="">
    <table width="100%"  border="0">
    <tr>
      <td width="35%" valign="top"><div align="right"><strong>Application name: </strong></div></td>
      <td width="65%"><?php echo $form->input('API.applicationName', array('size'=>'40','label'=>''))?>
       </td>
    </tr>
    <tr>
      <td width="35%" valign="top"><div align="right"><strong>Default token expiration time (min): </strong></div></td>
      <td width="65%"><?php echo $form->input('API.experiationtime', array('size'=>'5','label'=>'','value'=>'60'))?>
       </td>
    </tr>
    <tr>
      <td>&nbsp;</td>
      <td><input type="submit" name="createAPIKey" value="Generate API key >>" /></td>
    </tr>
  </table>
</form>
