<?php
/*=========================================================================
 MIDAS Server
 Copyright (c) Kitware SAS. 26 rue Louis Guérin. 69100 Villeurbanne, FRANCE
 All rights reserved.
 More information http://www.kitware.com

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

         http://www.apache.org/licenses/LICENSE-2.0.txt

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
=========================================================================*/
?>
<h2>Web API Configuration</h2>
&gt; <a href="<?php echo $this->webroot?>user">My Midas</a>
<?php if(isset($error)) {echo "<br>*".$error;} ?>
<br/><br/>
<b>Web API URL: </b><?php echo $serverURL.$this->webroot.'api/rest' ?>
<br/><br/>
<div class="separator"></div>
<h3>Generated API keys</h3>
<?php
if(count($apikeys)==0)
  {
  echo "You don't have any API keys";
  }
else
  {
?>
<table width="100%"  border="0">
 <tr bgcolor="#999999">
   <td width="20%"><center><b>Application Name</b></center></td>
   <td width="40%"><center><b>API Key</b></center></td>
   <td width="20%"><center><b>Default expiration</b></center></td>
   <td width="10%"><center><b>Date</b></center></td>
   <td width="10%"><center><b>Action</b></center></td>
 </tr>
  <?php
  foreach($apikeys as $apikey)
    {
   ?>
 <tr>
   <td><?php echo $apikey['applicationname']; ?></td>
   <td><?php echo $apikey['key']; ?></td>
   <td><?php echo $apikey['tokenexpiration']; ?> minutes</td>
   <td><?php echo $apikey['creationdate']; ?></td>
   <td><a href="<?php echo $this->webroot ?>api/user/deletekey/<?php echo $apikey['id']; ?>">[remove]</a></td>
 </tr>
  <?php
    } // end foreach keys
  ?>
</table>
  <?php
  } // end count
?>

<div class="separator"></div>
<h3>Generate new API key</h3>
<form name="createKey" id="createKey" method="post" action="">
    <table width="100%"  border="0">
    <tr>
      <td width="35%" valign="top"><div align="right"><strong>Application name: </strong></div></td>
      <td width="65%"><?php echo $form->input('API.applicationName', array('size'=>'40','label'=>''))?>
       </td>
    </tr>
    <tr>
      <td width="35%" valign="top"><div align="right"><strong>Default token expiration time (min): </strong></div></td>
      <td width="65%"><?php echo $form->input('API.experiationtime', array('size'=>'5','label'=>'','value'=>'60'))?>
       </td>
    </tr>
    <tr>
      <td>&nbsp;</td>
      <td><input type="submit" name="createAPIKey" value="Generate API key >>" /></td>
    </tr>
  </table>
</form>
