<?php
/*=========================================================================
 Midas Server
 Copyright Kitware SAS, 26 rue Louis Guérin, 69100 Villeurbanne, France.
 All rights reserved.
 For more information visit http://www.kitware.com/.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

         http://www.apache.org/licenses/LICENSE-2.0.txt

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
=========================================================================*/
?>
<link type="text/css" rel="stylesheet" href="<?php echo $this->moduleWebroot; ?>/public/css/upload/upload.index.css"/>
<b><?php echo $this->t('Step 1: Where do you want to upload your files') ?>?</b>
<div>
    <br/>
    <b><?php echo $this->t('Destination:'); ?></b>
    <span class="destinationUpload"><?php echo $this->escape($this->defaultUploadLocationText); ?></span>
    <br/>

    <div class="belowDestinationUpload"></div>
    <input type="hidden" name="parent" class="destinationId" value="<?php echo $this->escape($this->defaultUploadLocation); ?>"/>
    <br/>
    <input class="browseMIDASLink globalButton" type="button" value="Choose location"/>
    <br/><br/>
</div>
<div>
    <b><?php echo $this->t('Step 2: Select a license'); ?></b>

    <div>
        <?php echo $this->element('license'); ?>
    </div>
</div>
<br/>
<b><?php echo $this->t('Step 3: Select files to upload'); ?></b>
<br/><br/>
<applet name="MidasUploader" class="uploadApplet" width="480" height="175"
        archive="<?php echo $this->moduleWebroot; ?>/public/java/upload/MidasUploader.jar?rev=3; ?>"
        code="com.kitware.utils.Main" mayscript="true">
    <param name="apiURL" value="<?php echo $this->escape($this->protocol)."://".$this->escape($this->host.$this->webroot); ?>/api/json"/>
    <param name="background" value="ffffff"/>
    <param name="baseURL"
           value="<?php echo $this->escape($this->protocol)."://".$this->escape($this->host.$this->webroot); ?>/javauploaddownload/upload/"/>
    <param name="getUploadFileOffsetBaseURL" value="gethttpuploadoffset/"/>
    <param name="loglevel" value="WARNING"/>
    <param name="onSuccessfulUploadRedirectEnable" value="true"/>
    <param name="onSuccessRedirectURL" value="review"/>
    <param name="sessionId" value="<?php echo $this->escape(session_id()); ?>"/>
    <param name="type" value="application/x-java-applet;version=1.5"/>
    <param name="uploadFileBaseURL" value="processjavaupload?sid="/>
    <param name="uploadType" value="item"/>
    <param name="uploadUniqueIdentifierURL" value="gethttpuploaduniqueidentifier/"/>
    <?php
    if ($this->directoryMode) {
        ?>
        <param name="directoryMode" value="true"/>
    <?php
    }
    ?>
    You must install and enable Java on your system in order to use the Java upload applet.
</applet>
<?php
foreach ($this->extraHtml as $module => $extra) {
    echo $extra.PHP_EOL;
}
?>
<script type="text/javascript" src="<?php echo $this->moduleWebroot; ?>/public/js/upload/upload.index.js"></script>
