<?php
/*=========================================================================
 MIDAS Server
 Copyright (c) Kitware SAS. 26 rue Louis Guérin. 69100 Villeurbanne, FRANCE
 All rights reserved.
 More information http://www.kitware.com

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

         http://www.apache.org/licenses/LICENSE-2.0.txt

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
=========================================================================*/
?>
<link href="<?php echo $this->coreWebroot?>/public/css/community/community.create.css" rel="stylesheet" type="text/css" />
<script type="text/javascript" src="<?php echo $this->coreWebroot?>/public/js/community/community.create.js"></script>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />

<form id="createCommunityForm" class="genericForm" method="<?php echo $this->form['method']?>"  action="<?php echo $this->form['action']?>">
  <div class="createNameElement">
    <label for="name"><?php echo $this->t('Name')?></label>
    <?php echo $this->form['name']?>
  </div>
  <div>
    <label for="description"><?php echo $this->t('Description')?></label>
    <?php echo $this->form['description']?>
  </div>
  <div class="radioElement">
    <h4><?php echo $this->t('Privacy')?></h4>
    <?php echo $this->form['privacy']?>

    <div id="canJoinDiv">
      <h4><?php echo $this->t('Who can join the community?')?></h4>
      <?php echo $this->form['canJoin']?>
    </div>
  </div>
  <div>
    <?php echo $this->form['submit']?>
  </div>
</form>
