<?php
/*=========================================================================
MIDAS Server
Copyright (c) Kitware SAS. 20 rue de la Villette. All rights reserved.
69328 Lyon, FRANCE.

See Copyright.txt for details.
This software is distributed WITHOUT ANY WARRANTY; without even
the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE.  See the above copyright notices for more information.
=========================================================================*/

$this->headScript()->appendFile($this->coreWebroot.'/public/js/jquery/jquery.dotdotdot-1.4.0-packed.js');
$this->headScript()->appendFile($this->coreWebroot.'/public/js/community/community.index.js');
?>
<link href="<?php echo $this->coreWebroot?>/public/css/community/community.index.css" rel="stylesheet" type="text/css" />

<div class="viewMain">
  <div class="communityList">
  <?php
  if(!empty($this->userCommunities))
    {
    foreach($this->userCommunities as $community)
      {
      ?>  
      <div class="communityBlock">
      <a class="communityTitle" href="<?php echo $this->webroot.'/community/'.$community->getKey();?>">
      <?php echo $community->getName()?></a>
      <br/>
      <?php
      $rawDescription = $community->getDescription();
      $description = $this->Utility->markDown($rawDescription);
      $strippedDescription = strip_tags($description);
      if(!empty($rawDescription)) {
      ?>
      <span class="communityDescription">
<?php echo substr($strippedDescription,0,240); ?><a class="more" href="<?php echo $this->webroot.'/community/'.$community->getKey();?>#tabs-info">More &raquo;</a>
      </span>
  <?php
        }
      echo '</div>';
      }
    }
  ?>
  </div>
  
    <?php 
  if(empty($this->userCommunities))
    {    
    echo "<h4>{$this->t("No community available")}. <a class='createCommunity' >{$this->t("Create your own community")}!</a> </h4>";
    }
    ?>
</div>
<div class="viewSideBar">
  <div class="sideElementFirst viewAction">
    <h1>Actions</h1>
    <ul>
      <li>
        <a class="createCommunity" ><img alt="" src="<?php echo $this->coreWebroot?>/public/images/icons/community2.png" /> <?php echo $this->t("Create a community");?></a>
      </li>
    </ul>
  </div>
  <div class="sideElement viewSelected" >
      <h1><?php echo $this->t('Selected')?></h1>
      <span></span>
  </div>
  <div class="sideElementLast viewInfo">
    <h1>Info</h1>    
    <?php
    echo count($this->userCommunities).' '.(count($this->userCommunities)>1?$this->t('Communities'):$this->t('Community'));
    ?>
  </div>
</div>




