<?php
  $this->headScript()->appendFile($this->webroot.'/public/js/community/community.index.js');
?>
<link href="<?php echo $this->webroot?>/public/css/community/community.index.css" rel="stylesheet" type="text/css" />

<div class="viewMain">
  <div class="communityList">
  <?php
  if(!empty($this->userCommunities))
    {
    foreach($this->userCommunities as $community)
      {
      echo "
      <div>
      <a href='{$this->webroot}/community/{$community->getKey()}'>{$community->getName()}</a>
      <br/>
        <span>
        {$community->getDescription()}
        </span>
      </div>
      ";
      }
    }
  ?>
  </div>
  
    <?php 
  if(empty($this->userCommunities))
    {    
    echo "<h4>{$this->t("No communty  available")}.<a class='createCommunity' >{$this->t("Create your own community")}!</a> </h4>";
    }
    ?>
</div>
<div class="viewSideBar">
  <div class="sideElementFirst viewAction">
    <h1>Actions</h1>
    <ul>
      <li>
        <a class="createCommunity" ><?php echo $this->t("Create a community");?></a>
      </li>
    </ul>
  </div>
  <div class="sideElement viewSelected" >
      <h1><?php echo $this->t('Selected')?></h1>
      <span></span>
  </div>
  <div class="sideElementLast viewInfo">
    <h1>Info</h1>    
    <?php
    echo count($this->userCommunities).' '.(count($this->userCommunities)>1?$this->t('Communities'):$this->t('Community'));
    ?>
  </div>
</div>




