<?php
/** AJAX Action !!!! */
echo '<script type="text/javascript" src="' . $this->coreWebroot . '/public/js/community/community.invitation.js?'.time().'"></script>';
?>
<link href="<?php echo $this->coreWebroot?>/public/css/community/community.invitation.css?<?php echo time();?> " rel="stylesheet" type="text/css" />

<?php
echo "      <div class='invitationSearch'>";
echo "        <input style='width:300px' type='text' id='live_invitation_search' value='{$this->t('Invite the user ...')}' autocomplete='off' autocorrect='off' autocapitalize='off' />";
echo "        <input type='hidden' id='live_invitation_search_value' value='init'  />";
echo "        <div id='searchInvitationLoading' style='display:none'></div>";
echo "      </div>";

?>
