<?php
/*=========================================================================
MIDAS Server
Copyright (c) Kitware SAS. 20 rue de la Villette. All rights reserved.
69328 Lyon, FRANCE.

See Copyright.txt for details.
This software is distributed WITHOUT ANY WARRANTY; without even
the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE.  See the above copyright notices for more information.
=========================================================================*/

$this->headScript()->appendFile($this->coreWebroot . '/public/js/jquery/jquery.form.js');
$this->headScript()->appendFile($this->coreWebroot . '/public/js/jquery/jquery.dataTable.js');
$this->headScript()->appendFile($this->coreWebroot . '/public/js/community/community.manage.js');
$this->headScript()->appendFile($this->coreWebroot.'/public/js/common/common.browser.js');
?>
<link type="text/css" rel="stylesheet" href="<?php echo $this->coreWebroot?>/public/css/community/community.manage.css" />
<link type="text/css" rel="stylesheet" href="<?php echo $this->coreWebroot?>/public/css/common/common.genericPage.css" />
<link type="text/css" rel="stylesheet" href="<?php echo $this->coreWebroot?>/public/css/jquery/jquery.dataTable.css" />
<link type="text/css" rel="stylesheet" href="<?php echo $this->coreWebroot?>/public/css/common/common.browser.css" />
<div class="viewMain">
  <div class="genericThumbnail">
  <?php
  $thumbnail=null;
  if(!empty($thumbnail))
    {
    echo "<img src='{$this->webroot}data/thumbnail/{$thumbnail}' alt=''/>";
    }
  else
    {
    echo "<img src='{$this->coreWebroot}/public/images/icons/community-big.png' alt=''/>";
    }
  ?>
  </div>
  <div class="genericInfo">
    <div class ="genericWrapperTopRight">

         <?php
          echo '<div style="float:right;margin-right:2px;" class="genericBigButton ">';
            echo "<a  href='{$this->webroot}/community/{$this->communityDao->getKey()}'><img style='float:left;margin-right:2px;' alt='' src='{$this->coreWebroot}/public/images/icons/back.png'/>";
            echo $this->t('Back');  
            echo "</a>";
          echo '</div>';
          
        ?>
    </div>
    <div class="genericName"><?php echo $this->communityDao->getName();?></div>
  </div>
  <img class="tabsLoading" alt=""  src="<?php echo $this->coreWebroot?>/public/images/icons/loading.gif" />
  <div class="tabs" id='tabsGeneric'>
    <ul>
      <li><a href="#tabs-1"><?php echo $this->t("Info")?></a></li>
      <li><a href="#tabs-members"><?php echo $this->t('Members');?></a></li>
      <li><a href="#tabs-2"><?php echo $this->t('Groups');?></a></li>
      <li><a href="#tabs-3"><?php echo $this->t('Files');?></a></li>
      <?php
          foreach($this->customTabs as $modules)
            {          
              foreach($modules as $name => $url)
               {
                 echo "<li><a href='{$url}?communityId={$this->communityDao->getKey()}'>{$name}</a></li>";
               }
            }
      ?>
    </ul>
    <div id="tabs-1">
       <form id="editCommunityForm" class="genericForm" method="<?php echo $this->infoForm['method']?>"  action="<?php echo $this->infoForm['action']?>">
        <div class="createNameElement">
          <label for="name"><?php echo $this->t('Nom')?></label>
          <?php echo $this->infoForm['name']?>
        </div>
        <div>
          <label for="description"><?php echo $this->t('Description')?></label>
          <?php echo $this->infoForm['description']?>
        </div>
        <div class="radioElement">
          <h4><?php echo $this->t('Privacy')?></h4>
          <?php echo $this->infoForm['privacy']?>

          <div id="canJoinDiv">
            <h4><?php echo $this->t('Who can join the community?')?></h4>
            <?php echo $this->infoForm['canJoin']?>
          </div>
        </div>
        <div>
          <?php echo $this->infoForm['submit']?>
          <input type="hidden" name='modifyInfo' value='1'/>
        </div>
      </form>

    </div>
    
    <div id="tabs-members">
      <td style="width: 50%;vertical-align: top;">
        <div  class='communityMemberList'>
          <?php 
          $allgroups=$this->groups;
          $allgroups['admin']=$this->adminGroup;
          $allgroups['moderator']=$this->moderatorGroup;
          foreach($allgroups as $k => $group)
            {
            $allgroups[$k]->users = $group->getUsers();
            }
            
          $administratorIds = array();
          $moderatorsIds = array();
          foreach($allgroups['admin']->users as $user)
            {
            $administratorIds[] = $user->getKey();
            }
          foreach($allgroups['moderator']->users as $user)
            {
            $moderatorsIds[] = $user->getKey();
            }
          ?>    
          <h4><?php echo $this->t('Community\'s Members')?>:</h4>	
          <?php
          echo "<div  id='memberList'>";
          echo '<table cellpadding="0" cellspacing="0" border="0" class="display dataTable">';
          echo "<thead>
                <tr>
                  <th>Name</th>
                </tr>
              </thead>"; 
          foreach($this->members as $user)
            {
            echo "<tr>";
            echo "<td width='70%' class='tdUser userid_{$user->getKey()}'><input ";
            if(in_array($user->getKey(), $administratorIds))
              {
              echo "admin = 'true' ";
              }
            else
              {
              echo "admin = 'false' ";
              }
            echo "userid='{$user->getKey()}' type='checkbox'/>{$user->getFullName()}</td>";
            if(in_array($user->getKey(), $administratorIds))
              {
              echo "<td>Administrator</td>";
              }
            if(in_array($user->getKey(), $moderatorsIds))
              {
              echo "<td>Moderator</td>";
              }
            else
              {
              echo "<td></td>";
              }
            echo "</tr>";
            }
          echo "</table>";
          echo "</div>";
          ?>
        </div>

    </div>
    
    <div id="tabs-2">
      <a href="javascript:;" id='createGroupLink'> <?php echo $this->t('Create a group')?></a>
      <div id="groupsList">
        <h4><?php echo $this->t('Groups')?>:</h4>	
        <?php
        echo '<ul>';
        if(empty($this->groups))
          {
          echo "{$this->t('There is no custom group.')}";
          }
        else
          {
          foreach($this->groups as $group)
            {
            echo "<li><a class='groupLink' groupid='{$group->getKey()}' href='javascript:;'>{$group->getName()}</a> [<a class='editGroupLink' groupid='{$group->getKey()}' href='javascript:;'>Edit</a>][<a class='deleteGroupLink' groupid='{$group->getKey()}' href='javascript:;'>Delete</a>]<span/> </li>";
            }
          }
        echo '</ul>';
        ?>
      </div>

            <div class='groupMemberList'>
              <?php

              foreach($allgroups as $group)
                {
                echo "<div style='display:none;' class='groupList' id='groupList_{$group->getKey()}'>";
                echo "<h4>{$this->t('Group\'s members')}</h4>";
                echo '<table cellpadding="0" cellspacing="0" border="0" groupid="'.$group->getKey().'" class="display dataTable">';
                echo "<thead>
                      <tr>
                        <th>Name</th>
                      </tr>
                    </thead>"; 
                foreach($group->users as $user)
                  {
                  echo "<tr>";
                  echo "<td  class='tdUser userid_{$user->getKey()}'><input  userid='{$user->getKey()}' type='checkbox'/>{$user->getFullName()}</td>";
                  echo "</tr>";
                  }
                echo "</table>";
                echo "</div>";
                }
              ?>
            </div>


      <div style="display:none;" id='createGroupFrom'>
        <form class="editGroupForm genericForm" method="<?php echo $this->createGroupForm['method']?>"  action="<?php echo $this->createGroupForm['action']?>">
          <div class="createNameElement">
            <label for="name"><?php echo $this->t('Name')?></label>
            <?php echo $this->createGroupForm['name']?>
          </div>
          <div>
            <br/>
            <?php echo $this->createGroupForm['submit']?>
            <input type="hidden" name='editGroup' value='1'/>
            <input type="hidden" name='groupId' value='0'/>
          </div>
        </form>
      </div>
    </div>

    <div id="tabs-3">
      <img class="tableLoading" alt=""  src="<?php echo $this->coreWebroot?>/public/images/icons/loading.gif" />
            Drag and drop to move elements.
            <br/>
            <br/>
      <table id="browseTable" class="midasTree">
        <thead>
              <th class="thData"><?php echo $this->t('Name');?></th>
              <th class="thSize"><?php echo $this->t('Size');?></th>
              <th class="thDate"><?php echo $this->t('Modified');?></th>
              <th class="thCheckbox"></th>
        </thead>
        <tbody>
            <?php
            $node=1;

            foreach($this->folders as $folder)
              {
              echo "<tr id='node--$node' class='parent' privacy='{$folder->getPrivacyStatus()}' policy='".MIDAS_POLICY_ADMIN."' type='folder' element='{$folder->getFolderId()}' ajax='{$folder->getFolderId()}'>";
              echo "  <td class='treeBrowseElement'><span class='notdraggable folder'>{$folder->getName()}</span></td>";
              echo "  <td><img class='folderLoading'  element='{$folder->getFolderId()}' alt='' src='{$this->coreWebroot}/public/images/icons/loading.gif'/></td>";
              echo "  <td>{$this->Date->ago($folder->getDateUpdate(),true)}</td>";
              echo "  <td><input type='checkbox' class='treeCheckbox' type='folder' element='{$folder->getFolderId()}' /></td>";
              echo "</tr>";
              $node++;
              } 
              
            foreach($this->items as $item)
              {
              echo "<tr id='node--$node' policy='{$item->policy}' privacy='{$item->getPrivacyStatus()}' class='' type='item' element='{$item->getItemId()}' >";
              echo "  <td class='treeBrowseElement'><span class='file'>{$this->slicename($item->getName(),40)}</span></td>";
              echo "  <td>{$item->size}</td>";
              echo "  <td>{$this->Date->ago($item->getDateUpdate(),true)}</td>";
              echo "  <td><input type='checkbox' class='treeCheckbox' type='item' element='{$item->getItemId()}' /></td>";
              echo "</tr>";
              $node++;
              }
            ?>

          </tbody>
      </table>

    </div>
  </div>
</div>
<div class="viewSideBar">
  
  <?php
  if($this->isAdmin)
    {
    echo "  
    <div class='sideElementFirst genericAction'>
      <h1>Actions</h1>
        <ul>
          <li><a onclick='createNewFolder(".$this->mainFolder->getKey().");'><img alt='' src='{$this->coreWebroot}/public/images/FileTree/directory.png'/> {$this->t('Create top level Folder')}</a></li>
          <li><a href='javascript:;' id='communityDeleteLink'><img alt='' src='{$this->coreWebroot}/public/images/icons/close.png'/> {$this->t('Delete')}</a></li>
       </ul>
    </div>";    
    }
  ?>
   <div class="sideElement<?php echo (!$this->isModerator&&!$this->isAdmin&&!$this->isMember)?'First':''?> genericCommunities">
    <h1><?php echo $this->t('Members')?></h1>    
      <ul>
      <?php
        $i=0;
        foreach($this->members as $member)
          {
          if($i>10)break;
          echo "<li>{$this->linkuser($member)}</li>";
          }
      ?>
      </ul>
   </div>
   <div class="sideElement memberSelection" style="display:none;">
     <h1><?php echo $this->t('Selected')?></h1>   
     <ul>
       <?php
       foreach($this->groups as $group)
          {
          echo "<li><a class='addUserLink' element='{$group->getKey()}'>{$this->t('Add in group')} {$group->getName()}</a></li>";
          }
       ?>
       <li><a class='addModeratorLink'><?php echo $this->t('Set as moderator')?></a></li>
       <li><a class='removeFromCommunity'><?php echo $this->t('Remove from community')?></a></li>
     </ul>
   </div>
   <div class="sideElement groupUsersSelection" style="display:none;">
     <h1><?php echo $this->t('Selected')?></h1>   
     <ul>
       <li><a class='removeUserLink'><?php echo $this->t('Remove from group')?></a></li>
     </ul>
   </div>
   <div class="sideElementLast genericStats">
    <h1>Stats</h1>  
    
    <?php
      echo "<ul>";
      echo "  <li>".count($this->members)." {$this->t("member")}".((count($this->members)>1)?'s':'')."</li>";
      echo "</ul>";
      ?>
   </div>

  
    <div class="sideElementFirst viewAction">
    <h1>Actions</h1>
      <ul>
        <li>

        </li>
      </ul>
    </div>
    <div class="sideElementLast viewInfo">
      <h1>Info</h1>    
      <img class="infoLoading" style="display:none;" alt="" src="<?php echo $this->coreWebroot?>/public/images/icons/loading.gif"/>
      <div class="ajaxInfoElement">
      </div>
    </div>
</div>






