<?php
/*=========================================================================
 MIDAS Server
 Copyright (c) Kitware SAS. 26 rue Louis Guérin. 69100 Villeurbanne, FRANCE
 All rights reserved.
 More information http://www.kitware.com

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

         http://www.apache.org/licenses/LICENSE-2.0.txt

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
=========================================================================*/

echo '<script type="text/javascript" src="'.$this->coreWebroot.'/public/js/jquery/jquery.form.js"></script>';
echo '<script type="text/javascript" src="'.$this->coreWebroot.'/public/js/community/community.promotedialog.js"></script>';

?>
<link type="text/css" rel="stylesheet"
      href="<?php echo $this->coreWebroot ?>/public/css/common/common.genericPage.css"/>
<link type="text/css" rel="stylesheet"
      href="<?php echo $this->coreWebroot ?>/public/css/community/community.promotedialog.css"/>

Add user
<b><?php echo $this->user->getFullName(); ?></b> to the following groups:
<br/><br/>
<div>
    <form class="genericForm" id="promoteGroupForm" action="<?php echo $this->webroot; ?>/community/promoteuser"
          method="POST">
        <?php
        if (count($this->availableGroups) == 0) {
            echo 'No available groups.';
        }
        foreach ($this->availableGroups as $group) {
            echo '<input type="checkbox" name="groupCheckbox_'.$group->getKey().'">'.$group->getName().'</input><br/>';
        }
        ?>
        <br/>
        <input id="addToGroupsSubmitButton" class="addToGroupsSubmit" type="submit" value="Add" name="addToGroups"/>
        <input type="hidden" id="promoteUserId" name="userId" value="<?php echo $this->user->getKey(); ?>"/>
        <input type="hidden" id="promoteCommunityId" name="communityId"
               value="<?php echo $this->community->getKey(); ?>"/>
    </form>
    <img style="display: none;" id="promoteDialogLoading" alt=""
         src="<?php echo $this->coreWebroot; ?>/public/images/icons/loading.gif"/>
</div>
