<?php
/*=========================================================================
MIDAS Server
Copyright (c) Kitware SAS. 20 rue de la Villette. All rights reserved.
69328 Lyon, FRANCE.

See Copyright.txt for details.
This software is distributed WITHOUT ANY WARRANTY; without even
the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE.  See the above copyright notices for more information.
=========================================================================*/

echo '<script type="text/javascript" src="'.$this->coreWebroot.'/public/js/jquery/jquery.form.js"></script>';
echo '<script type="text/javascript" src="'.$this->coreWebroot.'/public/js/community/community.promotedialog.js"></script>';

?>
<link type="text/css" rel="stylesheet" href="<?php echo $this->coreWebroot?>/public/css/common/common.genericPage.css" />
<link type="text/css" rel="stylesheet" href="<?php echo $this->coreWebroot?>/public/css/community/community.promotedialog.css" />

Add user <b><?php echo $this->user->getFullName(); ?></b> to the following groups:
<br/><br/>
<div>
  <form class="genericForm" id="promoteGroupForm" action="<?php echo $this->webroot; ?>/community/promoteuser" method="POST">
    <?php
    if(count($this->availableGroups) == 0)
      {
      echo 'No available groups.';
      }
    foreach($this->availableGroups as $group)
      {
      echo '<input type="checkbox" name="groupCheckbox_'.$group->getKey().'">'.$group->getName().'</input><br/>';
      }
    ?>
    <br />
    <input id="addToGroupsSubmitButton" class="addToGroupsSubmit" type="submit" value="Add" name="addToGroups" />
    <input type="hidden" id="promoteUserId" name="userId" value="<?php echo $this->user->getKey(); ?>" />
    <input type="hidden" id="promoteCommunityId" name="communityId" value="<?php echo $this->community->getKey(); ?>" />
  </form>
  <img style="display: none;" id="promoteDialogLoading" alt="" src="<?php echo $this->coreWebroot; ?>/public/images/icons/loading.gif" />
</div>
