<?php
/*=========================================================================
 Midas Server
 Copyright Kitware SAS, 26 rue Louis Guérin, 69100 Villeurbanne, France.
 All rights reserved.
 For more information visit http://www.kitware.com/.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

         http://www.apache.org/licenses/LICENSE-2.0.txt

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
=========================================================================*/
?>
<script type="text/javascript"
        src="<?php echo $this->coreWebroot ?>/public/js/community/community.selectgroup.js"></script>
<link type="text/css" rel="stylesheet"
      href="<?php echo $this->coreWebroot ?>/public/css/community/community.selectgroup.css"/>

<div class="groupSelectContainer">
    Which community group would you like to invite the user to?
    <div>
        <select id="groupSelect">
            <?php
            foreach ($this->groups as $group) {
                echo '<option value="'.$this->escape($group->getKey()).'">'.$this->escape($group->getName()).'</option>';
            }
            ?>
        </select>
    </div>
</div>

<div class="bottomButtons">
    <input id="groupSelectOk" type="button" class="globalButton" value="OK"/>
</div>
