<?php
$this->headScript()->appendFile($this->coreWebroot . '/public/js/community/community.view.js');
$this->headScript()->appendFile($this->coreWebroot.'/public/js/common/common.browser.js');
?>
<link type="text/css" rel="stylesheet" href="<?php echo $this->coreWebroot?>/public/css/community/community.view.css" />
<link type="text/css" rel="stylesheet" href="<?php echo $this->coreWebroot?>/public/css/common/common.browser.css" />
<link type="text/css" rel="stylesheet" href="<?php echo $this->coreWebroot?>/public/css/common/common.genericPage.css" />
<div class="viewMain">
  <div class="genericThumbnail">
  <?php
  $thumbnail=null;
  if(!empty($thumbnail))
    {
    echo "<img src='{$this->webroot}data/thumbnail/{$thumbnail}' alt=''/>";
    }
  else
    {
    echo "<img src='{$this->coreWebroot}/public/images/icons/community-big.png' alt=''/>";
    }
  ?>
  </div>
  <div class="genericInfo">
    <div class="genericName"><?php echo $this->communityDao->getName();?></div>
  </div>
  <img class="tabsLoading" alt=""  src="<?php echo $this->coreWebroot?>/public/images/icons/loading.gif" />
  <div class="tabs" id='tabsGeneric'>
  <ul>
    <li><a href="#tabs-1"><?php echo $this->t("Feed")?></a></li>
    <?php
    if(!empty($this->information))
      {
      ?>
    <li><a href="#tabs-2"><?php echo $this->t('Info');?></a></li>
    <?php
      }
      ?>
    <li><a href="#tabs-3"><?php echo $this->t('Data');?></a></li>
  </ul>
  <div id="tabs-1">
     <?
      echo $this->element('feed');
      ?>
  </div>
        <?php
    if(!empty($this->information))
      {
      ?>
    <div id="tabs-2">
      ???
    </div>
    <?php
      }
      ?>
    <div id="tabs-3">
      <img class="tableLoading" alt=""  src="<?php echo $this->coreWebroot?>/public/images/icons/loading.gif" />
      <table id="browseTable" class="midasTree">
        <thead>
              <th class="thData"><?php echo $this->t('Name');?></th>
              <th class="thSize"><?php echo $this->t('Size');?></th>
              <th class="thDate"><?php echo $this->t('Modified');?></th>
              <th class="thCheckbox"></th>
        </thead>
        <tbody>
            <?php
            $node=1;

            foreach($this->folders as $folder)
              {
              echo "<tr id='node--$node' class='parent' type='folder' element='{$folder->getFolderId()}' ajax='{$folder->getFolderId()}'>";
              echo "  <td class='treeBrowseElement'><span class='folder'>{$folder->getName()}</span></td>";
              echo "  <td><img class='folderLoading'  element='{$folder->getFolderId()}' alt='' src='{$this->coreWebroot}/public/images/icons/loading.gif'/></td>";
              echo "  <td>{$this->Date->ago($folder->getDate(),true)}</td>";
              echo "  <td><input type='checkbox' class='treeCheckbox' type='folder' element='{$folder->getFolderId()}' /></td>";
              echo "</tr>";
              $node++;
              } 
            ?>

          </tbody>
      </table>
  </div>
</div>

</div>
<div class="viewSideBar">
  
  <?php
  if(!$this->isMember&&$this->communityDao->getPrivacy()==MIDAS_COMMUNITY_PUBLIC)
    {
    echo "
    <form type='post' action=''>
      <input name='joinCommunity' type='submit' class='globalButton' value='{$this->t('Join the community')}' />
    </form>
    ";
    }
  else if(!$this->isMember&&$this->communityDao->getPrivacy()==MIDAS_COMMUNITY_SEMIPRIVATE)
    {
    echo "
      <input type='button' class='globalButton' value='{$this->t('Request to join the community')}' />
    ";
    }
  
  if($this->isModerator||$this->isAdmin||$this->isMember)
    {
    echo "  
    <div class='sideElementFirst genericAction'>
      <h1>Actions</h1>
        <ul>";
    if($this->isModerator)
      {
      echo "
          <li><a href=''>{$this->t('Manage')}</a></li>
          ";
      }
    if($this->isAdmin)
      {
      echo "
          <li><a href='javascript:;' id='communityDeleteLink'>{$this->t('Delete')}</a></li>
          ";
      }
    if($this->isMember&&!$this->isAdmin)
      {
      echo "
          <li><a href=''>{$this->t('Leave the community')}</a></li>
          ";
      }
    echo 
    "  </ul>
    </div>";
    }
  ?>
   <div class="sideElement<?php echo (!$this->isModerator&&!$this->isAdmin&&!$this->isMember)?'First':''?> genericCommunities">
    <h1><?php echo $this->t('Members')?></h1>    
      <ul>
      <?php
        $i=0;
        foreach($this->members as $member)
          {
          if($i>10)break;
          echo "<li><a href='{$this->webroot}/user/{$member->getKey()}'>{$member->getFullName()}</a></li>";
          }
      ?>
      </ul>
   </div>
   <div class="sideElementLast genericStats">
    <h1>Stats</h1>  
    
    <?php
      echo "<ul>";
      echo "  <li>".count($this->members)." {$this->t("member")}".((count($this->members)>1)?'s':'')."</li>";
      echo "</ul>";
      ?>
   </div>
  
    <div class="sideElementFirst viewAction">
    <h1>Actions</h1>
      <ul>
        <li>

        </li>
      </ul>
    </div>
    <div class="sideElementLast viewInfo">
      <h1>Info</h1>    
      <img class="infoLoading" style="display:none;" alt="" src="<?php echo $this->coreWebroot?>/public/images/icons/loading.gif"/>
      <div class="ajaxInfoElement">
      </div>
    </div>
</div>






