<?php
echo '<script type="text/javascript" src="' . $this->coreWebroot . '/public/js/upload/upload.javaupload.js"></script>';
?>
<b><?php echo $this->t('Step 1: Where do you want to upload your files')?>?</b>
<div>
  <br/>
  <b><?php echo $this->t('Current selected location:')?></b>
  <span class="destinationUpload"><?php echo $this->defaultUploadLocationText?></span>
  <br/><br/>
  <div class="belowDestinationUpload" style="display: none;"></div>
  <input type="hidden" name="parent" class="destinationId" value="<?php echo $this->defaultUploadLocation?>"/>
  <br/>
  <input style="margin-left:0;" class="browseMIDASLink globalButton" type="button" value="Choose location" />
  <br/><br/>
</div>
  <b><?php echo $this->t('Step 2: Select a license')?></b>
<div>
  <?php
  echo $this->element('license')?>
</div>
<br/>
<b><?php echo $this->t('Step 3: Select files to upload')?></b>
<br/><br/>
<applet name="MidasUploader"
        class="uploadApplet"
        archive="<?php echo $this->coreWebroot?>/public/java/upload/MidasUploader.jar?rev=3&<?php echo time()?>"
        width="480" height="175" mayscript="true"
        code="com.kitware.utils.Main">
  <param name = "type" value = "application/x-java-applet;version=1.5" />
  <param name = "background" value = "ffffff" />
  <param name = "loglevel" value = "WARNING" />
  <param name = "sessionId" value = "<?php echo session_id();?>"/>
  <param name = "baseURL" value="<?php echo $this->protocol."://".$this->host.$this->webroot ?>/upload/"/>
  <param name = "apiURL" value="<?php echo $this->protocol."://".$this->host.$this->webroot ?>/api/json"/>
  <param name = "getUploadFileOffsetBaseURL" value="gethttpuploadoffset/"/>
  <param name = "onSuccessfulUploadRedirectEnable" value="true"/>
  <param name = "onSuccessRedirectURL" value="review"/>
  <param name = "uploadUniqueIdentifierURL" value="gethttpuploaduniqueidentifier/"/>
  <param name = "uploadFileBaseURL" value="processjavaupload/?sid="/>
  <param name = "uploadType" value="item"/>
  <?php
  if($this->directoryMode)
    {
    echo '<param name="directoryMode" value="true"/>';
    }
  ?>
  You must install and enable Java on your system in order to use the large file uploader.
</applet>
<?php
foreach($this->extraHtml as $module => $extra)
  {
  echo $extra."\n";
  }
