      <applet name="MidasUploader" code="com.kitware.utils.Main"
              archive="<?php echo $this->coreWebroot?>/public/java/uploader/dist/MidasUploader.jar?rev=3"
              width="305" height="230" mayscript="">
        <param name = "type"      value = "application/x-java-applet;version=1.5" />
        
        <param name = "background" value = "ffffff" />
        
        <param name = "loglevel" value = "WARNING" />
        
        <param name = "sessionId" value = "<?php echo session_id();?>"/>
        <param name = "baseURL" value="<?php echo $this->protocol."://".$this->host . $this->webroot ?>/upload/"/>
        <param name = "getUploadFileOffsetBaseURL" value="gethttpuploadoffset/"/>
        <param name = "onSuccessfulUploadRedirectEnable" value="false"/>
        <param name = "uploadUniqueIdentifierURL" value="gethttpuploaduniqueidentifier/"/>
        <param name = "uploadFileBaseURL" value="processjavaupload/?sid="/>
      </applet> 
