<?php
/*=========================================================================
MIDAS Server
Copyright (c) Kitware SAS. 20 rue de la Villette. All rights reserved.
69328 Lyon, FRANCE.

See Copyright.txt for details.
This software is distributed WITHOUT ANY WARRANTY; without even
the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE.  See the above copyright notices for more information.
=========================================================================*/
?>
<link href="<?php echo $this->coreWebroot?>/public/css/upload/upload.simpleupload.css?<?php echo time()?>" rel="stylesheet" type="text/css" />
<link href="<?php echo $this->coreWebroot?>/public/css/jquery/jquery.fileupload-ui.css?<?php echo time()?>" rel="stylesheet" type="text/css" />
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />

<?php
  if(Zend_Registry::get("configGlobal")->smartoptimizer == 1)
    {
    echo '<script type="text/javascript" src="' . $this->coreWebroot . '/public/js/swfupload/js/swfupload.js,swfupload.queue.js,fileprogress.js,handlers.js"></script>';
    }
  else
    {
    ?>
    <script type="text/javascript" src="<?php echo $this->coreWebroot?>/public/js/swfupload/js/swfupload.js"></script>
    <script type="text/javascript" src="<?php echo $this->coreWebroot?>/public/js/swfupload/js/swfupload.queue.js"></script>
    <script type="text/javascript" src="<?php echo $this->coreWebroot?>/public/js/swfupload/js/fileprogress.js"></script>
    <script type="text/javascript" src="<?php echo $this->coreWebroot?>/public/js/swfupload/js/handlers.js"></script>
    <?php
    }
    ?>

<div class="tabs uploadTabs" id='uploadTabs'>
  <ul>
    <li><a href="#uploadTabs-1">Simple</a></li>
    <li><a href="<?php echo $this->webroot?>/upload/javaupload"><?php echo $this->t('Large Files');?></a></li>
    <li><a href="#uploadTabs-3"><?php echo $this->t('Links');?></a></li>
  </ul>
  <div id="uploadTabs-1">
      <b><?php echo $this->t('Step 1: Select files to upload')?></b>
      <br/>
      <div id="swfuploadContent" style="display: none;">
        <span id="spanButtonPlaceHolder"></span>
        <div>
          <div class="fieldset flash" id="fsUploadProgress"></div>
        </div>
      </div>
      <div id="jqueryFileUploadContent" style="display: none;">
        <div class="file_upload">
            <form action="<?php echo $this->webroot?>/upload/saveuploaded" method="POST" enctype="multipart/form-data">
                <input class="fileUploaderInput" type="file" name="file[]" multiple>
                <button type="submit">Upload</button>
                <div class="file_upload_label"><?php echo $this->t('Browse or drop files')?></div>
                <div class="file_upload_label_folder"><?php echo $this->t('Browse')?></div>
            </form>
            <div id="changeUploadMode" style="display:none;">
              <br/>
              <?php echo $this->t('or')?> <a style="color:blue; cursor:pointer;" class="uploadModeLink" id="uploadModeFolderLink"><?php echo $this->t('upload a folder')?></a>
              <a style="color:#56758B; cursor:pointer;" class="uploadModeLink" id="uploadModeFileLink"><?php echo $this->t('upload files')?></a>
            </div>

            <div class="uploadedFilesWrapper">
              <table class="files">
                  <tr class="file_upload_template" style="display:none;">
                      <td class="file_name"></td>
                      <td class="file_size"></td>
                      <td class="file_upload_progress"><div></div></td>
                      <td class="file_upload_start" style='display:none;'><button>Start</button></td>
                      <td class="file_upload_cancel"><button></button></td>
                  </tr>
                  <tr class="file_download_template" style="display:none;">
                      <td class="file_name"><a></a></td>
                      <td class="file_size"></td>
                  </tr>
                  <div class="file_upload_buttons" style='display:none;'>
                    <button class="file_upload_start">Start All</button>
                    <button class="file_upload_cancel">Cancel All</button>
                    <button class="file_download_delete">Delete All</button>
                  </div>
              </table>
            </div>
            <div class="file_upload_overall_progress" style='display:none;'><div style="display:none;"></div></div>
        </div>
        <div class="uploadValidationError"><img src="<?php echo $this->coreWebroot ?>/public/images/icons/close.png" alt=""/><b></b><hr></div>
        <div class="tooBigUpload">
          <img src="<?php echo $this->coreWebroot ?>/public/images/icons/close.png" alt=""/> <b><?php echo $this->t('Please use the large file tool, the following files are too big:')?></b>
          <ul>

          </ul>
        </div>

      </div>
      <b><?php echo $this->t('Step 2: Where do you want to upload your files')?>?</b>
      <div>
      <br/>
      <b><?php echo $this->t('Current selected location:')?></b>
          <span id="destinationUpload"><?php echo $this->defaultUploadLocationText?></span>
        <input type="hidden" name="destinationId" id="destinationId" value="<?php echo $this->defaultUploadLocation?>"/>
        <br/><br/>
        <div class="belowDestinationUpload" style="display: none;"></div>
        <br/>
        <input style="margin-left:0px;" class="browseMIDASLink globalButton" type="button" value="Change location" />
        <br/>
        <br/>
      </div>
      <b><?php echo $this->t('Step 3: Select a license')?></b>
      <div>
        <?php
        echo $this->element('license')?>
      </div>
      <br/>
      <b><?php echo $this->t('Step 4: Start the upload')?></b>
      <br/>
      <input id="btnCancel" style="display:none;" type="button" value="Cancel All Uploads" onclick="midas.upload.simpleupload.swfu.cancelQueue();" disabled="disabled" style="margin-left: 2px; font-size: 8pt; height: 29px;" />

      <span id="btnStartUpload" >
        <input style="margin-left:0px;" id='startUploadLink' class="globalButton" type="button" qtip="<?php echo $this->t("Don't forget to start the upload.")?>" value="<?php echo $this->t('Start Upload')?>" />
      </span>
      <div>
        <?php echo $this->t('Number of uploaded files');?> <span class="globalUploadedCount">0</span>
      </div>
  </div>
    <div id="uploadTabs-3">
      <form id="linkForm" class="genericForm" method="<?php echo $this->form['method']?>"  action="<?php echo $this->form['action']?>">
        <div>
          <label for="name"><b><?php echo $this->t('Step 1: Set a name')?></b></label><br/>
          <?php echo $this->form['name']?><br/><br/>
        </div>
        <div>
          <label for="url"><b><?php echo $this->t('Step 2: Set the url')?></b></label><br/>
          <?php echo $this->form['url']?><br/><br/>
        </div>
        <b><?php echo $this->t('Step 3: Where do you want to upload your files')?></b>
          <div>
          <br/>
          <b><?php echo $this->t('Curent selected location:')?></b>
          <span class="destinationUpload"><?php echo $this->defaultUploadLocationText?></span>
          <input type="hidden" name="parent" class="destinationId" value="<?php echo $this->defaultUploadLocation?>"/>
            <br/>
            <input style="margin-left:0px;" class="browseMIDASLink globalButton" type="button" value="Change location" />
            <br/>
            <br/>
        </div>
        <div>
          <?php echo $this->form['submit']?>
        </div>
      </form>
  </div>
</div>

<div class="reviewUploaded">
  <form method="post" action="<?php echo $this->webroot?>/browse/uploaded">
    <input class="globalButton" type="submit" value="<?php echo $this->t('Review uploaded files');?>" />
  </form>
</div>
<input type="hidden" class="buttonBrowse" value="<?php echo $this->t('Browse');?>"/>
<input type="hidden" class="sessionId" value="<?php echo session_id();?>"/>
<input type="hidden" class="maxSizeFile" value="<?php echo $this->maxSizeFile;?>"/>
<input type="hidden" class="uploadedSimple" value="0"/>
<input type="hidden" class="uploadedJava" value="0"/>
<input type="hidden" class="uploadedLinks" value="0"/>


<?php
    if(Zend_Registry::get("configGlobal")->smartoptimizer == 1)
      {
      echo '<script type="text/javascript" src="' . $this->coreWebroot . '/public/js/jquery/jquery.fileupload.js,jquery.fileupload-ui.js,jquery.fileupload-uix.js,jquery.form.js"></script>';
      }
    else
      {
      ?>
      <script type="text/javascript" src="<?php echo $this->coreWebroot?>/public/js/jquery/jquery.fileupload.js"></script>
      <script type="text/javascript" src="<?php echo $this->coreWebroot?>/public/js/jquery/jquery.fileupload-ui.js"></script>
      <script type="text/javascript" src="<?php echo $this->coreWebroot?>/public/js/jquery/jquery.fileupload-uix.js"></script>
      <script type="text/javascript" src="<?php echo $this->coreWebroot?>/public/js/jquery/jquery.form.js"></script>
      <?php
      }

    foreach($this->extraHtml as $module => $extra)
      {
      echo $extra."\n";
      }
?>
<script type="text/javascript" src="<?php echo $this->coreWebroot?>/public/js/upload/upload.simpleupload.js"></script>