<?php
/*=========================================================================
 Midas Server
 Copyright Kitware SAS, 26 rue Louis Guérin, 69100 Villeurbanne, France.
 All rights reserved.
 For more information visit http://www.kitware.com/.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

         http://www.apache.org/licenses/LICENSE-2.0.txt

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
=========================================================================*/
?>
<div id="ratingsDiv">

    <h4>RATINGS</h4>

    <div id="ratingsAverage" style="display: none;">
        <input type="radio" name="avgrate" value="1"/>
        <input type="radio" name="avgrate" value="2"/>
        <input type="radio" name="avgrate" value="3"/>
        <input type="radio" name="avgrate" value="4"/>
        <input type="radio" name="avgrate" value="5"/>
        <input type="radio" name="avgrate" value="6"/>
        <input type="radio" name="avgrate" value="7"/>
        <input type="radio" name="avgrate" value="8"/>
        <input type="radio" name="avgrate" value="9"/>
        <input type="radio" name="avgrate" value="10"/>
        <span class="averageStats"><span id="averageValue"></span> (<span id="voteTotal"></span> votes)</span>
    </div>

    <div id="ratingsUser" style="display: none;">
        <span class="addRating">Click to rate</span>
        <input type="radio" name="newrate" value="1" title="1 star"/>
        <input type="radio" name="newrate" value="2" title="2 stars"/>
        <input type="radio" name="newrate" value="3" title="3 stars"/>
        <input type="radio" name="newrate" value="4" title="4 stars"/>
        <input type="radio" name="newrate" value="5" title="5 stars"/>
    </div>
    <div class="loginToRate" style="display: none;">
        <span><a id="loginToRate">Login</a> or <a id="registerToRate">register</a> to rate.</span>
    </div>

    <div class="ratingsVSpacer"></div>
    <div id="ratingsChart" style="height: 130px; width: 100%;"></div>
</div>
