<?php
/*=========================================================================
MIDAS Server
Copyright (c) Kitware SAS. 20 rue de la Villette. All rights reserved.
69328 Lyon, FRANCE.

See Copyright.txt for details.
This software is distributed WITHOUT ANY WARRANTY; without even
the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE.  See the above copyright notices for more information.
=========================================================================*/
?>

<pre>
Enabling JavaScript is required.

Internet Explorer 7.0+

Click the Tools menu.
Select Internet Options.
Click the Security tab.
Click the Custom Level button.
Scroll down until you see the 'Scripting' section. Select the 'Enable' radio button for 'Active Scripting.'
Click the OK button.
If you see a confirmation window, click the Yes button.
Firefox 3.6+

Click the Tools menu.
Select Options.
Click the Content tab.
Select the 'Enable JavaScript' checkbox.
Click the OK button.
Safari 2 or 3

Click the Safari menu.
Select Preferences.
Click the Security tab.
Select the 'Enable JavaScript' checkbox.
<pre>
