<?php
/*=========================================================================
 MIDAS Server
 Copyright (c) Kitware SAS. 26 rue Louis Guérin. 69100 Villeurbanne, FRANCE
 All rights reserved.
 More information http://www.kitware.com

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

         http://www.apache.org/licenses/LICENSE-2.0.txt

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
=========================================================================*/
?>
<pre>
Enabling JavaScript is required.

Internet Explorer 7.0+

Click the Tools menu.
Select Internet Options.
Click the Security tab.
Click the Custom Level button.
Scroll down until you see the 'Scripting' section. Select the 'Enable' radio button for 'Active Scripting.'
Click the OK button.
If you see a confirmation window, click the Yes button.
Firefox 3.6+

Click the Tools menu.
Select Options.
Click the Content tab.
Select the 'Enable JavaScript' checkbox.
Click the OK button.
Safari 2 or 3

Click the Safari menu.
Select Preferences.
Click the Security tab.
Select the 'Enable JavaScript' checkbox.
<pre>
