<?php
/*=========================================================================
 Midas Server
 Copyright Kitware SAS, 26 rue Louis Guérin, 69100 Villeurbanne, France.
 All rights reserved.
 For more information visit http://www.kitware.com/.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

         http://www.apache.org/licenses/LICENSE-2.0.txt

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
=========================================================================*/
?>
<link type="text/css" rel="stylesheet"
      href="<?php echo $this->coreWebroot ?>/public/css/assetstore/assetstore.movedialog.css"/>

<script type="text/javascript"
        src="<?php echo $this->coreWebroot ?>/public/js/assetstore/assetstore.movedialog.js"></script>

<form id='moveBitstreamsForm' action="<?php echo $this->webroot ?>/assetstore/movecontents" method="post">
    Destination asset store:
    <select id="dstAssetstoreId">
        <?php
        foreach ($this->assetstores as $assetstore) {
            if ($assetstore->getKey() != $this->srcAssetstore->getKey()) {
                echo '<option value="'.$this->escape($assetstore->getKey()).'">'.$this->escape($assetstore->getName()).'</option>';
            }
        }
        ?>
    </select>
    <input type="hidden" id="srcAssetstoreId" value="<?php echo $this->escape($this->srcAssetstore->getKey()); ?>"/>

    <div id="moveBitstreamsProgressBar"></div>
    <div id="moveBitstreamsProgressMessage"></div>

    <div class="bottomButtons">
        <input type="button" class="globalButton" id="moveBitstreamsConfirm" value="Move"/>
    </div>
</form>
