<?php
/*=========================================================================
 MIDAS Server
 Copyright (c) Kitware SAS. 26 rue Louis Guérin. 69100 Villeurbanne, FRANCE
 All rights reserved.
 More information http://www.kitware.com

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

         http://www.apache.org/licenses/LICENSE-2.0.txt

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
=========================================================================*/

$this->headScript()->appendFile($this->coreWebroot . '/public/js/jquery/jquery.form.js');
$this->headScript()->appendFile($this->moduleWebroot . '/public/js/config/config.index.js');
?>

<link type="text/css" rel="stylesheet" href="<?php echo $this->coreWebroot?>/public/css/common/common.genericPage.css" />
<div class="viewMain">
     <div class ="genericWrapperTopRight">
         <?php
          echo '<div style="float:right;margin-right:2px;" class="genericBigButton ">';
            echo "<a  href='{$this->webroot}/admin#tabs-modules'><img style='float:left;margin-right:2px;' alt='' src='{$this->coreWebroot}/public/images/icons/back.png'/>";
            echo $this->t('Back');
            echo "</a>";
          echo '</div>';

        ?>
    </div>

    This module requires dcm2xml from dcmtk.<br/>
    To install it: <a href="http://support.dcmtk.org/redmine/projects/dcmtk/wiki/howto" target="_blank">http://support.dcmtk.org/redmine/projects/dcmtk/wiki/howto</a><br/><br/>
     <?php
      echo "
      <form class='genericForm' id='configForm' method='{$this->configForm['method']}'  action='{$this->configForm['action']}'>
      <h3>DICOM Extractor Configuration:</h3>
            <div >
              <label for='dcm2xml'>Command to run dcm2xml (for data)</label>
              {$this->configForm['dcm2xml']}
            </div>
            <br />
            <div >
              <label for='dcmjpnm'>Command to run dcmj2pnm (for thumbnail)</label>
              {$this->configForm['dcmj2pnm']}
            </div >
            <br />
            <div >
              <label for='dcmftest'>Command to run dcmftest to verify if a file is valid DICOM.</label>
              {$this->configForm['dcmftest']}
            </div >
            <br />
            <div >
              <label for='dcmdictpath'>The value of the DCMDICTPATH environment
              variable.</label>
              {$this->configForm['dcmdictpath']}
            </div >
          <div>
            {$this->configForm['submitConfig']}
          </div>
       </form>";
       ?>

</div>
