<?php
/*=========================================================================
 Midas Server
 Copyright Kitware SAS, 26 rue Louis Guérin, 69100 Villeurbanne, France.
 All rights reserved.
 For more information visit http://www.kitware.com/.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

         http://www.apache.org/licenses/LICENSE-2.0.txt

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
=========================================================================*/
?>
<link type="text/css" rel="stylesheet" href="<?php echo $this->coreWebroot ?>/public/css/admin/admin.dashboard.css"/>
<script type="text/javascript" src="<?php echo $this->coreWebroot ?>/public/js/admin/admin.dashboard.js"></script>

<?php
foreach ($this->dashboard as $module => $dasboard) {
    echo '<h3>'.ucfirst($this->escape($module)).'</h3>';
    echo '<table>';
    foreach ($dasboard as $name => $status) {
        echo '<tr>';
        echo '<td>'.$this->escape($name).'</td>';
        if ($status[0]) {
            echo '<td><img src="'.$this->coreWebroot.'/public/images/icons/ok.png" /></td>';
        } else {
            echo '<td><img src="'.$this->coreWebroot.'/public/images/icons/nok.png" /></td>';
        }
        if (isset($status[1])) {
            echo '<td>'.$this->escape($status[1]).'</td>';
        }
        echo '</tr>';
    }
    echo '</table>';
}
?>

<div class="databaseIntegrityWrapper" style="display: none">
    <h3 class="sectionHeader"><a href="#">Database Integrity</a></h3>

    <div>
        <div class="integrityLoading">
            <img alt="" src="<?php echo $this->coreWebroot ?>/public/images/icons/loading.gif"/>
            Computing database integrity. This may take several minutes...
        </div>
        <div class="integrityList" style="display: none">
            <ul>
                <li class="integrityItem">
                    <span>Number of orphaned folders:</span>
                    <span class="nFolder"></span>
                    <span class="integrityButton"><button element="Folder" class="removeOrphans">Clean</button></span>
                </li>
                <li class="integrityItem">
                    <span>Number of orphaned items:</span>
                    <span class="nItem"></span>
                    <span class="integrityButton"><button element="Item" class="removeOrphans">Clean</button></span>
                </li>
                <li class="integrityItem">
                    <span>Number of orphaned revisions:</span>
                    <span class="nItemRevision"></span>
                    <span class="integrityButton"><button element="ItemRevision" class="removeOrphans">Clean
                        </button></span>
                </li>
                <li class="integrityItem">
                    <span>Number of orphaned bitstreams:</span>
                    <span class="nBitstream"></span>
                    <span class="integrityButton"><button element="Bitstream" class="removeOrphans">Clean
                        </button></span>
                </li>
            </ul>
        </div>
    </div>
</div>
