<?php
/*=========================================================================
MIDAS Server
Copyright (c) Kitware SAS. 20 rue de la Villette. All rights reserved.
69328 Lyon, FRANCE.

See Copyright.txt for details.
This software is distributed WITHOUT ANY WARRANTY; without even
the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE.  See the above copyright notices for more information.
=========================================================================*/

$this->headScript()->appendFile($this->coreWebroot . '/public/js/jquery/jquery.form.js');
$this->headScript()->appendFile($this->coreWebroot . '/public/js/admin/admin.index.js');
?>
<link type="text/css" rel="stylesheet" href="<?php echo $this->coreWebroot?>/public/css/admin/admin.index.css" />
<link type="text/css" rel="stylesheet" href="<?php echo $this->coreWebroot?>/public/css/common/common.genericPage.css" />
<div class="viewMain">

  <img class="tabsLoading" alt=""  src="<?php echo $this->coreWebroot?>/public/images/icons/loading.gif" />
  <div class="tabs" id='tabsGeneric'>
  <ul>
    <li><a href="#tabs-configuration">Configuration</a></li>
    <li><a href="#tabs-modules">Modules</a></li>
    <li><a href="#tabs-assetstore">Assetstores</a></li>
    <li><a href="<?php echo $this->webroot?>/admin/upgrade">Upgrade</a></li>    
    <li><a href="<?php echo $this->webroot?>/admin/dashboard">Dasboard</a></li>    
    <li><a href="<?php echo $this->webroot?>/admin/showlog">Logs</a></li>
  </ul>
    <div id="tabs-configuration">
     <?php
      echo "
      <form class='genericForm' id='configForm' method='{$this->configForm['method']}'  action='{$this->configForm['action']}'>
      <h3>Configuration:</h3>
              <div class='installName'>
                <label for='name'>Application name</label>
                {$this->configForm['name']}
              </div>
              <div class='description'>
                <label for='name'>Description</label>
                {$this->configForm['description']}
              </div>
              <div class='keywords'>
                <label for='name'>Keywords</label>
                {$this->configForm['keywords']}
              </div>
              <div class='installLang'>
                <label for='lang'>Language</label>
                {$this->configForm['lang']}
              </div>
              <div class='installEnvironment'>
                <label for='environment'>Environment</label>
                {$this->configForm['environment']}
              </div>
              <div class='installTimezone'>
                <label for='environment'>Timezone</label>
                {$this->configForm['timezone']}
              </div>
              <div class='installSmartoptimizer'>
                <label for='smartoptimizer'>CSS and Javascript optimizer</label>
                {$this->configForm['smartoptimizer']}
              </div>
              <div class='defaultLicense'>
                <label for='licenseSelect'>Default license</label>
                ".$this->element('license')."
              </div>
          <div>
            {$this->configForm['submitConfig']}
          </div>
       </form>";
       ?>
    </div>
    <div id="tabs-assetstore">
     <?php
     foreach($this->assetstores as $assetstore)
       {
       echo "<div class='assetstoreElement'>
              <b><span class='assetstoreName'>{$assetstore->getName()}</span></b>
               (";
       if($assetstore->default)
         {
         echo "<span class='defaultAssetstore' element='{$assetstore->getKey()}'>default assetstore</span>";
         }
       else
         {
         echo "<a class='defaultAssetstoreLink' element='{$assetstore->getKey()}'>set as default</a>";
         }
       echo ")<br/>";
       if($assetstore->totalSpaceText==false)
         {
         echo "<b>Unable to access assetstore</b>";
         }
       else
         {
         echo "Total space: {$assetstore->totalSpaceText}<br/>";
         if(($assetstore->freeSpace/$assetstore->totalSpace<0.10))
           {
           echo "<b>Free space: {$assetstore->freeSpaceText}. Almost full!!!</b>";
           }
         else
           {
           echo "<b>Free space: {$assetstore->freeSpaceText}</b>";
           }
         }
       echo "<br/>Path: <span class='assetstorePath'>{$assetstore->getPath()}</span>";
       echo "<br/>Type: ";
       switch ($assetstore->getType())
         {
          case MIDAS_ASSETSTORE_LOCAL:
              echo "Local";
              break;
          case MIDAS_ASSETSTORE_REMOTE:
              echo "Remote";
              break;
          case MIDAS_ASSETSTORE_AMAZON:
              echo "Amazon S3";
              break;
          default:
              echo $assetstore->getType();
              break;
         }
       echo "<br/><a class='editAssetstoreLink' element='{$assetstore->getKey()}'>edit</a> <a class='removeAssetstoreLink' element='{$assetstore->getKey()}'>remove</a>";
       echo"</div>";
       }
     ?>
      
      <a class="load-newassetstore" href="#newassetstore-form" rel="#newassetstore-form" title="<?php echo $this->t('Add a new assetstore')?>">Add a new assetstore</a>
      <br/>
      <a  href="<?php echo $this->webroot?>/import" >Import local files</a>

      <div id="newassetstore-form"  style="display:none">
         <?php echo $this->assetstoreForm; ?>
      </div>
    </div>
    
    <div id="tabs-modules">
      <table>
      <?php
      foreach($this->modulesList as $key=>$module)
         {
          if(isset($module->db->{$this->databaseType}))
            {
             echo "
               <tr class='moduleElement'>
                  <td>
                       <input type='checkbox' class='moduleCheckbox' module='{$key}' name='module[{$key}]'   ".((in_array($key, $this->modulesEnable))?'checked':'')."/>
                  </td>    
                  <td>
                  <b>{$module->fullname}</b><br/>
                  {$module->description}
                  </td>";              
                  if($module->configPage)
                    {
                  echo "
                  <td class='configLink' style='display:none;'>
                    <a href='{$this->webroot}/$key/config'>View configuration</a>
                  </td>";
                    }
                  echo "
               </tr>
              ";
            }
         }
      ?>
      </table>
    </div>
  </div>

</div>
<div class="viewSideBar">
  
 
</div>






