<?php
/*=========================================================================
 MIDAS Server
 Copyright (c) Kitware SAS. 26 rue Louis Guérin. 69100 Villeurbanne, FRANCE
 All rights reserved.
 More information http://www.kitware.com

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

         http://www.apache.org/licenses/LICENSE-2.0.txt

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
=========================================================================*/

$this->headScript()->appendFile($this->coreWebroot.'/public/js/admin/admin.migrate.js');
$this->headScript()->appendFile($this->coreWebroot.'/public/js/jquery/jquery.form.js');

$this->headLink()->appendStylesheet($this->coreWebroot.'/public/css/jquery/jquery.filetree.css');
$this->headLink()->appendStylesheet($this->coreWebroot.'/public/css/admin/admin.migrate.css');
$this->headLink()->appendStylesheet($this->coreWebroot.'/public/css/assetstore/assetstore.add.css');
?>

<h2> Migrating from MIDAS version 2 to MIDAS version 3</h2>
<?php
echo $this->migrateForm;

echo $this->element('serversidefilechooser',
                    array('id'=>'midas2_assetstore_button',
                          'fileFilterErrorMsg' => 'Select the MIDAS2 assetstore directory on the server',
                          'destSelector' => '#midas2_assetstore',
                   ))
?>

<div id="newassetstore-form"  style="display:none">
   <?php echo $this->assetstoreForm; ?>
</div>

<script language="javascript">
var assetstores = eval(<?php echo json_encode($this->assetstores)?>);
</script>
