<?php
/*=========================================================================
 MIDAS Server
 Copyright (c) Kitware SAS. 26 rue Louis Guérin. 69100 Villeurbanne, FRANCE
 All rights reserved.
 More information http://www.kitware.com

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

         http://www.apache.org/licenses/LICENSE-2.0.txt

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
=========================================================================*/
?>
<link type="text/css" rel="stylesheet" href="<?php echo $this->coreWebroot?>/public/css/admin/admin.upgrade.css" />
<script type="text/javascript" src="<?php echo $this->coreWebroot?>/public/js/admin/admin.upgrade.js"></script>

<h3>Core:</h3>
Current version: <?php echo $this->core['currentText']?><br/>
<?php
  if($this->core['current']<$this->core['target'])
    {
    echo "Need to upgrade to version: ".$this->core['targetText'];
    }
  else
    {
    echo "Midas Platform is up to date.";
    }
?>
<h3>Modules:</h3>
<?php
foreach($this->modules as $name => $module)
  {
  echo "<b>{$name}</b><br/>";
  echo "Current version: {$module['currentText']} <br/>";
  if($module['current']<$module['target'])
    {
    echo "Need to upgrade to version: ".$module['targetText'].'<br/>';
    }
  }

if(count($this->modules) == 0)
  {
  echo "No module enabled.";
  }
?>
<br/>
<br/>
<form id='upgradeMIDAS'  action="<?php echo $this->webroot?>/admin/upgrade" method="post">
  <input type='submit' class="globalButton" value="Upgrade"/>
</form>
<br/><br/>
<a href="<?php echo $this->webroot?>/admin/migratemidas2">Upgrade from MIDAS2</a>
