<?php
/*=========================================================================
 Midas Server
 Copyright Kitware SAS, 26 rue Louis Guérin, 69100 Villeurbanne, France.
 All rights reserved.
 For more information visit http://www.kitware.com/.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

         http://www.apache.org/licenses/LICENSE-2.0.txt

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
=========================================================================*/
?>
<link type="text/css" rel="stylesheet" href="<?php echo $this->coreWebroot ?>/public/css/admin/admin.upgrade.css"/>
<script type="text/javascript" src="<?php echo $this->coreWebroot ?>/public/js/admin/admin.upgrade.js"></script>

<h3>Core:</h3>
Current version: <?php echo $this->escape($this->core['current']); ?><br/>
<?php
if (version_compare($this->core['current'], $this->core['target']) === -1) {
    echo 'Need to upgrade to version: '.$this->escape($this->core['target']);
} else {
    echo 'Midas Server is up to date.';
}
?>
<h3>Modules:</h3>
<?php
foreach ($this->modules as $name => $module) {
    echo '<b>'.$this->escape($name).'</b><br/>';
    echo 'Current version: '.$this->escape($module['current']).'<br/>';
    if (version_compare($module['current'], $module['target']) === -1) {
        echo 'Need to upgrade to version: '.$this->escape($module['target']).'<br/>';
    }
}

if (count($this->modules) === 0) {
    echo 'No modules enabled.';
}
?>
<br/>
<br/>
<form id="upgradeMIDAS" action="<?php echo $this->webroot; ?>/admin/upgrade" method="post">
    <input type="submit" class="globalButton" value="Upgrade"/>
</form>
<a href="<?php echo $this->webroot; ?>/admin/migratemidas2">Upgrade from Midas Server 2.x</a>
