<?php
/*=========================================================================
MIDAS Server
Copyright (c) Kitware SAS. 20 rue de la Villette. All rights reserved.
69328 Lyon, FRANCE.

See Copyright.txt for details.
This software is distributed WITHOUT ANY WARRANTY; without even
the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE.  See the above copyright notices for more information.
=========================================================================*/
$this->headScript()->appendFile($this->moduleWebroot . '/public/js/index/index.dashboard.js');
$this->headScript()->appendFile($this->coreWebroot . '/public/js/jquery/jquery.dashboard.min.js');
?>
<link type="text/css" rel="stylesheet" href="<?php echo $this->moduleWebroot?>/public/css/index/index.dashboard.css" />
<link type="text/css" rel="stylesheet" href="<?php echo $this->coreWebroot?>/public/css/jquery/jquery.dashboard.css" />

 <div id="dashboard" class="dashboard">
    <div class="layout layout-ba"><div class="column first column-first"></div><div class="column second column-second"></div></div>
 </div>
