<?php
/*=========================================================================
 MIDAS Server
 Copyright (c) Kitware SAS. 26 rue Louis Guérin. 69100 Villeurbanne, FRANCE
 All rights reserved.
 More information http://www.kitware.com

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

         http://www.apache.org/licenses/LICENSE-2.0.txt

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
=========================================================================*/
?>
<link type="text/css" rel="stylesheet" href="<?php echo $this->moduleWebroot?>/public/css/index/index.selectaction.css" />
<script type="text/javascript" src="<?php echo $this->moduleWebroot?>/public/js/index/index.selectaction.js"></script>
<div id="selectactionBlock">
   <br/>
     Click on the action of you choice to start using the MIDAS processing platform.

     <br/><br/>
     <div id="seperatorSelectAction">
     </div>
     <br/>
       <div class="blockSet" id="blockDashboardLink">
        <table>
          <tbody><tr>
            <td class="logo">
              <img alt="" src="<?php echo  $this->moduleWebroot?>/public/images/bigicon-dashboard.png" />
            </td>
            <td>
              <h4 >Access your dashboard</h4>
              <span style="color:grey;">The dasboard shows the results and the status of your jobs.</span>
            </td>
          </tr>
        </tbody>
        </table>
      </div>
      <div class="blockSet" id="blockManageScheduledLink">
        <table>
          <tbody><tr>
            <td class="logo">
              <img alt="" src="<?php echo  $this->moduleWebroot?>/public/images/bigicon-managescheduled.png" />
            </td>
            <td>
              <h4>Manage your scheduled jobs</h4>
              <span style="color:grey;">Allow you to view and manage scheduled jobs.</span>
            </td>
          </tr>
        </tbody>
        </table>
      </div>
     <br/>
     <div class="blockSet" id="blockCreateLink">
        <table>
          <tbody><tr>
            <td class="logo">
              <img alt="" src="<?php echo  $this->moduleWebroot?>/public/images/bigicon-job.png" />
            </td>
            <td>
              <h4 >Create a new job</h4>
              <span style="color:grey;">Run a process one or multiple inputs and parameters.</span>
            </td>
          </tr>
        </tbody>
        </table>
      </div>
      <div class="blockSet" id="blockCreateScheduledLink">
        <table>
          <tbody><tr>
            <td class="logo">
              <img alt="" src="<?php echo  $this->moduleWebroot?>/public/images/bigicon-scheduled.png" />
            </td>
            <td>
              <h4>Schedule a new job</h4>
              <span style="color:grey;">Allow you to run periodically a job on a set of data.</span>
            </td>
          </tr>
        </tbody>
        </table>
      </div>
     <br/>

</div>
