<?php
/*=========================================================================
MIDAS Server
Copyright (c) Kitware SAS. 20 rue de la Villette. All rights reserved.
69328 Lyon, FRANCE.

See Copyright.txt for details.
This software is distributed WITHOUT ANY WARRANTY; without even
the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE.  See the above copyright notices for more information.
=========================================================================*/

?>
<link type="text/css" rel="stylesheet" href="<?php echo $this->moduleWebroot?>/public/css/index/index.selectaction.css" />
<script type="text/javascript" src="<?php echo $this->moduleWebroot?>/public/js/index/index.selectaction.js"></script>
<div id="selectactionBlock">
   <br/>
     Click on the action of you choice to start using the MIDAS processing platform.

     <br/><br/>
     <div id="seperatorSelectAction">
     </div>
     <br/>
     <!--
      <div class="blockSet" id="blockCreateScheduledLink">
        <table>
          <tbody><tr>
            <td class="logo">
              <img alt="" src="<?php echo  $this->moduleWebroot?>/public/images/bigicon-scheduled.png" />
            </td>
            <td>
              <h4>Schedule a new workflow</h4>
              <span style="color:grey;">Allow you to run periodically a workflow on a set of data.</span>
            </td>
          </tr>
        </tbody>
        </table>
      </div>
     -->
      <div class="blockSet" id="blockManageScheduledLink">
        <table>
          <tbody><tr>
            <td class="logo">
              <img alt="" src="<?php echo  $this->moduleWebroot?>/public/images/bigicon-managescheduled.png" />
            </td>
            <td>
              <h4>Manage your scheduled workflows</h4>
              <span style="color:grey;">Allow you to view and manage scheduled workflows.</span>
            </td>
          </tr>
        </tbody>
        </table>
      </div>
     <br/>
     <?php
     $results = Zend_Registry::get('notifier')->callback("CALLBACK_REMOTEPROCESSING_ENABLEDASHBOARD", array());
     foreach($results as $result)
        {
        if($result !==false)
          {
          ?>
          <div class="blockSet" id="blockDashboardLink">
            <input type="hidden" id="customDashboardUrl" value ="<?php echo $result?>"/>
            <table>
              <tbody><tr>
                <td class="logo">
                  <img alt="" src="<?php echo  $this->moduleWebroot?>/public/images/bigicon-dashboard.png" />
                </td>
                <td>
                  <h4 >Access your dashboard</h4>
                  <span style="color:grey;">The dasboard shows the results and the status of your workflow.</span>
                </td>
              </tr>
            </tbody>
            </table>
          </div>
          <?php
          }
        }
      ?>


</div>