<?php
/*=========================================================================
MIDAS Server
Copyright (c) Kitware SAS. 20 rue de la Villette. All rights reserved.
69328 Lyon, FRANCE.

See Copyright.txt for details.
This software is distributed WITHOUT ANY WARRANTY; without even
the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE.  See the above copyright notices for more information.
=========================================================================*/

?>
<link type="text/css" rel="stylesheet" href="<?php echo $this->moduleWebroot?>/public/css/index/index.selectaction.css" />
<script type="text/javascript" src="<?php echo $this->moduleWebroot?>/public/js/index/index.selectaction.js"></script>
<div id="selectactionBlock">
   <br/>
     Click on the action of you choice to start using the MIDAS processing platform.

     <br/><br/>
     <div id="seperatorSelectAction">
     </div>
     <br/>
       <div class="blockSet" id="blockDashboardLink">
        <table>
          <tbody><tr>
            <td class="logo">
              <img alt="" src="<?php echo  $this->moduleWebroot?>/public/images/bigicon-dashboard.png" />
            </td>
            <td>
              <h4 >Access your dashboard</h4>
              <span style="color:grey;">The dasboard shows the results and the status of your jobs.</span>
            </td>
          </tr>
        </tbody>
        </table>
      </div>
      <div class="blockSet" id="blockManageScheduledLink">
        <table>
          <tbody><tr>
            <td class="logo">
              <img alt="" src="<?php echo  $this->moduleWebroot?>/public/images/bigicon-managescheduled.png" />
            </td>
            <td>
              <h4>Manage your scheduled jobs</h4>
              <span style="color:grey;">Allow you to view and manage scheduled jobs.</span>
            </td>
          </tr>
        </tbody>
        </table>
      </div>
     <br/>
     <div class="blockSet" id="blockCreateLink">
        <table>
          <tbody><tr>
            <td class="logo">
              <img alt="" src="<?php echo  $this->moduleWebroot?>/public/images/bigicon-job.png" />
            </td>
            <td>
              <h4 >Create a new job</h4>
              <span style="color:grey;">Run a process one or multiple inputs and parameters.</span>
            </td>
          </tr>
        </tbody>
        </table>
      </div>
      <div class="blockSet" id="blockCreateScheduledLink">
        <table>
          <tbody><tr>
            <td class="logo">
              <img alt="" src="<?php echo  $this->moduleWebroot?>/public/images/bigicon-scheduled.png" />
            </td>
            <td>
              <h4>Schedule a new job</h4>
              <span style="color:grey;">Allow you to run periodically a job on a set of data.</span>
            </td>
          </tr>
        </tbody>
        </table>
      </div>
     <br/>

</div>