<?php
/*=========================================================================
MIDAS Server
Copyright (c) Kitware SAS. 20 rue de la Villette. All rights reserved.
69328 Lyon, FRANCE.

See Copyright.txt for details.
This software is distributed WITHOUT ANY WARRANTY; without even
the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE.  See the above copyright notices for more information.
=========================================================================*/

echo '<script type="text/javascript" src="' . $this->coreWebroot . '/public/js/folder/folder.createfolder.js?'.time().'"></script>';
echo '<script type="text/javascript" src="' . $this->coreWebroot . '/public/js/jquery/jquery.form.js"></script>';
?>

<link type="text/css" rel="stylesheet" href="<?php echo $this->coreWebroot?>/public/css/folder/folder.createfolder.css" />

<form id="createFolderForm" class="genericForm" method="POST"  action="<?php echo $this->webroot?>/folder/createFolder">
   <input type="hidden" name="folderId" value="<?php echo $this->parentFolder->getKey()?>"/>
      <div >
        <label for="name"><?php echo $this->t("Name")?></label>
        <?php echo $this->form['name']?>
      </div>
      <div >
        <label for="description"><?php echo $this->t("Description")?></label>
        <?php echo $this->form['description']?>
      </div>
      <div >
        <label for="teaser"><?php echo $this->t("Teaser")?></label>
        <?php echo $this->form['teaser']?>
      </div>
     
      <div>
         <input type='submit' name='createFolder' value='<?php echo $this->t('Create')?>'/>
      </div>
</form>
