<?php
/*=========================================================================
 MIDAS Server
 Copyright (c) Kitware SAS. 26 rue Louis Guérin. 69100 Villeurbanne, FRANCE
 All rights reserved.
 More information http://www.kitware.com

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

         http://www.apache.org/licenses/LICENSE-2.0.txt

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
=========================================================================*/

echo '<script type="text/javascript" src="'.$this->coreWebroot.'/public/js/folder/folder.deletedialog.js?'.time(
    ).'"></script>';
?>

Are you sure you want to delete the folder
<b><?php echo $this->folder->getName() ?></b>? (<?php echo $this->sizeStr ?>)
<br/><br/>
<div id="deleteFolderProgress"></div>
<div id="deleteFolderProgressMessage"></div>
<br/><br/>
<input id="deleteFolderId" type="hidden" value="<?php echo $this->folder->getKey() ?>"/>
<div style="float: right;">
    <input class="globalButton deleteFolderYes" element="'+id+'" type="button" value="Yes"/>
    <input style="margin-left:15px;" class="globalButton deleteFolderNo" type="button" value="No"/>
</div>
