<?php
/*=========================================================================
MIDAS Server
Copyright (c) Kitware SAS. 20 rue de la Villette. All rights reserved.
69328 Lyon, FRANCE.

See Copyright.txt for details.
This software is distributed WITHOUT ANY WARRANTY; without even
the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE.  See the above copyright notices for more information.
=========================================================================*/

echo '<script type="text/javascript" src="' . $this->coreWebroot . '/public/js/folder/folder.edit.js?'.time().'"></script>';
?>

<link type="text/css" rel="stylesheet" href="<?php echo $this->coreWebroot?>/public/css/folder/folder.edit.css" />

<form id="editFolderForm" class="genericForm" method="<?php echo $this->form['method']?>"  action="<?php echo $this->form['action']?>">
   <input type="hidden" name="folderId" value="<?php echo $this->folderDao->getKey()?>"/>
      <div >
        <label for="name"><?php echo $this->t("Name")?></label>
        <?php echo $this->form['name']?>
      </div>
      <div >
        <label for="description"><?php echo $this->t("Description")?></label>
        <?php echo $this->form['description']?>
      </div>
      <div >
        <label for="teaser"><?php echo $this->t("Teaser")?></label>
        <?php echo $this->form['teaser']?>
      </div>
      <div>
        <?php echo $this->form['submit']?>
      </div>
</form>