<?php
/*=========================================================================
MIDAS Server
Copyright (c) Kitware SAS. 20 rue de la Villette. All rights reserved.
69328 Lyon, FRANCE.

See Copyright.txt for details.
This software is distributed WITHOUT ANY WARRANTY; without even
the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE.  See the above copyright notices for more information.
=========================================================================*/

$this->headScript()->appendFile($this->coreWebroot . '/public/js/jquery/jquery.form.js');
$this->headScript()->appendFile($this->coreWebroot.'/public/js/jquery/jquery.checkboxrange.js');
$this->headScript()->appendFile($this->coreWebroot.'/public/js/folder/folder.view.js');
$this->headScript()->appendFile($this->coreWebroot.'/public/js/common/common.browser.js');
?>
<link type="text/css" rel="stylesheet" href="<?php echo $this->coreWebroot?>/public/css/common/common.genericPage.css" />
<link type="text/css" rel="stylesheet" href="<?php echo $this->coreWebroot?>/public/css/common/common.browser.css" />
<link type="text/css" rel="stylesheet" href="<?php echo $this->coreWebroot?>/public/css/folder/folder.view.css" />

<div class="viewMain">
  


  <div class="tabs" id='tabsGeneric'>
    <ul>
      <li><a href="#tabs-1"><?php echo $this->t("Data")?></a></li>
      <li><a href="#tabs-2"><?php echo $this->t('Info');?></a></li>
    </ul>
  <div class="genericBigButton genericWrapperTopRight">
    <?php
    echo "<a  href='{$this->webroot}/download/?folders={$this->mainFolder->getKey()}'>";
    echo $this->t('Download');  
    echo '</a>';
     ?>
  </div>
  <div id="tabs-1">


  <img class="tableLoading" alt="" src="<?php echo $this->coreWebroot?>/public/images/icons/loading.gif"/>
  <table id="browseTable" class="midasTree">
    <thead>
      <tr>
        <th class="thData"><?php echo $this->t('Name');?></th>
        <th class="thSize"><?php echo $this->t('Size');?></th>
        <th class="thDate"><?php echo $this->t('Modified');?></th>
        <th class="thCheckbox"><input type="checkbox" id="browseTableHeaderCheckbox" /></th>
      </tr>
    </thead>
    <tbody>
      <?php
      $node=1;  
        
      foreach($this->folders as $folder)
        {
        echo "<tr id='node--$node' deletable='true' privacy='{$folder->getPrivacyStatus()}' policy='{$folder->policy}' class='parent' type='folder' element='{$folder->getFolderId()}' ajax='{$folder->getFolderId()}'>";
        echo "  <td class='treeBrowseElement'><span class='folder'>{$this->slicename($folder->getName(),40)}</span></td>";
        echo "  <td><img class='folderLoading'  element='{$folder->getFolderId()}' alt='' src='{$this->coreWebroot}/public/images/icons/loading.gif'/></td>";
        echo "  <td>{$this->Date->ago($folder->getDateUpdate(),true)}</td>";
        echo "  <td><input type='checkbox' class='treeCheckbox' type='folder' element='{$folder->getFolderId()}' /></td>";
        echo "</tr>";
        $node++;
        }
      
      foreach($this->items as $item)
        {
        echo "<tr id='node--$node' policy='{$item->policy}' privacy='{$item->getPrivacyStatus()}' class='' type='item' element='{$item->getItemId()}' >";
        echo "  <td class='treeBrowseElement'><span class='file'>{$this->slicename($item->getName(),40)}</span></td>";
        echo "  <td>{$item->size}</td>";
        echo "  <td>{$this->Date->ago($item->getDateUpdate(),true)}</td>";
        echo "  <td><input type='checkbox' class='treeCheckbox' type='item' element='{$item->getItemId()}' /></td>";
        echo "</tr>";
        $node++;
        }
      ?>          
       
    </tbody>
  </table>
  
    <?php 
  if(empty($this->folders)&&empty($this->items))
    {    
    echo "<h4>{$this->t("This folder is empty")}.</h4>";
    }
    ?>

    </div>
    <div id="tabs-2">
      <?php 
      $descriptionMainFolder=$this->mainFolder->getDescription();
      echo $descriptionMainFolder?>
    </div>
  </div>

</div>

<div id="guideRobot">
   <?php
   foreach($this->folders as $folder)    
      {
      echo "<a href='{$this->webroot}/folder/{$folder->getKey()}'>{$folder->getName()}</a> ";
      } 
   foreach($this->items as $item) 
      {
      echo "<a href='{$this->webroot}/item/{$item->getKey()}'>{$item->getName()}</a> ";
      } 
    ?>  
</div>

<div class="viewSideBar">
  <?php
  if(empty($this->folders)&&empty($this->items))
    {
    echo '<div class="sideElementFirst viewInfo">';
    }
  else
    {
    echo '
  <div class="sideElementFirst viewAction">
    <h1>Actions</h1>
    <ul>
      <li>
        
      </li>
    </ul>
  </div>
  <div class="sideElement viewSelected" >
  <h1>'.$this->t('Selected').'<span></span></h1>
    <span></span>
  </div>
  <div class="sideElementLast viewInfo">';
    }?>
    
  
    <h1>Info</h1>    
    <img class="infoLoading" style="display:none;" alt="" src="<?php echo $this->coreWebroot?>/public/images/icons/loading.gif"/>
    <div class="ajaxInfoElement">
    </div>
  </div>
</div>

<?php
$policy=MIDAS_POLICY_READ;
if($this->isModerator||$this->isAdmin)
  {
  $policy=MIDAS_POLICY_WRITE;
  }
?>

<div class="defaultSideTrigger" policy='<?php echo $policy?>' type='folder' element='<?php echo $this->mainFolder->getFolderId() ?>'>
</div>


