<link href="<?php echo $this->webroot?>/public/css/install/install.css" rel="stylesheet" type="text/css" />

<div class="viewMain"> 

  <h2>Welcome to MIDAS!</h2>
    <p>MIDAS is a collection of server, client, and stand-alone tools for data archiving, analysis, and access.</p>
    <ul>
      <li>Hosts public and private collections of data</li>
      <li>Handles massive collections and images</li>
      <li>Manages image and non-image files and meta-data</li>
      <li>Integrates BatchMake technology for server-side and stand-alone batch processing</li>
      <li>Builds upon open source code and open standards</li>
      </ul>
      <div class="separator"></div>
      <h3>Installation</h3>
      This script will guide you during the installation of MIDAS. 
      MIDAS will store the datasets and related information in these directories.
      Make sure they are fitting your installation or modify your config.php file.
      <br/><br/>For more information go to: <a href="http://www.kitware.com/midaswiki/index.php/Installation">http://www.kitware.com/midaswiki/index.php/Installation</a>

      <h3>System check</h3>
  <?php
    echo "<ul>";
    if(!empty($this->phpextension_missing))
      {
      foreach($this->phpextension_missing as $missing)
        {
        echo "<li><span style=\"color:#d48304\"> $missing </span> </li>";
        }
      }

    if($this->convertfound[0]==false)
      {
      echo "<li><span style=\"color:#d48304\"> {$this->convertfound[1]}</span>";
      if(strstr(PHP_OS,"WIN"))
        {
        echo " <br/>If you have installed Image Magick and it still doesn't work. Copy the convert.exe file to im-convert.exe in the Image Magick Folder. There may be a conflict with the windows convert application.";
        }
      echo "</li>";
      }
      
    if($this->writable==false)
      {
      echo "<li><span style=\"color:red\"> Unable to right in the application folder: {$this->basePath}. Please check you apache server permissions</span> </li>";
      }
      
    if($this->writable&&$this->convertfound[0]&&empty($this->phpextension_missing))
      {
      echo "<li><span style=\"color:green\"> Your system is OK</span> </li>";
      }
    echo "</ul>";
    
    if($this->writable!=false)
      {
      echo "<form method='post' action=''>";
      echo "<input type='submit' name='submit' value='Go to next step'>";
      echo "</form>";
      }
    else
      {
      echo "<input type='submit' name='submit' value='Go to next step' disabled> <br/>";
      echo "Please fix the differents problems to be able to access to the next step.";
      }
  ?>

</div>