<?php
/*=========================================================================
 Midas Server
 Copyright Kitware SAS, 26 rue Louis Guérin, 69100 Villeurbanne, France.
 All rights reserved.
 For more information visit http://www.kitware.com/.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

         http://www.apache.org/licenses/LICENSE-2.0.txt

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
=========================================================================*/
?>
<link href="<?php echo $this->coreWebroot ?>/public/css/install/install.css" rel="stylesheet" type="text/css"/>

<div class="viewMain">
    <h2>Welcome to Midas Platform!</h2>

    <p>Midas Platform is a collection of server, client, and standalone tools for data archiving, analysis, and
        access.</p>
    <ul>
        <li>Hosts public and private collections of data;</li>
        <li>Handles massive collections and images;</li>
        <li>Manages images, files, and metadata;</li>
        <li>Integrates BatchMake technology for server-side and standalone batch processing;</li>
        <li>Builds upon open source code and open standards.</li>
    </ul>
    <div class="separator"></div>
    <h3>Installation</h3>
    This script will guide you during the installation of Midas Platform.<br/><br/>
    For more information go to
    <a href="https://midas-server.readthedocs.org/en/latest/">Read the Docs</a>.

    <h3>System check</h3>
    <?php
    echo "<ul>";
    if (!empty($this->phpextension_missing)) {
        foreach ($this->phpextension_missing as $missing) {
            echo "<li><span style=\"color:#d48304\">{$this->escape($missing)}</span></li>";
        }
    }

    if (empty($this->phpextension_missing)) {
        echo "<li><span style=\"color:green\"> Your system is OK.</span></li>";
    }
    echo "</ul>";

    if (empty($this->phpextension_missing)) {
        echo "<form method='post' action=''>";
        echo "<input type='submit' name='submit' value='Go to next step'>";
        echo "</form>";
    } else {
        echo "<input type='submit' name='submit' value='Go to next step' disabled><br/>";
        echo "Please fix the above issues to proceed to the next step.";
    }
    ?>
</div>
