<link href="<?php echo $this->webroot?>/public/css/install/install.css" rel="stylesheet" type="text/css" />
<link href="<?php echo $this->webroot?>/public/css/install/install.step2.css" rel="stylesheet" type="text/css" />

<?php
  $this->headScript()->appendFile($this->webroot.'/public/js/install/install.step2.js');
?>

<div class="viewMain"> 

   <h3>Select a database type:</h3>
   
   <?php 
   echo "<select id='databaseType'>";
   echo "<option value=''>Please select a database</option>";
    foreach($this->databaseType as $d=>$form)
      {
      echo "<option value='{$d}'>$d</option>";
      }
   echo "</select>";
   
   foreach($this->databaseType as $d=>$form)
      {
      echo "<div class='dbForm' id='form$d'>";
      echo "<form class='genericForm' method='{$form['method']}'  action='{$form['action']}'>";
      if(isset($this->phpextension_missing[$d]))
        {
        echo "<span style='color:red;'>{$this->phpextension_missing[$d]}</span>";
        }

      echo "  {$form['type']}
              <div>
                <label for='host'>Host</label>
                {$form['host']}
              </div>
              <div>
                <label for='username'>Username</label>
                {$form['username']}
              </div>
              <div>
                <label for='password'>Password</label>
                {$form['password']}
              </div>
              <div>
                <label for='dbname'>Database</label>
                {$form['dbname']}
              </div>
              <div>
                <label for='port'>Port</label>
                {$form['port']}
              </div>
              <div>
                <div id='dbResult'>
                  <div>
                <img style='display:none;' class='testLoading'  alt='' src='{$this->webroot}/public/images/icons/loading.gif'/>
                <img style='display:none;' class='testOk'  alt='' src='{$this->webroot}/public/images/icons/ok.png'/>
                <img style='display:none;' class='testNok'  alt='' src='{$this->webroot}/public/images/icons/nok.png'/>             
                <span class='testError'/>
                  </div>
                </div>
                
              </div>";
                
      echo "  <h3>Set up Administrator account:</h3> 
        
              <div >
                <label for='email'>E-mail</label>
                 {$form['email']}
              </div>
              <div >
                <label for='firstname'>Firstname</label>
                 {$form['firstname']}
              </div>
              <div>
                <label for='lastname'>Lastname</label>
                 {$form['lastname']}
              </div>
              <div>
                <label for='userpassword1'>Password</label>
                 {$form['userpassword1']}
              </div>
              <div>
                <label for='userpassword2'>Confirm Password</label>
                 {$form['userpassword2']}
              </div>
              ";
              
      echo "    <div>
                {$form['submit']}
                </div>
              </form>";
      echo "</div>";
      }
   ?>
  

</div>