<?php
/*=========================================================================
 MIDAS Server
 Copyright (c) Kitware SAS. 26 rue Louis Guérin. 69100 Villeurbanne, FRANCE
 All rights reserved.
 More information http://www.kitware.com

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

         http://www.apache.org/licenses/LICENSE-2.0.txt

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
=========================================================================*/
?>
<link href="<?php echo $this->coreWebroot ?>/public/css/install/install.css" rel="stylesheet" type="text/css"/>
<link href="<?php echo $this->coreWebroot ?>/public/css/install/install.step2.css" rel="stylesheet" type="text/css"/>

<?php
$this->headScript()->appendFile($this->coreWebroot.'/public/js/install/install.step2.js');
?>

<div class="viewMain">

    <h3>Select a database type:</h3>

    <?php
    echo "<select id='databaseType'>";
    echo "<option value=''>Please select a database</option>";
    foreach ($this->databaseType as $d => $form) {
        echo "<option value='{$this->escape($d)}'>{$this->escape($d)}</option>";
    }
    echo "</select>";

    foreach ($this->databaseType as $d => $form) {
        echo "<div class='dbForm' id='form{$this->escape($d)}'>";
        echo "<form class='genericForm' method='{$form['method']}'  action='{$form['action']}'>";
        echo "  {$form['type']}
              <div class='configDBForm'>
                <div>
                  <label for='host'>Host</label>
                  {$form['host']}
                </div>
                <div>
                  <label for='port'>Port</label>
                  {$form['port']}
                </div>
                <div>
                  <label for='unix_socket'>Socket</label>
                  {$form['unix_socket']}
                </div>
                <div>
                  <label for='dbname'>Database</label>
                  {$form['dbname']}
                </div>
                <div>
                  <label for='username'>Username</label>
                  {$form['username']}
                </div>
                <div>
                  <label for='password'>Password</label>
                  {$form['password']}
                </div>
                <div>
                  <div id='dbResult'>
                    <div>
                  <img style='display:none;' class='testLoading'  alt='' src='{$this->coreWebroot}/public/images/icons/loading.gif'/>
                  <img style='display:none;' class='testOk'  alt='' src='{$this->coreWebroot}/public/images/icons/ok.png'/>
                  <img style='display:none;' class='testNok'  alt='' src='{$this->coreWebroot}/public/images/icons/nok.png'/>
                  <span class='testError'/>
                    </div>
                  </div>

                </div>
                <div>
                </div>
              </div>";

        echo "  <h3>Set up Administrator account:</h3>

              <div class='adminAcountForm'>
                <div>
                  <label for='firstname'>First name</label>
                   {$form['firstname']}
                </div>
                <div>
                  <label for='lastname'>Last name</label>
                   {$form['lastname']}
                </div>
                <div>
                  <label for='email'>Email</label>
                   {$form['email']}
                </div>
                <div>
                  <label for='userpassword1'>Password</label>
                   {$form['userpassword1']}
                </div>
                <div>
                  <label for='userpassword2'>Confirm password</label>
                   {$form['userpassword2']}
                </div>
                <div>
                  <label for='gravatar'>Use Gravatar to fetch user icons?</label>
                  {$form['gravatar']}
                </div>
              </div>
              ";

        echo "    <div>
                {$form['submit']}
                </div>
              </form>";
        echo "</div>";
    }
    ?>
</div>
