
<link href="<?php echo $this->webroot?>/public/css/install/install.step3.css" rel="stylesheet" type="text/css" />

<?php
  $this->headScript()->appendFile($this->webroot.'/public/js/install/install.step3.js');
?>


<div class="viewMain">
     <?php
      echo "
      <form class='genericForm' method='{$this->form['method']}'  action='{$this->form['action']}'>
      <h3>Configuration:</h3>
              <div class='installName'>
                <label for='name'>Application name</label>
                {$this->form['name']}
              </div>
              <div class='installLang'>
                <label for='lang'>Language</label>
                {$this->form['lang']}
              </div>
              <div class='installEnvironment'>
                <label for='environment'>Environment</label>
                {$this->form['environment']}
              </div>
               <div class='installProcess'>
                <label for='process'>Select process type</label>
                {$this->form['process']}
              </div>
              <div class='installTimezone'>
                <label for='environment'>Timezone</label>
                {$this->form['timezone']}
              </div>
              <div class='installSmartoptimizer'>
                <label for='smartoptimizer'>CSS and Javascript optimizer</label>
                {$this->form['smartoptimizer']}
              </div>
              <div class='installAssetstrore'>
                <label for='assetstore'>Default Assetstore</label>
                {$this->form['assetstore']}
              </div> 

       <h3>Modules:</h3>  
           <table>
                ";
       foreach($this->modules as $key=>$module)
         {
         echo "
           <tr class='moduleElement'>
              <td>
              <b>{$module->fullname}</b><br/>
              {$module->description}
              </td>
              <td>";
          if(isset($module->db->{$this->databaseType}))
            {
             echo " 
               <input type='checkbox' name='module[{$key}]'   ".(($this->defaultModules->$key==1)?'checked':'')."/>";
            }
          else
            {
            echo "
              Module not available with your database type.
              ";
            }
          echo"
              </td>              
           </tr>
          ";
         }
         echo"
          </table>
          <div>
            {$this->form['submit']}
          </div>
       </form>";
                
     ?>
</div>
<div class="viewSideBar">
  <div class="sideElementFirst " >
      <h1>Help</h1>
      <div class="installHelp">
        This page allow you to configure your installation.
      </div>
  </div>
</div>

<div class='hiddenProcces' style="display:none;">
  <?php 
echo "<br/>
    Windows:".BASE_PATH."<br/>/library/Executable/windows/32/<br/>wget.exe -O <br/>".BASE_PATH."<br/>/log/task.log<br/> http://localhost{$this->webroot}/task<br/><br/>
    Linux:  wget -O ".BASE_PATH."<br/>/log/task.log http://localhost{$this->webroot}/task";
    ?>
</div>
