<?php
/*=========================================================================
MIDAS Server
Copyright (c) Kitware SAS. 20 rue de la Villette. All rights reserved.
69328 Lyon, FRANCE.

See Copyright.txt for details.
This software is distributed WITHOUT ANY WARRANTY; without even
the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE.  See the above copyright notices for more information.
=========================================================================*/
?>
<link href="<?php echo $this->coreWebroot?>/public/css/install/install.css" rel="stylesheet" type="text/css" />
<link href="<?php echo $this->coreWebroot?>/public/css/install/install.step2.css" rel="stylesheet" type="text/css" />

<?php
  $this->headScript()->appendFile($this->coreWebroot.'/public/js/install/install.step2.js');
?>

<div class="viewMain">

   <h3>Select a database type:</h3>

   <?php
   echo "<select id='databaseType'>";
   echo "<option value=''>Please select a database</option>";
    foreach($this->databaseType as $d => $form)
      {
      echo "<option value='{$d}'>$d</option>";
      }
   echo "</select>";

   foreach($this->databaseType as $d => $form)
      {
      echo "<div class='dbForm' id='form$d'>";
      echo "<form class='genericForm' method='{$form['method']}'  action='{$form['action']}'>";
      echo "  {$form['type']}
              <div class='configDBForm'>
                <div>
                  <label for='host'>Host</label>
                  {$form['host']}
                </div>
                <div>
                  <label for='username'>Username</label>
                  {$form['username']}
                </div>
                <div>
                  <label for='password'>Password</label>
                  {$form['password']}
                </div>
                <div>
                  <label for='dbname'>Database</label>
                  {$form['dbname']}
                </div>
                <div>
                  <label for='port'>Port</label>
                  {$form['port']}
                </div>
                <div>
                  <div id='dbResult'>
                    <div>
                  <img style='display:none;' class='testLoading'  alt='' src='{$this->coreWebroot}/public/images/icons/loading.gif'/>
                  <img style='display:none;' class='testOk'  alt='' src='{$this->coreWebroot}/public/images/icons/ok.png'/>
                  <img style='display:none;' class='testNok'  alt='' src='{$this->coreWebroot}/public/images/icons/nok.png'/>
                  <span class='testError'/>
                    </div>
                  </div>

                </div>
                <div>
                </div>
              </div>";

      echo "  <h3>Set up Administrator account:</h3>

              <div class='adminAcountForm'>
                <div>
                  <label for='email'>E-mail</label>
                   {$form['email']}
                </div>
                <div >
                  <label for='firstname'>Firstname</label>
                   {$form['firstname']}
                </div>
                <div>
                  <label for='lastname'>Lastname</label>
                   {$form['lastname']}
                </div>
                <div>
                  <label for='userpassword1'>Password</label>
                   {$form['userpassword1']}
                </div>
                <div>
                  <label for='userpassword2'>Confirm Password</label>
                   {$form['userpassword2']}
                </div>
                <div>
                  <label for='gravatar'>Use Gravatar to fetch user icons?</label>
                  {$form['gravatar']}
                </div>
              </div>
              ";

      echo "    <div>
                {$form['submit']}
                </div>
              </form>";
      echo "</div>";
      }
   ?>

</div>
