<?php
/*=========================================================================
 Midas Server
 Copyright Kitware SAS, 26 rue Louis Guérin, 69100 Villeurbanne, France.
 All rights reserved.
 For more information visit http://www.kitware.com/.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

         http://www.apache.org/licenses/LICENSE-2.0.txt

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
=========================================================================*/
?>

<?php
$this->headScript()->appendFile($this->coreWebroot.'/public/js/install/install.step3.js');
?>

<div class="viewMain">
    <?php
    echo "
      <form class='genericForm' method='{$this->form['method']}'  action='{$this->form['action']}'>
      <h3>Configuration:</h3>
              <div class='installName'>
                <label for='name'>Application name</label>
                {$this->form['name']}
              </div>
              <div class='installDescription'>
                <label for='name'>Description</label>
                {$this->form['description']}
              </div>
              <div class='installLang'";
    if ((int) Zend_Registry::get('configCore')->get('internationalization', 0) === 0) {
        echo " style='display:none;' ";
    }
    echo ">
                <label for='lang'>Language</label>
                {$this->form['lang']}
              </div>
              <div class='installTimezone'>
                <label for='timezone'>Time zone</label>
                {$this->form['timezone']}
              </div>
                ";

    echo "
          </table>
          <div>
            {$this->form['submit']}
          </div>
       </form>";

    ?>
</div>
<div class="viewSideBar">
    <div class="sideElementFirst">
        <h1>Help</h1>

        <div class="installHelp">
            This page allows you to configure your installation.
        </div>
    </div>
</div>
