<?php
/*=========================================================================
 MIDAS Server
 Copyright (c) Kitware SAS. 26 rue Louis Guérin. 69100 Villeurbanne, FRANCE
 All rights reserved.
 More information http://www.kitware.com

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

         http://www.apache.org/licenses/LICENSE-2.0.txt

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
=========================================================================*/

$this->declareVars('form', 'pageTitle');
$this->headTitle($this->escape($this->pageTitle));
$this->headLink()->appendStylesheet($this->baseUrl('modules/solr/public/css/admin/admin.index.css'));
$this->headScript()->appendFile($this->baseUrl('modules/solr/public/js/admin/admin.index.js'));
?>

<div class="viewMain">
    <h1><?php echo $this->escape($this->pageTitle); ?></h1>
    <div class="instructionContainer">
        This module requires you to run a specially configured Apache Solr server. Install instructions and a link to
        download the server are hosted <a href="http://midas3.kitware.com/midas/item/19589">here</a>. If you have
        existing content in this instance, make sure to rebuild the index using the link at the bottom of this page
        once the Solr server is installed and running.
    </div>
    <?php echo $this->form; ?>
    <div class="rebuildIndexContainer">
        <p>Click the button below to rebuild the Lucene index on all items.</p>
        <div>
            <input class="globalButton" type="button" id="rebuildIndexButton" value="Rebuild index" />
        </div>
        <div id="rebuildProgressBar"></div>
        <div id="rebuildProgressMessage"></div>
    </div>
    <p><a href="<?php echo $this->url(array('controller' => 'admin', 'action' => 'index'), 'default'); ?>#tabs-modules">&laquo; Back to Modules Administration</a></p>
</div>
