<?php
define("MIDAS_POLICY_READ", 0);
define("MIDAS_POLICY_WRITE", 1);
define("MIDAS_POLICY_ADMIN", 2);

define("MIDAS_PRIVACY_PUBLIC", 0);
define("MIDAS_PRIVACY_SHARED", 1);
define("MIDAS_PRIVACY_PRIVATE", 2);
?>
