<?php
/*=========================================================================
 MIDAS Server
 Copyright (c) Kitware SAS. 26 rue Louis Guérin. 69100 Villeurbanne, FRANCE
 All rights reserved.
 More information http://www.kitware.com

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

         http://www.apache.org/licenses/LICENSE-2.0.txt

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
=========================================================================*/
?>
<script type="text/javascript" src="<?php echo $this->moduleWebroot ?>/public/js/extract/extract.dialog.js"></script>
<script type="text/javascript" src="<?php echo $this->coreWebroot ?>/public/js/jquery/jquery.form.js"></script>

<link type="text/css" rel="stylesheet" href="<?php echo $this->moduleWebroot ?>/public/css/extract/extract.dialog.css"/>

<div class="archiveExtractPromptText">
    Click <b>Extract</b> to begin extracting the archive.
</div>

<input type="checkbox" id="deleteArchiveWhenDone" checked="checked">Delete archive item when done</input>

<div id="extractArchiveProgressBar"></div>
<div id="extractArchiveProgressMessage"></div>

<div id="extractArchiveButtons" style="float: right">
    <input type='hidden' id="itemId" value="<?php echo $this->escape($this->itemId); ?>"/>
    <input class="globalButton" type='submit' name='submitButton' id='beginArchiveExtract' value='Extract'/>
    <input class="globalButton" style="margin-left: 15px;" type='button' name='declineArchiveExtract'
           id='declineArchiveExtract'
           value='Cancel'/>
</div>
