<?php
/*=========================================================================
MIDAS Server
Copyright (c) Kitware SAS. 20 rue de la Villette. All rights reserved.
69328 Lyon, FRANCE.

See Copyright.txt for details.
This software is distributed WITHOUT ANY WARRANTY; without even
the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE.  See the above copyright notices for more information.
=========================================================================*/
?>
<script type="text/javascript" src="<?php echo $this->moduleWebroot?>/public/js/extract/extract.dialog.js"></script>
<script type="text/javascript" src="<?php echo $this->coreWebroot?>/public/js/jquery/jquery.form.js"></script>

<link type="text/css" rel="stylesheet" href="<?php echo $this->moduleWebroot?>/public/css/extract/extract.dialog.css" />

<div class="archiveExtractPromptText">
Click <b>Extract</b> to begin extracting the archive.
</div>

<input type="checkbox" id="deleteArchiveWhenDone" checked="checked">Delete archive item when done</input>

<div id="extractArchiveProgressBar"></div>
<div id="extractArchiveProgressMessage"></div>

<div id="extractArchiveButtons" style="float: right">
  <input type='hidden' id="itemId" value="<?php echo $this->itemId; ?>" />
  <input class="globalButton" type='submit' name='submitButton' id='beginArchiveExtract' value='Extract' />
  <input class="globalButton" style="margin-left: 15px;" type='button' name='declineArchiveExtract' id='declineArchiveExtract'
         value='Cancel' />
</div>
