<?php
/*=========================================================================
MIDAS Server
Copyright (c) Kitware SAS. 20 rue de la Villette. All rights reserved.
69328 Lyon, FRANCE.

See Copyright.txt for details.
This software is distributed WITHOUT ANY WARRANTY; without even
the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE.  See the above copyright notices for more information.
=========================================================================*/

?>

<link type="text/css" rel="stylesheet" href="<?php echo $this->coreWebroot?>/public/css/item/item.editbitstream.css" />

<form id="editBitstreamForm" class="genericForm" method="<?php echo $this->bitstreamform['method'];?>" action="<?php echo $this->bitstreamform['action'];?>">
   <input type="hidden" name="bitstreamId" value="<?php echo $this->bitstreamDao->getKey(); ?>"/>
      <div>
        <label for="name"><?php echo $this->t('Name'); ?></label>
        <?php echo $this->bitstreamform['name']; ?>
      </div>
      <br/>
      <div>
        <label for="mimetype"><?php echo $this->t('Mimetype'); ?></label>
        <?php echo $this->bitstreamform['mimetype']; ?>
      </div>
      <br/>
      <div>
        <?php echo $this->bitstreamform['submit']?>
      </div>
</form>
