<?php
/*=========================================================================
 Midas Server
 Copyright Kitware SAS, 26 rue Louis Guérin, 69100 Villeurbanne, France.
 All rights reserved.
 For more information visit http://www.kitware.com/.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

         http://www.apache.org/licenses/LICENSE-2.0.txt

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
=========================================================================*/

echo '<script type="text/javascript" src="'.$this->coreWebroot.'/public/js/item/item.editmetadata.js"></script>';
?>

<link type="text/css" rel="stylesheet" href="<?php echo $this->coreWebroot ?>/public/css/item/item.editmetadata.css"/>

<form id="editMetadataForm" class="genericForm" method="POST"
      action="<?php echo $this->webroot ?>/item/<?php echo $this->escape($this->itemDao->getKey()); ?>">
    <?php
    if ($this->metadata) {
        echo '<input type="hidden" name="updateMetadata" value ="true"/>';
        $id = $this->metadata->getKey();
    } else {
        $id = '';
    }
    ?>
    <?php
    if ($this->itemrevision) {
        echo '<input type="hidden" name="itemrevision" value="'.$this->escape($this->itemrevision).'"/>';
    }
    ?>
    <input type="hidden" name="metadataId" value="<?php echo $this->escape($id); ?>"/>
    <input type="hidden" name="editMetadata" value="1"/>

    <div>
        <label for="metadatatype"><?php echo $this->t('Data Type'); ?></label>
        <select id="midas_item_metadata_metadatatype" name="metadatatype">
            <?php
            foreach ($this->metadataTypes as $const => $name) {
                echo '<option value="'.$this->escape($const).'"';
                if ($this->metadata && $const == $this->metadata->getMetadatatype()
                ) {
                    echo ' selected ';
                }
                echo '>'.$this->escape($name).'</option>';
            }
            ?>
        </select>
    </div>
    <div>
        <label for="element"><?php echo $this->t('Element') ?></label>
        <input id="midas_item_metadata_element" name="element" <?php if ($this->metadata) {
            echo ' readonly ';
        } ?> value="<?php echo (!$this->metadata) ? '' : $this->escape($this->metadata->getElement()); ?>"/>
    </div>
    <div>
        <label for="qualifier"><?php echo $this->t('Qualifier (Optional)') ?></label>
        <input id="midas_item_metadata_qualifier" name="qualifier" <?php if ($this->metadata) {
            echo ' readonly ';
        } ?> value="<?php echo (!$this->metadata) ? '' : $this->escape($this->metadata->getQualifier()); ?>"/>
    </div>
    <div>
        <label for="value"><?php echo $this->t('Value') ?></label>
        <input id="midas_item_metadata_value" name="value"
               value="<?php echo (!$this->metadata) ? '' : $this->escape($this->metadata->getValue()); ?>"/>
    </div>
    <?php
    if ($this->metadata) {
        echo '<div>
            <input type="submit" value="'.$this->t("Save").'"/>
          </div>';
    }
    ?>
</form>

<div id="jsonMetadata" style='display:none;'>
    <?php echo $this->jsonMetadataType ?>
</div>
