<?php
/*=========================================================================
MIDAS Server
Copyright (c) Kitware SAS. 20 rue de la Villette. All rights reserved.
69328 Lyon, FRANCE.

See Copyright.txt for details.
This software is distributed WITHOUT ANY WARRANTY; without even
the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE.  See the above copyright notices for more information.
=========================================================================*/
?>
<link type="text/css" rel="stylesheet" href="<?php echo $this->coreWebroot?>/public/css/common/common.genericPage.css" />
<link type="text/css" rel="stylesheet" href="<?php echo $this->coreWebroot?>/public/css/item/item.view.css" />
<link type="text/css" rel="stylesheet" href="<?php echo $this->coreWebroot?>/public/css/common/common.browser.css" />

<?php
$this->headScript()->appendFile($this->coreWebroot . '/public/js/item/item.view.js');
if($this->preview) // module visualize
  {
  $this->headScript()->appendFile($this->coreWebroot.'/public/js/common/common.browser.js');
  $this->headScript()->appendFile($this->webroot . '/modules/visualize/public/js/main.js');
  }
?>
<div class="viewMain">

  <div class ="genericWrapperTopRight">
      <div style="float:right;" class="genericBigButton ">
        <?php
        echo "<a  href='{$this->webroot}/download/?items={$this->itemDao->getKey()}'><img style='float:left;margin-right:2px;' alt='' src='{$this->coreWebroot}/public/images/icons/download.png'/>";
        if($this->itemIsLink)
          {
          echo $this->t('View as weblink');
          }
        else
          {
          echo $this->t('Download');
          }
        echo '</a>';
         ?>
      </div>

       <?php
      if($this->backUploaded)
        {
        echo '<div style="float:right;margin-right:2px;" class="genericBigButton ">';
          echo "<a  href='{$this->webroot}/browse/uploaded'><img style='float:left;margin-right:2px;' alt='' src='{$this->coreWebroot}/public/images/icons/back.png'/>";
          echo $this->t('Back');
          echo "</a>";
        echo '</div>';
        }
      else if($this->currentFolder)
        {
        echo '<div style="float:right;margin-right:2px;" class="genericBigButton ">';
          echo "<a  href='{$this->webroot}/folder/{$this->currentFolder->getKey()}'><img style='float:left;margin-right:2px;' alt='' src='{$this->coreWebroot}/public/images/icons/back.png'/>";
          echo $this->t('Back');
          echo "</a>";
        echo '</div>';
        }
      ?>

      <br/>
      <div class="itemStats">
      <?php echo $this->itemDao->getView()?> <?php echo $this->t('views'); ?>,
      <?php echo $this->itemDao->getDownload()?> <?php echo $this->t('downloads');?></div>
  </div>
  <div style='width:400px;' class="genericInfo">
     <div class="genericThumbnail">
    <?php
      echo "<img src='{$this->coreWebroot}/public/images/icons/document-big.png' alt=''/>";
    ?>
    </div>
    <div class="genericName <?php if(strlen($this->itemDao->getName()) > 30) echo "tips";?>" <?php if(strlen($this->itemDao->getName()) > 30) echo "style='cursor:help;' title='".$this->itemDao->getName()."'";?>  ><?php   echo $this->slicename($this->itemDao->getName(),30);  ?></div>
    <div class="genericSubtitle" style="color:grey;"><?php echo $this->itemSize;?></div>

  </div>

  <table style='display:block;' class="midasTree">
    <thead>
      <tr>
        <th style="width:100px;" ><?php echo $this->t('Revision');?></th>
        <th style="width:240px;" ><?php echo $this->t('Uploaded');?></th>
        <th  style="width:250px;"><?php echo $this->t('Changes');?></th>
      </tr>
    </thead>
    <tbody>
      <?php
      $node=1;
      foreach($this->itemDao->revisions as $revision)
        {
        echo "<tr>";
        echo "  <td ><a href='{$this->webroot}/download/?items={$this->itemDao->getKey()},{$revision->getRevision()}'>Revision {$revision->getRevision()}</a></td>";
        echo "  <td>{$this->Date->ago($revision->getDate(),false)} {$this->t('by')} {$this->linkuser($revision->getUser())} </td>";
        echo "  <td>{$revision->getChanges()}</td>";
        echo "</tr>";
        $node++;
        }
      ?>
    </tbody>
  </table>

  <h4 style="margin-bottom: 5px;"><?php echo $this->t('Latest revision metadata')?>:</h4>

  <?php if(count($this->metadatavalues) == 0)
    {
    echo "No metadata for this revision.";
    }
  else
    {
  ?>
  <table style='display:block;'  id="metadataTable" class="midasTree">
    <thead>
      <tr>
        <th class='elementHeader'><?php echo $this->t('Element');?></th>
        <th class='qualifierHeader'><?php echo $this->t('Qualifier');?></th>
        <th class='valueHeader'><?php echo $this->t('Value');?></th>
      </tr>
    </thead>
    <tbody>
      <?php
      foreach($this->metadatavalues as $metadata)
        {
        echo "<tr>";
        echo "  <td>".$metadata->getElement()."</td>";
        echo "  <td>".$metadata->getQualifier()."</td>";
        echo "  <td>".$metadata->getValue();
        if($this->isModerator)
          {
          echo "<div class='manageMetadata'>";
          echo "<a  href='javascript:;' element='".$metadata->getKey()."' class='metadataEditLink'><img alt='' src='{$this->coreWebroot}/public/images/icons/edit.png'/></a>";
          echo "<a  href='javascript:;' element='".$metadata->getKey()."' class='metadataDeleteLink'><img alt='' src='{$this->coreWebroot}/public/images/icons/close.png'/></a>";
          echo "</div>";
          }
        echo "  </td>";
        echo "</tr>";
        }
      ?>
    </tbody>
  </table>
  <?php } ?>
  <br/>
  <br/>

  <a onclick="$('#revisionContent').show();$(this).remove();"><?php echo $this->t('Show Content')?></a>

  <div id="revisionContent">
  <?php if(isset($this->itemDao->lastrevision) && $this->itemDao->lastrevision !== false)       
        { ?>        
    <h4 style="margin-top: 0px;margin-bottom: 5px;"><?php echo $this->t('Latest revision content')?>:</h4>

    <table style='display:block;'  id="browseTable" class="midasTree">
      <thead>
        <tr>
          <th ><?php echo $this->t('Name');?></th>
          <th ><?php echo $this->t('Size');?></th>
          <th ><?php echo $this->t('Type');?></th>
        </tr>
      </thead>
      <tbody>
        <?php
        $bitstreams=$this->itemDao->lastrevision->getBitstreams();
        foreach($bitstreams as $bitstream)
          {
          echo "<tr>";
          echo "  <td>{$this->slicename($bitstream->getName(),50)}</td>";
          echo "  <td>{$this->Utility->formatSize($bitstream->getSizebytes())}  </td>";
          echo "  <td>{$bitstream->getMimetype()}</td>";
          echo "</tr>";
          }
        ?>
  <?php } // check for $this->itemDao->lastRevision ?>
      </tbody>
    </table>
  </div>

</div>
<div class="viewSideBar">
  <?php
  if($this->preview || $this->isModerator || $this->isAdmin)
    {?>
  <div class="sideElementFirst viewAction">

    <h1>Actions</h1>
    <ul>
      <?php
      if($this->preview)
        {
      echo
     "<li>
        <a id='itemPreviewLink'><img alt='' src='{$this->coreWebroot}/public/images/icons/view.png'/> {$this->t('Preview')}</a>
      </li>
        ";
        }
      if($this->isModerator)
        {
        echo
       "<li>
          <a href='javascript:;' class='shareItemLink' ><img alt='' src='{$this->coreWebroot}/public/images/icons/item-share.png'/> {$this->t('Share')}</a>
        </li>
        <li>
          <a href='javascript:;' class='duplicateItemLink' ><img alt='' src='{$this->coreWebroot}/public/images/icons/copy.png'/> {$this->t('Duplicate')}</a>
        </li> 
        <li>
          <a href='javascript:;' class='editItemLink' ><img alt='' src='{$this->coreWebroot}/public/images/icons/edit.png'/> {$this->t('Edit')}</a>
        </li>
        <li>
          <a href='javascript:;' class='addMetadataLink' ><img alt='' src='{$this->coreWebroot}/public/images/icons/metadata.png'/> {$this->t('Add Metadata')}</a>
        </li>
        <li>
          <a href='javascript:;' type='item' element='{$this->itemDao->getKey()}' class='uploadRevisionLink' ><img alt='' src='{$this->coreWebroot}/public/images/icons/upload.png'/> {$this->t('Upload new revision')}</a>
        </li>
          ";
        }
      if($this->isAdmin)
        {
        echo "
        <li>
          <a href='javascript:;' type='item' element='{$this->itemDao->getKey()}' class='sharingLink' ><img alt='' src='{$this->coreWebroot}/public/images/icons/lock.png'/> {$this->t('Permissions')}</a>
        </li>
        <li>
          <a  href='javascript:;' id='itemDeleteLink'><img alt='' src='{$this->coreWebroot}/public/images/icons/close.png'/> {$this->t('Delete')}</a>
        </li>";
        }
      $htmltArray = Zend_Registry::get('notifier')->callback("CALLBACK_CORE_ITEM_VIEW_ACTIONMENU", array('item' => $this->itemDao, 'isModerator' => $this->isModerator, 'isAdmin' => $this->isAdmin));
      foreach($htmltArray as $html)
        {
        if(!empty($html))
          {
          echo $html;
          }
        }
      ?>
    </ul>
  </div>
  <?php } ?>
  <div class="<?php echo (!$this->preview && !$this->isModerator && !$this->isAdmin)?'sideElementFirst':''; ?>sideElement<?php if(count($this->sameLocation) > 1) echo "Last"?> viewInfo">
    <h1>Info</h1>
    <table>
      <tbody>
      <?php if(isset($this->itemDao->lastrevision) && $this->itemDao->lastrevision !== false)       
            { ?>
        <tr>
          <td><?php echo $this->t('Created')?></td>
          <td><?php echo $this->itemDao->creation?></td>
        </tr>
        <tr>
          <td><?php echo $this->t('Uploaded by');?></td>
          <td><?php echo $this->linkuser($this->itemDao->lastrevision->getUser())?></td>
        </tr>
        <tr>
          <td>Revision</td>
          <td><?php echo $this->itemDao->lastrevision->getRevision()?></td>
        </tr>
        <tr>
          <td><?php echo $this->t('Files');?></td>
          <td><?php echo count($this->itemDao->lastrevision->getBitstreams())?></td>
        </tr>
      <?php } // check for $this->itemDao->lastRevision 
          else
            { ?>
        <tr>
          <td><?php echo $this->t('No Revisions');?></td>
        </tr>
      <?php } // else ?>
      </tbody>
    </table>
    <?php
    $path=$this->itemDao->getThumbnail();
    if(!empty($path)&&  file_exists(BASE_PATH.'/'.$path))
      {
      echo "
        <h1>{$this->t('Preview')}</h1>
        <img class='infoLogo' alt='' src='{$this->webroot}/{$path}'/>
        ";
      }
      ?>
  </div>
  <?php
  $htmltArray = Zend_Registry::get('notifier')->callback("CALLBACK_CORE_ITEM_VIEW_INFO", array('item' => $this->itemDao, 'isModerator' => $this->isModerator, 'isAdmin' => $this->isAdmin));
    foreach($htmltArray as $html)
      {
      if(!empty($html))
        {
        echo $html;
        }
      }
  if(count($this->sameLocation) > 1)
    {?>
  <div class='sideElementLast viewSameLocation'>
    <h1><?php echo $this->t('In the same location')?></h1>
    <ul>
    <?php
    foreach($this->sameLocation as $item)
      {
      echo "<li>";
      echo "<a class='linkedcontentLink' preview='{$item->preview}' element='{$item->getKey()}' href='{$this->webroot}/item/{$item->getKey()}'>".$this->slicename($item->getName(),25)."</a>";
      echo "</li>";
      }
    ?>
    </ul>
  </div>
  <?php
    }
    ?>
</div>
