<?php
/*=========================================================================
MIDAS Server
Copyright (c) Kitware SAS. 20 rue de la Villette. All rights reserved.
69328 Lyon, FRANCE.

See Copyright.txt for details.
This software is distributed WITHOUT ANY WARRANTY; without even
the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE.  See the above copyright notices for more information.
=========================================================================*/
?>
<link type="text/css" rel="stylesheet" href="<?php echo $this->coreWebroot?>/public/css/common/common.genericPage.css" />
<link type="text/css" rel="stylesheet" href="<?php echo $this->coreWebroot?>/public/css/item/item.view.css" />
<link type="text/css" rel="stylesheet" href="<?php echo $this->coreWebroot?>/public/css/common/common.browser.css" />

<?php
$this->headScript()->appendFile($this->coreWebroot.'/public/js/item/item.view.js');

$cssArray = Zend_Registry::get('notifier')->callback('CALLBACK_CORE_ITEM_VIEW_CSS', array('item' => $this->itemDao));
$jsArray = Zend_Registry::get('notifier')->callback('CALLBACK_CORE_ITEM_VIEW_JS', array('item' => $this->itemDao));

foreach($jsArray as $module => $list)
  {
  foreach($list as $script)
    {
    $this->headScript()->appendFile($script);
    }
  }
foreach($cssArray as $module => $list)
  {
  foreach($list as $stylesheet)
    {
    echo '<link type="text/css" rel="stylesheet" href="'.$stylesheet.'" />';
    }
  }
?>
<div class="viewMain">

  <div class ="genericWrapperTopRight">
      <div style="float:right;">
        <button class="topDownloadButton downloadObject">
        <?php
        if($this->itemIsLink)
          {
          echo $this->t('View');
          }
        else
          {
          echo $this->t('Download');
          }
        ?>
        </button>
      </div>
      <?php
      $htmltArray = Zend_Registry::get('notifier')->callback('CALLBACK_CORE_ITEM_VIEW_BUTTON', array('item' => $this->itemDao, 'isModerator' => $this->isModerator, 'isAdmin' => $this->isAdmin));
      $htmltArray = array_diff($htmltArray, array(''));
      echo join(" ",$htmltArray);
      ?>
      <br/>
  </div>
  <div style='width:460px;' class="genericInfo">
     <div class="genericThumbnail">
    <?php
      echo "<img src='{$this->coreWebroot}/public/images/icons/document-big.png' alt=''/>";
    ?>
    </div>
    <div class="genericName <?php if(strlen($this->itemDao->getName()) > 30) echo "tips";?>" <?php if(strlen($this->itemDao->getName()) > 30) echo "style='cursor:help;' title='".$this->itemDao->getName()."'";?>  ><?php   echo $this->slicename($this->itemDao->getName(),30);  ?></div>
    <div class="genericSubtitle" style="color:grey;"><?php echo $this->itemSize;?></div>
  </div>
  <div class="itemViewMainSection">
    <?php
    $elements = Zend_Registry::get('notifier')->callback('CALLBACK_CORE_ITEM_VIEW_PREPEND_ELEMENTS', array('item' => $this->itemDao));
    foreach($elements as $module => $elementList)
      {
      foreach($elementList as $element)
        {
        echo '<div class="itemViewMainSection">';
        echo $this->element($element, $module);
        echo '</div>';
        }
      }
    ?>
    <h4>LICENSE</h4>
    <div id="licenseDiv">
      <?php
      if(count($this->itemDao->revisions) > 0)
        {
        $licenseId = $this->itemDao->lastrevision->getLicenseId();
        if($licenseId != null)
          {
          $license = $this->itemDao->lastrevision->getLicense();
          echo '<a name="'.$license->getName().'" class="licenseLink" href="javascript:;" element="'.$license->getKey().'">'.$license->getName().'</a>';
          }
        else
          {
          echo 'No license set on the current revision.';
          }
        }
      else
        {
        echo 'No license (zero revisions in this item)';
        }
      ?>
    </div>
  </div>

  <?php
  if($this->itemDao->getDescription() != '')
    {
  ?>
    <div class="itemViewMainSection">
      <h4>DESCRIPTION</h4>
      <div id="descriptionDiv">
        <?php echo $this->itemDao->getDescription(); ?>
      </div>
    </div>
  <?php
    }
  ?>

  <div class="itemViewMainSection">
    <h4>HISTORY</h4>
    <img id="historyLoading" alt="" src="<?php echo $this->coreWebroot?>/public/images/icons/loading.gif" />
    <div id="revisionList" style="display:none;">
      <?php
      foreach($this->itemDao->revisions as $revision)
        {
        echo '<h3><a href="#">Revision '.$revision->getRevision();
        if($revision->getChanges() != '')
          {
          echo ' ('.$revision->getChanges().')';
          }
        echo '</a></h3>';
        echo '<div class="revisionEntry">';
        echo '  <span>Uploaded '.$revision->getDate().' by '.$this->linkuser($revision->getUser()).'</span>';

        echo '<div style="float: right;">';
        echo '  <div class="genericBigButton downloadObject">';
        echo '    <a href="'.$this->webroot.'/download/?items='.$this->itemDao->getKey().','.$revision->getRevision().'">';
        echo '    <img alt="" src="'.$this->coreWebroot.'/public/images/icons/download.png" />';
        echo '    Download </a>';
        echo '  </div>';
        if($this->isAdmin)
          {
          echo '  <div style="float: right; margin: 0 0 0 5px;">';
          echo ' <form id="deleteItemrevisionForm'.$revision->getItemrevisionId().'" class="genericForm" method="POST"  action="'.$this->webroot.'/item/deleteitemrevision">';
          echo ' <input type="hidden" name="itemrevisionId" value="'.$revision->getItemrevisionId().'"/>';
          echo ' <input type="hidden" name="itemId" value="'.$this->itemDao->getKey().'"/>';
          echo '    <a qtip="Delete revision" href="javascript:;" class="deleteItemRevision" itemrevisionId="'.$revision->getItemrevisionId().'" itemId="'.$this->itemDao->getKey().'">';
          echo '    <img alt="" src="'.$this->coreWebroot.'/public/images/icons/close.png" /></a>';
          echo '  </form></div>';
          }
        echo '</div>';



        echo '<div class="revisionMetadata">';
        echo '<h4>METADATA</h4>';
        if(count($revision->metadatavalues) == 0)
          {
          echo "No metadata for this revision.";
          }
        else
          {
          ?>
          <table style='display:block;' id="metadataTable" class="metadataList">
            <thead>
              <tr>
                <th><?php echo $this->t('Element');?></th>
                <th><?php echo $this->t('Qualifier');?></th>
                <th><?php echo $this->t('Value');?></th>
              </tr>
            </thead>
            <tbody>
              <?php
              foreach($revision->metadatavalues as $metadata)
                {
                echo '<tr>';
                echo '  <td>'.$metadata->getElement().'</td>';
                echo '  <td>'.$metadata->getQualifier().'</td>';
                echo '  <td><span style="float: left;">'.$metadata->getValue().'</span>';
                if($this->isModerator)
                  {
                  echo "<span class='manageMetadata'>";
                  echo "<a href='javascript:;' itemrevision='".$revision->getRevision()."' element='".$metadata->getKey()."' class='metadataEditLink'><img alt='' src='{$this->coreWebroot}/public/images/icons/edit.png'/></a>";
                  echo "<a href='javascript:;' itemrevision='".$revision->getRevision()."' element='".$metadata->getKey()."' class='metadataDeleteLink'><img alt='' src='{$this->coreWebroot}/public/images/icons/close.png'/></a>";
                  echo "</span>";
                  }
                echo "  </td>";
                echo "</tr>";
                }
              ?>
            </tbody>
          </table>
        <?php
          }
        echo '<br/><br/>';
        echo '</div>';
        echo '<div class="revisionContent">';
        echo '<h4 style="margin-top: 0px;margin-bottom: 5px;">'.$this->t('CONTENT').'</h4>';
        echo '<table style="display:block;" class="bitstreamList">'; ?>
                <thead>
                  <tr>
                    <th><?php echo $this->t('Name');?></th>
                    <th><?php echo $this->t('Size');?></th>
                  </tr>
                </thead>
                <tbody>
                  <?php
                  $bitstreams = $revision->getBitstreams();
                  foreach($bitstreams as $bitstream)
                    {
                    $linkDestination = $this->webroot.'/download/bitstream/'.
                        $bitstream->getKey().'/'.urlencode($bitstream->getName());
                    if(preg_match('/^https?:\/\//', $bitstream->getPath()))
                      {
                          $linkDestination = $bitstream->getPath();
                      }

                    echo '<tr class="bitstreamRow">';
                    echo '<td>';
                    echo '  <div style="display: none;">';
                    echo '    <span name="bitstream_id">'.$bitstream->getKey().'</span>';
                    echo '    <span name="filename">'.$bitstream->getName().'</span>';
                    echo '    <span name="md5">'.$bitstream->getChecksum().'</span>';
                    echo '    <span name="sizeBytes">'.$bitstream->getSizebytes().'</span>';
                    echo '    <span name="mimeType">'.$bitstream->getMimetype().'</span>';
                    echo '  </div>';
                    echo '<a href="'.$linkDestination.'">';
                    echo $this->slicename($bitstream->getName(), 50);
                    echo '</a>';
                    if($this->isModerator)
                      {
                      echo '<img element="'.$bitstream->getKey().'" class="editBitstreamIcon" alt="" src="'.$this->coreWebroot.'/public/images/icons/edit.png" />';
                      }
                    if($this->isAdmin)
                      {
                      echo '<img element="'.$bitstream->getKey().'" class="deleteBitstreamIcon" alt="" src="'.$this->coreWebroot.'/public/images/icons/close.png" />';
                      }
                    echo '<img element="'.$bitstream->getKey().'" class="bitstreamInfoIcon" alt="" src="'.$this->coreWebroot.'/public/images/icons/message.png" />';
                    echo '</td>';
                    echo '<td>'.UtilityComponent::formatSize($bitstream->getSizebytes()).'</td>';
                    echo '</tr>';
                    }
                  ?>
                </tbody>
              </table>
            </div>
        </div>
        <?php } ?>
    </div>
  </div>
  <?php
  $elements = Zend_Registry::get('notifier')->callback('CALLBACK_CORE_ITEM_VIEW_APPEND_ELEMENTS', array('item' => $this->itemDao));
  foreach($elements as $module => $elementList)
    {
    foreach($elementList as $element)
      {
      echo '<div class="itemViewMainSection">';
      echo $this->element($element, $module);
      echo '</div>';
      }
    }
    ?>
</div>
<div class="viewSideBar">
  <?php
  $htmltArray = Zend_Registry::get('notifier')->callback("CALLBACK_CORE_ITEM_VIEW_ACTIONMENU", array('item' => $this->itemDao, 'isModerator' => $this->isModerator, 'isAdmin' => $this->isAdmin));
  $htmltArray = array_diff($htmltArray, array(''));
  if(!empty($htmltArray) || $this->isModerator || $this->isAdmin)
    {?>
  <div class="sideElementFirst viewAction">

    <h1>Item Actions</h1>
    <ul>
      <?php
      echo
        "<li>
          <a href='javascript:;' class='linkItemLink' ><img alt='' src='{$this->coreWebroot}/public/images/icons/link.png'/> Share</a>
        </li>";
      if($this->isModerator)
        {
        echo
       "<li>
          <a href='javascript:;' class='duplicateItemLink' ><img alt='' src='{$this->coreWebroot}/public/images/icons/copy.png'/> {$this->t('Copy')}</a>
        </li>
        <li>
          <a href='javascript:;' class='editItemLink' ><img alt='' src='{$this->coreWebroot}/public/images/icons/edit.png'/> {$this->t('Edit')}</a>
        </li>
        <li>
          <a href='javascript:;' class='addMetadataLink' ><img alt='' src='{$this->coreWebroot}/public/images/icons/metadata.png'/> {$this->t('Add Metadata')}</a>
        </li>
        <li>
          <a href='javascript:;' type='item' element='{$this->itemDao->getKey()}' class='uploadRevisionLink' ><img alt='' src='{$this->coreWebroot}/public/images/icons/upload.png'/> {$this->t('Upload new revision')}</a>
        </li>
          ";
        }
      if($this->isAdmin)
        {
        echo "
        <li>
          <a href='javascript:;' type='item' element='{$this->itemDao->getKey()}' class='sharingLink' ><img alt='' src='{$this->coreWebroot}/public/images/icons/lock.png'/> {$this->t('Permissions')}</a>
        </li>
        <li>
          <a  href='javascript:;' id='itemDeleteLink'><img alt='' src='{$this->coreWebroot}/public/images/icons/close.png'/> {$this->t('Delete')}</a>
        </li>";
        }
      foreach($htmltArray as $html)
        {
        if(!empty($html))
          {
          echo $html;
          }
        }
      ?>
    </ul>
  </div>
  <?php } ?>
  <div class="<?php echo (!$this->preview && !$this->isModerator && !$this->isAdmin)?'sideElementFirst':'sideElement'; ?> viewInfo">
    <h1>Info</h1>
    <table>
      <tbody>
      <?php if(isset($this->itemDao->lastrevision) && $this->itemDao->lastrevision !== false)
            { ?>
        <tr>
          <td><?php echo $this->t('Created')?></td>
          <td><?php echo $this->itemDao->creation?></td>
        </tr>
        <tr>
          <td><?php echo $this->t('Uploaded by');?></td>
          <td><?php echo $this->linkuser($this->itemDao->lastrevision->getUser())?></td>
        </tr>
        <tr>
          <td>Views</td>
          <td><?php echo $this->itemDao->getView(); ?></td>
        </tr>
        <tr>
          <td>Downloads</td>
          <td><?php echo $this->itemDao->getDownload(); ?></td>
        </tr>
        <tr>
          <td>Revisions</td>
          <td><?php echo $this->itemDao->lastrevision->getRevision()?></td>
        </tr>
        <tr>
          <td><?php echo $this->t('Files');?></td>
          <td><?php echo count($this->itemDao->lastrevision->getBitstreams())?></td>
        </tr>
      <?php } // check for $this->itemDao->lastRevision
          else
            { ?>
        <tr>
          <td><?php echo $this->t('No Revisions');?></td>
        </tr>
      <?php } // else ?>
      </tbody>
    </table>
    <?php
    if($this->itemDao->getThumbnailId())
      {
      echo '<h1>Preview</h1>'.
           '<img class="infoLogo" alt="" src="'.$this->webroot.'/item/thumbnail?itemId='.
           $this->itemDao->getKey().'"/>';
      }
      ?>
  </div>
  <?php
  if(count($this->folders) > 1)
    { ?>
    <div class="sideElementLast">
    <h1>IN FOLDERS</h1>
      <div id="parentList">
        <?php
        foreach($this->folders as $folder)
          {
          echo '<a href="'.$this->webroot.'/folder/'.$folder->getKey().'">';
          echo '<img alt="" src="'.$this->coreWebroot.'/public/images/TreeTable/folder.png" />';
          echo ' '.$folder->getName().'</a>';
          echo '<br />';
          } ?>
      </div>
    </div>
  <?php
    }
  $htmltArray = Zend_Registry::get('notifier')->callback('CALLBACK_CORE_ITEM_VIEW_INFO', array('item' => $this->itemDao, 'isModerator' => $this->isModerator, 'isAdmin' => $this->isAdmin));
  foreach($htmltArray as $html)
    {
    if(!empty($html))
      {
      echo $html;
      }
    }
  ?>
</div>
