<link type="text/css" rel="stylesheet" href="<?php echo $this->coreWebroot ?>/public/css/download/download.applet.css" />

<div class="viewMain">
  <div class="downloadDescription">
    <img class="descriptionImage" alt="" src="<?php echo $this->coreWebroot ?>/public/images/icons/move.png" />
    <?php echo $this->contentDescription ?> will be downloaded.
  </div>
  <div class="downloadInstructions">
     Press the <b>Download</b> button to choose your destination and begin the download.
  </div>
  <div class="pointToDownloadButton">
    <img class="pointToDownload" alt="" src="<?php echo $this->coreWebroot ?>/public/images/icons/arrow_down.png" />
  </div>

  <applet name="MidasUploader" code="com.kitware.utils.Main"
          archive="<?php echo $this->coreWebroot?>/public/java/upload/MidasUploader.jar?rev=3"
          width="569" height="190" mayscript="true">
    <param name="type" value="application/x-java-applet;version=1.5" />
    <param name="background" value="ffffff" />
    <param name="downloadMode" value="true" />
    <param name="loglevel" value="WARNING" />
    <param name="sessionId" value="<?php echo session_id();?>"/>
    <param name="baseURL" value="<?php echo $this->protocol."://".$this->host.$this->webroot ?>/"/>
    <param name="itemIds" value="<?php echo $this->itemIds?>" />
    <param name="folderIds" value="<?php echo $this->folderIds?>" />
    <param name="totalSize" value="<?php echo $this->totalSize?>" />
    You must install and enable Java on your system in order to use the large data downloader.
  </applet>
</div>
