<?php
/*=========================================================================
MIDAS Server
Copyright (c) Kitware SAS. 20 rue de la Villette. All rights reserved.
69328 Lyon, FRANCE.

See Copyright.txt for details.
This software is distributed WITHOUT ANY WARRANTY; without even
the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE.  See the above copyright notices for more information.
=========================================================================*/

$this->headScript()->appendFile($this->coreWebroot . '/public/js/jquery/jquery.form.js');
$this->headScript()->appendFile($this->coreWebroot.'/public/js/browse/browse.index.js');
$this->headScript()->appendFile($this->coreWebroot.'/public/js/common/common.browser.js');
?>


<link type="text/css" rel="stylesheet" href="<?php echo $this->coreWebroot?>/public/css/common/common.browser.css" />
<link type="text/css" rel="stylesheet" href="<?php echo $this->coreWebroot?>/public/css/browse/browse.index.css" />
<div class="viewMain">
 
</div>





<div class="viewSideBar">
  <div class="sideElementFirst viewAction" >
    <h1>Actions</h1>
    <ul>
      <li>
        
      </li>
    </ul>
  </div>
  <div class="sideElement viewSelected" >
    <h1><?php echo $this->t('Selected')?></h1>
    <span></span>
  </div>
  <div class="sideElementLast viewInfo" >
    <h1>Info</h1>    
    <img class="infoLoading" style="display:none;" alt="" src="<?php echo $this->coreWebroot?>/public/images/icons/loading.gif"/>
    <div class="ajaxInfoElement">
    </div>
  </div>
  
  
  <div class="defaultSide" >
    <div align="justify"  class='sideElementFirst feedNotification'>
MIDAS integrates multimedia server technology with open-source data analysis and visualization clients. The server follows open standards for data storage, access and harvesting.
  </div>
      <?php
    if(!empty($this->notifications))
      {
      echo   "<div class='sideElement feedNotification'>
                <h1>Notifications</h1>
              </div>";
      }
      ?>
    <?php 
    if(!empty($this->itemThumbnails))
      {
      echo '<div class="sideElement feedThumbnail">';
      echo '<h1>Thumbnails</h1>';
      foreach($this->itemThumbnails as $item)
        {
        echo "<a href='{$this->webroot}/item/{$item->getKey()}'>";
        echo "<img src='{$this->webroot}/{$item->getThumbnail()}' alt=''/>"; 
        echo "</a>";
        }
      echo '</div>';
      }
      ?>
    <div class="sideElementLast feedStats">
      <h1>Stats</h1>
      <?php
      echo "<ul>";
      echo "  <li>{$this->nUsers} user".(($this->nUsers>1)?'s':'')."</li>";
      echo "  <li>{$this->nCommunities} ".(($this->nCommunities>1)?'communities':'community')."</li>";
      echo "  <li>{$this->nItems} item".(($this->nItems>1)?'s':'')."</li>";
      echo "</ul>";
      ?>
    </div>
  </div>
</div>




