<?php
/*=========================================================================
MIDAS Server
Copyright (c) Kitware SAS. 20 rue de la Villette. All rights reserved.
69328 Lyon, FRANCE.

See Copyright.txt for details.
This software is distributed WITHOUT ANY WARRANTY; without even
the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE.  See the above copyright notices for more information.
=========================================================================*/

echo '<script type="text/javascript" src="' . $this->coreWebroot . '/public/js/common/common.browser.js"></script>';
echo '<script type="text/javascript" src="' . $this->coreWebroot . '/public/js/browse/browse.movecopy.js"></script>';
?>

<link type="text/css" rel="stylesheet" href="<?php echo $this->coreWebroot?>/public/css/common/common.browser.css" />
<link type="text/css" rel="stylesheet" href="<?php echo $this->coreWebroot?>/public/css/browse/browse.movecopy.css" />

  <div class="destinationDisplay">
    <b>Destination:</b> <span id="selectedDestination"> <?php echo $this->t('Please select a folder.') ?> </span>
  </div>
  <img class="tableLoading" alt="" src="<?php echo $this->coreWebroot?>/public/images/icons/loading.gif"/>
  <table id="moveCopyTable" class="midasTree">
    <thead>
      <?php
    if(!empty($this->communities))
      {  ?>
      <tr>
        <th><?php echo $this->t('Name');?></th>
      </tr>
     <?php
      }
     ?>
    </thead>
    <tbody>
      <?php
      $node=1;
      foreach($this->communities as $community)
        {
        $folder=$community->getFolder();
        echo "<tr id='node--$node' valid='false' class='parent' privacy='".($community->getPrivacy() == 1 ? MIDAS_PRIVACY_PRIVATE : MIDAS_PRIVACY_PUBLIC )."' type='community' element='{$folder->getFolderId()}'>";
        echo "  <td class='treeBrowseElement'><span class='community'>{$community->getName()}</span></td>";
        echo "</tr>";
        $node++;
        }

      $folder=$this->user->getFolder();
      echo "<tr id='node--$node' class='parent' privacy='{$folder->getPrivacyStatus()}' type='folder' valid='false' element='{$folder->getFolderId()}'>";
      echo "  <td class='treeBrowseElement'><span class='folder'>{$this->t('My Files')} ({$this->user->getFullName()})</span></td>";
      echo "</tr>";
      $node++;
      ?>
    </tbody>
  </table>
  <form class="genericForm" id="moveCopyForm" type='post' action="<?php echo $this->webroot?>/browse/movecopy">
    <input type='hidden' name='elements' value='<?php echo $this->folderIds?>;<?php echo $this->itemIds?>' />
    <input type='hidden' name='from' value='<?php echo $this->from?>' />
    <input type='hidden' id="selectedDestinationHidden" name='destination' />
    <?php
    if($this->shareEnabled || $this->duplicateEnabled)
      { ?>
      <div class="copySymlinkSelect">
        <input type="radio" checked="checked" name="copytype" value="reference"><?php echo $this->referenceMessage;?><br/>
        <input type="radio" name="copytype" value="copy"><?php echo $this->copyMessage;?><br/>
      </div>
    <?php
      } 
    ?>
    <div class="movecopySubmitWrapper">
      <img style="display: none;" class="submitWaiting" alt="" src="<?php echo $this->coreWebroot?>/public/images/icons/loading.gif"/>
        <?php
    if($this->moveEnabled)
      {?>
      <input type="submit" disabled  name='moveElement' id='moveElement'  value="<?php echo $this->t('Move')?>"/>
    <?php
      }
    elseif($this->selectEnabled)
      {
      ?>
      <input type="submit" disabled  name='selectElement' id='selectElement'  value="<?php echo $this->t('Select')?>"/>
      <?php
      }
    elseif($this->shareEnabled)
      {
      ?>
      <input type="submit" disabled  name='shareElement' id='shareElement'  value="<?php echo $this->t('Share')?>"/>
      <?php
      }
    elseif($this->duplicateEnabled)
      {
      ?>
      <input type="submit" disabled name='duplicateElement' id='duplicateElement'  value="<?php echo $this->t('Copy')?>"/>
      <?php
      }?>
    </div>
  </form>
