

<?php
echo '<script type="text/javascript" src="' . $this->coreWebroot . '/public/js/common/common.browser.js"></script>';
echo '<script type="text/javascript" src="' . $this->coreWebroot . '/public/js/browse/browse.movecopy.js"></script>';
?>

<link type="text/css" rel="stylesheet" href="<?php echo $this->coreWebroot?>/public/css/common/common.browser.css" />
<link type="text/css" rel="stylesheet" href="<?php echo $this->coreWebroot?>/public/css/browse/browse.movecopy.css" />

  <h4><?php echo $this->t('Please select a folder.')?></h4>
  <img class="tableLoading" alt="" src="<?php echo $this->coreWebroot?>/public/images/icons/loading.gif"/>
  <table id="moveTable" class="midasTree">
    <thead>
      <?php 
    if(!empty($this->communities))
      {  ?>
      <tr>
        <th class="thData"><?php echo $this->t('Name');?></th>
      </tr>
     <?php 
      }
     ?>
    </thead>
    <tbody>
      <?php
      $node=1;
      foreach($this->communities as $community)
        {
        $folder=$community->getFolder();
        echo "<tr id='node--$node' class='parent' privacy='".($community->getPrivacy() == 1 ? MIDAS_PRIVACY_PRIVATE : MIDAS_PRIVACY_PUBLIC )."' type='community' element='{$community->getCommunityId()}' ajax='{$folder->getFolderId()}'>";
        echo "  <td class='treeBrowseElement'><span class='community'>{$community->getName()}</span></td>";
        echo "</tr>";
        $node++;
        }  
        
        $folder=$this->user->getFolder();
        echo "<tr id='node--$node' class='parent' privacy='{$folder->getPrivacyStatus()}' type='folder' element='-1' ajax='{$folder->getFolderId()}'>";
        echo "  <td class='treeBrowseElement'><span class='folder'>{$this->t('My Files')} ({$this->user->getFullName()})</span></td>";
        echo "</tr>";
        $node++;
      ?>        
    </tbody>
  </table>
   <br/> <br/>
  <form class="genericForm" type='post' action="<?php echo $this->webroot?>/browse/movecopy">
    <input type='hidden' name='elements' value='<?php echo $this->folderIds?>;<?php echo $this->itemIds?>' />
    <input type='hidden' id="selectedDestinationHidden" name='destination' />
    Destination: <span id="selectedDestination" > <?php echo $this->t('Please select a folder.') ?> </span> <br/>
        <?php
    if($this->moveEnabled)
      {?>
      <input type="submit" disabled  name='moveElements' id='moveElements'  value="<?php echo $this->t('Move')?>"/>
    <?php      
      }
    elseif($this->selectEnabled)
      {
      ?>
      <input type="submit" disabled  name='selectElements' id='selectElements'  value="<?php echo $this->t('Select')?>"/>
      <?php
      }
       else
         {
      ?>
    <input type="submit" disabled id='copyElement'  name='copyElement' value="<?php echo $this->t('Copy')?>"/>
    <?php
        }?>
  </form>
  
  <?php 
  if(empty($this->communities))
    {    
    echo "<h4>{$this->t("No community available")}.</h4>";
    }
    ?>
