<?php
/*=========================================================================
 MIDAS Server
 Copyright (c) Kitware SAS. 26 rue Louis Guérin. 69100 Villeurbanne, FRANCE
 All rights reserved.
 More information http://www.kitware.com

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

         http://www.apache.org/licenses/LICENSE-2.0.txt

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
=========================================================================*/

echo '<script type="text/javascript" src="' . $this->coreWebroot . '/public/js/common/common.browser.js"></script>';
echo '<script type="text/javascript" src="' . $this->coreWebroot . '/public/js/browse/browse.selectitem.js"></script>';
?>

<link type="text/css" rel="stylesheet" href="<?php echo $this->coreWebroot?>/public/css/common/common.browser.css" />
<link type="text/css" rel="stylesheet" href="<?php echo $this->coreWebroot?>/public/css/browse/browse.selectitem.css" />

<div class="selectedItemContainer"><b>Selection:</b> <span id="selectedDestination"> <?php echo $this->t('Please select an item.') ?> </span></div>

<img class="tableLoading" alt="" src="<?php echo $this->coreWebroot?>/public/images/icons/loading.gif"/>
<table id="moveTable" class="midasTree">
  <thead>
    <?php
  if(!empty($this->communities))
    {  ?>
    <tr>
      <th><?php echo $this->t('Name');?></th>
    </tr>
   <?php
    }
   ?>
  </thead>
  <tbody>
    <?php
    $node=1;
    foreach($this->communities as $community)
      {
      $folder=$community->getFolder();
      echo "<tr id='node--$node' class='parent' privacy='".($community->getPrivacy() == 1 ? MIDAS_PRIVACY_PRIVATE : MIDAS_PRIVACY_PUBLIC )."' type='community' element='{$folder->getFolderId()}'>";
      echo "  <td class='treeBrowseElement'><span class='community'>{$community->getName()}</span></td>";
      echo "</tr>";
      $node++;
      }

      $folder=$this->user->getFolder();
      echo "<tr id='node--$node' class='parent' privacy='{$folder->getPrivacyStatus()}' type='folder' element='{$folder->getFolderId()}'>";
      echo "  <td class='treeBrowseElement'><span class='folder'>{$this->t('My Files')} ({$this->user->getFullName()})</span></td>";
      echo "</tr>";
      $node++;
    ?>
  </tbody>
</table>

<br/>
<input type="text" id="live_search_item" value="<?= $this->t('Or search it...') ?>"  autocomplete="off" autocorrect="off" autocapitalize="off" />
<input type="hidden" id="live_search_item_value" value="init" />
<div id="searchloadingSelectItem" style="display:none"></div>
<br/>

<div class="bottomButtons">
  <form class="genericForm" type='post' action="<?php echo $this->webroot?>/browse/selectitem">
    <input type='hidden' name='elements' value='<?php echo $this->folderIds?>;<?php echo $this->itemIds?>' />
    <input type='hidden' id="selectedDestinationHidden" name='destination' />
    <input type="submit" disabled  name='selectElements' id='selectElements'  value="<?php echo $this->t('Select')?>"/>
  </form>
</div>
