<?php
/*=========================================================================
MIDAS Server
Copyright (c) Kitware SAS. 20 rue de la Villette. All rights reserved.
69328 Lyon, FRANCE.

See Copyright.txt for details.
This software is distributed WITHOUT ANY WARRANTY; without even
the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE.  See the above copyright notices for more information.
=========================================================================*/

echo '<script type="text/javascript" src="' . $this->coreWebroot . '/public/js/common/common.browser.js"></script>';
echo '<script type="text/javascript" src="' . $this->coreWebroot . '/public/js/browse/browse.selectfolder.js?'.time().'"></script>';
?>

<link type="text/css" rel="stylesheet" href="<?php echo $this->coreWebroot?>/public/css/common/common.browser.css" />
<link type="text/css" rel="stylesheet" href="<?php echo $this->coreWebroot?>/public/css/browse/browse.selectfolder.css?<?php echo time()?>" />

  <img class="tableLoading" alt="" src="<?php echo $this->coreWebroot?>/public/images/icons/loading.gif"/>
  <div id="browserWrapper" >
    <table id="moveTable" class="midasTree">
      <thead>
      <?php
    if(!empty($this->communities))
      {  ?>
      <tr>
        <th><?php echo $this->t('Name');?></th>
      </tr>
     <?php
      }
     ?>
      </thead>
      <tbody>
        <?php
        $node=1;
        foreach($this->communities as $community)
          {
          $folder = $community->getFolder();
          echo "<tr id='node--$node' class='parent' privacy='".($community->getPrivacy() == 1 ? MIDAS_PRIVACY_PRIVATE : MIDAS_PRIVACY_PUBLIC )."' type='community' element='{$folder->getFolderId()}'>";
          echo "  <td class='treeBrowseElement'><span class='community'>{$community->getName()}</span></td>";
          echo "</tr>";
          $node++;
          }

        $folder=$this->user->getFolder();
        echo "<tr id='node--$node' class='parent userTopLevel' privacy='{$folder->getPrivacyStatus()}' type='folder' element='{$folder->getFolderId()}'>";
        echo "  <td class='treeBrowseElement'><span class='folder'>{$this->t('My Files')} ({$this->user->getFullName()})</span></td>";
        echo "</tr>";
        $node++;
      ?>
      </tbody>
    </table>

  </div>


   <br/>
   <?php
   echo '<div class="genericBigButton" id="createFolderButton" >';
      echo "<a ><img style='float:left;margin-right:2px;' alt='' src='{$this->coreWebroot}/public/images/FileTree/directory.png'/>";
      echo $this->t('Create a new Folder');
      echo "</a>";
    echo '</div>';
    ?>

   <div id="createFolderContent">

   </div>
   <br/>

  <form class="genericForm" type='post' action="<?php echo $this->webroot?>/browse/selectitem">
    <input type='hidden' name='elements' value='<?php echo $this->folderIds?>;<?php echo $this->itemIds?>' />
    <input type='hidden' id="selectedDestinationHidden" name='destination' />
    Destination: <span id="selectedDestination" > <?php echo $this->t('Please select a folder.') ?> </span> <br/>
    <div class="bottomButtonsContainer">
      <input type="submit" disabled  name='selectElements' id='selectElements'  value="<?php echo $this->t('Select')?>"/>
    </div>
  </form>

  <input id="defaultPolicy" type="hidden" value="<?php echo $this->policy?>"/>
