<?php
/*=========================================================================
MIDAS Server
Copyright (c) Kitware SAS. 20 rue de la Villette. All rights reserved.
69328 Lyon, FRANCE.

See Copyright.txt for details.
This software is distributed WITHOUT ANY WARRANTY; without even
the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE.  See the above copyright notices for more information.
=========================================================================*/

$this->headScript()->appendFile($this->coreWebroot.'/public/js/browse/browse.uploaded.js');
$this->headScript()->appendFile($this->coreWebroot.'/public/js/common/common.browser.js');
?>
<div class="viewMain">
  <img class="tableLoading" alt="" src="<?php echo $this->coreWebroot?>/public/images/icons/loading.gif"/>
  <table id="browseTable" class="midasTree">
    <thead>
      <tr>
        <th class="thData">Data</th>
        <th class="thSize">Size</th>
        <th class="thDate">Date</th>
        <th class="thCheckbox"><input type="checkbox" id="browseTableHeaderCheckbox" /></th>
      </tr>
    </thead>
    <tbody>
      <?php
      $node=1;
  
      foreach($this->items as $item)
        {
        echo "<tr id='node--$node' policy='{$item->policy}' class='' type='item' element='{$item->getItemId()}' >";
        echo "  <td class='treeBrowseElement'><span class='file'>{$this->slicename($item->getName(),50)}</span></td>";
        echo "  <td>{$item->size}</td>";
        echo "  <td>{$this->Date->ago($item->getDateUpdate(),true)}</td>";
        echo "  <td><input type='checkbox' class='treeCheckbox' type='item' element='{$item->getItemId()}' /></td>";
        echo "</tr>";
        $node++;
        }
      ?>          
       
    </tbody>
  </table>
</div>
<div class="viewSideBar">
    <div class="sideElementFirst viewAction" style="display:none;">
    <h1>Actions</h1>
    <ul>
      <li>
        
      </li>
    </ul>
  </div>
  <div class="sideElement viewSelected" >
    <h1><?php echo $this->t('Selected')?></h1>
    <span></span>
  </div>
  <div class="sideElementLast viewInfo" style="display:none;">
    <h1>Info</h1>    
    <img class="infoLoading" style="display:none;" alt="" src="<?php echo $this->coreWebroot?>/public/images/icons/loading.gif"/>
    <div class="ajaxInfoElement">
    </div>
  </div>
</div>




