<?php
/*=========================================================================
 Midas Server
 Copyright Kitware SAS, 26 rue Louis Guérin, 69100 Villeurbanne, France.
 All rights reserved.
 For more information visit http://www.kitware.com/.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

         http://www.apache.org/licenses/LICENSE-2.0.txt

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
=========================================================================*/

echo '<script type="text/javascript" src="'.$this->coreWebroot.'/public/js/share/share.applyrecursivedialog.js"></script>';
$this->headScript()->appendFile($this->coreWebroot.'/public/js/jquery/jquery.form.js');
?>
<link href="<?php echo $this->coreWebroot ?>/public/css/share/share.dialog.css" rel="stylesheet" type="text/css"/>
<br/>
<?php echo $this->t('Would you also like to apply these permissions to all items and subfolders?'); ?>

<br/><br/><br/>

<div id="applyPoliciesRecursiveProgressBar"></div>
<div id="applyPoliciesRecursiveMessage"></div>

<div id="applyPoliciesRecursiveForm" style="float: right">
    <input type='hidden' id="folderId" value="<?php echo $this->escape($this->folderId); ?>"/>
    <input class="globalButton" type='submit' name='submitButton' id='acceptApplyRecursive'
           value='<?php echo $this->t('Yes') ?>'/>
    <input class="globalButton" style="margin-left: 15px;" type='button' name='declineApplyRecursive'
           id='declineApplyRecursive'
           value='<?php echo $this->t('No') ?>'/>
</div>
<img id="applyPoliciesRecursiveLoadingGif" style="display: none; float: left" alt=""
     src="<?php echo $this->coreWebroot ?>/public/images/icons/loading.gif"/>
