<?php
/*=========================================================================
 Midas Server
 Copyright Kitware SAS, 26 rue Louis Guérin, 69100 Villeurbanne, France.
 All rights reserved.
 For more information visit http://www.kitware.com/.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

         http://www.apache.org/licenses/LICENSE-2.0.txt

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
=========================================================================*/

echo '<script type="text/javascript" src="'.$this->coreWebroot.'/public/js/share/share.dialog.js?'.time().'"></script>';
?>
<link href="<?php echo $this->coreWebroot ?>/public/css/share/share.dialog.css" rel="stylesheet" type="text/css"/>

<div id='permissionsContent'>
    <div id='permissionPublic' <?php echo(($this->private) ? 'style="display:none;"' : '') ?>>
        <img alt="" src="<?php echo $this->coreWebroot; ?>/public/images/icons/world.png"/>
        <b><?php echo $this->t('Public') ?></b> <?php echo $this->t(
            'Anyone can find and access. No sign-in required.'
        ) ?>
        <a id='setElementPrivateLink'><?php echo $this->t('You can set the permission as private.') ?></a>
    </div>

    <div id='permissionPrivate' <?php echo((!$this->private) ? 'style="display:none;"' : '') ?>>
        <img alt="" src="<?php echo $this->coreWebroot; ?>/public/images/icons/key.png"/>
        <b><?php echo $this->t('Private') ?></b> <?php echo $this->t(
            'Only people explicitly granted permission can access. Sign-in required.'
        ) ?>
        <a id='setElementPublicLink'><?php echo $this->t('You can set the permission as public.') ?></a>
    </div>

    <h4><?php echo $this->t('Permissions List') ?></h4>

    <div id='permissionEntity'>
        <table>
            <?php
            foreach ($this->groupPolicies as $policy) {
                ?>
                <tr type='group' element='<?php echo $this->escape($policy->group->getKey()); ?>'>
                    <td>
                        <img src='<?php echo $this->coreWebroot ?>/public/images/icons/community.png'/>
                    </td>
                    <td class='changePermissionSelect'>
                        <?php echo $this->escape($policy->group->getCommunity()->getName()).' ('.$this->escape($policy->group->getName()).')' ?>
                    </td>
                    <td class='changePermissionSelectBox'>
                        <select class='changePermissionSelect'>
                            <?php
                            echo "<option value='".MIDAS_POLICY_ADMIN."' ".(($policy->getPolicy(
                                    ) == MIDAS_POLICY_ADMIN) ? 'selected' : '').">{$this->t('is owner')}</option>";
                            echo "<option value='".MIDAS_POLICY_WRITE."' ".(($policy->getPolicy(
                                    ) == MIDAS_POLICY_WRITE) ? 'selected' : '').">{$this->t('can edit')}</option>";
                            echo "<option value='".MIDAS_POLICY_READ."' ".(($policy->getPolicy(
                                    ) == MIDAS_POLICY_READ) ? 'selected' : '').">{$this->t('can read')}</option>";
                            ?>
                        </select>
                    </td>
                    <td class='changePermissionDelete'>
                        <a class='removeShareLink'><img
                                src='<?php echo $this->coreWebroot ?>/public/images/icons/close.png' alt=''/></a>
                    </td>
                </tr>
            <?php
            }

            foreach ($this->userPolicies as $policy) {
                ?>
                <tr type='user' element='<?php echo $this->escape($policy->user->getKey()); ?>'>
                    <td>
                        <img src='<?php echo $this->coreWebroot ?>/public/images/icons/unknownUser-small.png'/>
                    </td>
                    <td class='changePermissionSelect'>
                        <?php echo $this->escape($policy->user->getFullName()); ?>
                    </td>
                    <td class='changePermissionSelectBox'>
                        <select class='changePermissionSelect'>
                            <?php
                            echo "<option value='".MIDAS_POLICY_ADMIN."' ".(($policy->getPolicy(
                                    ) == MIDAS_POLICY_ADMIN) ? 'selected' : '').">{$this->t('is owner')}</option>";
                            echo "<option value='".MIDAS_POLICY_WRITE."' ".(($policy->getPolicy(
                                    ) == MIDAS_POLICY_WRITE) ? 'selected' : '').">{$this->t('can edit')}</option>";
                            echo "<option value='".MIDAS_POLICY_READ."' ".(($policy->getPolicy(
                                    ) == MIDAS_POLICY_READ) ? 'selected' : '').">{$this->t('can read')}</option>";
                            ?>
                        </select>
                    </td>
                    <?php
                    if ($policy->user->getKey() != $this->userDao->getKey()) {
                        echo "<td class='changePermissionDelete'>";
                        echo "  <a class='removeShareLink'><img src='{$this->coreWebroot}/public/images/icons/close.png' alt=''/></a>";
                        echo "</td>";
                    }
                    ?>
                </tr>
            <?php
            }
            ?>
        </table>
        <br/>

        <div class='shareSearch'>
            <input type='text' id='live_share_search' value='<?php echo $this->t('Add a permission to ...') ?>'
                   autocomplete='off' autocorrect='off' autocapitalize='off'/>
            <input type='hidden' id='live_share_search_value' value='init'/>

            <div id='searchShareLoading' style='display:none'></div>
        </div>
    </div>

    <br/><br/>

    <div style="float: right;">
        <input type='button' style='margin-left: 0;' class='globalButton permissionsDone'
               value='<?php echo $this->t('Done') ?>'/>
    </div>
</div>

<div style="display: none;" class="jsonShareContent">
    <?php echo $this->jsonShare ?>
</div>
