<?php
/*=========================================================================
MIDAS Server
Copyright (c) Kitware SAS. 20 rue de la Villette. All rights reserved.
69328 Lyon, FRANCE.

See Copyright.txt for details.
This software is distributed WITHOUT ANY WARRANTY; without even
the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE.  See the above copyright notices for more information.
=========================================================================*/
echo '<script type="text/javascript" src="' . $this->coreWebroot . '/public/js/share/share.dialog.js?'.time().'"></script>';
?>
<link href="<?php echo $this->coreWebroot?>/public/css/share/share.dialog.css?<?php echo time();?> " rel="stylesheet" type="text/css" />

<?php
echo "<div id='elementDirectLink' ".(($this->private)?'style="display:none;"':'').">";
echo $this->t('You can use the following direct link to share the').' '.$this->t($this->type).':<br/>';
echo "<input type='text' id='urlInput' readonly='readonly' value='{$this->shareUrl}' />";
echo "</div>";
echo "<br/>";

echo "<div id='permissionsContent'>";
echo "  <div id='permissionPublic' ".(($this->private)?'style="display:none;"':'').">";
echo "    <b>{$this->t('Public')}</b> {$this->t('Anyone can find and access. No sign-in required.')}";
echo "    <a id='setElementPrivateLink'>{$this->t('You can set the permission as private.')}</a>";
echo "  </div>";

echo "  <div id='permissionPrivate' ".((!$this->private)?'style="display:none;"':'').">";
echo "    <b>{$this->t('Private')}</b> {$this->t('Only people explicitly granted permission can access. Sign-in required.')}";
echo "    <a id='setElementPublicLink'>{$this->t('You can set the permission as public.')}</a>";
echo "  </div>";

echo "      <h4>".$this->t('Permissions')."</h4>";
echo "      <div id='permissionEntity'>";
echo "        <table>";
foreach($this->groupPolicies as $policy)
  {
  echo "        <tr type='group' element='{$policy->group->getKey()}'>";
  echo "          <td>";
  echo "            <img src='{$this->coreWebroot}/public/images/icons/community.png'";
  echo "          </td>";
  echo "          <td class='changePermissionSelect'>";
  echo "            ".(($policy->communityMemberGroup)?$policy->group->getCommunity()->getName():$policy->group->getName());
  echo "          </td>";
  echo "          <td>";
  if((!$this->isAdmin&&$policy->getPolicy()==MIDAS_POLICY_ADMIN))
    {
    switch ($policy->getPolicy())
      {
      case MIDAS_POLICY_ADMIN:
        echo $this->t('is owner');
        break;
      case MIDAS_POLICY_WRITE:
        echo $this->t('can edit');
        break;
      default:
        break;
      }
    }
  else
    {
    echo "            <select class='changePermissionSelect'>";
    if($this->isAdmin)
      {
      echo "            <option value='".MIDAS_POLICY_ADMIN."' ".(($policy->getPolicy()==MIDAS_POLICY_ADMIN)?'selected':'').">{$this->t('is owner')}</option>";
      }
    echo "              <option value='".MIDAS_POLICY_WRITE."' ".(($policy->getPolicy()==MIDAS_POLICY_WRITE)?'selected':'').">{$this->t('can edit')}</option>";
    echo "              <option value='".MIDAS_POLICY_READ."' ".(($policy->getPolicy()==MIDAS_POLICY_READ)?'selected':'').">{$this->t('can read')}</option>";
    echo "            </select>";
    }
  echo "          </td>";
  echo "          <td>";
  echo "            <a class='removeShareLink'><img  src='{$this->coreWebroot}/public/images/icons/close.png' alt=''/></a>";
  echo "          </td>";
  echo "        </tr>";
  }
  
foreach($this->userPolicies as $policy)
  {
  echo "        <tr type='user' element='{$policy->user->getKey()}'>";
  echo "          <td>";
  echo "            <img src='{$this->coreWebroot}/public/images/icons/unknownUser-small.png'";
  echo "          </td>";
  echo "          <td>";
  echo "            ".$policy->user->getFullName();
  echo "          </td>";
  echo "          <td>";
  if((!$this->isAdmin&&$policy->getPolicy()==MIDAS_POLICY_ADMIN)||$policy->user->getKey()==$this->userDao->getKey())
    {
    switch ($policy->getPolicy())
      {
      case MIDAS_POLICY_ADMIN:
        echo $this->t('is owner');
        break;
      case MIDAS_POLICY_WRITE:
        echo $this->t('can edit');
        break;
      default:
        break;
      }
    }
  else
    {
  echo "            <select class='changePermissionSelect'>";
    if($this->isAdmin)
      {
      echo "          <option value='".MIDAS_POLICY_ADMIN."' ".(($policy->getPolicy()==MIDAS_POLICY_ADMIN)?'selected':'').">{$this->t('is owner')}</option>";
      }
    echo "            <option value='".MIDAS_POLICY_WRITE."' ".(($policy->getPolicy()==MIDAS_POLICY_WRITE)?'selected':'').">{$this->t('can edit')}</option>";
    echo "            <option value='".MIDAS_POLICY_READ."' ".(($policy->getPolicy()==MIDAS_POLICY_READ)?'selected':'').">{$this->t('can read')}</option>";
    echo "           </select>";
    }
  echo "          </td>";
  if($policy->user->getKey()!=$this->userDao->getKey())
    {
    echo "          <td>";
    echo "            <a class='removeShareLink' ><img src='{$this->coreWebroot}/public/images/icons/close.png' alt=''/></a>";
    echo "          </td>";
    }
  echo "        </tr>";
  }
echo "        </table>";
echo " <br/>";
echo "      <div class='shareSearch'>";
echo "        <input type='text' id='live_share_search' value='{$this->t('Add a permission to ...')}' autocomplete='off' autocorrect='off' autocapitalize='off' />";
echo "        <input type='hidden' id='live_share_search_value' value='init'  />";
echo "        <div id='searchShareLoading' style='display:none'></div>";
echo "      </div>";
echo "    </div>";

echo "</div>";

?>
<div style="display: none;" class="jsonShareContent">
  <?php echo $this->jsonShare?>
</div>