<?php
/*=========================================================================
 MIDAS Server
 Copyright (c) Kitware SAS. 26 rue Louis Guérin. 69100 Villeurbanne, FRANCE
 All rights reserved.
 More information http://www.kitware.com

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

         http://www.apache.org/licenses/LICENSE-2.0.txt

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
=========================================================================*/

echo '<script type="text/javascript" src="'.$this->coreWebroot.'/public/js/share/share.links.js"></script>';
?>
<link href="<?php echo $this->coreWebroot ?>/public/css/share/share.links.css" rel="stylesheet" type="text/css"/>

<div class="viewLinkContainer">
    You can use the following direct link to
    <b>view</b> this <?php echo $this->escape($this->type); ?>:<br/>
    <input type='text' id='resourceViewDisplay' readonly='readonly' value='<?php echo $this->escape($this->viewUrl); ?>'/>
    <button id="selectViewUrl"></button>
</div>

<div class="downloadLinkContainer">
    You can use the following direct link to
    <b>download</b> this <?php echo $this->escape($this->type); ?>:<br/>
    <input type='text' id='resourceDownloadDisplay' readonly='readonly' value='<?php echo $this->escape($this->downloadUrl); ?>'/>
    <button id="selectDownloadUrl"></button>
</div>

<div style="float: right;">
    <input type='button' class='globalButton linksDone' value='Done'/>
</div>
