<?php
/*=========================================================================
 Midas Server
 Copyright Kitware SAS, 26 rue Louis Guérin, 69100 Villeurbanne, France.
 All rights reserved.
 For more information visit http://www.kitware.com/.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

         http://www.apache.org/licenses/LICENSE-2.0.txt

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
=========================================================================*/


echo '<script type="text/javascript" src="/modules/api/public/js/common/common.ajaxapi.js"></script>';
echo '<script type="text/javascript" src="'.$this->moduleWebroot.'/public/js/producer/producer.aggregateMetric.js"></script>';
?>
<link type="text/css" rel="stylesheet" href="<?php echo $this->moduleWebroot; ?>/public/css/producer/producer.aggregatemetric.css"/>

<div id='aggregateMetricSpecManage'>
    <?php
        echo '<input type="hidden" id="producerId" value="'.$this->producer->getProducerId().'" />';
    ?>
    <input type="hidden" id='aggregateMetricSpecEditId'/>
    <div id='aggregateMetricSpecList'>
        <table id='aggregateMetricSpecListTable' class='actionTable'>
            <thead>
                <tr>
                    <th><?php echo $this->producer->getDisplayName().' metrics'; ?></th>
                    <th>Actions</th>
                </tr>
                <tbody>
                </tbody>
        </table>
    </div>
    <?php echo '<div id="addAggregateMetricSpec"><a class="actionLink aggregateMetricSpecAction" tip="Add an aggregate metric spec"><img alt="" src="'.$this->coreWebroot.'/public/images/icons/add.png" /> Add aggregate metric spec</a>'; ?>
    <img id="aggregateMetricSpecDeleteLoading" class="loadingImg" alt="loading" style="display: none;" src="/core/public/images/icons/loading.gif" /></div>
    <div id='aggregateMetricSpecCreateEdit' style='display: none;'>
        <div class="aggregateMetricSpecCreate aggregateMetricSectionTitle subsectionTitle" style="display: none;">Create aggregate metric spec</div>
        <div class="aggregateMetricSpecEdit aggregateMetricSectionTitle subsectionTitle" style="display: none;">Edit aggregate metric spec</div>
            <table class="fieldTable">
                <tbody>
                    <tr>
                        <td><label for="name"><?php echo $this->t('name') ?></label></td>
                        <td><input id='aggregateMetricSpecName' class="amsField" style="width: 100%" type="text" /></td>
                    </tr>
                    <tr>
                        <td><label for="description"><?php echo $this->t('description') ?></label></td>
                        <td><textarea rows="4" id='aggregateMetricSpecDescription' class="amsField" cols="30" style="width: 100%" /></td>
                    </tr>
                </tbody>
            </table>

        <div class="aggregateMetricSpecComposition">
            <div class="aggregateMetricSectionTitle subsubsectionTitle">Define the aggregate metric</div>
            <div id="aggregateMetricSpecEditWarning" class="aggregateMetricSpecEdit" style="display: none">Warning: do not change the metric definition of an existing spec</div>
            <table class="fieldTable">
                <tbody>
                    <tr>
                        <td>metric name</td>
                        <td>
                            <select id='aggregateMetricSpecMetricName'>
                                <option disabled selected value>  -- select a metric name -- </option>
                                <?php
                                    foreach($this->distinctTrendNames as $name) {
                                        echo '<option>'.$name.'</option>';
                                    }
                                ?>
                            </select>
                        </td>
                    </tr>
                    <tr>
                        <td>aggregate metric</td>
                        <td>
                            <select class="amsField" id='aggregateMetricSpecAggregateMetric'>
                                <option selected value='percentile'>percentile</option>
                            </select>
                        </td>
                    </tr>
                    <tr>
                        <td>percentile</td>
                        <td><input class="amsField" id='aggregateMetricSpecParam' type="text" value="95"/></td>
                    </tr>
                    <tr>
                        <td colspan="2"><div class="amsField resultingMetricText subsubsectionTitle">Generated metric</div></td>
                    </tr>
                    <tr>
                        <td colspan="2"><input style="width:100%;" id='aggregateMetricSpecSpec' type="text" disabled='disabled'/></td>
                    </tr>
                </tbody>
            </table>
        </div>
        <div id="aggregateMetricSpecSaveState" class="saveState">
            <img id="aggregateMetricSpecSaveLoading" class="loadingImg" alt="loading" style="display: none;" src="/core/public/images/icons/loading.gif" />
            <label id="aggregateMetricSpecValidationError" class="validationError"></label>
            <input id="aggregateMetricSpecCreate" class="aggregateMetricSpecCreate" style="display: none;" input type="button" value="Create" />
            <input id="aggregateMetricSpecUpdate" class="aggregateMetricSpecEdit" style="display: none;" input type="button" value="Update" />
            <input id="aggregateMetricSpecCancel" type="button" value="Cancel" />
        </div>
    </div>
    <div id='aggregateMetricUserAlerts' style='display: none;'>
        <div class='subsectionTitle'><span>Alerts for <label id='aggregateMetricUserAlertsSpecName'></label></span></div>
        <div><textarea rows='4' id='aggregateMetricUserAlertsSpec' disabled="disabled"/></div>
        <div id='aggregateMetricNotifications'>
            <table id='aggregateMetricNotificationsTable' class='actionTable'>
                <thead>
                    <tr>
                        <th>Branch</th>
                        <th>Comparison</th>
                        <th>Value</th>
                        <th>Actions</th>
                    </tr>
                    <tbody>
                    </tbody>
            </table>
        </div>
    <?php echo '<div id="addAggregateMetricNotification"><a class="actionLink aggregateMetricNotificationAction" tip="Add an aggregate metric alert"><img alt="" src="'.$this->coreWebroot.'/public/images/icons/add.png" /> Add notification to the current aggregate metric spec</a></div>'; ?>
          <div id='aggregateMetricNotificationEdit' style="display: none;">
            <div class='subsectionTitle editAlert' style="display: none;">Edit alert</div>
            <div class='subsectionTitle createAlert' style="display: none;">Create alert</div>
            <table class="fieldTable">
                <tbody>
                    <tr>
                        <td>alert threshold branch</td>
                        <td><input id='aggregateMetricNotificationBranch' class="amsField" type="text" /></td>
                    </tr>
                    <tr>
                        <td>alert threshold value</td>
                        <td><input id='aggregateMetricNotificationValue' class="amsField" type="text" /></td>
                    </tr>
                    <tr>
                        <td>alert threshold comparison</td>
                        <td>
                            <select class="amsField" id='aggregateMetricNotificationComparison'>
                                <option disabled selected value>  -- select a comparison -- </option>
                                <option>&#62;</option>
                                <option>&#62;&#61;</option>
                                <option>&#60;</option>
                                <option>&#60;&#61;</option>
                                <option>&#61;&#61;</option>
                                <option>&#33;&#61;</option>
                            </select>
                        </td>
                    </tr>
                </tbody>
            </table>
            <div id="aggregateMetricNotificationSaveState" class="saveState">
                <img id="aggregateMetricNotificationSaveLoading" class="loadingImg" alt="loading" style="display: none;" src="/core/public/images/icons/loading.gif" />
                <label id="aggregateMetricNotificationValidationError" class="validationError"></label>
                <input id="aggregateMetricNotificationCreate" class="aggregateMetricNotificationCreate" style="display: none;" input type="button" value="Create" />
                <input id="aggregateMetricNotificationUpdate" class="aggregateMetricNotificationEdit" style="display: none;" input type="button" value="Update" />
                <input id="aggregateMetricNotificationSaveCancel" type="button" value="Cancel" />
            </div>
          </div>
        <div id='aggregateMetricNotificationUsers' style="display: none;">
            <div class='subsectionTitle'></div>
            <table id='aggregateMetricSpecAlertedUsers' class='actionTable'>
                <thead>
                    <tr>
                        <th>Alerted Users</th>
                        <th>Actions</th>
                    </tr>
                    <tbody>
                    </tbody>
            </table>
            <div id="addAggregateMetricSpecAlertUser">
                <div class="subsubsectionTitle">Add a user to be alerted</div>
                <div class='alertUserSearch'>
                        <input type='text' id='addAlertUserSearch' value='' autocomplete='off'
                           autocorrect='off' autocapitalize='off'/>
                    <input type='hidden' id='addAlertUserSearchValue' value='init'/>
                </div>
            </div>
            <div id="aggregateMetricSpecUserAlertsSaveState" class="saveState">
                <img id="aggregateMetricSpecAlertsLoading" class="loadingImg" alt="loading" style="display: none;" src="/core/public/images/icons/loading.gif" />
                <label id="aggregateMetricSpecUserAlertsValidationError" class="validationError"></label>
                <input id="aggregateMetricSpecUserAlertsDone" type="button" value="Cancel" />
            </div>
        </div>
        <div class="saveState">
            <img id="aggregateMetricNotificationRemoveLoading" class="loadingImg" alt="loading" style="display: none;" src="/core/public/images/icons/loading.gif" />
            <input id="aggregateMetricNotificationCancel" type="button" style="display: none;" value="Cancel" />
        </div>
    </div>
    <div style="display: none;" class="trackerJsonContent">
        <?php echo $this->escape($this->trackerJson).PHP_EOL; ?>
    </div>
</div>
