<?php
/*=========================================================================
 Midas Server
 Copyright Kitware SAS, 26 rue Louis Guérin, 69100 Villeurbanne, France.
 All rights reserved.
 For more information visit http://www.kitware.com/.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

         http://www.apache.org/licenses/LICENSE-2.0.txt

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
=========================================================================*/

echo '<script type="text/javascript" src="/modules/api/public/js/common/common.ajaxapi.js"></script>';
echo '<script type="text/javascript" src="'.$this->moduleWebroot.'/public/js/producer/producer.aggregateMetric.js"></script>';
?>
<link type="text/css" rel="stylesheet" href="<?php echo $this->moduleWebroot; ?>/public/css/producer/producer.aggregatemetric.css"/>

<div id='aggregateMetricSpecManage'>
    <?php
        echo '<input type="hidden" id="producerId" value="'.$this->producer->getProducerId().'" />';
        echo $this->producer->getDisplayName().' existing aggregate metric specs';
    ?>
    <div id='aggregateMetricSpecList'>
    <table id='aggreagteMetricSpecListTable'>
        <thead>
            <tr>
                <th>Name</th>
                <th>Actions</th>
            </tr>
            <tbody>
                <?php
                    /** @var Tracker_AggregateMetricSpecDao $AggregateMetricSpecDao */
                    foreach ($this->aggregateMetricSpecs as $aggregateMetricSpecDao) {
                        echo '<tr>';
                        echo '<td class="specName">'.$aggregateMetricSpecDao->getName().'</td>';
                        echo '  <td><span class="actionsList">';
                        echo '  <a qtip="Edit aggregate metric spec" class="tableActions aggregateMetricSpecAction editAggregateMetricSpec" data-aggregate_metric_spec_id="'.$aggregateMetricSpecDao->getAggregateMetricSpecId().'">';
                        echo '    <img class="tableActions" alt="" src="'.$this->coreWebroot.'/public/images/icons/edit.png" /> Edit</a>';
                        echo '  <a qtip="Remove aggregate metric spec" class="tableActions aggregateMetricSpecAction removeAggregateMetricSpec" data-aggregate_metric_spec_id="'.$aggregateMetricSpecDao->getAggregateMetricSpecId().'">';
                        echo '    <img class="tableActions" alt="" src="'.$this->coreWebroot.'/public/images/icons/close.png" /> Delete</a>';
                        echo '</tr>';
                    }
                ?>
            </tbody>
    </table>
    </div>
    <?php echo '<div id="addAggregateMetricSpec"><a class="aggregateMetricSpecAction" tip="Add an aggregate metric spec"><img class="tableActions" alt="" src="'.$this->coreWebroot.'/public/images/icons/add.png" /> Add aggregate metric spec</a>'; ?>
    <img id="aggregateMetricSpecDeleteLoading" alt="loading" style="display: none;" src="/core/public/images/icons/loading.gif" /></div>
    <div id='aggregateMetricSpecCreateEdit' style='display: none;'>
        <input type="hidden" id='aggregateMetricSpecEditId'/>
        <div class="aggregateMetricSectionTitle aggregateMetricSpecCreate" style="display: none;">Create the aggregate metric spec</div>
        <div class="aggregateMetricSectionTitle aggregateMetricSpecEdit" style="display: none;">Edit aggregate metric spec</div>
            <table>
                <tbody>
                    <tr>
                        <td><label for="name"><?php echo $this->t('name') ?></label></td>
                        <td><input id='aggregateMetricSpecName' class="amsField" style="width: 100%" type="text" /></td>
                    </tr>
                    <tr>
                        <td><label for="description"><?php echo $this->t('description') ?></label></td>
                        <td><textarea rows="4" id='aggregateMetricSpecDescription' class="amsField" cols="30" style="width: 100%" /></td>
                    </tr>
                </tbody>
            </table>

        <div class="aggregateMetricSpecComposition">
            <div class="aggregateMetricSectionTitle">Define the aggregate metric</div>
            <table>
                <tbody>
                    <tr>
                        <td>metric name</td>
                        <td>
                            <select id='aggregateMetricSpecMetricName'>
                                <option disabled selected value>  -- select a metric name -- </option>
                                <?php
                                    foreach($this->distinctTrendNames as $name) {
                                        echo '<option>'.$name.'</option>';
                                    }
                                ?>
                            </select>
                        </td>
                    </tr>
                    <tr>
                        <td>branch</td>
                        <td>
                            <select class="amsField" id='aggregateMetricSpecBranch'>
                                <option disabled selected value>  -- select a branch -- </option>
                            </select>
                        </td>
                    </tr>
                    <tr>
                        <td>aggregate metric</td>
                        <td>
                            <select class="amsField" id='aggregateMetricSpecAggregateMetric'>
                                <option selected value='percentile'>percentile</option>
                            </select>
                        </td>
                    </tr>
                    <tr>
                        <td>percentile</td>
                        <td><input class="amsField" id='aggregateMetricSpecParam' type="text" value="95"/></td>
                    </tr>
                    <tr>
                        <td colspan="2"><div class="amsField resultingMetricText">generated metric</div></td>
                    </tr>
                    <tr>
                        <td colspan="2"><input style="width:100%;" id='aggregateMetricSpecSpec' type="text" disabled='disabled'/></td>
                    </tr>
                </tbody>
            </table>
            <div class="aggregateMetricSectionTitle">Define the notification threshold</div>
            <table>
                <tbody>
                    <tr>
                        <td>notification threshold comparison</td>
                        <td>
                            <select class="amsField" id='aggregateMetricSpecComparison'>
                                <option disabled selected value>  -- select a comparison -- </option>
                                <option>&#62;</option>
                                <option>&#62;&#61;</option>
                                <option>&#60;</option>
                                <option>&#60;&#61;</option>
                                <option>&#61;&#61;</option>
                                <option>&#33;&#61;</option>
                            </select>
                        </td>
                    </tr>
                    <tr>
                        <td>notification threshold value</td>
                        <td><input id='aggregateMetricSpecValue' class="amsField" type="text" /></td>
                    </tr>
                </tbody>
            </table>
        </div>
        <div id="aggregateMetricSpecSaveState">
            <img id="aggregateMetricSpecSaveLoading" alt="loading" style="display: none;" src="/core/public/images/icons/loading.gif" />
            <label id="aggregateMetricSpecValidationError"></label>
            <input id="aggregateMetricSpecCreate" class="aggregateMetricSpecCreate" style="display: none;" input type="button" value="Create" />
            <input id="aggregateMetricSpecUpdate" class="aggregateMetricSpecEdit" style="display: none;" input type="button" value="Update" />
            <input id="aggregateMetricSpecCancel" type="button" value="Cancel" />
        </div>
    </div>
</div>
