<?php
/*=========================================================================
 MIDAS Server
 Copyright (c) Kitware SAS. 26 rue Louis Guérin. 69100 Villeurbanne, FRANCE
 All rights reserved.
 More information http://www.kitware.com

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

         http://www.apache.org/licenses/LICENSE-2.0.txt

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
=========================================================================*/
?>
<script type="text/javascript" src="<?php echo $this->coreWebroot; ?>/public/js/jquery/jquery.form.js"></script>
<script type="text/javascript"
        src="<?php echo $this->coreWebroot; ?>/public/js/jquery/jquery.autogrow-textarea.js"></script>
<script type="text/javascript" src="<?php echo $this->moduleWebroot; ?>/public/js/producer/producer.edit.js"></script>

<link type="text/css" rel="stylesheet" href="<?php echo $this->moduleWebroot; ?>/public/css/producer/producer.edit.css"/>

<div class="formWrapper">
    <form class="editProducerForm genericForm" action="<?php echo $this->webroot; ?>/tracker/producer/editsubmit"
          method="POST">
        <div class="formRow">
            <label for="displayName">Name</label>
            <input type="text" id="displayName" name="displayName" value="<?php echo $this->producer->getDisplayName(); ?>"/>
        </div>
        <div class="formRow">
            <label for="description">Description</label>
            <textarea class="description" id="description" name="description"><?php echo $this->producer->getDescription(); ?></textarea>
        </div>
        <div class="formRow">
            <label for="repository">Repository URL</label>
            <input type="text" id="repository" name="repository" value="<?php echo $this->producer->getRepository(); ?>"/>
        </div>
        <div class="formRow">
            <label for="revisionUrl">Revision URL</label>
            <input type="text" id="revisionUrl" name="revisionUrl" value="<?php echo $this->producer->getRevisionUrl(); ?>"/>
        </div>
        <div class="formRow">
            <label for="executableName">Executable Name</label>
            <input type="text" id="executableName" name="executableName" value="<?php echo $this->producer->getExecutableName(); ?>"/>
        </div>
        <input type="hidden" id="producerId" name="producerId" value="<?php echo $this->producer->getKey(); ?>"/>

        <div class="submitButtonContainer">
            <input type="submit" class="globalButton" value="Save"/>
        </div>
    </form>
</div>
