<?php
/*=========================================================================
MIDAS Server
Copyright (c) Kitware SAS. 20 rue de la Villette. All rights reserved.
69328 Lyon, FRANCE.

See Copyright.txt for details.
This software is distributed WITHOUT ANY WARRANTY; without even
the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE.  See the above copyright notices for more information.
=========================================================================*/
?>
<script type="text/javascript" src="<?php echo $this->moduleWebroot?>/public/js/producer/producer.list.js"></script>
<link type="text/css" rel="stylesheet" href="<?php echo $this->moduleWebroot?>/public/css/producer/producer.list.css" />

<div class="producersTabWrapper">
  <div class="introText">The <?php echo $this->community->getName(); ?> community contains the following producers:</div>

  <div class="producerList">
    <?php
    if(count($this->producers) == 0)
      {
      echo '<div class="noProducers">There are no producers for this community yet.</div>';
      }

    foreach($this->producers as $producer)
      {
      echo '<div class="producerContainer">';
      echo   '<a class="producerLink" href="'.$this->webroot.'/tracker/producer/view?producerId='.$producer->getKey().'">';
      echo   $producer->getDisplayName().'</a>';
      if($producer->getDescription() != '')
        {
        echo '<div class="producerDescription">'.$producer->getDescription().'</div>';
        }
      echo '</div>';
      }
    ?>
  </div>
</div>
