<?php
/*=========================================================================
 Midas Server
 Copyright Kitware SAS, 26 rue Louis Guérin, 69100 Villeurbanne, France.
 All rights reserved.
 For more information visit http://www.kitware.com/.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

         http://www.apache.org/licenses/LICENSE-2.0.txt

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
=========================================================================*/
?>
<script type="text/javascript" src="<?php echo $this->moduleWebroot; ?>/public/js/producer/producer.list.js"></script>
<link type="text/css" rel="stylesheet" href="<?php echo $this->coreWebroot; ?>/public/css/common/common.genericPage.css"/>
<link type="text/css" rel="stylesheet" href="<?php echo $this->coreWebroot; ?>/public/css/community/community.view.css"/>
<link type="text/css" rel="stylesheet" href="<?php echo $this->moduleWebroot; ?>/public/css/producer/producer.list.css"/>

<?php
if ($this->directLink) {
?>
   <div class="viewMain">
     <div class="genericThumbnail">
       <?php
         $thumbnail = null;
         if (!empty($thumbnail)) {
           echo "<img src='{$this->webroot}data/thumbnail/{$this->escape($thumbnail)}' alt=''/>";
         } else {
           echo "<img src='{$this->coreWebroot}/public/images/icons/community-big.png' alt=''/>";
         }
       ?>
       </div>
       <div class="genericInfo">
       <div class="genericName"><?php echo $this->escape($this->community->getName().' Producers'); ?></div>
       <div id="communitySubtitle" class="genericSubtitle" style="color:grey;">
         <?php
         if (!empty($rawDescription)) {
           echo substr($this->escape($strippedDescription), 0, 240).' <a href="#" class="more">More &raquo;</a>';
         }
         ?>
       </div>
     </div>
<?php
    echo '<div class="producersDirectLink">';
} else {
    echo '<div class="producersTabWrapper">';
}
?>
    <div class="producerList">
        <?php
        if (empty($this->producers)) {
            echo '<div class="noProducers">There are no producers for this community yet.</div>';
        }

        /** @var Tracker_ProducerDao $producerDao */
        foreach ($this->producers as $producerDao) {
            echo '<div class="producerContainer">';
            echo '<a class="producerLink" href="'.$this->webroot.'/tracker/producer/view?producerId='.$this->escape($producerDao->getKey(
                )).'">';
            echo $producerDao->getDisplayName().'</a>';
            if ($producerDao->getDescription() != '') {
                echo '<div class="producerDescription">'.$this->escape($producerDao->getDescription()).'</div>';
            }
            if (array_key_exists($producerDao->getProducerId(), $this->producerListLinks)) {
                /** @var string $text */
                /** @var string $url */
                foreach($this->producerListLinks[$producerDao->getProducerId()] as $text => $url) {
                    echo '<div class="producerLink"><a href="'.$url.'">'.$text.'</a></div>';
                }
            }
            echo '</div>';
        }
        ?>
    </div>
</div>
<?php
if ($this->directLink) {
    echo '</div>';
}
?>
