<?php
/*=========================================================================
 MIDAS Server
 Copyright (c) Kitware SAS. 26 rue Louis Guérin. 69100 Villeurbanne, FRANCE
 All rights reserved.
 More information http://www.kitware.com

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

         http://www.apache.org/licenses/LICENSE-2.0.txt

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
=========================================================================*/
?>
<script type="text/javascript" src="<?php echo $this->moduleWebroot; ?>/public/js/producer/producer.list.js"></script>
<link type="text/css" rel="stylesheet" href="<?php echo $this->moduleWebroot; ?>/public/css/producer/producer.list.css"/>

<div class="producersTabWrapper">
    <div class="introText">The <?php echo $this->escape($this->community->getName()); ?> community contains the following producers:
    </div>

    <div class="producerList">
        <?php
        if (empty($this->producers)) {
            echo '<div class="noProducers">There are no producers for this community yet.</div>';
        }

        /** @var Tracker_ProducerDao $producerDao */
        foreach ($this->producers as $producerDao) {
            echo '<div class="producerContainer">';
            echo '<a class="producerLink" href="'.$this->webroot.'/tracker/producer/view?producerId='.$this->escape($producerDao->getKey(
                )).'">';
            echo $producerDao->getDisplayName().'</a>';
            if ($producerDao->getDescription() != '') {
                echo '<div class="producerDescription">'.$this->escape($producerDao->getDescription()).'</div>';
            }
            echo '</div>';
        }
        ?>
    </div>
</div>
