<?php
/*=========================================================================
MIDAS Server
Copyright (c) Kitware SAS. 20 rue de la Villette. All rights reserved.
69328 Lyon, FRANCE.

See Copyright.txt for details.
This software is distributed WITHOUT ANY WARRANTY; without even
the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE.  See the above copyright notices for more information.
=========================================================================*/
$this->headScript()->appendFile($this->moduleWebroot.'/public/js/producer/producer.view.js');
?>
<link type="text/css" rel="stylesheet" href="<?php echo $this->moduleWebroot?>/public/css/producer/producer.view.css" />
<link type="text/css" rel="stylesheet" href="<?php echo $this->coreWebroot?>/public/css/common/common.browser.css" />

<div class="viewMain">
  <div class="producerInfoContainer">
    <div class="sectionTitle">Producer Information</div>
    <div class="producerData"><b>Description:</b> <span class="description"><?php echo $this->producer->getDescription();?></span></div>
    <div class="producerData"><b>Repository:</b> <span class="repository"><?php echo $this->producer->getRepository();?></span></div>
    <div class="producerData"><b>Executable:</b> <span class="executable"><?php echo $this->producer->getExecutableName();?></span></div>
  </div>

  <div class="producerTrendsContainer">
    <div class="sectionTitle">Trends (<?php echo count($this->trends);?>)</div>
      <?php
      foreach($this->trends as $trend)
        {
        echo '<div class="trendContainer">';
        echo '<input type="checkbox" class="selectTrend" element="'.$trend->getKey().'" />';
        echo '<a class="trendLink" href="'.$this->webroot.'/tracker/trend/view?trendId='.$trend->getKey().'">';
        echo $trend->getDisplayName().'</a>'; 
        echo '</div>';
        }
      ?>
  </div>
</div>

<div class="viewSideBar">
  <div class="sideElementFirst viewAction">
    <h1>Actions</h1>
    <ul>
    <?php if($this->isAdmin)
      {
    ?>
      <li>
        <a class="editProducerInfo">
          <img alt="" src="<?php echo $this->coreWebroot?>/public/images/icons/edit.png"/> Edit
        </a>
      </li>
      <li>
        <a class="deleteProducer"><img alt="" src="<?php echo $this->coreWebroot?>/public/images/icons/close.png"/> Delete</a>
      </li>
    <?php
      }
    ?>
      <li>
        <a class="visualizeSelected"><img alt="" src="<?php echo $this->moduleWebroot?>/public/images/chart_line.png"/> Visualize selected</a>
      </li>
    </ul>
  </div>
</div>
