<?php
/*=========================================================================
 MIDAS Server
 Copyright (c) Kitware SAS. 26 rue Louis Guérin. 69100 Villeurbanne, FRANCE
 All rights reserved.
 More information http://www.kitware.com

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

         http://www.apache.org/licenses/LICENSE-2.0.txt

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
=========================================================================*/

$this->headScript()->appendFile($this->moduleWebroot.'/public/js/producer/producer.view.js');
?>
<link type="text/css" rel="stylesheet" href="<?php echo $this->moduleWebroot ?>/public/css/producer/producer.view.css"/>
<link type="text/css" rel="stylesheet" href="<?php echo $this->coreWebroot ?>/public/css/common/common.browser.css"/>

<div class="viewMain">
    <div class="producerInfoContainer">
        <div class="sectionTitle">Producer Information</div>
        <div class="producerData"><b>Description:</b>
            <span class="description"><?php echo $this->escape($this->producer->getDescription()); ?></span>
        </div>
        <div class="producerData"><b>Repository:</b>
            <span class="repository"><?php echo $this->escape($this->producer->getRepository()); ?></span>
        </div>
        <div class="producerData"><b>Executable:</b>
            <span class="executable"><?php echo $this->escape($this->producer->getExecutableName()); ?></span>
        </div>
    </div>

    <div class="sectionTitle">Trends</div>

    <?php
    foreach ($this->trendGroups as $trendGroup)
    {
    echo '<div class="trendGroupContainer">';
    if ($trendGroup['configItem']) {
        echo '<div class="datasetHeader"><b>Configuration:</b> ';
        echo '<a href='.$this->webroot.'/item/'.$this->escape($trendGroup['configItem']->getKey(
            )).'>'.$this->escape($trendGroup['configItem']->getName()).'</a>';
        echo '</div>';
    }
    if ($trendGroup['testDataset']) {
        echo '<div class="datasetHeader"><b>Test Data:</b> ';
        echo '<a href='.$this->webroot.'/item/'.$this->escape($trendGroup['testDataset']->getKey(
            )).'>'.$this->escape($trendGroup['testDataset']->getName()).'</a>';
        echo '</div>';
    }
    if ($trendGroup['truthDataset']) {
        echo '<div class="datasetHeader"><b>Ground Truth Data: </b>';
        echo '<a href='.$this->webroot.'/item/'.$this->escape($trendGroup['truthDataset']->getKey(
            )).'>'.$this->escape($trendGroup['truthDataset']->getName()).'</a>';
        echo '</div>';
    }
    if ($trendGroup['configItem'] || $trendGroup['testDataset'] || $trendGroup['truthDataset']) {
        echo '<div class="headerSeparator"></div>';
    }
    ?>
    <div class="producerTrendsContainer">
        <?php
        foreach ($trendGroup['trends'] as $trend) {
            echo '<div class="trendContainer">';
            echo '<input type="checkbox" class="selectTrend" element="'.$this->escape($trend->getKey()).'" />';
            echo '<a class="trendLink" href="'.$this->webroot.'/tracker/trend/view?trendId='.$this->escape($trend->getKey()).'">';
            echo $this->escape($trend->getDisplayName()).'</a>';
            echo '</div>';
        }
        ?>
    </div>
</div>
<?php
}
?>
</div>

<div class="viewSideBar">
    <div class="sideElementFirst viewAction">
        <h1>Actions</h1>
        <ul>
            <?php if ($this->isAdmin) {
                ?>
                <li>
                    <a class="editProducerInfo">
                        <img alt="" src="<?php echo $this->coreWebroot ?>/public/images/icons/edit.png"/> Edit
                    </a>
                </li>
                <li>
                    <a class="deleteProducer"><img alt=""
                                                   src="<?php echo $this->coreWebroot ?>/public/images/icons/close.png"/>
                        Delete</a>
                </li>
            <?php
            }
            ?>
            <li>
                <a style="display: none;" class="visualizeSelected"><img alt=""
                                                                         src="<?php echo $this->moduleWebroot ?>/public/images/chart_line.png"/>
                    Plot selected (<span class="selectedTrendCount"></span>)</a>
            </li>
            <li>
                <a style="display: none;" class="visualizeDualAxis"><img alt=""
                                                                         src="<?php echo $this->moduleWebroot ?>/public/images/chart_line.png"/>
                    Dual axis plot</a>
            </li>
        </ul>
    </div>
</div>
