<?php
/*=========================================================================
 Midas Server
 Copyright Kitware SAS, 26 rue Louis Guérin, 69100 Villeurbanne, France.
 All rights reserved.
 For more information visit http://www.kitware.com/.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

         http://www.apache.org/licenses/LICENSE-2.0.txt

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
=========================================================================*/

echo '<script type="text/javascript" src="'.$this->coreWebroot.'/public/js/user/user.deletedialog.js?'.time(
    ).'"></script>';
$this->headScript()->appendFile($this->coreWebroot.'/public/js/jquery/jquery.form.js');
?>
<link href="<?php echo $this->coreWebroot ?>/public/css/user/user.deletedialog.css" rel="stylesheet" type="text/css"/>

<span id="deleteDialogCaution">CAUTION:</span>
<?php
if ($this->deleteSelf) {
    ?>
    Are you sure you want to delete your user account?
<?php
} else {
    ?>
    Are you sure you want to delete the user
    <span id="deleteDialogUserName"><?php echo $this->escape($this->user->getFirstname()).' '.$this->escape($this->user->getLastname()); ?></span>?
<?php
} ?>
<br/><br/>
<?php
if ($this->deleteSelf) {
    ?>
    Your entire folder tree and all data within it will be deleted as well. This action cannot be undone.
<?php
} else {
    ?>
    The user's entire folder tree and all data within it will be deleted as well.  This action cannot be undone.
<?php
} ?>
<div>
    <br/>

    <form id="deleteDialogForm" class="genericForm" method="POST" action="<?php echo $this->webroot ?>/user/delete">
        <input type='hidden' name="userId" value="<?php echo $this->escape($this->user->getKey()); ?>"/>
        <input type="checkbox" id="deleteDialogAgreeCheckbox">I understand the implications and wish to proceed.</input>
        <br/><br/>

        <div style="float: right;">
            <input class="genericButton" disabled="disabled" type='submit' name='submitButton'
                   id='deleteDialogDeleteButton'
                   value='<?php echo $this->t('Delete') ?>'/>
            <input class="genericButton" style="margin-left: 15px;" type='button' name='deleteDialogCancelButton'
                   id='deleteDialogCancelButton'
                   value='<?php echo $this->t('Cancel') ?>'/>
        </div>
    </form>
    <img id="deleteDialogLoadingGif" style="display: none; float: left" alt=""
         src="<?php echo $this->coreWebroot ?>/public/images/icons/loading.gif"/>
</div>
