<?php
/*=========================================================================
MIDAS Server
Copyright (c) Kitware SAS. 20 rue de la Villette. All rights reserved.
69328 Lyon, FRANCE.

See Copyright.txt for details.
This software is distributed WITHOUT ANY WARRANTY; without even
the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE.  See the above copyright notices for more information.
=========================================================================*/

$this->headScript()->appendFile($this->coreWebroot.'/public/js/jquery/jquery.form.js');
$this->headScript()->appendFile($this->coreWebroot.'/public/js/user/user.emailregister.js');
?>
<link type="text/css" rel="stylesheet" href="<?php echo $this->coreWebroot?>/public/css/user/user.emailregister.css" />

<div class="viewMain">
  Fill in the form below to complete your registration and join the community.

  <div>
  </div>
  <form class="genericForm" id="registerForm" method="POST">
    <input type="hidden" name="email" value="<?php echo $this->email?>" />
    <input type="hidden" name="authKey" value="<?php echo $this->authKey?>" />
    <div class="emailLabelContainer">
      <label>Email</label>
      <span class="emailDisplay"><?php echo $this->email?></span>
    </div>
    <div>
      <label for="firstName">First name</label>
      <input type="text" name="firstName" />
    </div>
    <div>
      <label for="lastName">Last name</label>
      <input type="text" name="lastName" />
    </div>
    <div>
      <label for="password">Password</label>
      <input type="password" name="password1" />
    </div>
    <div>
      <label for="password2">Retype password</label>
      <input type="password" name="password2" />
    </div>
    <div class="tosContainer">
      <label for="conditions"></label>
      <?php echo $this->t("I have read and accept the")?> <a class='termOfService' href='javascript:;'>
      <?php echo $this->t('terms of service')?></a>
      <input type="checkbox" name="conditions" class="tosAccept" />
    </div>
    <input type="submit" name="submitRegistration" value="Submit" />
  </form>
</div>
