<?php
/*=========================================================================
 MIDAS Server
 Copyright (c) Kitware SAS. 26 rue Louis Guérin. 69100 Villeurbanne, FRANCE
 All rights reserved.
 More information http://www.kitware.com

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

         http://www.apache.org/licenses/LICENSE-2.0.txt

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
=========================================================================*/

$this->headScript()->appendFile($this->coreWebroot.'/public/js/jquery/jquery.form.js');
$this->headScript()->appendFile($this->coreWebroot.'/public/js/user/user.emailregister.js');
?>
<link type="text/css" rel="stylesheet" href="<?php echo $this->coreWebroot ?>/public/css/user/user.emailregister.css"/>

<div class="viewMain">
    Fill in the form below to complete your registration and join the community.

    <div>
    </div>
    <form class="genericForm" id="registerForm" method="POST">
        <input type="hidden" name="email" value="<?php echo $this->escape($this->email); ?>"/>
        <input type="hidden" name="authKey" value="<?php echo $this->escape($this->authKey); ?>"/>

        <div class="emailLabelContainer">
            <label>Email</label>
            <span class="emailDisplay"><?php echo $this->escape($this->email); ?></span>
        </div>
        <div>
            <label for="firstName">First name</label>
            <input type="text" name="firstName"/>
        </div>
        <div>
            <label for="lastName">Last name</label>
            <input type="text" name="lastName"/>
        </div>
        <div>
            <label for="password">Password</label>
            <input type="password" name="password1"/>
        </div>
        <div>
            <label for="password2">Retype password</label>
            <input type="password" name="password2"/>
        </div>
        <div class="tosContainer">
            <label for="conditions"></label>
            <?php echo $this->t("I have read and accept the") ?>
            <a class='termOfService' href='javascript:;'>
                <?php echo $this->t('terms of service') ?></a>
            <input type="checkbox" name="conditions" class="tosAccept"/>
        </div>
        <input type="submit" name="submitRegistration" value="Submit"/>
    </form>
</div>
