<?php
/*=========================================================================
MIDAS Server
Copyright (c) Kitware SAS. 20 rue de la Villette. All rights reserved.
69328 Lyon, FRANCE.

See Copyright.txt for details.
This software is distributed WITHOUT ANY WARRANTY; without even
the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE.  See the above copyright notices for more information.
=========================================================================*/

$this->headScript()->appendFile($this->coreWebroot.'/public/js/user/user.index.js');
?>
<link href="<?php echo $this->coreWebroot?>/public/css/user/user.index.css" rel="stylesheet" type="text/css" />

<div class="viewMain">
  <div class="userList">
  <?php
  echo "<h3 class='userSubTitle'>";
  switch ($this->order)
    {
    case 'lastname':
      echo $this->t('Alphabetic');
      break;
    case 'view':
      echo $this->t('Most Popular');
      break;
    default:
      break;
    }
  echo "</h3>";
  if($this->order == 'lastname')
    {
    echo "<a href='{$this->webroot}/user?order=lastname'>{$this->t('All')}</a> ";
    for ($i=ord("A");$i<ord("Z");$i++)
      {
      if($this->offset === chr($i))
        {
        echo chr($i)." ";
        }
      else
        {
        echo "<a href='{$this->webroot}/user?order=lastname&offset=".chr($i)."'>".chr($i)."</a> ";
        }
      }
    
    }
  if(!empty($this->users))
    {
    foreach($this->users as $user)
      {
      ?>  
      <div class="userBlock">
      <?php
        echo $this->linkuser($user);
      ?>
      <br/>
      </div>
  <?php    
      }
    }
  ?>
  </div>
  
    <?php 
  if(empty($this->users))
    {    
    echo "<h4>{$this->t("No public user to show.")}. </h4>";
    }
    ?>
</div>
<div class="viewSideBar">
  <div class="sideElementFirst viewAction">
    <h1>Order</h1>
    <ul>
      <?php
      if($this->order != 'lastname')
        {
        echo "<li><a href='{$this->webroot}/user?order=lastname'>{$this->t('Alphabetic')}</a></li>";
        }
      else
        {
         echo "<li>{$this->t('Alphabetic')}</li>"; 
        }
      ?>
      <?php
      if($this->order != 'view')
        {
        echo "<li><a href='{$this->webroot}/user?order=view'>{$this->t('Popularity')}</a></li>";
        }
      else
        {
         echo "<li>{$this->t('Popularity')}</li>"; 
        }
      ?>
    </ul>
  </div>

  <div class="sideElement viewSelected" >
      <h1><?php echo $this->t('Selected')?></h1>
      <span></span>
  </div>
      
  <div class="sideElementLast viewInfo">
    <h1>Info</h1>    
    <?php
    echo count($this->users).' '.(count($this->users)>1?$this->t('Public users'):$this->t('Public user'));
    ?>
  </div>
</div>




