<?php
/*=========================================================================
MIDAS Server
Copyright (c) Kitware SAS. 20 rue de la Villette. All rights reserved.
69328 Lyon, FRANCE.

See Copyright.txt for details.
This software is distributed WITHOUT ANY WARRANTY; without even
the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE.  See the above copyright notices for more information.
=========================================================================*/

$this->headScript()->appendFile($this->coreWebroot . '/public/js/jquery/jquery.form.js');
$this->headScript()->appendFile($this->coreWebroot . '/public/js/user/user.manage.js');
$this->headScript()->appendFile($this->coreWebroot.'/public/js/common/common.browser.js');
?>
<link type="text/css" rel="stylesheet" href="<?php echo $this->coreWebroot?>/public/css/user/user.manage.css" />
<link type="text/css" rel="stylesheet" href="<?php echo $this->coreWebroot?>/public/css/common/common.browser.css" />
<link type="text/css" rel="stylesheet" href="<?php echo $this->coreWebroot?>/public/css/common/common.genericPage.css" />

<div class="viewMain">
  <div class="genericThumbnail">
  <?php
  $thumbnail=$this->user->getThumbnail();
  if(!empty($thumbnail))
    {
    echo "<img class='thumbnailSmall' src='{$this->webroot}/{$thumbnail}' alt=''/>";
    }
  else
    {
    echo "<img  class='thumbnailSmall' src='{$this->coreWebroot}/public/images/icons/unknownUser.png' alt=''/>";
    }
  ?>
  </div>
  <div class="genericInfo">
    <div class="genericName"><?php echo $this->user->getFullName();?></div>
    <div class="genericCompany"><?php echo $this->user->getCompany();?></div>
  </div>

  <img class="tableLoading" alt=""  src="<?php echo $this->coreWebroot?>/public/images/icons/loading.gif" />
  Drag and drop to move elements.
  <table id="browseTable" class="midasTree">
    <thead>
          <th class="thData"><?php echo $this->t('Name');?></th>
          <th class="thSize"><?php echo $this->t('Size');?></th>
          <th class="thDate"><?php echo $this->t('Modified');?></th>
          <th class="thCheckbox"></th>
    </thead>
    <tbody>
            <?php
            $node=1;

            foreach($this->folders as $folder)
              {
              echo "<tr id='node--$node' class='parent' privacy='{$folder->getPrivacyStatus()}' policy='".MIDAS_POLICY_ADMIN."' type='folder' element='{$folder->getFolderId()}' ajax='{$folder->getFolderId()}'>";
              echo "  <td class='treeBrowseElement'><span class='notdraggable folder'>{$folder->getName()}</span></td>";
              echo "  <td><img class='folderLoading'  element='{$folder->getFolderId()}' alt='' src='{$this->coreWebroot}/public/images/icons/loading.gif'/></td>";
              echo "  <td>{$this->Date->ago($folder->getDate(),true)}</td>";
              echo "  <td><input type='checkbox' class='treeCheckbox' type='folder' element='{$folder->getFolderId()}' /></td>";
              echo "</tr>";
              $node++;
              } 
              
            foreach($this->items as $item)
              {
              echo "<tr id='node--$node' policy='{$item->policy}' privacy='{$item->getPrivacyStatus()}' class='' type='item' element='{$item->getItemId()}' >";
              echo "  <td class='treeBrowseElement'><span class='file'>{$this->slicename($item->getName(),40)}</span></td>";
              echo "  <td>{$item->size}</td>";
              echo "  <td>{$this->Date->ago($item->getDate(),true)}</td>";
              echo "  <td><input type='checkbox' class='treeCheckbox' type='item' element='{$item->getItemId()}' /></td>";
              echo "</tr>";
              $node++;
              }
            ?>


      </tbody>
  </table>
 
</div>

<div class="viewSideBar">
  
    <div class="sideElementFirst viewAction">
    <h1>Actions</h1>
      <ul>
        <?php
        echo "<li><a onclick='createNewFolder(".$this->mainFolder->getKey().");'><img alt='' src='{$this->coreWebroot}/public/images/FileTree/directory.png'/> {$this->t('Create top level Folder')}</a></li>";
        ?>
      </ul>
    </div>
    <div class="sideElement viewSelected" >
      <h1><?php echo $this->t('Selected')?></h1>
      <span></span>
    </div>
    <div class="sideElementLast viewInfo">
      <h1>Info</h1>    
      <img class="infoLoading" style="display:none;" alt="" src="<?php echo $this->coreWebroot?>/public/images/icons/loading.gif"/>
      <div class="ajaxInfoElement">
      </div>
    </div>
</div>



