<?php
/** AJAX Action !!!! */
  echo '<script type="text/javascript" src="' . $this->coreWebroot . '/public/js/jquery/jquery.form.js"></script>';
  echo '<script type="text/javascript" src="' . $this->coreWebroot . '/public/js/user/user.recoverpassword.js?'.time().'"></script>';
?>

<link type="text/css" rel="stylesheet" href="<?php echo $this->coreWebroot?>/public/css/user/user.recoverpassword.css" />

<form id="recoverPasswordForm" class="genericForm" method="POST"  action="<?php echo $this->webroot?>/user/recoverpassword">
  <h4><?php echo $this->t('Please enter your e-mail address.');?></h4>
      <div >
        <label for="email"><?php echo $this->t("E-mail")?></label>
        <input type='text' name="email"/>
      </div>
     <br/>
      <div>
         <input type='submit' name='createFolder' value='<?php echo $this->t('Recover')?>'/>
      </div>
</form>