<?php
/*=========================================================================
 MIDAS Server
 Copyright (c) Kitware SAS. 26 rue Louis Guérin. 69100 Villeurbanne, FRANCE
 All rights reserved.
 More information http://www.kitware.com

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

         http://www.apache.org/licenses/LICENSE-2.0.txt

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
=========================================================================*/

echo '<script type="text/javascript" src="'.$this->coreWebroot.'/public/js/jquery/jquery.form.js"></script>';
echo '<script type="text/javascript" src="'.$this->coreWebroot.'/public/js/user/user.recoverpassword.js"></script>';
?>

<form id="recoverPasswordForm" class="genericForm" method="POST"
      action="<?php echo $this->webroot ?>/user/recoverpassword">
    <h4><?php echo $this->t('Please enter your email address.'); ?></h4>

    <div>
        <label for="email"><?php echo $this->t("Email") ?></label>
        <input type='text' name="email"/>
    </div>
    <br/>

    <div>
        <input type='submit' name='createFolder' value='<?php echo $this->t('Recover') ?>'/>
    </div>
</form>
