<?php
echo '<script type="text/javascript" src="' . $this->coreWebroot . '/public/js/jquery/jquery.form.js"></script>';
echo '<script type="text/javascript" src="' . $this->coreWebroot . '/public/js/user/user.settings.js?'.time().'"></script>';
?>
<link type="text/css" rel="stylesheet" href="<?php echo $this->coreWebroot?>/public/css/user/user.settings.css?<?php echo time(); ?>" />

<div id="tabsSettings">
	<ul>
		<li><a href="#tabs-account"><?php echo $this->t('My Account') ?></a></li>
		<li><a href="#tabs-password"><?php echo $this->t('Password') ?></a></li>
		<li><a href="#tabs-modules"><?php echo $this->t('Modules') ?></a></li>
	</ul>
	<div id="tabs-account">
    <h3><?php echo $this->t('Modify my information')?>:</h3>
    <form  class="genericForm" id="modifyAccount" method="<?php echo $this->accountForm['method']?>"  action="<?php echo $this->accountForm['action']?><?php echo (isset($_GET['userId'])?'?userId='.$_GET['userId']:'')?>">
      <table>
        <tr>
          <td><?php echo $this->t('Firstname');?><?php echo $this->accountForm['firstname']?></td>
          <td><?php echo $this->t('Lastname');?><?php echo $this->accountForm['lastname']?></td>
        </tr>
        <tr>
          <td><?php echo $this->t('Company');?><?php echo $this->accountForm['company']?></td>
        </tr>
        <tr>
          <td><?php echo $this->t('Privacy');?><?php echo $this->accountForm['privacy']?></td>
        </tr>
        <tr>
          <td><?php echo $this->accountForm['modifyAccount']?></td>
        </tr>
      </table>
    </form>
    <h3><?php echo $this->t('My picture')?>:</h3>
      <?php
      $thumbnail=$this->thumbnail;
      if(!empty($thumbnail))
        {
        echo "<img id='userTopThumbnail' src='{$this->webroot}/{$thumbnail}' alt=''/>";
        }
      else
        {
        echo "<img id='userTopThumbnail' src='{$this->coreWebroot}/public/images/icons/unknownUser.png' alt=''/>";
        }
      ?>
    <h3><?php echo $this->t('Modify my picture')?>:</h3>
    <form class="genericForm" id="modifyPicture" action="<?php echo $this->webroot?>/user/settings<?php echo (isset($_GET['userId'])?'?userId='.$_GET['userId']:'')?>" method="POST" enctype="multipart/form-data">
      <input type="hidden" name="MAX_FILE_SIZE" value="1000000">
      <?php echo $this->t('Choose a picture')?>: <input type="file" name="file" />
      <br/>
      <input type="submit" name='modifyPicture' value="<?php echo $this->t('Modifier Picture')?>">
    </form>
  </div>
	<div id="tabs-password">
    <h3><?php echo $this->t('Modify my password')?>:</h3>
    <form  class="genericForm" id="modifyPassword" method='POST' action='<?php echo $this->webroot?>/user/settings<?php echo (isset($_GET['userId'])?'?userId='.$_GET['userId']:'')?>'>
      <table>
        <?php
        if(!$this->userDao->isAdmin()||$this->user->isAdmin())
          {
          ?>
        <tr>
          <td><?php echo $this->t('My old password');?><input type="password" name="oldPassword"/></td>
        </tr>
        <?php
          }
          ?>
        <tr>
          <td><?php echo $this->t('My new password');?><input type="password" name="newPassword"/></td>
          <td><?php echo $this->t('Confirmation');?><input type="password" name="newPasswordConfirmation"/></td>
        </tr>
        <tr>
          <td><input type='submit' name='modifyPassword' value='<?php echo $this->t('Modify');?>'/></td>
        </tr>
      </table>
    </form>
  </div>
	<div id="tabs-modules">
    Module
  </div>
</div>
<div style="display: none;" class="jsonSettingsContent">
  <?php echo $this->jsonSettings?>
</div>