<?php
/*=========================================================================
MIDAS Server
Copyright (c) Kitware SAS. 20 rue de la Villette. All rights reserved.
69328 Lyon, FRANCE.

See Copyright.txt for details.
This software is distributed WITHOUT ANY WARRANTY; without even
the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE.  See the above copyright notices for more information.
=========================================================================*/

echo '<script type="text/javascript" src="' . $this->coreWebroot . '/public/js/jquery/jquery.form.js"></script>';
echo '<script type="text/javascript" src="' . $this->coreWebroot . '/public/js/user/user.settings.js?'.time().'"></script>';
?>
<link type="text/css" rel="stylesheet" href="<?php echo $this->coreWebroot?>/public/css/user/user.settings.css?<?php echo time(); ?>" />

<div id="tabsSettings">
	<ul>
		<li><a href="#tabs-account"><?php echo $this->t('My Account') ?></a></li>
		<li><a href="#tabs-image"><?php echo $this->t('My Avatar') ?></a></li>
		<li><a href="#tabs-password"><?php echo $this->t('My Password') ?></a></li>
		<li><a href="#tabs-communities"><?php echo $this->t('My Communities') ?></a></li>
    <?php
    foreach($this->customTabs as $modules)
      {
      foreach($modules as $name => $url)
        {
        echo "<li><a href='{$url}'>{$name}</a></li>";
        }
      }
      ?>
	</ul>
	<div id="tabs-account">
    <h3><?php echo $this->t('My information')?>:</h3>
    <form  class="genericForm" id="modifyAccount" method="<?php echo $this->accountForm['method']?>"  action="<?php echo $this->accountForm['action']?><?php echo (isset($_GET['userId'])?'?userId='.$_GET['userId']:'')?>">
      <table>
        <tr>
          <td><span><?php echo $this->t('Firstname');?>:</span><?php echo $this->accountForm['firstname']?></td>
          <td><span><?php echo $this->t('Lastname');?>:</span><?php echo $this->accountForm['lastname']?></td>
        </tr>
        <tr>
          <td><span><?php echo $this->t('Website');?>:</span><?php echo $this->accountForm['website']?></td>
          <td><span><?php echo $this->t('Company');?>:</span><?php echo $this->accountForm['company']?></td>
        </tr>
        <tr>
          <td><span><?php echo $this->t('City');?>:</span><?php echo $this->accountForm['city']?></td>
          <td><span><?php echo $this->t('Country');?>:</span><?php echo $this->accountForm['country']?></td>
        </tr>
        <tr>
          <td colspan="2"><span><?php echo $this->t('Biography');?>:</span><?php echo $this->accountForm['biography']?>
          </td>
        </tr>
        <tr>
          <td colspan=2><?php echo $this->t('Privacy');?>:
          <div id='accountPrivacy'><?php echo $this->accountForm['privacy']?>
          </div>
          </td>
        </tr>
        <?php
          if($this->currentUser->isAdmin())
            { ?>
            <tr>
              <td colspan="2">
                <?php echo $this->t('Administrator');?>:
                <input type="checkbox" name="adminStatus" id="adminStatusCheckbox"
                <?php
                if($this->user->isAdmin())
                  {
                  echo ' checked="checked" ';
                  }
                if($this->user->getKey() == $this->currentUser->getKey())
                  {
                  echo ' disabled="disabled" ';
                  } ?>
                  />
             </td>
           </tr>
        <?php
            } ?>
        <tr>
          <td><?php echo $this->accountForm['modifyAccount']?></td>
        </tr>
      </table>
    </form>

  </div>

  <div id="tabs-image">

    <div id="imageActual">
    <h4><?php echo $this->t('Current Avatar')?>:</h4>
      <?php
      echo $this->userthumbnail($this->thumbnail,'userTopThumbnail');
      ?>
    </div>
    <h3><?php echo $this->t('My Avatar')?>:</h3>
    <form class="genericForm" id="modifyPicture" action="<?php echo $this->webroot?>/user/settings<?php echo (isset($_GET['userId'])?'?userId='.$_GET['userId']:'')?>" method="POST" enctype="multipart/form-data">

      <?php echo $this->t('Please select an image file on your computer (2 MB maximum)')?>
      <input type="file" name="file" />
      <br/>
      <br/>
      <input type="submit" name='modifyPicture' value="<?php echo $this->t('Upload new avatar')?>">
      <br/>
      <?php
      echo "<br/>";
      if(strpos($this->thumbnail, 'http://') === false && $this->isGravatar)
        {
        echo ' <input type="submit" name="modifyPictureGravatar" value="'.$this->t('Use gravatar').'">';
        }
      ?>
      <br/>
    </form>
  </div>

	<div id="tabs-password">
    <h3><?php echo $this->t('My Password')?>:</h3>
    <form  class="genericForm" id="modifyPassword" method='POST' action='<?php echo $this->webroot?>/user/settings<?php echo (isset($_GET['userId'])?'?userId='.$_GET['userId']:'')?>'>
      <table>
        <?php
        if(!$this->userDao->isAdmin()||$this->user->isAdmin())
          {
          ?>
        <tr>
          <td><?php echo $this->t('My old password');?><input type="password" name="oldPassword"/></td>
        </tr>
        <?php
          }
          ?>
        <tr>
          <td><?php echo $this->t('My new password');?><input type="password" name="newPassword"/></td>
          <td><?php echo $this->t('Retype new password');?><input type="password" name="newPasswordConfirmation"/></td>
        </tr>
        <tr>
          <td><input type='submit' name='modifyPassword' value='<?php echo $this->t('Modify password');?>'/></td>
        </tr>
      </table>
    </form>
  </div>
	<div id="tabs-communities">
    <?php
    if(empty($this->communities))
      {
      echo $this->t('You don\'t belong to any community.');
      }
    else
      {
      echo "<h3>{$this->t('My Communities')}:</h3>";
      echo "<ul>";
      foreach($this->communities as $community)
        {
        echo "<li class='settingsCommunityList'><a style='color:white;' href='{$this->webroot}/community/{$community->getKey()}'>{$community->getName()}</a>";
        echo "<ul>";
        foreach($community->groups as $group)
          {
          $name=$group->getName();
          if($group->getKey()==$community->getAdmingroupId())
            {
            $name=$this->t("Administrator");
            }
          if($group->getKey()==$community->getModeratorgroupId())
            {
            $name=$this->t("Moderator");
            }
          if($group->getKey()==$community->getMembergroupId())
            {
            continue;
            }
          echo "<li>{$name}";
          echo "</li>";
          }
        echo "</ul>";
        echo "</li>";
        }
      echo "</ul>";
      }
     ?>
  </div>
</div>
<div style="display: none;" class="jsonSettingsContent">
  <?php echo $this->jsonSettings?>
</div>