<?php
/*=========================================================================
MIDAS Server
Copyright (c) Kitware SAS. 20 rue de la Villette. All rights reserved.
69328 Lyon, FRANCE.

See Copyright.txt for details.
This software is distributed WITHOUT ANY WARRANTY; without even
the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE.  See the above copyright notices for more information.
=========================================================================*/
?>

<?php
if(file_exists(BASE_PATH.'/core/configs/termsofservice.txt'))
  {
  echo file_get_contents(BASE_PATH.'/core/configs/termsofservice.txt');
  return;
  }
?>

<b>Privacy</b>
<pre>
Your privacy & safety are our top concerns. If you ever feel uncomfortable with a user, please let 
us know.
</pre>
<b>Terms of Service</b>
<pre>
By using this web site you are agreeing to be bound by the following terms and conditions
 ("Terms of Use").
</pre>

<b>Basic Terms</b>
<pre>
You are responsible for any activity that occurs under your account.
You are responsible for keeping your account secure.
You must not abuse, harass, threaten, impersonate or intimidate other Midas users.
You may not use the service provided by this web site for any illegal or unauthorized purpose.
International users agree to comply with all local laws regarding online conduct and acceptable content.
You are solely responsible for your conduct and any data, text, information, screen names, and
links ("Content") that you submit, post, and display on the service.
You must not modify, adapt or hack this website or modify another website.
You must not create or submit unwanted email to any members ("Spam").
You must not transmit any worms or viruses or any code of a destructive nature.
You must not, in the use of this website, violate any laws in your jurisdiction (including
but not limited to copyright laws).
Violation of any of these agreements will result in the termination of your account. While
we prohibits such conduct and content on its site, you understand and agree that Kitware 
cannot be responsible for the Content posted on its web site and you nonetheless may be
 exposed to such materials and that you use the service at your own risk.
</pre>
<b>General Conditions</b>

<pre>
We reserve the right to modify or terminate the service for any reason, without notice at any time.
We reserve the right to alter these Terms of Use at any time. If the alterations constitute a
material change to the Terms of Use, we will notify you via internet mail according to the 
preference expressed on your account. What constitutes a "material change" will be 
determined at our sole discretion, in good faith and using common sense and reasonable judgement.
We reserve the right to refuse service to anyone for any reason at any time.
We may, but have no obligation to, remove Content and accounts containing Content that we 
determine in our sole discretion are unlawful, offensive, threatening, libelous, defamatory, 
obscene or otherwise objectionable or violates any party's intellectual property or these Terms of Use.
The service makes it possible to post images and text hosted on this website to outside 
websites. This use is accepted.
</pre>
<b>Copyright (What's Yours is Yours)</b>

<pre>
We claim no intellectual property rights over the material you provide. Your profile 
and materials uploaded remain yours. You can remove your profile at any time by deleting your account.
We encourage users to contribute their creations to the public domain or consider 
progressive licensing terms.
We undertakes to obey all relevant copyright laws. We will review all claims of copyright 
infringement received and remove content deemed to have been posted or distributed in
 violation of any such laws. To make a claim, please provide us with the following:
A physical or electronic signature of the copyright owner or the person authorized to 
act on its behalf;
A description of the copyrighted work claimed to have been infringed;
A description of the infringing material and information reasonably sufficient to permit 
to locate the material;
Your contact information, including your address, telephone number, and email;
A statement by you that you have a good faith belief that use of the material in 
the manner complained of is not authorized by the copyright owner, its agent, or the law; and
A statement that the information in the notification is accurate, and, under the 
pains and penalties of perjury, that you are authorized to act on behalf of the copyright owner.
Contact the agent designated to receive and act on copyright violations under the 
Digital Millennium Copyright Act (DMCA).
</pre>