<?php
/*=========================================================================
MIDAS Server
Copyright (c) Kitware SAS. 20 rue de la Villette. All rights reserved.
69328 Lyon, FRANCE.

See Copyright.txt for details.
This software is distributed WITHOUT ANY WARRANTY; without even
the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE.  See the above copyright notices for more information.
=========================================================================*/

$this->headScript()->appendFile($this->coreWebroot . '/public/js/jquery/jquery.form.js');
$this->headScript()->appendFile($this->coreWebroot.'/public/js/jquery/jquery.checkboxrange.js');
$this->headScript()->appendFile($this->coreWebroot . '/public/js/user/user.userpage.js');
$this->headScript()->appendFile($this->coreWebroot.'/public/js/common/common.browser.js');
?>
<link type="text/css" rel="stylesheet" href="<?php echo $this->coreWebroot?>/public/css/user/user.userpage.css" />
<link type="text/css" rel="stylesheet" href="<?php echo $this->coreWebroot?>/public/css/common/common.browser.css" />
<link type="text/css" rel="stylesheet" href="<?php echo $this->coreWebroot?>/public/css/common/common.genericPage.css" />
<div class="viewMain">
  <div class="genericThumbnail">
  <?php
  echo $this->userthumbnail($this->user->getThumbnail());
  ?>
  </div>
  <div class="genericInfo">
    <div class="genericName"><?php echo $this->user->getFullName();?></div>
    <div class="genericSubtitle"><?php echo $this->user->getCompany();?>
        <span id="locationUser">
        <?php
        $city = $this->user->getCity();
        $country = $this->user->getCountry();
        if(!empty($city))
          {
          echo $city;
          if(!empty($country))
            {
            echo ', ';
            }
          }
        if(!empty($country))
          {
          echo $country;
          }
          ?>
        </span>
      </div>
  </div>
  <img class="tabsLoading" alt=""  src="<?php echo $this->coreWebroot?>/public/images/icons/loading.gif" />
  <div class="tabs" id='tabsGeneric'>
  <ul>
    <li><a href="#tabs-3"><?php echo $this->t('Data');?></a></li>
    <li><a href="#tabs-1"><?php echo $this->t("Feed")?></a></li>
    <?php
    if(!empty($this->information))
      {
      ?>
    <li><a href="#tabs-2"><?php echo $this->t('Info');?></a></li>
    <?php
      }
      ?>

    <?php
    if($this->isViewAction)
      {
      ?>
    <li><a href="#tabs-4"><?php echo $this->t('Owned by me');?></a></li>
    <li><a href="#tabs-5"><?php echo $this->t('Shared to me');?></a></li>
    <?php
      }
    foreach($this->moduleTabs as $module)
      {
      foreach($module as $name => $url)
        {
        echo "<li><a href='{$url}'>{$name}</a></li>";
        }
      }
      ?>
  </ul>
  <div id="tabs-1">
     <?
      echo $this->element('feed');
      ?>
  </div>
        <?php
    if(!empty($this->information))
      {
      ?>
    <div id="tabs-2">
      ???
    </div>
    <?php
      }
      ?>
    <div id="tabs-3">
      <img class="tableLoading" alt=""  src="<?php echo $this->coreWebroot?>/public/images/icons/loading.gif" />
      <table id="browseTable" class="midasTree">
        <thead>
              <th class="thData"><?php echo $this->t('Name');?></th>
              <th class="thSize"><?php echo $this->t('Size');?></th>
              <th class="thDate"><?php echo $this->t('Modified');?></th>
              <th class="thCheckbox"><input type="checkbox" id="browseTableHeaderCheckbox" /></th>
        </thead>
        <tbody>
            <?php
            $node=1;
            foreach($this->folders as $folder)
              {
              $folderId = $folder->getFolderId();
              if ($folderId == $this->privateFolderId || $folderId == $this->publicFolderId)
                {
                $deletableStatus = 'false';
                }
              else
                {
                $deletableStatus = 'true';
                }
              echo "<tr id='node--$node' policy='{$folder->policy}' deletable=$deletableStatus class='parent' privacy='{$folder->getPrivacyStatus()}' type='folder' element='$folderId' ajax='$folderId'>";
              echo "  <td class='treeBrowseElement'><span class='folder'>{$folder->getName()}</span></td>";
              echo "  <td><img class='folderLoading'  element='$folderId' alt='' src='{$this->coreWebroot}/public/images/icons/loading.gif'/></td>";
              echo "  <td>{$this->Date->ago($folder->getDateUpdate(),true)}</td>";
              echo "  <td><input type='checkbox' class='treeCheckbox' type='folder' element='$folderId' /></td>";
              echo "</tr>";
              $node++;
              }

            foreach($this->items as $item)
              {
              echo "<tr id='node--$node' policy='{$item->policy}' privacy='{$item->getPrivacyStatus()}' class='' type='item' element='{$item->getItemId()}' >";
              echo "  <td class='treeBrowseElement'><span class='file'>{$this->slicename($item->getName(),40)}</span></td>";
              echo "  <td>{$item->size}</td>";
              echo "  <td>{$this->Date->ago($item->getDateUpdate(),true)}</td>";
              echo "  <td><input type='checkbox' class='treeCheckbox' type='item' element='{$item->getItemId()}' /></td>";
              echo "</tr>";
              $node++;
              }
            ?>

          </tbody>
      </table>
  </div>
        <?php
    if($this->isViewAction)
      {
      ?>
  <div id="tabs-4">
     <?
      $this->listFiles=$this->ownedItems;
      echo $this->element('listfiles');
      ?>
  </div>
  <div id="tabs-5">
     <?
      $this->listFiles=$this->shareItems;
      echo $this->element('listfiles');
      ?>
  </div>
    <?php
      }
      ?>
</div>

</div>
<div class="viewSideBar">
  <?php
  if($this->isViewAction)
    {
    echo '
  <div class="sideElementFirst genericAction">
    <h1>Actions</h1>
    <ul>
      <li class="myAccountLink" userid="'.$this->user->getKey().'"><a><img alt="" src="'.$this->coreWebroot.'/public/images/icons/user.png"/> '.$this->t('Manage Profile').'</a></li>
      <li><a href="'.$this->webroot.'/user/manage/?userId='.$this->user->getKey().'"><img alt="" src="'.$this->coreWebroot.'/public/images/icons/data.png"/> '.$this->t('Manage Files').'</a></li>
      <li><a onclick="createNewFolder('.$this->mainFolder->getKey().');"><img alt="" src="'.$this->coreWebroot.'/public/images/icons/folder_add.png"/> '.$this->t('Create a top level Folder').'</a></li>';
      
    if($this->isAdmin && !$this->user->isAdmin())
      {
      echo '
      <li><a onclick="midas.user.showDeleteDialog('.$this->user->getKey().');"><img alt="" src="'.$this->coreWebroot.'/public/images/icons/close.png"/> '.$this->t('Delete User').'</a></li>';
      }
    else if(!$this->user->isAdmin() && $this->user->getKey() == $this->currentUser->getKey())
      {
      echo '
      <li><a onclick="midas.user.showDeleteDialog('.$this->user->getKey().');"><img alt="" src="'.$this->coreWebroot.'/public/images/icons/close.png"/> '.$this->t('Delete My Account').'</a></li>';
      }
    echo '
    </ul>
  </div>';
    }

  if(!empty($this->userCommunities))
    {
    echo "
    <div class='sideElement".(($this->isViewAction)?'':'First')." genericCommunities'>
    <h1>{$this->t('Communities')}</h1>
    <ul>";

    foreach($this->userCommunities as $community)
      {
      echo "<li><a href='{$this->webroot}/community/{$community->getKey()}'>{$community->getName()}</a></li>";
      }
   echo "
     </ul>
     </div>";
    }

  if(!empty($this->communityInvitations))
    {
    echo "
    <div class='sideElement genericCommunities'>
    <h1>{$this->t('Community Invitations')}</h1>
    <ul>";

    foreach($this->communityInvitations as $community)
      {
      echo "<li><a href='{$this->webroot}/community/{$community->getKey()}'>{$community->getName()}</a></li>";
      }
   echo "
     </ul>
     </div>";
    }

  $website = $this->user->getWebsite();
  if(!empty($website))
    {
    echo "
    <div class='sideElement websiteBlock'>
    <h1>{$this->t('Website')}</h1>
      <ul>
        <li><a target='_blank' href='{$website}'>{$website}</a></li>
      </ul>
     </div>";
    }

  $biography = $this->user->getBiography();
  if(!empty($biography))
    {
    echo "
    <div class='sideElement biographyBlock'>
    <h1>{$this->t('Biography')}</h1>
      ".nl2br($biography)."
     </div>";
    }

    ?>


    <div class="sideElementActions viewAction">
      <ul>
        <li>

        </li>
      </ul>
    </div>
    <div class="sideElement viewSelected" >
      <h1><?php echo $this->t('Selected')?><span></span></h1>
      <span></span>
    </div>
    <div class="sideElementLast viewInfo">
      <h1>Info</h1>
      <img class="infoLoading" style="display:none;" alt="" src="<?php echo $this->coreWebroot?>/public/images/icons/loading.gif"/>
      <div class="ajaxInfoElement">
      </div>
    </div>
</div>
