<?php
$this->headScript()->appendFile($this->coreWebroot . '/public/js/jquery/jquery.form.js');
$this->headScript()->appendFile($this->coreWebroot . '/public/js/user/user.userpage.js');
$this->headScript()->appendFile($this->coreWebroot.'/public/js/common/common.browser.js');
?>
<link type="text/css" rel="stylesheet" href="<?php echo $this->coreWebroot?>/public/css/user/user.userpage.css" />
<link type="text/css" rel="stylesheet" href="<?php echo $this->coreWebroot?>/public/css/common/common.browser.css" />
<link type="text/css" rel="stylesheet" href="<?php echo $this->coreWebroot?>/public/css/common/common.genericPage.css" />
<div class="viewMain">
  <div class="genericThumbnail">
  <?php
  $thumbnail=$this->user->getThumbnail();
  if(!empty($thumbnail))
    {
    echo "<img class='thumbnailSmall' src='{$this->webroot}/{$thumbnail}' alt=''/>";
    }
  else
    {
    echo "<img  class='thumbnailSmall' src='{$this->coreWebroot}/public/images/icons/unknownUser.png' alt=''/>";
    }
  ?>
  </div>
  <div class="genericInfo">
    <div class="genericName"><?php echo $this->user->getFullName();?></div>
    <div class="genericCompany"><?php echo $this->user->getCompany();?></div>
  </div>
  <img class="tabsLoading" alt=""  src="<?php echo $this->coreWebroot?>/public/images/icons/loading.gif" />
  <div class="tabs" id='tabsGeneric'>
  <ul>
    <li><a href="#tabs-1"><?php echo $this->t("Feed")?></a></li>
    <?php
    if(!empty($this->information))
      {
      ?>
    <li><a href="#tabs-2"><?php echo $this->t('Info');?></a></li>
    <?php
      }
      ?>
    <li><a href="#tabs-3"><?php echo $this->t('Data');?></a></li>
  </ul>
  <div id="tabs-1">
     <?
      echo $this->element('feed');
      ?>
  </div>
        <?php
    if(!empty($this->information))
      {
      ?>
    <div id="tabs-2">
      ???
    </div>
    <?php
      }
      ?>
    <div id="tabs-3">
      <img class="tableLoading" alt=""  src="<?php echo $this->coreWebroot?>/public/images/icons/loading.gif" />
      <table id="browseTable" class="midasTree">
        <thead>
              <th class="thData"><?php echo $this->t('Name');?></th>
              <th class="thSize"><?php echo $this->t('Size');?></th>
              <th class="thDate"><?php echo $this->t('Modified');?></th>
              <th class="thCheckbox"></th>
        </thead>
        <tbody>
            <?php
            $node=1;
            foreach($this->folders as $folder)
              {
              echo "<tr id='node--$node' class='parent' type='folder' element='{$folder->getFolderId()}' ajax='{$folder->getFolderId()}'>";
              echo "  <td class='treeBrowseElement'><span class='folder'>{$folder->getName()}</span></td>";
              echo "  <td><img class='folderLoading'  element='{$folder->getFolderId()}' alt='' src='{$this->coreWebroot}/public/images/icons/loading.gif'/></td>";
              echo "  <td>{$this->Date->ago($folder->getDate(),true)}</td>";
              echo "  <td><input type='checkbox' class='treeCheckbox' type='folder' element='{$folder->getFolderId()}' /></td>";
              echo "</tr>";
              $node++;
              } 
            ?>

          </tbody>
      </table>
  </div>
</div>

</div>
<div class="viewSideBar">
  <div class="sideElementFirst genericAction">
    <h1>Actions</h1>

  </div>
   <div class="sideElement genericCommunities">
    <h1>Communities</h1>    
    <ul>
    <?php 
      foreach($this->userCommunities as $community)
        {
        echo "<li><a href='{$this->webroot}/community/{$community->getKey()}'>{$community->getName()}</a></li>";
        }
    ?>
      </ul>
   </div>
   <div class="sideElementLast genericStats">
    <h1>Stats</h1>  
    
   </div>
  
    <div class="sideElementFirst viewAction">
    <h1>Actions</h1>
      <ul>
        <li>

        </li>
      </ul>
    </div>
    <div class="sideElement viewSelected" >
      <h1><?php echo $this->t('Selected')?></h1>
      <span></span>
    </div>
    <div class="sideElementLast viewInfo">
      <h1>Info</h1>    
      <img class="infoLoading" style="display:none;" alt="" src="<?php echo $this->coreWebroot?>/public/images/icons/loading.gif"/>
      <div class="ajaxInfoElement">
      </div>
    </div>
</div>



