<?php
/*=========================================================================
MIDAS Server
Copyright (c) Kitware SAS. 20 rue de la Villette. All rights reserved.
69328 Lyon, FRANCE.

See Copyright.txt for details.
This software is distributed WITHOUT ANY WARRANTY; without even
the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE.  See the above copyright notices for more information.
=========================================================================*/
?>
<link type="text/css" rel="stylesheet" href="<?php echo $this->moduleWebroot?>/public/css/paraview/paraview.common.css" />

<?php
$this->headScript()->appendFile($this->moduleWebroot.'/public/import/ext/js-core/autobahn.min.js');
$this->headScript()->appendFile($this->moduleWebroot.'/public/import/ext/js-core/jquery.hammer.min.js');
$this->headScript()->appendFile($this->moduleWebroot.'/public/import/lib/js/vtkweb-all.min.js');

$this->headScript()->appendFile($this->coreWebroot.'/public/js/layout/midas.progress.js');
$this->headScript()->appendFile($this->moduleWebroot.'/public/js/paraview/paraview.share.js');
$this->headScript()->appendFile($this->webroot.'/modules/api/public/js/common/common.ajaxapi.js');
?>

<div class="viewMain">
  <div class="shareSessionMessage">You are viewing someone else's session. Interaction is disabled.</div>
  <div id='renderercontainer' class="viewport-container">
    <!-- The renderer will be inserted here -->
  </div>
</div>

<div class="viewSideBar">
</div>
