<?php
/*=========================================================================
MIDAS Server
Copyright (c) Kitware SAS. 20 rue de la Villette. All rights reserved.
69328 Lyon, FRANCE.

See Copyright.txt for details.
This software is distributed WITHOUT ANY WARRANTY; without even
the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE.  See the above copyright notices for more information.
=========================================================================*/
?>
<link type="text/css" rel="stylesheet" href="<?php echo $this->moduleWebroot?>/public/css/paraview/paraview.slice.css" />
<link type="text/css" rel="stylesheet" href="<?php echo $this->coreWebroot?>/public/css/layout/jquery-ui.css" />

<?php
$this->headScript()->appendFile($this->moduleWebroot.'/public/import/ext/js-core/autobahn.min.js');
$this->headScript()->appendFile($this->moduleWebroot.'/public/import/lib/js/vtkweb-all.min.js');

$this->headScript()->appendFile($this->moduleWebroot.'/public/js/paraview/paraview.common.js');
$this->headScript()->appendFile($this->moduleWebroot.'/public/js/paraview/paraview.slice.js');
$this->headScript()->appendFile($this->coreWebroot.'/public/js/layout/midas.progress.js');
$this->headScript()->appendFile($this->webroot.'/modules/api/public/js/common/common.ajaxapi.js');

/** Dynamic js library imports for action handlers */
foreach($this->jsImports as $jsImport)
  {
  $this->headScript()->appendFile($jsImport);
  }
?>

<div class="viewMain">
  <div id='renderercontainer' style="">
    <div id='rendererOverlay'></div>
    <div id="sliceControlContainer">
      <div id="sliceSlider"></div>
      <div id="sliceInfo"></div>
    </div>

    <div id="labelmapOpacityControlContainer">
      <div id="labelmapOpacityInfo"></div>
      <div id="labelmapOpacitySlider"></div>
    </div>
    <div id="windowLevelControlContainer">
      <div id="windowLevelInfo"></div>
      <div id="windowLevelSlider"></div>
    </div>
    <!-- The renderer will be inserted here -->
  </div>
</div>

<div class="viewSideBar">
  <div class="sideElementFirst viewAction">
  <h1>Display</h1>
    <ul>
      <li>
        <a onclick="midas.pvw.toggleControlVisibility();">
        <img alt="" src="<?php echo $this->moduleWebroot;?>/public/images/control_equalizer_blue.png"/>
        Toggle Overlay Visibility
        </a>
      </li>
      <li>
        <a onclick="midas.pvw.setSliceMode('XY Plane');">
        <img alt="" src="<?php echo $this->moduleWebroot;?>/public/images/camera_go.png"/>
        XY Plane View
        </a>
      </li>
      <li>
        <a onclick="midas.pvw.setSliceMode('XZ Plane');">
        <img alt="" src="<?php echo $this->moduleWebroot;?>/public/images/camera_go.png"/>
        XZ Plane View
        </a>
      </li>
      <li>
        <a onclick="midas.pvw.setSliceMode('YZ Plane');">
        <img alt="" src="<?php echo $this->moduleWebroot;?>/public/images/camera_go.png"/>
        YZ Plane View
        </a>
      </li>
    </ul>
  </div>
  <div class="sideElementActions viewAction">
    <h1>Other</h1>
    <ul>
      <li>
        <a href="javascript:;" id="shareSessionLink">
        <img alt="" src="<?php echo $this->coreWebroot;?>/public/images/icons/link.png"/>
        Share Session
        </a>
      </li>
      <li>
        <a href="javascript:;" class="switchToVolumeView">
        <img alt="" src="<?php echo $this->moduleWebroot;?>/public/images/volume.png"/>
        Switch to Volume Rendering
        </a>
      </li>
    </ul>
  </div>
  <div class="sideElement">
    <h1>Info</h1>
    Bounds (x): <span id="boundsXInfo" class="infoValue"></span><br/>
    Bounds (y): <span id="boundsYInfo" class="infoValue"></span><br/>
    Bounds (z): <span id="boundsZInfo" class="infoValue"></span><br/>
    Scalar Range: <span id="scalarRangeInfo" class="infoValue"></span><br/>
  </div>
</div>

<!-- UI Action widget templates -->
<button id="actionButtonTemplate" style="display: none;" class="actionButton actionInactive"></button>
