<?php
/*=========================================================================
MIDAS Server
Copyright (c) Kitware SAS. 20 rue de la Villette. All rights reserved.
69328 Lyon, FRANCE.

See Copyright.txt for details.
This software is distributed WITHOUT ANY WARRANTY; without even
the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE.  See the above copyright notices for more information.
=========================================================================*/
?>
<link type="text/css" rel="stylesheet" href="<?php echo $this->moduleWebroot?>/public/css/paraview/paraview.surface.css" />
<link type="text/css" rel="stylesheet" href="<?php echo $this->coreWebroot?>/public/css/layout/jquery-ui.css" />

<?php
$this->headScript()->appendFile($this->moduleWebroot.'/public/js/paraview/get_modules.js');
$this->headScript()->appendFile('/PWService/js/ParaViewWeb.js');
$this->headScript()->appendFile($this->moduleWebroot.'/public/js/paraview/paraview.surface.js');
$this->headScript()->appendFile($this->webroot.'/modules/api/public/js/common/common.ajaxapi.js');

/** Dynamic js library imports for action handlers */
foreach($this->jsImports as $jsImport)
  {
  $this->headScript()->appendFile($jsImport);
  }
?>

<div class="viewMain">
  <img class="visuLoading" alt="" src="<?php echo $this->coreWebroot?>/public/images/icons/loading.gif" />
  <span id="loadingStatus"></span>

  <div id='renderercontainer' style="">
    <div id='rendererOverlay'></div>
    <!-- The renderer will be inserted here -->
  </div>
</div>

<div class="viewSideBar">
  <div class="sideElementFirst viewAction">
  <h1>Display</h1>
    <ul>
      <li>
        <a onclick="midas.visualize.resetCamera();">
        <img alt="" src="<?php echo $this->moduleWebroot;?>/public/images/camera_go.png"/>
        Reset Camera
        </a>
      </li>
      <li>
        <a onclick="midas.visualize.toggleEdges();">
        <img alt="" src="<?php echo $this->moduleWebroot;?>/public/images/pqUnstructuredGrid16.png"/>
        Show Edges
        </a>
      </li>
    </ul>
  </div>
  <div class="sideElement">
    <h1>Renderer</h1>
    <select disabled="disabled" id="rendererSelect">
      <option selected="selected" value="js">Server side</option>
      <option value="webgl">WebGL</option>
    </select>
  </div>
  <div class="sideElement">
    <h1>Info</h1>
    Number of Points: <span id="nbPointsInfo" class="infoValue"></span><br/>
    Number of Cells: <span id="nbCellsInfo" class="infoValue"></span><br/>
    Bounds (x): <span id="boundsXInfo" class="infoValue"></span><br/>
    Bounds (y): <span id="boundsYInfo" class="infoValue"></span><br/>
    Bounds (z): <span id="boundsZInfo" class="infoValue"></span><br/>
  </div>
</div>

<!-- UI Action widget templates -->
<button id="actionButtonTemplate" style="display: none;" class="actionButton actionInactive"></button>

