<?php
/*=========================================================================
 MIDAS Server
 Copyright (c) Kitware SAS. 26 rue Louis Guérin. 69100 Villeurbanne, FRANCE
 All rights reserved.
 More information http://www.kitware.com

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

         http://www.apache.org/licenses/LICENSE-2.0.txt

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
=========================================================================*/

echo $this->doctype().PHP_EOL;
?>
<html lang="<?php echo $this->lang; ?>" xml:lang="<?php echo $this->lang; ?>" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <?php
    $this->headMeta()->appendHttpEquiv('Content-Type', 'text/html; charset=UTF-8');
    $this->headMeta()->appendName('description', htmlspecialchars($this->metaDescription, ENT_QUOTES, 'UTF-8'));
    echo $this->headMeta().PHP_EOL;

    $this->headTitle(htmlspecialchars($this->title, ENT_QUOTES, 'UTF-8'));
    $this->headTitle()->setSeparator(' - ');
    echo $this->headTitle().PHP_EOL;

    $this->headLink()->appendStylesheet($this->baseUrl('core/public/css/layout/midas.empty.css'));
    $this->headLink()->appendStylesheet($this->baseUrl('core/public/css/layout/view.css'));
    $this->headLink()->appendStylesheet($this->baseUrl('core/public/css/layout/jquery-ui.min.css'));
    $this->headLink()->appendStylesheet($this->baseUrl('core/public/css/layout/form.css'));
    $this->headLink()->appendStylesheet($this->baseUrl('core/public/css/layout/loginForm.css'));
    $this->headLink()->appendStylesheet($this->baseUrl('core/public/css/layout/jquery.treeTable.css'));
    $this->headLink()->appendStylesheet($this->baseUrl('core/public/css/layout/jquery.qtip.min.css'));
    $this->headLink()->headLink(array('rel' => 'icon', 'href' => $this->baseUrl('favicon.ico'), 'APPEND'));
    echo $this->headLink().PHP_EOL;

    $this->headScript()->prependFile($this->baseUrl('core/public/js/layout/jquery.qtip.min.js'));
    $this->headScript()->prependFile($this->baseUrl('core/public/js/layout/jquery.treeTable.js'));
    $this->headScript()->prependFile($this->baseUrl('core/public/js/layout/midas.progress.js'));
    $this->headScript()->prependFile($this->baseUrl('core/public/js/layout/midas.dialog.js'));
    $this->headScript()->prependFile($this->baseUrl('core/public/js/layout/midas.callback.js'));
    $this->headScript()->prependFile($this->baseUrl('core/public/js/layout/midas.notice.js'));
    $this->headScript()->prependFile($this->baseUrl('core/public/js/layout/midas.empty.js'));
    $this->headScript()->prependFile($this->baseUrl('core/public/js/layout/midas.common.js'));
    $this->headScript()->prependFile($this->baseUrl('core/public/js/layout/jquery-ui.js'));
    $this->headScript()->prependFile($this->baseUrl('core/public/js/layout/jquery.js'));

    echo $this->headStyle().PHP_EOL;
    ?>
</head>
<body>
<div class="MainDialog" style="display:none;">
    <div class="MainDialogContent"></div>
    <div class="MainDialogLoading">
        <img alt="" src="<?php echo $this->baseUrl('core/public/images/icons/loading.gif'); ?>"/>
    </div>
    <input type="hidden" class="DialogContentPage"/>
</div>
<div class="viewNoticeWrapper">
    <div class="viewNotice"></div>
</div>
<div class="Wrapper">
    <div class="viewWrapper">
        <!-- Content -->
        <?php echo $this->layout()->content.PHP_EOL; ?>
        <!-- End Content -->
    </div>
</div>
<?php echo $this->headScript().PHP_EOL; ?>
<input type="hidden" class="webroot" value="<?php $this->baseUrl(); ?>"/>

<div style="display: none;" class="jsonContent">
    <?php echo $this->json.PHP_EOL; ?>
</div>
</body>
<?php
$footers = Zend_Registry::get('notifier')->callback('CALLBACK_CORE_GET_FOOTER_LAYOUT', array());
if (!empty($footers)) {
    foreach ($footers as $footer) {
        echo $footer;
    }
}
?>
</html>
