<?php
/*=========================================================================
 MIDAS Server
 Copyright (c) Kitware SAS. 26 rue Louis Guérin. 69100 Villeurbanne, FRANCE
 All rights reserved.
 More information http://www.kitware.com

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

         http://www.apache.org/licenses/LICENSE-2.0.txt

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
=========================================================================*/
echo $this->doctype()
?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
  <title><?php echo $this->title ?></title>

  <meta name="description" content="<?php echo htmlentities($this->metaDescription)?>" />
  <meta name="keywords" content="<?php echo htmlentities($this->metaKeywords)?>" />
  <meta name="robots" content="index, follow, all" />
  <noscript>
  <meta http-equiv="refresh" content="1; URL=<?php echo $this->webroot?>/index/nojs">
  </noscript>

  <!--[if lte IE 6]>
    <meta http-equiv="refresh" content="1; URL=<?php echo $this->webroot?>/index/nobrowser">
  <![endif]-->

  <!-- Import CSS -->
  <link rel="shortcut icon" href="<?php echo $this->coreWebroot ?>/public/images/icons/favicon.ico" />
  <?php
  if(Zend_Registry::get("configGlobal")->smartoptimizer == 1)
    {
    echo '<link type="text/css" rel="stylesheet" href="'.$this->coreWebroot.'/public/css/layout/view.css,'.
         'midas.empty.css,'.
         'jquery-ui.css,'.
         'form.css,'.
         'loginForm.css,'.
         'jquery.treeTable.css,'.
         'jquery.qtip.min.css" />';
    }
  else
    {
    echo '<link type="text/css" rel="stylesheet" href="'.$this->coreWebroot.'/public/css/layout/midas.empty.css" />';
    echo '<link type="text/css" rel="stylesheet" href="'.$this->coreWebroot.'/public/css/layout/view.css" />';
    echo '<link type="text/css" rel="stylesheet" href="'.$this->coreWebroot.'/public/css/layout/jquery-ui.css" />';
    echo '<link type="text/css" rel="stylesheet" href="'.$this->coreWebroot.'/public/css/layout/form.css" />';
    echo '<link type="text/css" rel="stylesheet" href="'.$this->coreWebroot.'/public/css/layout/loginForm.css" />';
    echo '<link type="text/css" rel="stylesheet" href="'.$this->coreWebroot.'/public/css/layout/jquery.treeTable.css" />';
    echo '<link type="text/css" rel="stylesheet" href="'.$this->coreWebroot.'/public/css/layout/jquery.qtip.min.css" />';
    }
  ?>

  <?php echo $this->headLink();  // import the css ?>
  <?php echo $this->headStyle(); // import the css ?>

</head>
<body>
  <div class="MainDialog" style="display:none;">
    <div class="MainDialogContent"></div>
    <div class="MainDialogLoading">
      <img alt="" src="<?php echo  $this->coreWebroot?>/public/images/icons/loading.gif" />
    </div>
    <input type="hidden" class="DialogContentPage"/>
  </div>

  <div class="viewNoticeWrapper">
    <div class="viewNotice"></div>
  </div>

  <div class="Wrapper">
    <div class="viewWrapper">
      <!-- Content -->
      <?php echo $this->layout()->content ?>
      <!-- End Content -->
    </div>
  </div>

  <?php
  if(Zend_Registry::get('configGlobal')->smartoptimizer == 1)
    {
    echo '<script type="text/javascript" src="'.$this->coreWebroot.'/public/js/layout/jquery.js,'.
         'jquery-ui.js,'.
         'midas.common.js,'.
         'midas.empty.js,'.
         'midas.callback.js,'.
         'midas.dialog.js,'.
         'midas.progress.js,'.
         'midas.notice.js,'.
         'jquery.treeTable.js,'.
         'jquery.qtip.min.js"></script>';
    }
  else
    {
    echo '<script type="text/javascript" src="'.$this->coreWebroot.'/public/js/layout/jquery.js"></script>';
    echo '<script type="text/javascript" src="'.$this->coreWebroot.'/public/js/layout/jquery-ui.js"></script>';
    echo '<script type="text/javascript" src="'.$this->coreWebroot.'/public/js/layout/midas.common.js"></script>';
    echo '<script type="text/javascript" src="'.$this->coreWebroot.'/public/js/layout/midas.empty.js"></script>';
    echo '<script type="text/javascript" src="'.$this->coreWebroot.'/public/js/layout/midas.notice.js"></script>';
    echo '<script type="text/javascript" src="'.$this->coreWebroot.'/public/js/layout/midas.callback.js"></script>';
    echo '<script type="text/javascript" src="'.$this->coreWebroot.'/public/js/layout/midas.dialog.js"></script>';
    echo '<script type="text/javascript" src="'.$this->coreWebroot.'/public/js/layout/midas.progress.js"></script>';
    echo '<script type="text/javascript" src="'.$this->coreWebroot.'/public/js/layout/jquery.treeTable.js"></script>';
    echo '<script type="text/javascript" src="'.$this->coreWebroot.'/public/js/layout/jquery.qtip.min.js"></script>';
    }
  ?>
  <?php echo $this->headScript() ?>
  <input type="hidden" class="webroot" value="<?php echo $this->webroot ?>" />
  <div style="display: none;" class="jsonContent">
    <?php echo $this->json ?>
  </div>
</body>

<?php
$footers = Zend_Registry::get('notifier')->callback('CALLBACK_CORE_GET_FOOTER_LAYOUT', array());
if(!empty($footers))
  {
  foreach($footers as $footer)
    {
    echo $footer;
    }
  }
?>
</html>
