<?php
/*=========================================================================
MIDAS Server
Copyright (c) Kitware SAS. 20 rue de la Villette. All rights reserved.
69328 Lyon, FRANCE.

See Copyright.txt for details.
This software is distributed WITHOUT ANY WARRANTY; without even
the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE.  See the above copyright notices for more information.
=========================================================================*/
echo $this->doctype()
?>
<html xmlns="http://www.w3.org/1999/xhtml">
  <head>

    <!-- Meta -->
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <title><?php echo $this->title ?></title>

    <meta name="description" content="<?php echo htmlentities($this->metaDescription)?>" />
    <meta name="keywords" content="<?php echo htmlentities($this->metaKeywords)?>" />
    <meta name="robots" content="index, follow, all" />
    <noscript>
    <meta http-equiv="refresh" content="1; URL=<?php echo $this->webroot?>/index/nojs">
    </noscript>

    <!--[if lte IE 6]>
      <meta http-equiv="refresh" content="1; URL=<?php echo $this->webroot?>/index/nobrowser">
    <![endif]-->

    <!-- Import CSS -->
    <link rel="shortcut icon" href="<?php echo $this->coreWebroot ?>/public/images/icons/favicon.ico" />
    <?php
    if (Zend_Registry::get("configGlobal")->smartoptimizer == 1)
      {
      echo '<link type="text/css" rel="stylesheet" href="' . $this->coreWebroot . '/public/css/layout/main.css,view.css,jquery-ui.css,form.css,loginForm.css,jquery.treeTable.css,jquery.qtip.min.css" />';
      }
    else
      {
      echo '<link type="text/css" rel="stylesheet" href="' . $this->coreWebroot . '/public/css/layout/main.css" />';
      echo '<link type="text/css" rel="stylesheet" href="' . $this->coreWebroot . '/public/css/layout/view.css" />';
      echo '<link type="text/css" rel="stylesheet" href="' . $this->coreWebroot . '/public/css/layout/jquery-ui.css" />';
      echo '<link type="text/css" rel="stylesheet" href="' . $this->coreWebroot . '/public/css/layout/form.css" />';
      echo '<link type="text/css" rel="stylesheet" href="' . $this->coreWebroot . '/public/css/layout/loginForm.css" />';
      echo '<link type="text/css" rel="stylesheet" href="' . $this->coreWebroot . '/public/css/layout/jquery.treeTable.css" />';
      echo '<link type="text/css" rel="stylesheet" href="' . $this->coreWebroot . '/public/css/layout/jquery.qtip.min.css" />';
      }
    ?>
    <?php
    $headers = Zend_Registry::get('notifier')->callback("CALLBACK_CORE_GET_FOOTER_HEADER", array());
    if(!empty($headers))
      {
      foreach($headers as $header)
        {
        echo $header;
        }
      }
    ?>

    <!--[if IE]>
      <?php echo  '<link type="text/css" rel="stylesheet" href="' . $this->coreWebroot . '/public/css/layout/mainIE.css" />';?>
      <?php echo '<script type="text/javascript" src="' . $this->coreWebroot . '/public/js/layout/roundCornerIE.js"></script>';?>
    <![endif]-->
    <?php echo $this->headLink();  // import the css ?>
    <?php echo $this->headStyle(); // import the css ?>

  </head>
  <body>
    <div class="MainDialog" style="display:none;">
      <div class="MainDialogContent">
      </div>
      <div class="MainDialogLoading">
        <img alt="" src="<?php echo  $this->coreWebroot?>/public/images/icons/loading.gif" />
      </div>
      <input type="hidden" class="DialogContentPage"/>
    </div>
    <div class="TopDynamicBar">
      <div class="TopDynamicClose">
        <a class="closeButton" href="#" ><span><?php echo $this->t('Close');?></span><img alt="" src="<?php echo $this->coreWebroot?>/public/images/icons/close.png"/> </a>
      </div>
      <div class="TopDynamicContent">
      </div>
      <div class="TopDynamicLoading">
        <img alt="" src="<?php echo  $this->coreWebroot?>/public/images/icons/loading.gif" />
      </div>
      <input type="hidden" class="DynamicContentPage"/>
    </div>
    <div class="Topbar">
      <div class="TopbarContent">
        <div class="TopbarLeft">
          <ul>
            <li class="first">
              <a target="_blank" href="http://midasplatform.org" >MIDAS</a>
            </li>
            <li>
              <a target="_blank" href="http://www.kitware.com" >Kitware</a>
            </li>
            <?php
            if($this->logged)
              {
              ?>
              <li>
                <a href="#" id="startingGuideLink" ><?php echo $this->t('Starting Guide')?></a>
              </li>
            <?php
              }?>
          </ul>
        </div>
        <div class="TopbarRight">
          <ul>
            <li class="first">
              <?php
              if($this->logged&&isset($this->userDao))
                {
                echo '
                   <b><a id="topUserName" href="'.$this->webroot.'/user/'.$this->userDao->getUserId().'" >'.$this->userDao->getFullName().' <img class="arrowUser" src="'.$this->coreWebroot.'/public/images/icons/arrow-user.gif" alt ="" /> </a> </b>
                    <ul>
                      <li onclick="location.replace(\''.$this->webroot.'/user/userpage\');"><a>'.$this->t('My Page').'</a></li>
                      <li class="myAccountLink"><a>'.$this->t('My Account').'</a></li>
                      ';
                if($this->userDao->isAdmin())
                  {
                  echo '
                      <li onclick="location.replace(\''.$this->webroot.'/admin\');"><a>'.$this->t('Administration').'</a></li>';
                  }


              $linksModules = Zend_Registry::get('notifier')->callback("CALLBACK_CORE_GET_USER_MENU", array());
              if(!empty($linksModules))
                {
                foreach($linksModules as $links)
                  {
                  foreach($links as $name => $link)
                    {
                    echo '
                        <li onclick="location.replace(\''.$link.'\');"><a>'.$name.'</a></li>';
                    }
                  }
                }
                echo '
                    </ul>
                   ';
                }
              else
                {
                echo '<b><a class="loginLink" href="#" >'.$this->t('Login').'</a></b>';
                }
                ?>
            </li>
            <li>
              <?php
              if($this->logged)
                {
                echo '<a  href="'.$this->webroot.'/user/logout" > '.$this->t('Logout').'</a>';
                }
              else
                {
                echo '<a class="registerLink" href="#" > '.$this->t('Register').'</a>';
                }
                ?>
            </li>
            <li>
              <a href="#" > <?= $this->t('Help') ?></a>
            </li>

            <?php
            if(!isset(Zend_Registry::get('configCore')->internationalization) || Zend_Registry::get('configCore')->internationalization == "1")
              {
              ?>
            <li>
                <a href="#" style="margin-right: 20px">
               <?php
               echo $this->t('My Language');
                ?>
              <img class="languageIcon" src="<?php echo $this->coreWebroot?>/public/images/icons/language.png" alt ="" />
                </a>
                <ul>
                  <li>
                  <?php
                  if($this->lang=='en')
                    {
                    echo '<a href="#"><b>English</b></a>';
                    }
                  else
                    {
                    echo '<a href="'.$this->webroot.'?lang=en">English</a>';
                    }
                    ?>
                  </li>
                  <li>
                  <?php
                  if($this->lang=='fr')
                    {
                    echo '<a href="#"><b>Francais</b></a>';
                    }
                  else
                    {
                    echo '<a href="'.$this->webroot.'?lang=fr">Francais</a>';
                    }
                    ?>
                  </li>
                </ul>
            </li>
            <?php
              }
              ?>
          </ul>
        </div>
      </div>
    </div>
    <div class="Header">
      <div class="HeaderContent">

        <div class="HeaderLogo" onclick="window.location='<?php echo $this->webroot?>';">
          <?php
          if($this->demoMode)
          echo 'Demo'
          ?>
        </div>
        <div class="HeaderSearch">
          <input type="text" id="live_search" value="<?= $this->t('Jump to a data, folder...') ?>" autocomplete="off" autocorrect="off" autocapitalize="off" />
          <input type="hidden" id="live_search_value" value="init"  />
          <div id="searchloading" style="display:none"></div>
       </div>
        <div class="HeaderAction">
          <ul>
            <li class="uploadFile" title="Upload" rel="<?php echo $this->webroot?>/upload/simpleupload">
              <a href="#"><img id="uploadAFile" src="<?= $this->coreWebroot ?>/public/images/icons/addfile.png" alt="Upload a file"/>
              <img id="uploadAFileLoadiing" style="margin-top:5px;display:none;" src="<?= $this->coreWebroot ?>/public/images/icons/loading.gif" alt="Upload a file"/>
                Upload
              </a>
            </li>
            <?php
            $htmltArray = Zend_Registry::get('notifier')->callback("CALLBACK_CORE_LAYOUT_TOPBUTTONS", array());
            foreach($htmltArray as $html)
              {
              if(!empty($html))
                {
                echo $html;
                }
              }
            ?>
          </ul>
          <div class="viewNoticeWrapper">
            <div class="viewNotice"></div>
          </div>
        </div>
      </div>
    </div>

    <div class="Wrapper">
      <?php
      if($this->needUpgrade)
        {
        echo '<span style="color:red;">MIDAS need to be upgraded. <a href="'.$this->webroot.'/admin/#ui-tabs-1">Upgrade</a></span><br/><br/>';
        }
      if($this->highNumberError)
        {
        echo '<span style="color:red;">More than 5 errors occured in the last 24 hours. <a href="'.$this->webroot.'/admin/#ui-tabs-3">Check the logs</a></span><br/><br/>';
        }
      ?>
      <div class="SubWrapper">

        <div class="MainContent">
          <div class="SideBar">
            <ul>
              <li <?php if($this->activemenu=='feed') {echo 'class="active"';} ?> onclick="location.replace('<?php echo $this->webroot?>/feed');" ><a href="<?php echo $this->webroot?>/feed"><img alt="" src="<?php echo $this->coreWebroot?>/public/images/icons/feed.png" /><span> <?php echo $this->t('Feed');?></span></a></li>
              <li <?php if($this->activemenu=='browse') {echo 'class="active"';} ?> onclick="location.replace('<?php echo $this->webroot?>/browse');" ><a href="<?php echo $this->webroot?>/browse"><img alt="" src="<?php echo $this->coreWebroot?>/public/images/icons/explore.png" /><span> <?php echo $this->t('Explore');?></span></a></li>
              <li <?php if($this->activemenu=='community') {echo 'class="active"';} ?> onclick="location.replace('<?php echo $this->webroot?>/community');" ><a href="<?php echo $this->webroot?>/community"><img alt="" src="<?php echo $this->coreWebroot?>/public/images/icons/community2.png" /><span> <?php echo $this->t('Communities');?></span></a></li>
              <li <?php if($this->activemenu=='user') {echo 'class="active"';} ?> onclick="location.replace('<?php echo $this->webroot?>/user');" ><a href="<?php echo $this->webroot?>/user"><img alt="" src="<?php echo $this->coreWebroot?>/public/images/icons/users.png" /><span> <?php echo $this->t('Users');?></span></a></li>
              <li id="menuUserInfo" <?php if($this->activemenu=='myprofile') {echo 'class="active"';} ?>  ><a href="javascript:;"><img alt="" src="<?php echo $this->coreWebroot?>/public/images/icons/user.png" /><span> <?php echo $this->t('My profile');?></span></a></li>

               <?php
              if($this->showUploadedLink)
                {
                ?>
               <li <?php if($this->activemenu=='uploaded') {echo 'class="active"';} ?> onclick="location.replace('<?php echo $this->webroot?>/browse/uploaded');" ><a href="<?php echo $this->webroot?>/browse/uploaded"><img alt="" src="<?php echo $this->coreWebroot?>/public/images/icons/addfile.png" /><span> <?php echo $this->t('My uploads');?></span></a></li>
              <?php
                }

              $linksModules = Zend_Registry::get('notifier')->callback("CALLBACK_CORE_GET_LEFT_LINKS", array());
              if(!empty($linksModules))
                {
                foreach($linksModules as $links)
                  {
                  foreach($links as $name => $array)
                    {
                    if(count($array) != 2)
                      {
                      throw new Zend_Exception('Key = 0 should be the link, Key = 1 should be the image');
                      }
                    $link = $array[0];
                    $image = $array[1];
                    ?>
                    <li  onclick="location.replace('<?php echo $link?>');" ><a href="<?php echo $link?>"><img alt="" src="<?php echo $image?>" /><span> <?php echo $name;?></span></a></li>
                    <?php
                    }
                  }
                }
              ?>
             </ul>
            <hr/>
            <?php
            if(isset($this->recentItems)&&!empty($this->recentItems))
              {
              echo "<h1>{$this->t('Recently Viewed')}</h1>";
              $recentReverse=array_reverse($this->recentItems);
              echo '<ul>';
              foreach ($recentReverse as $item)
                {
                if(is_array($item))
                  {
                  echo "<li onclick=\"location.replace('{$this->webroot}/item/{$item['item_id']}');\" class='recentItem' qtip='".  str_replace("'", '"', $item['name'])."'><a  href='{$this->webroot}/item/{$item['item_id']}'>".$this->slicename($item['name'],20)."</a></li>";
                  }
                }
              echo '</ul>';
              }
            ?>
          </div>
          <div class="SubMainContent">
            <?php
            if (isset($this->header))
              {
              echo "<div class='viewHeader'>{$this->header} </div>";
              }
            ?>

            <div class="viewWrapper">
              <!-- Content -->
              <?php echo $this->layout()->content ?>
              <!-- End Content -->

            </div>
            <div class="clear"/>
          </div>
        </div>
        <div class="SupraFooter">
          <?php
            $contentFooters = Zend_Registry::get('notifier')->callback("CALLBACK_CORE_GET_SUPRA_FOOTER", array());
            if(!empty($contentFooters))
              {
              foreach($contentFooters as $contentFooter)
                {
                echo $contentFooter;
                }
              }
          ?>
        </div>
        <div class="Footer"><a href="http://www.kitware.com/products/midas.html">MIDAS</a> <?php echo $this->version ?> by <a href="http://www.kitware.com">Kitware</a> © <?php echo date("Y") ?> -
         <?php
         echo $this->t('Generated in').' '.$this->generatedTimer." s";
         ?>
        - <a href="http://public.kitware.com/MidasBT/my_view_page.php"><?php echo $this->t('Report bug');?></a>
        </div>
      </div>
      <hr style="display: none;"/>
    </div>
    <?php
      if (Zend_Registry::get("configGlobal")->smartoptimizer == 1)
        {
        echo '<script type="text/javascript" src="' . $this->coreWebroot . '/public/js/layout/jquery.js,jquery-ui.js,main.js,jquery.treeTable.js,jquery.qtip.min.js"></script>';
        }
      else
        {
        echo '<script type="text/javascript" src="' . $this->coreWebroot . '/public/js/layout/jquery.js"></script>';
        echo '<script type="text/javascript" src="' . $this->coreWebroot . '/public/js/layout/jquery-ui.js"></script>';
        echo '<script type="text/javascript" src="' . $this->coreWebroot . '/public/js/layout/main.js"></script>';
        echo '<script type="text/javascript" src="' . $this->coreWebroot . '/public/js/layout/jquery.treeTable.js"></script>';
        echo '<script type="text/javascript" src="' . $this->coreWebroot . '/public/js/layout/jquery.qtip.min.js"></script>';
        }
    ?>
    <?php echo $this->headScript() ?>
    <input type="hidden" class="webroot" value="<?php echo $this->webroot?>" />
    <div style="display: none;" class="jsonContent">
      <?php echo $this->json?>
    </div>

    <div id="dialogStartingGuide" style="display:none;" title="<?php echo $this->t('Starting Guide')?>">
      <br/>
     Click on the action of you choice to start using the MIDAS Platform.

     <br/><br/>
     <div id="seperatorStartingGuide">

     </div>
     <br/>
       <div class="blockSet" id="blockPersoLink">
        <table>
          <tbody><tr>
            <td class="logo">
              <img alt="" src="<?php echo  $this->coreWebroot?>/public/images/bigicons/folder-lock.png" />
            </td>
            <td>
              <h4  >Access your personal folder</h4>
              <span style="color:grey;">Store data in a secured location.</span>
            </td>
          </tr>
        </tbody>
        </table>
      </div>
      <div class="blockSet" id="blockSettingsLink">
        <table>
          <tbody><tr>
            <td class="logo">
              <img alt="" src="<?php echo  $this->coreWebroot?>/public/images/bigicons/explore.png" />
            </td>
            <td>
              <h4>Manage your profile</h4>
              <span style="color:grey;">Manage your information and your privacy.</span>
            </td>
          </tr>
        </tbody>
        </table>
      </div>
     <br/>
      <div class="blockSet" id="blockExploreLink">
        <table>
          <tbody><tr>
            <td class="logo">
              <img alt="" src="<?php echo  $this->coreWebroot?>/public/images/bigicons/profile.png" />
            </td>
            <td>
              <h4>Explore the data</h4>
              <span style="color:grey;">Browse the data hosted on the MIDAS Platform.</span>
            </td>
          </tr>
        </tbody>
        </table>
      </div>
      <div class="blockSet" id="blockCommunityLink" >
        <table>
          <tbody><tr>
            <td class="logo">
              <img alt="" src="<?php echo  $this->coreWebroot?>/public/images/bigicons/community.png" />
            </td>
            <td>
              <h4>Join a community</h4>
              <span style="color:grey;">Be part of a project!</span>
            </td>
          </tr>
        </tbody>
        </table>
      </div>
     <br/>
     <div style="float:left;">
       <input type="checkbox" name="disableStartingGuide" id="disableStartingGuide" <?php if(isset($this->userDao) && $this->userDao->getDynamichelp() == 0) echo 'checked'?> />
       <label style="color:grey;font-size: 11px;" for="disableStartingGuide">Always hide the help animation and this window.</label>
     </div>
    </div>
  </body>

  <?php
  $footers = Zend_Registry::get('notifier')->callback("CALLBACK_CORE_GET_FOOTER_LAYOUT", array());
  if(!empty($footers))
    {
    foreach($footers as $footer)
      {
      echo $footer;
      }
    }
  ?>
</html>
