<?php 
/*=========================================================================
MIDAS Server
Copyright (c) Kitware SAS. 20 rue de la Villette. All rights reserved.
69328 Lyon, FRANCE.

See Copyright.txt for details.
This software is distributed WITHOUT ANY WARRANTY; without even
the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE.  See the above copyright notices for more information.
=========================================================================*/

echo '<script type="text/javascript" src="' . $this->moduleWebroot . '/public/js/config/config.usertab.js"></script>';
?>
<link type="text/css" rel="stylesheet" href="<?php echo $this->moduleWebroot?>/public/css/config/config.usertab.css" />

<h3><?php echo $this->t('Generated API keys')?></h3>
<?php if(count($this->userapiDaos)==0)
{
 echo "You don't have any API keys.<br/>";
}
else
{
?>
<table width="100%"  border="0">
 <tr bgcolor="#999999">
   <td><center><b><?php echo $this->t('Application Name')?></b></center></td>
   <td><center><b>API Key</b></center></td>
   <td><center><b><?php echo $this->t('Default expiration')?></b></center></td>
   <td><center><b>Creation</b></center></td>
   <td><center><b>Action</b></center></td>
 </tr>
<?php foreach($this->userapiDaos as $userapiDao)
 {
 ?>
 <tr>
   <td><?php echo $userapiDao->getApplicationName(); ?></td>
   <td><?php echo $userapiDao->getApikey(); ?></td>
   <td><?php echo $userapiDao->getTokenExpirationTime(); ?> minutes</td>
   <td><?php echo $this->Date->ago($userapiDao->getCreationDate()); ?></td>
   <td><a style='text-decoration: underline;' class='deleteApiKeyLink' element='<?php echo $userapiDao->getKey()?>'><?php echo $this->t('delete')?></a></td>
 </tr>
<?php } // end foreach keys ?>
</table>
<?php } // end count ?>

<a href="<?php echo $this->webroot?>/api">Web API Information</a>

<div class="separator"></div>
<h3><?php echo $this->t('Generate new API key')?></h3>

<form class="genericForm" id="generateKeyForm" method="<?php echo $this->form['method']?>"  action="<?php echo $this->form['action']?>">
  <input type="hidden" id="apiUserId" name="userId" value="<?php echo $this->user->getKey(); ?>" />
  <div >
    <label for="appplication_name"><?php echo $this->t('Application Name')?>:</label>
    <?php echo $this->form['appplication_name']?>
  </div>
  <div >
    <label for="expiration"><?php echo $this->t('Default expiration')?> (min):</label>
    <?php echo $this->form['expiration']?>
  </div>
  <div>
     <?php echo $this->form['createAPIKey']?>
  </div>
</form>
