<?php
/*=========================================================================
 MIDAS Server
 Copyright (c) Kitware SAS. 26 rue Louis Guérin. 69100 Villeurbanne, FRANCE
 All rights reserved.
 More information http://www.kitware.com

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

         http://www.apache.org/licenses/LICENSE-2.0.txt

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
=========================================================================*/

$this->headScript()->appendFile($this->coreWebroot.'/public/js/jquery/jquery.form.js');
$this->headScript()->appendFile($this->moduleWebroot.'/public/js/config/config.index.js');
?>

<div class="viewMain">
    <form id="configForm" class="genericForm" method="POST"
          action="<?php echo $this->webroot; ?>/tracker/config/submit">
        <div class="explanation">
            <p>Set this field to the number of hours that unofficial submissions should be kept before being deleted
                automatically
                by the scheduler. The default value is 24 hours.</p>
        </div>
        <div>
            <label for="tempScalarTtl">Unofficial Scalar TTL</label>
            <input type="text" name="tempScalarTtl" value="<?php echo $this->tempScalarTtl; ?>"/>
        </div>
        <div>
            <input type="submit" value="Save"/>
        </div>
    </form>
</div>
