<?php
/*=========================================================================
MIDAS Server
Copyright (c) Kitware SAS. 20 rue de la Villette. All rights reserved.
69328 Lyon, FRANCE.

See Copyright.txt for details.
This software is distributed WITHOUT ANY WARRANTY; without even
the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE.  See the above copyright notices for more information.
=========================================================================*/
$this->headScript()->appendFile($this->coreWebroot.'/public/js/jquery/jquery.form.js');
$this->headScript()->appendFile($this->moduleWebroot.'/public/js/config/config.index.js');
?>

<div class="viewMain">
  <form id="configForm" class="genericForm" method="POST" action="<?php echo $this->webroot;?>/tracker/config/submit">
    <div class="explanation">
      <p>Set this field to the number of hours that unofficial submissions should be kept before being deleted automatically
         by the scheduler.  The default value is 24 hours.</p>
    </div>
    <div>
      <label for="tempScalarTtl">Unofficial Scalar TTL</label>
      <input type="text" name="tempScalarTtl" value="<?php echo $this->tempScalarTtl;?>" />
    </div>
    <div>
      <input type="submit" value="Save" />
    </div>
  </form>
</div>
