<?php
/*=========================================================================
MIDAS Server
Copyright (c) Kitware SAS. 20 rue de la Villette. All rights reserved.
69328 Lyon, FRANCE.

See Copyright.txt for details.
This software is distributed WITHOUT ANY WARRANTY; without even
the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE.  See the above copyright notices for more information.
=========================================================================*/

$this->headScript()->appendFile($this->coreWebroot . '/public/js/jquery/jquery.form.js');
$this->headScript()->appendFile($this->moduleWebroot . '/public/js/config/config.index.js');
?>
<link type="text/css" rel="stylesheet" href="<?php echo $this->moduleWebroot?>/public/css/config/config.index.css" />
<link type="text/css" rel="stylesheet" href="<?php echo $this->coreWebroot?>/public/css/common/common.genericPage.css" />

<div class="viewMain">

  <div class ="genericWrapperTopRight">
         <?php
          echo '<div style="float:right;margin-right:2px;" class="genericBigButton ">';
            echo "<a  href='{$this->webroot}/admin#tabs-modules'><img style='float:left;margin-right:2px;' alt='' src='{$this->coreWebroot}/public/images/icons/back.png'/>";
            echo $this->t('Back');
            echo "</a>";
          echo '</div>';

        ?>
    </div>

     <?php
      echo "
      <form class='genericForm' id='configForm' method='{$this->configForm['method']}'  action='{$this->configForm['action']}'>
      <h3>Ldap Configuration:</h3>
            <div qtip='This is the url to the ldap server. (required)'  >
              <label for='hostname'>Ldap Hostname</label>
              {$this->configForm['hostname']}
            </div>
            <div qtip='Port on which server is listening (required). Default is 389, or 636 for SSL.'  >
              <label for='port'>Ldap Port</label>
              {$this->configForm['port']}
            </div>
            <div qtip=\"This is the url to the backup server. Leave blank if you don't want to use a backup server.\" >
              <label for='hostname'>Backup Server</label>
              {$this->configForm['backup']}
            </div>
            <div qtip='This is the context object used to search on the directory. Example: cn=user,ou=people,dc=myorganization,dc=com'>
              <label  for='hostname'>Bind Dn</label>
              {$this->configForm['bindn']}
            </div>
            <div qtip='Password of the object context.' >
              <label  for='hostname'>Bind Password</label>
              {$this->configForm['bindpw']}
            </div>
            <div >
              <label  for='basedn'>Base Dn</label>
              {$this->configForm['basedn']}
            </div>
            <div >
              <label for='protocolVersion'>Ldap Protocol Version</label>
              {$this->configForm['protocolVersion']}
            </div>
            <div qtip=' This is the unique identifier field in the LDAP directory where the username is stored' >
              <label  for='search'>Search Attribute</label>
              {$this->configForm['search']}
            </div>
            <div >
              <label for='proxyBasedn'>Proxy Base Dn</label>
              {$this->configForm['proxyBasedn']}
            </div>
            <div >
              <label for='proxyPassword'>Proxy Password</label>
              {$this->configForm['proxyPassword']}
            </div>
            <div >
              <label for='useActiveDirectory'>Use Active Directory?</label>
              {$this->configForm['useActiveDirectory']}
            </div>
            <div >
              <label for='autoAddUnknownUser'>Add user if not in database?</label>
              {$this->configForm['autoAddUnknownUser']}
            </div>
          <div>
            {$this->configForm['submitConfig']}
          </div>
       </form>";
       ?>
</div>
