<?php
/*=========================================================================
MIDAS Server
Copyright (c) Kitware SAS. 20 rue de la Villette. All rights reserved.
69328 Lyon, FRANCE.

See Copyright.txt for details.
This software is distributed WITHOUT ANY WARRANTY; without even
the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE.  See the above copyright notices for more information.
=========================================================================*/

echo '<script type="text/javascript" src="'.$this->moduleWebroot.'/public/js/login/login.dialog.js"></script>';
?>
<link type="text/css" rel="stylesheet" href="<?php echo $this->moduleWebroot?>/public/css/login/login.dialog.css" />


<form class="genericForm" id="mfaLoginForm" method="POST" action="<?php echo $this->webroot?>/mfa/login/submit">
  <input type="hidden" name="userId" value="<?php echo $this->user->getKey();?>" />
  <div>
    <input id="otpToken" type="password" name="token" />
  </div>
  <div>
    <input type="submit" value="Enter" id="otpLoginSubmit" />
  </div>
</form>
