<?php
/*=========================================================================
MIDAS Server
Copyright (c) Kitware SAS. 20 rue de la Villette. All rights reserved.
69328 Lyon, FRANCE.

See Copyright.txt for details.
This software is distributed WITHOUT ANY WARRANTY; without even
the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE.  See the above copyright notices for more information.
=========================================================================*/
$this->headScript()->appendFile($this->coreWebroot . '/public/js/jquery/jquery.form.js');
$this->headScript()->appendFile($this->coreWebroot . '/public/js/jquery/jquery.json.min.js');
$this->headScript()->appendFile($this->coreWebroot . '/public/js/jquery/jquery.timepicker-addon.js');
$this->headScript()->appendFile($this->moduleWebroot . '/public/js/job/job.init.js');
$this->headScript()->appendFile($this->coreWebroot . '/public/js/jquery/jquery.smartWizard-2.0.js');

echo $this->lesscss($this->moduleWebroot.'/public/css/job/job.init.less', array());
?>
<!-- <link type="text/css" rel="stylesheet" href="<?php echo $this->moduleWebroot?>/public/css/job/job.init.css" /> -->
<link type="text/css" rel="stylesheet" href="<?php echo $this->coreWebroot?>/public/css/jquery/jquery.timepicker-addon.css" />
<link type="text/css" rel="stylesheet" href="<?php echo $this->coreWebroot?>/public/css/jquery/jquery.smartWizard-2.0.css" />

<div id="wizard" class="swMain">
  <ul>
    <li>
      <a href="#step-1">
          <span class="stepDesc">
             1. Upload<br />
             <small>Upload additional data</small>
          </span>
      </a>
    </li>
    <li>
      <a href="#step-2">
          <span class="stepDesc">
             2. Workflow<br />
             <small>Create workflow</small>
          </span>
      </a>
    </li>
    <li>
      <a href="#step-3">
          <span class="stepDesc">
             3. Jobs<br />
             <small>Set up the jobs</small>
          </span>
      </a>
    </li>
    <li>
      <a href="#step-4">
          <span class="stepDesc">
             4. Schedule<br />
             <small>Schedule the workflow</small>
          </span>
      </a>
    </li>
  </ul>
  <div id="step-1">
      <h2 class="StepTitle">Upload (Optional)</h2>
      <br/><b>A processing job requires at least an executable. <br/>Please upload the file you want to process.</b> (you can use browse MIDAS content)<br/>
      <br/>

      <div id='uploadContentBlock'>
        <img  src="<?php echo $this->webroot?>/core/public/images/icons/loading.gif" alt="Loading..." />
      </div>
      <br/>
      <b>Go to the <a onclick="$('.buttonNext').click();" >next step</a> if you want to use already uploaded files.</b>

  </div>
  <div id="step-2">
    <h2 class="StepTitle">Set up your Workflow</h2>
    <form id="workflowForm" class="genericForm">
      <span>Name:</span> <input type="text" id="workflowName" name="workflowName" value="Workflow_<?php echo time()?>"/><br/>
      <span qtip="The Uuid is used to submit external job." >Uuid:</span> <input type="text" id="workflowUuid" disabled name="workflowUuid" value="<?php echo uniqid() . md5(mt_rand())?>"/><br/>
      <span>Description:</span><br/>
      <textarea name="workflowDescription" id="workflowDescription" rows="24" cols="80" ></textarea><br/>

      <span>Domain:</span>
      <select id="workflowDomain" name="workflowDomain" onchange="if($('#workflowDomain').val()==-1)$('#createDomain').show();else $('#createDomain').hide();">
        <?php
        foreach($this->domains as $domain)
          {
          echo "<option value='".$domain->getKey()."'>".$domain->getName()."</option>";
          }
        ?>
        <option value="-1">Register a new Domain</option>
      </select>

    </form>
    <div id="createDomain">
      <form id="workflowDomainForm" class="genericForm">
        <b>Provide details of your new Domain below:</b><br/><br/>
      <span>Name:</span> <input type="text" id="workflowDomainName" name="workflowDomainName" value="Domain_<?php echo time()?>"/><br/>
      <span>Description:</span><br/>
      <textarea name="workflowDomainDescription" id="workflowDomainDescription" rows="24" cols="80" ></textarea><br/>
      </form>
    </div>


  </div>
  <div id="step-3">
        <?php
          echo '<div  class="genericBigButton ">';
            echo "<a id='addJobLink' ><img style='float:left;margin-right:2px;' alt='' src='{$this->coreWebroot}/public/images/icons/add.png'/>";
            echo $this->t('Add an Job');
            echo "</a>";
          echo '</div>';
        ?>
    <div id="jobListing">
    </div>

    <br/>
      <b>Here are listed the options executable options. Please fill the form using the data you want to process.</b><br/><br/>
      <?php
      if($this->scheduled)
        {?>
        A scheduled job require folder inputs. All the data located in these folders will be periodically processed.<br/><br/>
        <?php
        }
      ?>

    <b>This feature is currently disabled</b>
    <div id="dialogJobCreation">
      <h3>Create a job</h3>
      <label for="jobNameForm">Name:</label><input type="text" name="jobNameForm" id="jobNameForm"/><br/>
      <label for="jobTypeForm">Job type:</label>
      <select name="jobTypeForm" id="jobTypeForm">
        <option value="-1">-Select a task-</option>
        <option value="executable">Executable remote task</option>
        <option value="internal">Internal Midas task</option>
        <option value="user">User task</option>
      </select>
      <br/>
      <div id="selectExecutable">
      <br/><b>Select the executable you want to use.</b>
      <br/><br/>
      <?php
        echo '<div id="browseExecutableFile" class="genericBigButton ">';
          echo "<a  ><img  alt='' src='{$this->coreWebroot}/public/images/FileTree/file.png'/>";
          echo "<span>".$this->t('Browse')."</span>";
          echo "</a>";
        echo '</div>';
        ?>
      <br/><br/>
      <b>Selected:</b> <span id="selectedExecutable">None</span>
      <input type="hidden" id="selectedExecutableId" value=""/>

      </div>
      <input class="globalButton" type="submit" id="createJobLink" value="Create"/>
    </div>
  </div>

  <div id="step-4">
    <h2 class="StepTitle">Schedule (Optional)</h2>
    <input type='checkbox' id="checkboxSchedule" name="checkboxSchedule"/> <label for="checkboxSchedule">Run as soon as possible</label>
    <br/>
    <div id="schedulerWrapper" >
      Date and Time: <input type="text" id="datepicker"> Every: <select id="intervalSelect">
        <option value="0">Only once</option>
        <option value="3600">Hours</option>
        <option value="86400">Days</option>
        <option value="604800">Weeks</option>
      </select>
    </div>
    <br/>
  </div>
</div>
