<?php
/*=========================================================================
 MIDAS Server
 Copyright (c) Kitware SAS. 26 rue Louis Guérin. 69100 Villeurbanne, FRANCE
 All rights reserved.
 More information http://www.kitware.com

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

         http://www.apache.org/licenses/LICENSE-2.0.txt

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
=========================================================================*/

$this->headScript()->appendFile($this->moduleWebroot . '/public/js/job/job.manage.js');
?>
<link type="text/css" rel="stylesheet" href="<?php echo $this->moduleWebroot?>/public/css/job/job.manage.css"
<link type="text/css" rel="stylesheet" href="<?php echo $this->coreWebroot?>/public/css/common/common.genericPage.css" />
<link type="text/css" rel="stylesheet" href="<?php echo $this->coreWebroot?>/public/css/common/common.browser.css" />

<div class="viewMain">

    <?php
          echo '<div  class="genericBigButton ">';
            echo "<a href='{$this->webroot}/remoteprocessing/job/init' ><img style='float:left;margin-right:2px;' alt='' src='{$this->coreWebroot}/public/images/icons/add.png'/>";
            echo $this->t('Create a Job');
            echo "</a>";
          echo '</div>';
        ?>

  <br/>
  <br/>

    <?php
  if(empty($this->relatedJobs))
    {
    echo "No started Jobs";
    }
  else
    {
    ?>
  <h4>10 last Jobs</h4>
  <table style='display:block;' class="midasTree">

    <thead>
      <tr>
        <th style="width:100px;" >Name</th>
        <th style="width:240px;" >Creation Date</th>
        <th  style="width:250px;">Status</th>
      </tr>
    </thead>
    <?php
    foreach($this->relatedJobs as $job)
      {
      echo "<tr element='".$job->getKey()."v'>";
      echo  "<td>".$job->getName()."</td>";
      echo  "<td>".$job->getCreationDate()."</td>";
      if($job->getStatus() == MIDAS_REMOTEPROCESSING_STATUS_DONE)
        {
        echo  "<td class='elementStatus'>Done</td>";
        }
      else if(strtotime($job->getExpirationDate()) < strtotime(date("Y-m-d H:i:s")))
        {
        echo  "<td class='elementStatus'>Expired</td>";
        }
      else if($job->getStatus() == MIDAS_REMOTEPROCESSING_STATUS_WAIT)
        {
        echo  "<td class='elementStatus'>Waiting</td>";
        }
      else if($job->getStatus() == MIDAS_REMOTEPROCESSING_STATUS_STARTED)
        {
        echo  "<td class='elementStatus'>Started</td>";
        }
      else
        {
        echo  "<td class='elementStatus'>Done</td>";
        }
      echo "</tr>";
      }
      ?>
  </table>
  <?php
    }
    ?>

    <?php
  if(empty($this->relatedJobs))
    {
    echo "No scheduled Jobs";
    }
  else
    {
    ?>
  <h4>Scheluded Jobs</h4>
  <table style='display:block;' class="midasTree">

    <thead>
      <tr>
        <th style="width:100px;" >Name</th>
        <th style="width:240px;" >Run Time</th>
        <th  style="width:250px;">Status</th>
      </tr>
    </thead>
    <?php
    foreach($this->scheduledJobs as $job)
      {
      $params = JsonComponent::decode($job->getParams());
      echo "<tr element='".$job->getKey()."v'>";
      echo  "<td>".$params['params']['job_name']."</td>";
      echo  "<td>".$job->getFireTime()."</td>";
      echo  "<td>Scheduled</td>";
      echo "</tr>";
      }
      ?>
  </table>
  <?php
    }
    ?>

</div>
<div class="viewSideBar">

   <div class="sideElementFirst viewAction" style ="display:none;">
    <h1>Actions</h1>
    <ul>
      <li>
        <a id='viewJob'><img alt='' src='<?php echo $this->coreWebroot?>/public/images/icons/view.png'/>View</a>
      </li>
    </ul>
   </div>
</div>
