<?php
/*=========================================================================
MIDAS Server
Copyright (c) Kitware SAS. 20 rue de la Villette. All rights reserved.
69328 Lyon, FRANCE.

See Copyright.txt for details.
This software is distributed WITHOUT ANY WARRANTY; without even
the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE.  See the above copyright notices for more information.
=========================================================================*/

$this->headScript()->appendFile($this->moduleWebroot . '/public/js/job/job.manage.js');

?>
<link type="text/css" rel="stylesheet" href="<?php echo $this->moduleWebroot?>/public/css/job/job.manage.css" />
<div class="viewMain">
     <div class ="genericWrapperTopRight">
         <?php
          echo '<div style="float:right;margin-right:2px;" class="genericBigButton ">';
            echo "<a  href='{$this->webroot}/item/{$this->itemDao->getKey()}'><img style='float:left;margin-right:2px;' alt='' src='{$this->coreWebroot}/public/images/icons/back.png'/>";
            echo $this->t('Back');
            echo "</a>";
          echo '</div>';

        ?>
    </div>

    <?php
          echo '<div  class="genericBigButton ">';
            echo "<a href='{$this->webroot}/remoteprocessing/job/init?itemId={$this->itemDao->getKey()}' ><img style='float:left;margin-right:2px;' alt='' src='{$this->coreWebroot}/public/images/icons/add.png'/>";
            echo $this->t('Add a Job');
            echo "</a>";
          echo '</div>';

        ?>

  <br/>
  <br/>
  <?php
  if(!$this->metaFile)
    {
    echo "<span style='color:red;'>Please first define the option definition file</span> <a href='".$this->webroot."/remoteprocessing/executable/define?itemId=".$this->itemDao->getKey()."'>here</a>.";
    }
    ?>
  <br/>

</div>

<div id="jsonMetadataContent"><?php echo $this->jsonMetadata?></div>








