<?php
/*=========================================================================
MIDAS Server
Copyright (c) Kitware SAS. 20 rue de la Villette. All rights reserved.
69328 Lyon, FRANCE.

See Copyright.txt for details.
This software is distributed WITHOUT ANY WARRANTY; without even
the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE.  See the above copyright notices for more information.
=========================================================================*/

$this->headScript()->appendFile($this->moduleWebroot . '/public/js/job/job.view.js');
$this->headScript()->appendFile($this->coreWebroot . '/public/js/jquery/jquery.dataTable.js');

?>
<link type="text/css" rel="stylesheet" href="<?php echo $this->moduleWebroot?>/public/css/job/job.view.css" />
<link type="text/css" rel="stylesheet" href="<?php echo $this->coreWebroot?>/public/css/jquery/jquery.dataTable.css" />
<div class="viewMain">
  <?php
   $jobStatus = "Done";
   if($this->job->getStatus() == MIDAS_REMOTEPROCESSING_STATUS_DONE)
      {
      $jobStatus =  "Done";
      }
    elseif(strtotime($this->job->getExpirationDate()) < strtotime(date('c')))
      {
      $jobStatus = "Expired";
      }
    elseif($this->job->getStatus() == MIDAS_REMOTEPROCESSING_STATUS_WAIT)
      {
      $jobStatus =  "Waiting";
      }
    elseif($this->job->getStatus() == MIDAS_REMOTEPROCESSING_STATUS_STARTED)
      {
      $jobStatus =  "Started";
      }


  ?>

  <h4 style="margin-bottom: 0px;">Job Status: <?php echo $jobStatus?></h4>
  <h4 style="margin-top: 0px;">Workflow: <a href="<?php echo $this->webroot?>/remoteprocessing/dashboard/workflow?workflowId=<?php echo $this->workflow->getKey()?>"><?php echo $this->workflow->getName();?></a></h4>

  <?php
    if($this->executable != false)
      {
      ?>
    <h4>Executable: <a href="<?php echo $this->webroot?>/item/<?php echo $this->executable->getKey()?>"><?php echo $this->executable->getName()?></a></h4>
  <?php
      }
    if($this->log != false)
      {
      ?>
    <a id="showLogLink">Toggle raw xml results</a><br/>
    <pre id="hiddenLog"><?php echo htmlentities($this->log)?></pre>

    <h4>Tasks grid:</h4>
    <table id="tableXml">
      <thead>
        <tr>
        <?php
        echo "<th ><b>#</b></th>";
        echo "<th qtip='Execution status'><b>Status</b></th>";
        echo "<th qtip='Duration'><b>Duration</b></th>";
        echo "<th qtip='Stdout Output'><b>Output</b></th>";
        echo "<th qtip='Stderr Output'><b>Error output</b></th>";

        $htmltArray = Zend_Registry::get('notifier')->callback("CALLBACK_REMOTEPROCESSING_JOB_DASHBOARD_HEADER", array($this->results));
        foreach($htmltArray as $html)
          {
          if(!empty($html))
            {
            echo $html;
            }
          }
        ?>
        </tr>
      </thead>
      <tbody>
    <?php
      foreach($this->results['tasks'] as $key => $result)
        {
        $parameters = "";
        foreach($this->inputs as $name => $notUsed)
          {
          $parameters .= "<b>".ucfirst($name)."</b>: ";
          if(isset($this->inputsValues[$key][$name]))
            {
            $parameters .= $this->inputsValues[$key][$name]."<br/>";
            }
          else
            {
            $parameters .= "-<br/>";
            }
          }
        echo "<td class='xmlId'><a qtip=\"".str_replace('"',"'",$parameters)."\" href='#'>".$key."</a></td>";
        echo "<td class='xmlStatus'>".$result['status']."</td>";
        echo "<td >".str_replace(' seconds', 's', $this->duration($result['time']))."</td>";
        echo "<td class='showInDialog' output='".htmlentities($result['stdout'])."'><a>".$this->slicename(htmlentities($result['stdout']),15)."</a></td>";
        echo "<td class='showInDialog' output='".htmlentities($result['stderr'])."'><a>".$this->slicename(htmlentities($result['stderr']),15)."</a></td>";


        $htmltArray = Zend_Registry::get('notifier')->callback("CALLBACK_REMOTEPROCESSING_JOB_DASHBOARD_BODY", array($result));
        foreach($htmltArray as $html)
          {
          if(!empty($html))
            {
            echo $html;
            }
          }
        echo "</tr>";
        }
        ?>
       </tbody>
    </table>

    <?php
    if(!empty($this->metrics))
      {?>
      <h4>Metrics grid:</h4>
      <table id="tableMetricsXml">
        <thead>
          <tr>
          <th ><b>#</b></th>
          <?php
          foreach($this->metrics as $name => $values)
            {
            echo "<th qtip='".ucfirst($name)."'><b>".$this->slicename(ucfirst($name),10)."</b></th>";
            }
          ?>
          </tr>
        </thead>
        <tbody>
      <?php
        foreach($this->results['tasks'] as $keyTask => $notUsed)
          {
          echo "<tr>";
          $parameters = "";
          foreach($this->inputs as $name => $notUsed)
            {
            $parameters .= "<b>".ucfirst($name)."</b>: ";
            if(isset($this->inputsValues[$keyTask][$name]))
              {
              $parameters .= $this->inputsValues[$keyTask][$name]."<br/>";
              }
            else
              {
              $parameters .= "-<br/>";
              }
            }
          echo "<td class='xmlId'><a qtip=\"".str_replace('"',"'",$parameters)."\" href='#'>".$keyTask."</a></td>";
          foreach($this->metrics as $name => $notUsed)
            {
            if(isset($this->metricsValues[$keyTask][$name]))
              {
              echo "<td class='xmlId'>".$this->metricsValues[$keyTask][$name]."</td>";
              }
            else
              {
              echo "<td ></td>";
              }
            }
          echo "</tr>";
          }
          ?>
        </tbody>
      </table>
    <?php
      }?>

    <div id="metricsWrapper" style="display:none;">
      <h4>Metrics: </h4>
    </div>
      <?php
      }

    if($this->job->getStatus() == MIDAS_REMOTEPROCESSING_STATUS_DONE && !empty($this->outputs))
      {
      ?>
    <h4>Output grid:</h4>

    <table id="tableResults">
      <thead>
        <tr>
        <?php
        echo "<th><b>Output</b></th>";
        echo "<th><b>Thumbnail</b></th>";

        foreach($this->parameters as $parameter)
          {
          echo "<th><b>".ucfirst($parameter)."</b></th>";
          }
        ?>
        </tr>
      </thead>
      <tbody>
      <?php
      foreach($this->outputs as $output)
        {
        echo "<tr>";
        echo "<td ><a href='".$this->webroot."/item/".$output->getKey()."' elementItem='".$output->getKey()."'>".$output->getName()."</a></td>";
        echo "<td>";
        if($output->getThumbnailId())
          {
          echo '<h1>Preview</h1>'.
              '<img class="infoLogo" alt="" src="'.$this->webroot.'/item/thumbnail?itemId='.
              $output->getKey().'"/>';
          }
        echo "</td>";
        if(isset($output->metadataValues) )
          {
          foreach($this->parameters as $value)
            {
            $parameter = null;
            if(isset($output->metadataValues[$value]))
              {
              $parameter = $output->metadataValues[$value];
              }
            if($parameter instanceof ItemDao)
              {
              echo "<td><a href='".$this->webroot."/item/".$parameter->getKey()."' elementItem='".$parameter->getKey()."'>".$parameter->getName()."</a></td>";
              }
            elseif(!empty($parameter))
              {
              echo "<td>".$parameter."</td>";
              }
            else
              {
              echo "<td></td>";
              }
            }
          }
        echo "</tr>";
        }
      ?>
      </tbody>
    </table>
        <?php
        $itemsList = "";
        foreach($this->outputs as $ouput)
          {
          $itemsList .= $ouput->getKey().'-';
          }
        echo '<div class="genericBigButton ">';
          echo "<a  href='{$this->webroot}/download?items={$itemsList}'><img style='float:left;margin-right:2px;' alt='' src='{$this->coreWebroot}/public/images/icons/download.png'/>";
          echo $this->t('Download Results');
          echo "</a>";
        echo '</div>';

        ?>
    <?php
      }
   ?>


</div>






