<?php
/*=========================================================================
 MIDAS Server
 Copyright (c) Kitware SAS. 26 rue Louis Guérin. 69100 Villeurbanne, FRANCE
 All rights reserved.
 More information http://www.kitware.com

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

         http://www.apache.org/licenses/LICENSE-2.0.txt

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
=========================================================================*/

$this->declareVars('form', 'pageTitle');
$this->headTitle($this->escape($this->pageTitle));
?>

<div class="viewMain">
    <h1><?php echo $this->escape($this->pageTitle); ?></h1>
    <p>For this module to work, you will need to build ParaView with Python enabled.
    Instructions are <a href="http://www.paraview.org/Wiki/ParaView:Build_And_Install#Build_ParaView">here</a>.</p>
    <p>You can turn off building with Qt when building ParaView. Make sure to
    symlink the <b>www</b> directory of your ParaView build directory as
    <b>modules/pvw/public/import</b>.</p>
    <?php echo $this->form; ?>
    <p><a href="<?php echo $this->url(array('controller' => 'admin', 'action' => 'index'), 'default'); ?>#tabs-modules">&laquo; Back to Modules Administration</a></p>
</div>
