<?php
/*=========================================================================
 MIDAS Server
 Copyright (c) Kitware SAS. 26 rue Louis Guérin. 69100 Villeurbanne, FRANCE
 All rights reserved.
 More information http://www.kitware.com

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

         http://www.apache.org/licenses/LICENSE-2.0.txt

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
=========================================================================*/

$this->headScript()->appendFile($this->coreWebroot.'/public/js/jquery/jquery.form.js');
$this->headScript()->appendFile($this->moduleWebroot.'/public/js/config/config.index.js');
?>

<link type="text/css" rel="stylesheet" href="<?php echo $this->coreWebroot?>/public/css/common/common.genericPage.css" />
<div class="viewMain">
  <h3>Google Auth Module Configuration</h3>
  <form class="genericForm" id="configForm" method="POST" action="<?php echo $this->webroot;?>/googleauth/config/submit">
    <div class="config-form-group">
      <label for="client_id">Client ID</label>
      <input type="text" name="client_id" value="<?php echo $this->clientId; ?>" />
    </div>
    <div class="config-form-group">
      <label for="client_secret">Client Secret</label>
      <input type="text" name="client_secret" value="<?php echo $this->clientSecret; ?>" />
    </div>
    <div class="config-submit-container">
      <input type="submit" value="Save" />
    </div>
  </form>
</div>
