<?php
/*=========================================================================
 MIDAS Server
 Copyright (c) Kitware SAS. 26 rue Louis Guérin. 69100 Villeurbanne, FRANCE
 All rights reserved.
 More information http://www.kitware.com

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

         http://www.apache.org/licenses/LICENSE-2.0.txt

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
=========================================================================*/
?>
<link type="text/css" rel="stylesheet" href="<?php echo $this->moduleWebroot?>/public/css/paraview/paraview.dual.css" />
<link type="text/css" rel="stylesheet" href="<?php echo $this->coreWebroot?>/public/css/layout/jquery-ui.min.css" />

<?php
$this->headScript()->appendFile($this->moduleWebroot.'/public/js/paraview/get_modules.js');
$this->headScript()->appendFile('/PWService/js/ParaViewWeb.js');
$this->headScript()->appendFile($this->moduleWebroot.'/public/js/paraview/paraview.dual.js');
$this->headScript()->appendFile($this->webroot.'/modules/api/public/js/common/common.ajaxapi.js');

/** Dynamic js library imports for action handlers */
foreach($this->jsImports as $jsImport)
  {
  $this->headScript()->appendFile($jsImport);
  }
?>

<div class="rendererWrapper">
  <div id="leftRenderer">
    <img class="leftLoading" alt="" src="<?php echo $this->coreWebroot?>/public/images/icons/loading.gif" />
    <span id="leftLoadingStatus"></span>
    <div id="leftRendererOverlay"></div>
    <!-- The left renderer will be inserted here -->
  </div>
  <div id="rightRenderer">
    <img class="rightLoading" alt="" src="<?php echo $this->coreWebroot?>/public/images/icons/loading.gif" />
    <span id="rightLoadingStatus"></span>
    <div id="rightRendererOverlay"></div>
    <!-- The right renderer will be inserted here -->
  </div>
</div>

<div class="slidersContainer">
  <div class="sliceControlContainer">
    <div id="sliceSlider"></div>
    <div id="sliceInfo"></div>
  </div>
  <div class="windowControlContainer">
    <div id="windowSlider"></div>
    <div id="windowInfo"></div>
  </div>
</div>

<!-- TEMPLATE: UI Action widget -->
<button id="actionButtonTemplate" style="display: none;" class="actionButton actionInactive"></button>

<!-- TEMPLATE: Fiducial point list dialog -->
<div id="pointListDialogTemplate" style="display: none;">
  <table class="pointListTable">
    <thead>
      <tr>
        <th>Left image point</th><th>Right image point</th><th>Actions</th>
      </tr>
    </thead>
    <tbody>
    </tbody>
  </table>
  <div class="bottomButtons">
    <button class="processButton">Process</button>
    <button class="closeButton">Close</button>
  </div>
</div>
