<?php
/*=========================================================================
MIDAS Server
Copyright (c) Kitware SAS. 20 rue de la Villette. All rights reserved.
69328 Lyon, FRANCE.

See Copyright.txt for details.
This software is distributed WITHOUT ANY WARRANTY; without even
the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE.  See the above copyright notices for more information.
=========================================================================*/
?>
<link type="text/css" rel="stylesheet" href="<?php echo $this->moduleWebroot?>/public/css/paraview/paraview.index.css" />

<?php
echo '<script type="text/javascript" src="' . $this->coreWebroot . '/public/js/layout/jquery.js"></script>';
$this->headScript()->appendFile('/PWService/js/ParaViewWeb.js');
$this->headScript()->appendFile($this->moduleWebroot . '/public/js/paraview/paraview.index.js');
?>

<img class="visuLoading" alt=""  src="<?php echo $this->coreWebroot?>/public/images/icons/loading.gif" />

<?php
if($this->useScreenshot)
  {
  ?>
<img style='width:<?php echo $this->width?>px;height:<?php echo $this->height?>px;'   id="bigScreenshot" src='<?php echo $this->webroot.'/'.$this->screenshotPath?>'/>
<?php
  }

if(!empty($this->pwapp))
  {?>
<br/>
<?php
  }
?>

 <select id="renderer-type" name="renderer-type" <?php if(!$this->usewebgl) echo "style='display:none;'"?>
                onchange="switchRenderer(false)" >
            <option <?php if($this->renderer == 'js')echo 'selected';?> value="js">JavaScript</option>
			<option <?php if($this->renderer == 'webgl')echo 'selected';?> value="webgl">WebGL</option>
</select>


 <div id="controlPanel">
Contours:
</b><br/>
<input type="test" id="contour" onChange="stateController.iso.setIsosurfaces($('#contour').val());" />
  </div>

<div id='renderercontainer' style="">
         <!-- The renderer will be inserted here -->
</div>


<?php echo $this->headScript() ?>
<div style="display: none;" class="jsonContent">
  <?php echo $this->json?>
</div>
