<?php
/*=========================================================================
MIDAS Server
Copyright (c) Kitware SAS. 20 rue de la Villette. All rights reserved.
69328 Lyon, FRANCE.

See Copyright.txt for details.
This software is distributed WITHOUT ANY WARRANTY; without even
the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE.  See the above copyright notices for more information.
=========================================================================*/
?>
<link type="text/css" rel="stylesheet" href="<?php echo $this->moduleWebroot?>/public/css/paraview/paraview.slice.css" />
<link type="text/css" rel="stylesheet" href="<?php echo $this->coreWebroot?>/public/css/layout/jquery-ui.css" />

<?php
$this->headScript()->appendFile('/PWService/js/ParaViewWeb.js');
$this->headScript()->appendFile($this->moduleWebroot.'/public/js/paraview/paraview.slice.js');
$this->headScript()->appendFile($this->webroot.'/modules/api/public/js/common/common.ajaxapi.js');

/** Dynamic js library imports for action handlers */
foreach($this->jsImports as $jsImport)
  {
  $this->headScript()->appendFile($jsImport);
  }
?>

<img class="visuLoading" alt="" src="<?php echo $this->coreWebroot?>/public/images/icons/loading.gif" />

<div id='renderercontainer' style="">
  <div id='rendererOverlay'></div>
  <div id="sliceControlContainer">
    <div id="sliceSlider"></div>
    <div id="sliceInfo"></div>
  </div>

  <div id="windowLevelControlContainer">
    <div id="windowLevelInfo"></div>
    <div id="windowLevelSlider"></div>
  </div>
  <!-- The renderer will be inserted here -->
</div>

<div class="belowViewportContainer">
  Click <a onclick="midas.visualize.toggleControlVisibility();">here</a> or press 'c' to toggle control visibility.
</div>

<!-- UI Action widget templates -->
<button id="actionButtonTemplate" style="display: none;" class="actionButton actionInactive"></button>

