<?php
/*=========================================================================
MIDAS Server
Copyright (c) Kitware SAS. 20 rue de la Villette. All rights reserved.
69328 Lyon, FRANCE.

See Copyright.txt for details.
This software is distributed WITHOUT ANY WARRANTY; without even
the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE.  See the above copyright notices for more information.
=========================================================================*/

$this->headScript()->appendFile($this->moduleWebroot . '/public/js/index/index.index.js');
$this->headScript()->appendFile($this->moduleWebroot . '/public/js/jquery.jqplot.js');
$this->headScript()->appendFile($this->moduleWebroot . '/public/js/jqplot/jqplot.dateAxisRenderer.min.js');
$this->headScript()->appendFile($this->moduleWebroot . '/public/js/jqplot/jqplot.pieRenderer.min.js');
?>
<!--[if lt IE 9]><script language="javascript" type="text/javascript" src="<?php echo $this->moduleWebroot?>/public/js/excanvas.min.js"></script><![endif]-->
<link rel="stylesheet" type="text/css" href="<?php echo $this->moduleWebroot?>/public/css/jquery.jqplot.css" />

<link type="text/css" rel="stylesheet" href="<?php echo $this->moduleWebroot?>/public/css/index/index.index.css" />
<link type="text/css" rel="stylesheet" href="<?php echo $this->coreWebroot?>/public/css/common/common.genericPage.css" />
<div class="viewMain">
  <h3>Statistics</h3>

  <p> More information are available on <a target="_blank" href="<?php echo $this->piwikUrl?>">PIWIK</a></p>
  <img class="tabsLoading" alt=""  src="<?php echo $this->coreWebroot?>/public/images/icons/loading.gif" />
  <div class="tabs" id='tabsGeneric'>
  <ul>
    <li><a href="#tabs-overview">Visitors Overview</a></li>
    <li><a href="#tabs-live">Live</a></li>
    <li><a href="#tabs-map">World Map</a></li>
    <li><a href="#tabs-configuration">Visitors Configuration</a></li>
    <li><a href="#tabs-referrers">Referrers</a></li>
    <li><a href="#tabs-errors">Errors</a></li>
    <li><a href="#tabs-assetstores">Assetstores</a></li>

  </ul>
    <div id="tabs-overview">
      <div id="widgetIframe"><iframe width="100%" height="650" src="<?php echo $this->piwikUrl?>/index.php?module=Widgetize&action=iframe&moduleToWidgetize=VisitsSummary&actionToWidgetize=index&idSite=<?php echo $this->piwikId?>&language=en&period=day&date=<?php echo date('Y-m-d')?>&disableLink=1&widget=1&token_auth=<?php echo $this->piwikKey?>" scrolling="yes" frameborder="0" marginheight="0" marginwidth="0"></iframe></div>
    </div>
    <div id="tabs-live">
      <div id="widgetIframeLive"><iframe width="100%" height="650" src="<?php echo $this->piwikUrl?>/index.php?module=Widgetize&action=iframe&moduleToWidgetize=Live&actionToWidgetize=widget&idSite=<?php echo $this->piwikId?>&language=en&period=day&date=today&disableLink=1&widget=1&token_auth=<?php echo $this->piwikKey?>" scrolling="yes" frameborder="0" marginheight="0" marginwidth="0"></iframe></div>
    </div>
    <div id="tabs-map">
      <div id="widgetIframeMap"><iframe width="100%" height="650" src="<?php echo $this->piwikUrl?>/index.php?module=Widgetize&action=iframe&moduleToWidgetize=UserCountryMap&actionToWidgetize=worldMap&language=en&idSite=<?php echo $this->piwikId?>&period=week&date=today&disableLink=1&widget=1&token_auth=<?php echo $this->piwikKey?>" scrolling="no" frameborder="0" marginheight="0" marginwidth="0"></iframe></div>
    </div>
    <div id="tabs-configuration">
      <div id="widgetIframeConfiguration"><iframe width="100%" height="650" src="<?php echo $this->piwikUrl?>/index.php?module=Widgetize&action=iframe&moduleToWidgetize=UserSettings&actionToWidgetize=getConfiguration&idSite=<?php echo $this->piwikId?>&language=en&period=day&date=today&disableLink=1&widget=1&token_auth=<?php echo $this->piwikKey?>" scrolling="yes" frameborder="0" marginheight="0" marginwidth="0"></iframe></div>
      </div>
    <div id="tabs-referrers">
      <div id="widgetIframeRef"><iframe width="100%" height="650" src="<?php echo $this->piwikUrl?>/index.php?module=Widgetize&action=iframe&moduleToWidgetize=Referers&actionToWidgetize=getRefererType&idSite=<?php echo $this->piwikId?>&language=en&period=day&date=today&disableLink=1&widget=1&token_auth=<?php echo $this->piwikKey?>" scrolling="yes" frameborder="0" marginheight="0" marginwidth="0"></iframe></div>
    </div>
    <div id="tabs-errors">
      <div id="chartErrors" style="height:450px;width:800px; "></div>
    </div>
    <div id="tabs-assetstores">
      <div id="chartAssetstore" ></div>
    </div>
  </div>

</div>
<div class="viewSideBar">


</div>
