<?php
/*=========================================================================
MIDAS Server
Copyright (c) Kitware SAS. 20 rue de la Villette. All rights reserved.
69328 Lyon, FRANCE.

See Copyright.txt for details.
This software is distributed WITHOUT ANY WARRANTY; without even
the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE.  See the above copyright notices for more information.
=========================================================================*/

$this->headScript()->appendFile($this->coreWebroot.'/public/js/common/common.license.js');

if(!isset($this->selectedLicense) || $this->selectedLicense == null)
  {
  $this->selectedLicense = -1; // don't pre-select any in this case
  }
?>

<div class="licenseSelectContent">
  <select name="licenseSelect">
  <?php
    foreach($this->allLicenses as $license)
      {
      echo '<option value="'.$license->getKey().'" '.(($this->selectedLicense == $license->getKey()) ? 'selected' : '').
           '>'.$license->getName().'</option>';
      }
  ?>

  </select>
</div>
