<?php
/*=========================================================================
 MIDAS Server
 Copyright (c) Kitware SAS. 26 rue Louis Guérin. 69100 Villeurbanne, FRANCE
 All rights reserved.
 More information http://www.kitware.com

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

         http://www.apache.org/licenses/LICENSE-2.0.txt

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
=========================================================================*/

$this->declareVars('form', 'pageTitle');
$this->headTitle(htmlspecialchars($this->pageTitle, ENT_QUOTES, 'UTF-8'));
?>

<div class="viewMain">
    <h1><?php echo htmlspecialchars($this->pageTitle, ENT_QUOTES, 'UTF-8'); ?></h1>
    <p>This module requires either the GD or ImageMagick PHP extension or the ImageMagick program.</p>
    <ul>
        <li>To install the ImageMagick program: <a href="http://www.imagemagick.org/">www.imagemagick.org</a>.</li>
        <li>To create a PDF thumbnail, you need Ghostscript: <a href="http://www.ghostscript.com/">www.ghostscript.com</a>.
        </li>
        <li>To create a video thumbnail, you need the codecs of the video.</li>
        <li>To create thumbnails for .nrrd and .mha 2D or 3D image files, you need Thumbnailer, a <a href="http://www.simpleitk.org/">Simple ITK</a>-based thumbnail program. Thumbnailer can be downloaded for many platforms <a href="http://midas3.kitware.com/midas/folder/5750">here</a>. Specify the location of the Thumbnailer executable below.</li>
    </ul>
    <?php echo $this->form; ?>
    <p><a href="<?php $this->url(array('controller' => 'admin', 'action' => 'index')); ?>#tabs-modules">&laquo; Back to Modules Administration</a></p>
</div>
