<?php
/*=========================================================================
 MIDAS Server
 Copyright (c) Kitware SAS. 26 rue Louis Guérin. 69100 Villeurbanne, FRANCE
 All rights reserved.
 More information http://www.kitware.com

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

         http://www.apache.org/licenses/LICENSE-2.0.txt

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
=========================================================================*/
?>
<link type="text/css" rel="stylesheet" href="<?php echo $this->moduleWebroot?>/public/css/index/index.index.css" />
<?php
$this->headScript()->appendFile($this->moduleWebroot . '/public/js/index/index.index.js');
?>
<div class="viewMain">
  <h2>MIDAS Web API</h2>

  The api will send you a REST response at the following URL:<br/>
  <pre><?php echo $this->serverURL.$this->webroot?>/api/rest?method=METHOD_NAME</pre>
  <br/>
    The api will send you a JSON response at the following URL:<br/>
  <pre><?php echo $this->serverURL.$this->webroot?>/api/json?method=METHOD_NAME</pre>

  <div class="api.listmethods" id="api.listmethods">
    Available methods:
    <ul class="listmethods">
      <?php
      foreach( $this->data['api.listmethods'] as $methodname )
        {
        echo "<li class='methodListElement'>".$methodname." <a class='showHideHelp'>?</a></li>";
        if(isset($this->help[$methodname]))
          {
          echo "<div class='helpContent'>";
          echo $this->help[$methodname]['description'].'<br/>';
          if(!empty($this->help[$methodname]['params']))
            {
            echo '<b>Parameters</b>';
            foreach($this->help[$methodname]['params'] as $key => $value)
              {
              echo '<ul>';
              echo "<li><b>{$key}</b> - {$value}</li>";
              echo '</ul>';
              }
            }
          if(!empty($this->help[$methodname]['return']))
            {
            echo '<b>Return</b> - '.$this->help[$methodname]['return'];
            }
          if(!empty($this->help[$methodname]['example']))
            {
            echo '<br/><b>Examples</b>';
            foreach($this->help[$methodname]['example'] as $key => $value)
              {
              echo '<ul>';
              echo "<li><b>{$value}</b> - {$key}</li>";
              echo '</ul>';
              }
            }
          echo "</div>";
          }
        }
      ?>
    </ul>
    </div>
</div>
