<link type="text/css" rel="stylesheet" href="<?php echo $this->coreWebroot?>/public/css/common/common.feed.css" />

<?php
  $this->headScript()->appendFile($this->coreWebroot.'/public/js/common/common.feed.js');
?>

<?
  $feeds=$this->feeds;
  if(!isset($feeds)||empty($feeds))
    {
    return;
    }

  echo "<div class='feedContainer'>";
  foreach($feeds as $key => $feed)
    {
    echo "<div class='feedElement'  element='{$feed->getKey()}'>";
    echo createFeedElement($this,$feed);
    echo "</div>";
    }
  echo "</div>";

  function createFeedElement(&$view,$feed)
    {
    $type=$feed->getType();
    if($feed->policy==2)
      {
      echo "<div class='feedDelete'>";
      echo "<img class='feedDeleteLink' element='{$feed->getKey()}' src='{$view->coreWebroot}/public/images/icons/close.png' alt=''/>";
      echo "</div>";
      }
    echo "<div class='feedUserImage'>";
    $thumbnail=$feed->getUser()->getThumbnail();
    if(!empty($thumbnail))
      {
      echo "<img class='thumbnailSmall' src='{$view->webroot}/{$thumbnail}' alt=''/>";
      }
    else
      {
      echo "<img class='thumbnailSmall' src='{$view->coreWebroot}/public/images/icons/unknownUser.png' alt=''/>";
      }
    echo "</div>";
    echo "<div class='feedInfo'>";
    echo $view->linkuser($feed->getUser()).' ';
    switch($type)
      {
      case MIDAS_FEED_CREATE_COMMUNITY:
        echo "{$view->t("added the community")} <a href='{$view->webroot}/community/{$feed->getRessource()->getKey()}'>".trimName($feed->getRessource()->getName())."</a>";
        break;
      case MIDAS_FEED_UPDATE_COMMUNITY:
      case MIDAS_FEED_CREATE_FOLDER:
      case MIDAS_FEED_CREATE_ITEM:
        echo "{$view->t("added the item")} <a href='{$view->webroot}/item/{$feed->getRessource()->getKey()}'>".trimName($feed->getRessource()->getName())."</a>";
        break;
      case MIDAS_FEED_CREATE_LINK_ITEM:
        echo "{$view->t("added the link")} <a href='{$view->webroot}/item/{$feed->getRessource()->getKey()}'>".trimName($feed->getRessource()->getName())."</a>";
        break;
      case MIDAS_FEED_CREATE_REVISION:
        echo "{$view->t("added a new revision to")} <a href='{$view->webroot}/item/{$feed->getRessource()->getItem()->getKey()}'>".trimName($feed->getRessource()->getItem()->getName())."</a>";
        break;
      case MIDAS_FEED_CREATE_USER:
        echo "{$view->t("registered")}";
        break;
      case MIDAS_FEED_DELETE_COMMUNITY:
      case MIDAS_FEED_DELETE_FOLDER:
      case MIDAS_FEED_DELETE_ITEM:
      default:
        break;
      }
    echo "</div>";
    echo "<div class='feedDate'>";
    echo  $view->Dateago(strtotime($feed->getDate()));
    echo "</div>";
    echo "<div style='clear:left;'></div>";
    }

    function trimName($name)
      {
      if(strlen($name)>35)
        {
        $name=substr($name,0, 10).'...'.substr($name,strlen($name)-35);
        }
      return $name;
      }
    
 ?>

