<?php
/*=========================================================================
 MIDAS Server
 Copyright (c) Kitware SAS. 26 rue Louis Guérin. 69100 Villeurbanne, FRANCE
 All rights reserved.
 More information http://www.kitware.com

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

         http://www.apache.org/licenses/LICENSE-2.0.txt

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
=========================================================================*/
?>
<link type="text/css" rel="stylesheet" href="<?php echo $this->coreWebroot?>/public/css/common/common.feed.css" />

<?php
  $this->headScript()->appendFile($this->coreWebroot.'/public/js/common/common.feed.js');

  if(!function_exists('createFeedElement'))
    {
    function createFeedElement(&$view, $feed)
      {
      $type=$feed->getType();
      if($feed->policy == 2)
        {
        echo "<div class='feedDelete'>";
        echo "<img class='feedDeleteLink' qtip='".$view->t('Delete the post')."' element='{$feed->getKey()}' src='{$view->coreWebroot}/public/images/icons/close.png' alt=''/>";
        echo "</div>";
        }

      if(!isset($view->disableFeedImages))
        {
        echo "<div class='feedUserImage'>";
        $thumbnail=$feed->getUser()->getThumbnail();

        echo $view->userthumbnail($thumbnail);
        echo "</div>";
        }
      echo "<div class='feedInfo'>";
      echo $view->linkuser($feed->getUser()).' ';
      switch($type)
        {
        case MIDAS_FEED_CREATE_COMMUNITY:
          echo "{$view->t("added the community")} <a href='{$view->webroot}/community/{$feed->getRessource()->getKey()}'>".$view->slicename($feed->getRessource()->getName(), 30)."</a>";
          break;
        case MIDAS_FEED_COMMUNITY_INVITATION:
          if($view->loggedUser && $view->loggedUser->getKey() == $feed->getRessource()->getUser()->getKey())
            {
            echo $view->t('invited you to the community');
            }
          else
            {
            echo $view->t('invited').' '.$view->linkuser($feed->getRessource()->getUser()).' '.$view->t('to the community');
            }
          echo  " <a href='{$view->webroot}/community/{$feed->getRessource()->getCommunity()->getKey()}'>".$view->slicename($feed->getRessource()->getCommunity()->getName(), 30)."</a>";
          break;
        case MIDAS_FEED_UPDATE_COMMUNITY:
        case MIDAS_FEED_CREATE_FOLDER:
        case MIDAS_FEED_CREATE_ITEM:
          echo "{$view->t("added the item")} <a  href='{$view->webroot}/item/{$feed->getRessource()->getKey()}'>".$view->slicename($feed->getRessource()->getName(), 30)."</a>";
          break;
        case MIDAS_FEED_CREATE_LINK_ITEM:
          echo "{$view->t("added the link")} <a href='{$view->webroot}/item/{$feed->getRessource()->getKey()}'>".$view->slicename($feed->getRessource()->getName(), 30)."</a>";
          break;
        case MIDAS_FEED_CREATE_REVISION:
          echo "{$view->t("added a new revision to")} <a href='{$view->webroot}/item/{$feed->getRessource()->getItem()->getKey()}'>".$view->slicename($feed->getRessource()->getItem()->getName(), 30)."</a>";
          break;
        case MIDAS_FEED_CREATE_USER:
          echo "{$view->t("registered")}";
          break;
        case MIDAS_FEED_DELETE_COMMUNITY:
        case MIDAS_FEED_DELETE_FOLDER:
        case MIDAS_FEED_DELETE_ITEM:
        default:
          break;
        }
      echo "</div>";
      echo "<div class='feedDate'>";
      echo  $view->Dateago(strtotime($feed->getDate()));
      echo "</div>";
      echo "<div style='clear:left;'></div>";
      }
    }

  $feeds=$this->feeds;
  if(!isset($feeds)||empty($feeds))
    {
    echo $this->t("Feed is currently empty. It could be that the community is not very active
          or you may not have the permissions to see the feeds.");
    return;
    }

  echo "<div class='feedContainer'>";
  foreach($feeds as $key => $feed)
    {
    echo "<div class='feedElement'  element='{$feed->getKey()}'>";
    if(isset($this->lastFeedVisit) && $this->lastFeedVisit < strtotime($feed->getDate()))
      {
      echo "<img class='newFeedElement'  src='{$this->coreWebroot}/public/images/icons/new.png' alt=''/>";
      }
    createFeedElement($this, $feed);
    echo "</div>";
    }
  echo "</div>";

