<?php
/*=========================================================================
 MIDAS Server
 Copyright (c) Kitware SAS. 26 rue Louis Guérin. 69100 Villeurbanne, FRANCE
 All rights reserved.
 More information http://www.kitware.com

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

         http://www.apache.org/licenses/LICENSE-2.0.txt

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
=========================================================================*/
?>
    <link type="text/css" rel="stylesheet"
          href="<?php echo $this->coreWebroot ?>/public/css/common/common.listfiles.css"/>

<?php
if (!function_exists('createFileElement')) {
    function createFileElement(&$view, $file)
    {
        echo "<div class='feedUserImage'>";
        echo "<img class='thumbnailSmall' src='{$view->coreWebroot}/public/images/icons/document-big.png' alt=''/>";
        echo "</div>";
        echo "<div class='fileInfo'>";
        echo " <a href='{$view->webroot}/item/{$view->escape($file->getKey())}'>".trimFileName($view->escape($file->getName()))."</a>";
        echo "</div>";
        echo "<div class='fileDate'>";
        echo $view->dateago(strtotime($file->policy_date));
        echo "</div>";
        echo "<div style='clear:left;'></div>";
    }
}

if (!function_exists('trimFileName')) {
    function trimFileName($name)
    {
        if (strlen($name) > 35) {
            $name = substr($name, 0, 10).'...'.substr($name, strlen($name) - 35);
        }

        return $name;
    }
}

$files = $this->listFiles;
if (empty($files)) {
    return;
}

echo "<div class='listFilesContainer'>";
foreach ($this->listFiles as $key => $file) {
    echo "<div class='fileElement'  element='{$this->escape($file->getKey())}'>";
    createFileElement($this, $file);
    echo "</div>";
}
echo "</div>";
