<?php
/*=========================================================================
MIDAS Server
Copyright (c) Kitware SAS. 20 rue de la Villette. All rights reserved.
69328 Lyon, FRANCE.

See Copyright.txt for details.
This software is distributed WITHOUT ANY WARRANTY; without even
the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE.  See the above copyright notices for more information.
=========================================================================*/
?>
<link type="text/css" rel="stylesheet" href="<?php echo $this->coreWebroot?>/public/css/common/common.listfiles.css" />

<?php
  $this->headScript()->appendFile($this->coreWebroot.'/public/js/common/common.listfiles.js');

   if(!function_exists('createFileElement'))
    {
    function createFileElement(&$view,$file)
      {
      echo "<div class='feedUserImage'>";
      echo "<img class='thumbnailSmall' src='{$view->coreWebroot}/public/images/icons/document-big.png' alt=''/>";
      echo "</div>";
      echo "<div class='fileInfo'>";
      echo " <a href='{$view->webroot}/item/{$file->getKey()}'>".trimFileName($file->getName())."</a>";
      echo "</div>";
      echo "<div class='fileDate'>";
      echo  $view->Dateago(strtotime($file->policy_date));
      echo "</div>";
      echo "<div style='clear:left;'></div>";
      }
    }

   if(!function_exists('trimFileName'))
    {
    function trimFileName($name)
      {
      if(strlen($name)>35)
        {
        $name=substr($name,0, 10).'...'.substr($name,strlen($name)-35);
        }
      return $name;
      }
    }

  $files=$this->listFiles;
  if(empty($files))
    {
    return;
    }

  echo "<div class='listFilesContainer'>";
  foreach($this->listFiles as $key => $file)
    {
    echo "<div class='fileElement'  element='{$file->getKey()}'>";
    echo createFileElement($this,$file);
    echo "</div>";
    }
  echo "</div>";


?>
