<?php
/**
 * File picker - display a tree view to choose a file or a folder on the local computer
 * All the html elements have the prefix 'fp-' (for File Picker)
 * @param $script : php script to call (default: 'admin/filePicker')
 * @param $fileFilter : JS regular expression to validate filenames (default: '' ie accept all)
 *                      Use '[.]xml$' to allow only xml file.
 *                      More resources about JS regular expression:
 *                      http://www.javascriptkit.com/javatutors/redev2.shtml
 *                      http://www.regular-expressions.info/javascript.html
 *                      http://www.regular-expressions.info/javascriptexample.html
 * @param $fileFilterErrorMsg : Message to display when regular expression is false
 * @param $destSelector : jquery selector to insert the filename when user click on 'OK'
 *
**/
?>
<?php
  // assign unique identifier to this element
  if(!isset($this->id))
    {
    throw new Zend_Exception("variable id is not set");
    }

  if( !isset($this->script) ) $this->script = $this->webroot.'/admin/serversidefilechooser';
  if( !isset($this->width) ) $this->width = 400;
  if( !isset($this->height) ) $this->height = 400;
  if( !isset($this->fileFilter) ) $this->fileFilter = '';
  if( !isset($this->errorMessage) ) $this->errorMessage = 'Incorrect file type';
  if( !isset($this->destSelector) ) $this->destSelector = 'body>XX'; // default selector return 0 elements
?>

<input type="hidden" id="serversidefilechooser-id" value="<?php echo $this->id; ?>">
<input type="hidden" id="serversidefilechooser-errorMessage" value="<?php echo $this->errorMessage; ?>">
<input type="hidden" id="serversidefilechooser-destSelector" value="<?php echo $this->destSelector; ?>">
<input type="hidden" id="serversidefilechooser-fileFilter" value="<?php echo $this->fileFilter; ?>">
<input type="hidden" id="serversidefilechooser-script" value="<?php echo $this->script; ?>">

<style>
.fp-container {
      }

/* The fp-XXX-pannel is the div that gets lighted */
#fp-<?php echo $this->id?>-panel {
        display:none;
        position:fixed;
        top:100px;
        left:50%;
        margin-left:-200px;
        width:<?php echo $this->width?>px;
        background:#FFFFFF;
        padding:10px 15px 10px 15px;
        border:2px solid #CCCCCC;
        z-index:101;
        }

/* The fp-XXX-pannel is the div that covers the rest of the page */
#fp-<?php echo $this->id?>-background {
         display:none;
         background:#000000;
         opacity:0.5;
         filter:alpha(opacity=90);  
         position:absolute;  
         top:0px;  
         left:0px;  
         min-width:100%;  
         min-height:100%;  
         z-index:100;  
        } 
       
.fp-fileTree {
        width: <?php echo $this->width?>px;
        height: 300px;
        border-top: solid 1px #BBB;
        border-left: solid 1px #BBB;
        border-bottom: solid 1px #FFF;
        border-right: solid 1px #FFF;
        background: #FFF;
        overflow: scroll;
        padding: 5px;
        text-align: left;
      }

.fp-inputFile {
        position: relative;
        width: <?php echo $this->width+5?>px;
      }

.fp-inputButton {
        position: relative;
        float: left;
        display: block;
        width: 100px;
        margin: 3px 40px;
      }

.fp-open {
      }
</style>
<?php
  $this->headScript()->appendFile($this->coreWebroot.'/public/js/jquery/jquery.filetree.js');
  $this->headScript()->appendFile($this->coreWebroot.'/public/js/element/serversidefilechooser.js');
?>

<!--  <input type="submit" id="fp-<?php echo $this->id?>-open" class="fp-open" value="Choose"></input>  -->
<div id="fp-<?php echo $this->id?>-container" class="fp-container">
  <div id="fp-<?php echo $this->id?>-panel">
    <div id="fp-<?php echo $this->id?>-fileTree" class="fp-fileTree"></div>
    <input id="fp-<?php echo $this->id?>-inputFile" class="fp-inputFile" type="text" disabled></input>
    <input id="fp-<?php echo $this->id?>-inputButtonCancel" class="fp-inputButton" type="submit" value="Cancel"></input>
    <input id="fp-<?php echo $this->id?>-inputButtonOK" class="fp-inputButton" type="submit" value="Ok"></input>
  </div>
</div>
