<?php
/*=========================================================================
MIDAS Server
Copyright (c) Kitware SAS. 20 rue de la Villette. All rights reserved.
69328 Lyon, FRANCE.

See Copyright.txt for details.
This software is distributed WITHOUT ANY WARRANTY; without even
the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE.  See the above copyright notices for more information.
=========================================================================*/
$this->headScript()->appendFile($this->coreWebroot.'/public/js/jquery/jquery.form.js');
$this->headScript()->appendFile($this->moduleWebroot.'/public/js/config/config.index.js');
?>

<link type="text/css" rel="stylesheet" href="<?php echo $this->moduleWebroot?>/public/css/config/config.index.css" />

<div class="viewMain">
  <div class ="genericWrapperTopRight">
    <div style="float:right;margin-right:2px;" class="genericBigButton ">
      <a href="<?php echo $this->webroot; ?>/admin#tabs-modules">
        <img style="float:left;margin-right:2px;"
             alt=""
             src="<?php echo $this->coreWebroot;?>/public/images/icons/back.png"/>
        Back
      </a>
    </div>
  </div>
  <h3>Multi-Factor Authentication Configuration</h3>
  <p>Configuration of One-Time Pass (OTP) devices can be done on the
    "My Account" page. Administrators can configure this information for any
    user.</p>
  <p>Currently, configuration of multi-factor authentication is dependent on the
    PAM configuration of the host machine and is thus restricted to hosts
    running PAM. To this point, the verification of the OTP is entirely
    delegated to PAM and custom configuration should take place there.</p>

  <form class="genericForm" id="configForm" method="POST" action="<?php echo $this->webroot?>/mfa/config/submit">
    <div>
      <input name="userOtpControl" type="checkbox"
        <?php if($this->userOtpControl) { echo 'checked="checked" '; } ?> />
      Allow users to configure their own two-factor authentication settings
      <div class="formElement">
        <label for="radiusServer">The IP or hostname of the RADIUS server</label>
        <input id="radiusServer" name="radiusServer" value="<?php echo $this->radiusServer;?>" autofocus />
      </div>
      <div class="formElement">
        <label for="radiusPort">The port of the RADIUS server</label>
        <input id="radiusPort" name="radiusPort" value="<?php echo $this->radiusPort;?>" />
      </div>
      <div class="formElement">
        <label for="radiusPassword">The password of the RADIUS server</label>
        <input type="password" id="radiusPassword" name="radiusPassword" value="<?php echo $this->radiusPassword;?>" />
      </div>
      <div class="formElement">
        <label for="radiusTimeout">The timeout when connecting to the RADIUS server</label>
        <input id="radiusTimeout" name="radiusTimeout" value="<?php echo $this->radiusTimeout;?>" />
      </div>
      <div class="formElement">
        <label for="radiusMaxTries">The maximum number of tries when connecting to the RADIUS server</label>
        <input id="radiusMaxTries" name="radiusMaxTries" value="<?php echo $this->radiusMaxTries;?>" />
      </div>
    </div>
    <div class="saveButton">
      <input type="submit" value="Save" />
    </div>
  </form>
</div>

