<?php
/*=========================================================================
 MIDAS Server
 Copyright (c) Kitware SAS. 26 rue Louis Guérin. 69100 Villeurbanne, FRANCE
 All rights reserved.
 More information http://www.kitware.com

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

         http://www.apache.org/licenses/LICENSE-2.0.txt

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
=========================================================================*/

echo '<script type="text/javascript" src="'.$this->moduleWebroot.'/public/js/config/config.usertab.js"></script>';
?>
<link type="text/css" rel="stylesheet" href="<?php echo $this->moduleWebroot ?>/public/css/config/config.usertab.css"/>

<form class="genericForm" id="mfaConfigForm" method="POST" action="<?php echo $this->webroot ?>/mfa/config/usersubmit">
    <input type="hidden" name="userId" value="<?php echo $this->escape($this->user->getKey()); ?>"/>

    <div class="useOtpCheckboxContainer">
        <input id="useOtpCheckbox" type="checkbox" name="useOtp" <?php if ($this->useOtp) {
            echo 'checked="checked" ';
        } ?> />
        Use a one-time password device for authentication
    </div>
    <table>
        <tr>
            <td>Type:</td>
            <td><select id="otpAlgorithmSelect" name="algorithm">
                    <?php foreach ($this->algList as $val => $text) {
                        echo '<option ';
                        if ($this->algorithm == $val) {
                            echo 'selected="selected" ';
                        }
                        echo 'value="'.$this->escape($val).'">'.$this->escape($text).'</option>';
                    }
                    ?>
                </select></td>
        </tr>

        <tr>
            <td>Key:</td>
            <td>
                <input id="otpSecret" type="text" name="secret" value="<?php echo $this->escape($this->secret); ?>"/>
            </td>
        </tr>

        <tr>
            <td>Token Length:</td>
            <td>
                <input id="otpLength" type="text" name="length" value="<?php echo $this->escape($this->length); ?>"/>
            </td>
        </tr>
    </table>
    <div>
        <input type="submit" value="Save" id="otpConfigSubmit"/>
    </div>
</form>
