<?php
/*=========================================================================
 MIDAS Server
 Copyright (c) Kitware SAS. 26 rue Louis Guérin. 69100 Villeurbanne, FRANCE
 All rights reserved.
 More information http://www.kitware.com

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

         http://www.apache.org/licenses/LICENSE-2.0.txt

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
=========================================================================*/
?>
<script type="text/javascript" src="<?php echo $this->coreWebroot ?>/public/js/jquery/jquery.form.js"></script>
<script type="text/javascript" src="<?php echo $this->coreWebroot ?>/public/js/licenses/licenses.index.js"></script>

<link type="text/css" rel="stylesheet"
      href="<?php echo $this->coreWebroot ?>/public/css/common/common.genericPage.css"/>
<link type="text/css" rel="stylesheet" href="<?php echo $this->coreWebroot ?>/public/css/licenses/licenses.index.css"/>

<span class="headerText">EXISTING LICENSES</span>

<div class="licenseList">
    <?php
    foreach ($this->licenses as $license) {
        echo '<div class="licenseContainer" element="'.$license->getKey().'">';
        echo '<form class="genericForm existingLicense" action="'.$this->webroot.'/licenses/save" method="POST">';
        echo '  <div><input class="licenseName" type="text" name="name" value="'.$license->getName().'" /></div>';
        echo '  <div><textarea class="licenseText" name="fulltext">'.htmlentities(
                $license->getFulltext()
            ).'</textarea></div>';
        echo '  <input type="hidden" name="licenseId" value="'.$license->getKey().'" />';
        echo '  <div><input class="globalButton" style="margin-left: 0;" type="submit" name="submit" value="Save" /></form>';
        echo '  <input element="'.$license->getKey(
            ).'" class="globalButton deleteLicense" style="margin-left: 10px;" type="button" value="Delete" />';
        echo '  </div>';
        echo '</div>';
    }
    ?>
</div>

<span class="headerText">CREATE NEW LICENSE</span>
<div class="licenseContainer">
    <form class="genericForm newLicense" action="<?php echo $this->webroot; ?>/licenses/create" method="POST">
        <div><input class="licenseName" type="text" name="name" value=""/>
        </div>
        <div><textarea class="licenseText" name="fulltext"></textarea></div>
        <div>
            <input class="globalButton" style="margin-left: 0;" type="submit" name="submit" value="Create"/>
        </div>
    </form>
</div>
