<?php
/*=========================================================================
MIDAS Server
Copyright (c) Kitware SAS. 20 rue de la Villette. All rights reserved.
69328 Lyon, FRANCE.

See Copyright.txt for details.
This software is distributed WITHOUT ANY WARRANTY; without even
the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE.  See the above copyright notices for more information.
=========================================================================*/
?>

<div class="viewMain">
  <h3>Instructions for Use</h3>
  <p>This module is intended to provide Readmes for communities as well as
      folders. The text of these readmes will be interpreted from
      <a href="http://daringfireball.net/projects/markdown/">Markdown</a>
      syntax and display in the info tab as well as below the hierarchical
      data view.</p>
  <p>For communities, place a file named readme, readme.txt, or readme.md
      (case insensitive) at the root of the "Public" folder.</p>
  <p>For folders, place a similarly named file at the root of the folder in
      question.</p>
</div>
