<?php
/*=========================================================================
 MIDAS Server
 Copyright (c) Kitware SAS. 26 rue Louis Guérin. 69100 Villeurbanne, FRANCE
 All rights reserved.
 More information http://www.kitware.com

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

         http://www.apache.org/licenses/LICENSE-2.0.txt

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
=========================================================================*/
?>
<div class="viewMain">
  <div class ="genericWrapperTopRight">
    <?php
    echo '<div style="float:right;margin-right:2px;" class="genericBigButton ">';
    echo "<a  href='{$this->webroot}/admin#tabs-modules'><img style='float:left;margin-right:2px;' alt='' src='{$this->coreWebroot}/public/images/icons/back.png'/>";
    echo $this->t('Back');
    echo "</a>";
    echo '</div>';
    ?>
  </div>
  <h3>Instructions for Use</h3>
  <p>This module is intended to provide Readmes for communities as well as
      folders. The text of these readmes will be interpreted from
      <a href="https://daringfireball.net/projects/markdown/syntax">Markdown</a>
      syntax and display in the info tab as well as below the hierarchical
      data view.</p>
  <p>For communities, place a file named readme, readme.txt, or readme.md
      (case insensitive) at the root of the "Public" folder.</p>
  <p>For folders, place a similarly named file at the root of the folder in
      question.</p>
</div>
