<?php
/*=========================================================================
 Midas Server
 Copyright Kitware SAS, 26 rue Louis Guérin, 69100 Villeurbanne, France.
 All rights reserved.
 For more information visit http://www.kitware.com/.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

         http://www.apache.org/licenses/LICENSE-2.0.txt

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
=========================================================================*/
?>
<script type="text/javascript" src="<?php echo $this->moduleWebroot; ?>/public/js/scalar/scalar.details.js"></script>
<link type="text/css" rel="stylesheet" href="<?php echo $this->moduleWebroot; ?>/public/css/scalar/scalar.details.css"/>

<input type="hidden" class="scalarId" value="<?php echo $this->escape($this->scalar->getKey()); ?>"/>

<div class="thisScalarInfo">
    <div class="sectionDivider"><span class="sectionTitle">Info</span></div>
    <table class="scalarInfoTable">
        <tbody>
        <tr>
            <th>Metric:</th>
            <td><span id="thisMetric"><?php echo $this->escape($this->scalar->getTrend()->getMetricName()); ?></span>
            </td>
        </tr>
        <tr>
            <th>Value:</th>
            <td><span id="thisValue"><?php echo $this->escape($this->scalar->getValue()).' '.$this->escape($this->scalar->getTrend()->getUnit(
                        )); ?></span>
            </td>
        </tr>
        <tr>
            <th>Submitted:</th>
            <td>
                <span id="thisSubmitTime"><?php echo $this->escape($this->scalar->getSubmitTime()); ?></span>
                <?php
                if ($this->submittedBy) {
                    echo ' by <a href="'.$this->webroot.'/user/'.$this->escape($this->submittedBy->getKey(
                        )).'">'.$this->escape($this->submittedBy->getFullName()).'</a> ';
                }
                if (!$this->scalar->getOfficial()) {
                    echo '(unofficial)';
                }
                ?>
            </td>
        </tr>
        <tr>
            <th>Revision:</th>
            <td>
                <span id="thisProducerRev"><?php echo $this->revisionHtml; ?></span>
            </td>
        </tr>
        <?php
        if ($this->scalar->getBranch()) {
            ?>
            <tr>
                <th>Branch:</th>
                <td><?php echo $this->escape($this->scalar->getBranch()); ?></td>
            </tr>
        <?php
        }
        if ($this->scalar->getBuildResultsUrl()) {
            ?>
            <tr>
                <th>Build Results:</th>
                <td>
                    <a target="_blank"
                       href="<?php echo $this->escape($this->scalar->getBuildResultsUrl()); ?>">Click here</a>
                </td>
            </tr>
        <?php
        }
        if ($this->extraUrls) {
            /** @var array $linkInfo */
            foreach ($this->extraUrls as $linkInfo) {
                echo '<tr><th>'.$this->escape($linkInfo['label']).':</th><td>';
                echo '<a target="_blank" href="'.$this->escape($linkInfo['href']).'">'.$this->escape($linkInfo['text']).'</a>';
                echo '</td></tr>';
            }
        }
        $htmlArray = Zend_Registry::get('notifier')->callback(
            'CALLBACK_TRACKER_SCALAR_DETAIL_INFO',
            array('scalar' => $this->scalar)
        );

        /** @var string $html */
        foreach ($htmlArray as $html) {
            if (!empty($html)) {
                echo $html;
            }
        }
        ?>
        </tbody>
    </table>
</div>

<?php
if (count($this->extraParams)) {
    ?>
    <div class="extraParams">
        <div class="sectionDivider">
            <span class="sectionTitle">Other Information</span></div>
        <table class="scalarInfoTable">
            <tbody>
            <?php
            /**
             * @var string $key
             * @var mixed $value
             */
            foreach ($this->extraParams as $key => $value) {
                echo '<tr><th>'.$this->escape($key).':</th><td>'.$this->escape($value).'</td></tr>';
            }
            ?>
            </tbody>
        </table>
    </div>
    <?php
}
?>

<div class="otherScalars">
    <div class="sectionDivider">
        <span class="sectionTitle">All values for this submission</span></div>
    <table class="otherScalarTable">
        <tbody>
        <?php
        /**
         * @var string $metricName
         * @var float $value
         */
        foreach ($this->otherValues as $metricName => $value) {
            echo '<tr><th>'.$this->escape($metricName).':</th><td>'.$this->escape($value).'</td></tr>';
        }
        ?>
        </tbody>
    </table>
</div>

<div class="resultItems">
    <div class="sectionDivider"><span class="sectionTitle">Result items</span>
    </div>
    <?php
    /** @var array $result */
    foreach ($this->resultItems as $result) {
        /** @var ItemDao $itemDao */
        $itemDao = $result['item'];
        echo '<div class="resultItemContainer"><span class="resultItemLabel">'.$this->escape($result['label']).':</span> ';
        echo '<a element="'.$this->escape($itemDao->getKey()).'" class="resultItemLink" href="'.$this->webroot.'/item/'.$this->escape($itemDao->getKey(
            )).'" ';
        echo 'thumbnail="'.$this->escape($itemDao->getThumbnailId()).'">'.$this->escape($itemDao->getName()).'</a>';
        echo '</div>';
    }
    if (empty($this->resultItems)) {
        echo '<span class="itemLinkNone">No result items submitted</span>';
    }
    ?>

</div>

<div class="bottomButtons">
    <?php
    if ($this->isAdmin) {
        ?>
        <input type="button" class="globalButton" id="deleteScalar" value="Delete"/>
        <?php
    }
    ?>
</div>
