<?php
/*=========================================================================
 MIDAS Server
 Copyright (c) Kitware SAS. 26 rue Louis Guérin. 69100 Villeurbanne, FRANCE
 All rights reserved.
 More information http://www.kitware.com

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

         http://www.apache.org/licenses/LICENSE-2.0.txt

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
=========================================================================*/
?>
<script type="text/javascript" src="<?php echo $this->moduleWebroot?>/public/js/scalar/scalar.details.js" />
<link type="text/css" rel="stylesheet" href="<?php echo $this->moduleWebroot?>/public/css/scalar/scalar.details.css" />

<input type="hidden" class="scalarId" value="<?php echo $this->scalar->getKey(); ?>" />

<div class="thisScalarInfo">
  <div class="sectionDivider"><span class="sectionTitle">Info</span></div>
  <table class="scalarInfoTable"><tbody>
    <tr><th>Metric:</th><td><span id="thisMetric"><?php echo $this->scalar->getTrend()->getMetricName(); ?></span></td></tr>
    <tr><th>Value:</th><td><span id="thisValue"><?php echo $this->scalar->getValue().' '.$this->scalar->getTrend()->getUnit(); ?></span></td></tr>
    <tr><th>Submitted:</th>
        <td>
          <span id="thisSubmitTime"><?php echo $this->scalar->getSubmitTime(); ?></span>
          <?php
          if($this->submittedBy)
            {
            echo ' by <a href="'.$this->webroot.'/user/'.$this->submittedBy->getKey().'">'.$this->submittedBy->getFullName().'</a> ';
            }
          if(!$this->scalar->getOfficial())
            {
            echo '(unofficial)';
            }
          ?>
        </td>
    </tr>
    <tr>
      <th>Revision:</th>
      <td><span id="thisProducerRev"><?php echo $this->revisionHtml; ?></span></td>
    </tr>
    <?php
    if($this->scalar->getBranch())
      { ?>
      <tr>
        <th>Branch:</th>
        <td><?php echo $this->scalar->getBranch();?></td>
      </tr>
    <?php
      }
    if($this->scalar->getBuildResultsUrl())
      { ?>
      <tr>
        <th>Build Results:</th>
        <td>
          <a target="_blank"
             href="<?php echo $this->scalar->getBuildResultsUrl();?>">Click here</a>
        </td>
      </tr>
    <?php
      }
      if ($this->extraUrls)
        {
        foreach($this->extraUrls as $linkInfo)
          {
          echo '<tr><th>'.$linkInfo['label'].':</th><td>';
          echo '<a target="_blank" href="'.$linkInfo['href'].'">'.$linkInfo['text'].'</a>';
          echo '</td></tr>';
          }
        }
    ?>
  </tbody></table>
</div>

<?php if(count($this->extraParams))
  { ?>
  <div class="extraParams">
    <div class="sectionDivider"><span class="sectionTitle">Other Information</span></div>
    <table class="scalarInfoTable"><tbody>
    <?php foreach($this->extraParams as $key => $value)
      {
      echo '<tr><th>'.$key.':</th><td>'.$value.'</td></tr>';
      }
    ?>
  </tbody></table>
  </div>
<?php } ?>

<div class="otherScalars">
  <div class="sectionDivider"><span class="sectionTitle">All values for this submission</span></div>
  <table class="otherScalarTable"><tbody>
  <?php
  foreach($this->otherValues as $metricName => $value)
    {
    echo '<tr><th>'.$metricName.':</th><td>'.$value.'</td></tr>';
    }
  ?>
  </tbody></table>
</div>

<div class="resultItems">
  <div class="sectionDivider"><span class="sectionTitle">Result items</span></div>
  <?php
  foreach($this->resultItems as $result)
    {
    $item = $result['item'];
    echo '<div class="resultItemContainer"><span class="resultItemLabel">'.$result['label'].':</span> ';
    echo '<a element="'.$item->getKey().'" class="resultItemLink" href="'.$this->webroot.'/item/'.$item->getKey().'" ';
    echo 'thumbnail="'.$item->getThumbnailId().'">'.$item->getName().'</a>';
    echo '</div>';
    }
  if(count($this->resultItems) === 0)
    {
    echo '<span class="itemLinkNone">No result items submitted</span>';
    }
  ?>

</div>

<div class="bottomButtons">
<?php if($this->isAdmin)
  { ?>
  <input type="button" class="globalButton" id="deleteScalar" value="Delete"/>
<?php
  }
?>
</div>
