<?php
/*=========================================================================
MIDAS Server
Copyright (c) Kitware SAS. 20 rue de la Villette. All rights reserved.
69328 Lyon, FRANCE.

See Copyright.txt for details.
This software is distributed WITHOUT ANY WARRANTY; without even
the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE.  See the above copyright notices for more information.
=========================================================================*/
?>
<script type="text/javascript" src="<?php echo $this->moduleWebroot?>/public/js/scalar/scalar.details.js" />
<link type="text/css" rel="stylesheet" href="<?php echo $this->moduleWebroot?>/public/css/scalar/scalar.details.css" />

<input type="hidden" class="scalarId" value="<?php echo $this->scalar->getKey(); ?>" />

<div class="thisScalarInfo">
  <div class="sectionDivider"><span class="sectionTitle">Info</span></div>
  <table class="scalarInfoTable"><tbody>
    <tr><th>Metric:</th><td><span id="thisMetric"><?php echo $this->scalar->getTrend()->getMetricName(); ?></span></td></tr>
    <tr><th>Value:</th><td><span id="thisValue"><?php echo $this->scalar->getValue().' '.$this->scalar->getTrend()->getUnit(); ?></span></td></tr>
    <tr><th>Submitted:</th>
        <td>
          <span id="thisSubmitTime"><?php echo $this->scalar->getSubmitTime(); ?></span>
          <?php
          if($this->submittedBy)
            {
            echo ' by <a href="'.$this->webroot.'/user/'.$this->submittedBy->getKey().'">'.$this->submittedBy->getFullName().'</a> ';
            }
          if(!$this->scalar->getOfficial())
            {
            echo '(unofficial)';
            }
          ?>
        </td>
    </tr>
    <tr><th>Revision:</th><td><span id="thisProducerRev"><?php echo $this->revisionHtml; ?></span></td></tr>
  </tbody></table>
</div>

<div class="otherScalars">
  <div class="sectionDivider"><span class="sectionTitle">All values for this submission</span></div>
  <table class="otherScalarTable"><tbody>
  <?php
  foreach($this->otherValues as $metricName => $value)
    {
    echo '<tr><th>'.$metricName.':</th><td>'.$value.'</td></tr>';
    }
  ?>
  </tbody></table>
</div>

<div class="resultItems">
  <div class="sectionDivider"><span class="sectionTitle">Result items</span></div>
  <?php
  foreach($this->resultItems as $result)
    {
    $item = $result['item'];
    echo '<div class="resultItemContainer"><span class="resultItemLabel">'.$result['label'].':</span> ';
    echo '<a element="'.$item->getKey().'" class="resultItemLink" href="'.$this->webroot.'/item/'.$item->getKey().'" ';
    echo 'thumbnail="'.$item->getThumbnailId().'">'.$item->getName().'</a>';
    echo '</div>';
    }
  if(count($this->resultItems) === 0)
    {
    echo '<span class="itemLinkNone">No result items submitted</span>';
    }
  ?>
  
</div>

<div class="bottomButtons">
<?php if($this->isAdmin)
  { ?>
  <input type="button" class="globalButton" id="deleteScalar" value="Delete"/>
<?php
  }
?>
</div>
