<?php 
/*=========================================================================
MIDAS Server
Copyright (c) Kitware SAS. 20 rue de la Villette. All rights reserved.
69328 Lyon, FRANCE.

See Copyright.txt for details.
This software is distributed WITHOUT ANY WARRANTY; without even
the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE.  See the above copyright notices for more information.
=========================================================================*/
echo '<script type="text/javascript" src="' . $this->moduleWebroot . '/public/js/config/config.agreementtab.js"></script>';
?>

<form id="createAgreementForm" class="genericForm" method="<?php echo $this->agreementForm['method']?>"  action="<?php echo $this->agreementForm['action']?>">
  <div>
    <label for="agreement"><?php echo $this->t('Community Agreement')?></label>
    <?php echo $this->agreementForm['agreement']?>
  </div>
  <div>
    <?php echo $this->agreementForm['submit']?>
  </div>
</form>