<?php
/*=========================================================================
 Midas Server
 Copyright Kitware SAS, 26 rue Louis Guérin, 69100 Villeurbanne, France.
 All rights reserved.
 For more information visit http://www.kitware.com/.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

         http://www.apache.org/licenses/LICENSE-2.0.txt

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
=========================================================================*/

$this->declareVars('jobs', 'jobsErrors', 'pageTitle');
$this->headTitle($this->escape($this->pageTitle));
?>

<div class="viewMain">
    <h1><?php echo $this->escape($this->pageTitle); ?></h1>
    <p>Visit the Midas Platform
    <a href="http://www.kitware.com/midaswiki/index.php/Documentation/Latest/User/Administration/ConfigurePlugins#Task_Scheduler">wiki
    pages</a> for instructions on completing the installation of the task scheduler.</a></p>
    <?php
    if (!empty($this->jobs)) {
        ?>
        <h2>Scheduled Tasks</h2>
        <table>
            <tr>
                <th>Name</th>
                <th>Date</th>
                <th>Parameters (JSON)</th>
                <th>Actions</th>
            </tr>
            <?php
            foreach ($this->jobs as $job) {
                ?>
                <tr>
                    <td>
                        <?php echo $this->escape($job->getTask()); ?>
                    </td>
                    <td>
                        <?php echo $this->escape($job->getFireTime()); ?>
                    </td>
                    <td qtip='<?php echo $this->escape(str_replace("'", '"', $job->getParams())); ?>'>
                        <?php echo $this->escape(substr($job->getParams(), 0, 30)); ?>
                    </td>
                    <td>
                        <a href="<?php echo $this->url(array('module' => 'scheduler', 'controller' => 'run', 'action' => 'index')); ?>?id=<?php echo $this->escape($job->getKey()); ?>">Run
                            Now</a>
                    </td>
                </tr>
            <?php
            }
            ?>
        </table>
    <?php
    }
    if (!empty($this->jobsErrors)) {
        ?>
        <h2>Last Failed Tasks</h2>
        <table>
            <tr>
                <th>Name</th>
                <th>Date</th>
                <th>Parameters (JSON)</th>
            </tr>
            <?php
            foreach ($this->jobsErrors as $job) {
                ?>
                <tr>
                    <td>
                        <?php echo $this->escape($job->getTask()); ?>
                    </td>
                    <td>
                        <?php echo $this->escape($job->getFireTime()); ?>
                    </td>
                    <td qtip="<?php echo $this->escape($job->getParams()); ?>">
                        <?php echo $this->escape(substr($job->getParams(), 0, 30)); ?>
                    </td>
                </tr>
            <?php
            }
            ?>
        </table>
    <?php
    }
    ?>
    <p><a href="<?php echo $this->url(array('controller' => 'admin', 'action' => 'index'), 'default'); ?>#tabs-modules">&laquo; Back to Modules Administration</a></p>
</div>

