<link type="text/css" rel="stylesheet" href="<?php echo $this->webroot?>/public/css/common/common.genericPage.css" />
<link type="text/css" rel="stylesheet" href="<?php echo $this->webroot?>/public/css/item/item.view.css" />
<link type="text/css" rel="stylesheet" href="<?php echo $this->webroot?>/public/css/common/common.browser.css" />

<div class="viewMain">
  <div class="genericThumbnail">
  <?php
    echo "<img src='{$this->webroot}/public/images/icons/document-big.png' alt=''/>";
  ?>
  </div>
  <div class="genericInfo">
    <div class="genericName"><?php   echo $this->itemDao->getName();  ?></div>
  </div>
  
  
  <table id="browseTable" class="midasTree">
    <thead>
      <tr>
        <th ><?php echo $this->t('Revision');?></th>
        <th ><?php echo $this->t('Uploaded');?></th>
        <th ><?php echo $this->t('Changes');?></th>
      </tr>
    </thead>
    <tbody>
      <?php
      $node=1;
      foreach($this->itemDao->revisions as $revision)
        {
        echo "<tr>";
        echo "  <td ><a href='{$this->webroot}/download/?items={$this->itemDao->getKey()},{$revision->getRevision()}'>Revision {$revision->getRevision()}</a></td>";
        echo "  <td>{$this->Date->ago($revision->getDate(),false)} {$this->t('by')} <a href='{$this->webroot}/user/{$revision->getUserId()}'>{$revision->getUser()->getFullName()}</a></td>";
        echo "  <td>{$revision->getChanges()}</td>";
        echo "</tr>";
        $node++;
        }  
      ?>        
    </tbody>
  </table>
</div>
<div class="viewSideBar">
  <div class="sideElementFirst viewAction">
    <h1>Actions</h1>
    <ul>
      <?php 
      echo 
      "
      <li>
        <a  href='{$this->webroot}/download/?items={$this->itemDao->getKey()}'>{$this->t('Download')}</a>
      </li>        
        ";
      ?>
    </ul>
  </div>
  <div class="sideElementLast viewInfo">
    <h1>Info</h1>    
    <table>  
      <tbody>
        <tr>    
          <td><?php echo $this->t('Created')?></td>
          <td><?php echo $this->itemDao->creation?></td> 
        </tr>
        <tr>   
          <td><?php echo $this->t('Uploaded by');?></td>  
          <td><a href="/Midas/MIDAS3/user/<?php echo $this->itemDao->lastrevision->getUser()->getKey()?>"><?php echo $this->itemDao->lastrevision->getUser()->getFullName()?></a></td>
        </tr>
        <tr> 
          <td>Revision</td>   
          <td><?php echo $this->itemDao->lastrevision->getRevision()?></td>
        </tr> 
        <tr>   
          <td><?php echo $this->t('File');?></td>
          <td><?php echo count($this->itemDao->lastrevision->getBitstreams())?></td> 
        </tr>
      </tbody>
    </table>
    <?php
    $path=$this->itemDao->getThumbnail();
    if(!empty($path)&&  file_exists(BASE_PATH.'/'.$path))
      {
      echo "
        <h1>{$this->t('Preview')}</h1>
        <img class='infoLogo' alt='' src='{$this->webroot}/{$path}'/>
        ";
      }
      ?>
  </div>
</div>




