<?php
/*=========================================================================
 Midas Server
 Copyright Kitware SAS, 26 rue Louis Guérin, 69100 Villeurbanne, France.
 All rights reserved.
 For more information visit http://www.kitware.com/.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

         http://www.apache.org/licenses/LICENSE-2.0.txt

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
=========================================================================*/

$this->headScript()->appendFile($this->coreWebroot.'/public/js/search/search.index.js');
?>
<link href="<?php echo $this->coreWebroot ?>/public/css/search/search.index.css" rel="stylesheet" type="text/css"/>
<div class="viewMain">
    <img class="searchLoading" alt="" src="<?php echo $this->coreWebroot ?>/public/images/icons/loading.gif"/>
    <ul id='searchResults'>

    </ul>
</div>
<div class="viewSideBar">
    <div class='sideElementFirst' id="resultTypeLinks">
        <ul>
            <li><a id="allResults">
                    <img alt='' src="<?php echo $this->coreWebroot ?>/public/images/FileTree/zip.png"/>
                    <?php echo $this->t('All results') ?>
                    (<?php echo $this->escape($this->nitems + $this->nusers + $this->nfolders + $this->ncommunities); ?>)</a>
            </li>
            <li><a id="itemResults">
                    <img alt='' src="<?php echo $this->coreWebroot ?>/public/images/FileTree/txt.png"/>
                    <?php echo $this->t('Items') ?>
                </a> (<?php echo $this->escape($this->nitems); ?>)
            </li>
            <li><a id="folderResults">
                    <img alt='' src="<?php echo $this->coreWebroot ?>/public/images/FileTree/directory.png"/>
                    <?php echo $this->t('Folders') ?>
                </a> (<?php echo $this->escape($this->nfolders); ?>)
            </li>
            <li><a id="communityResults">
                    <img alt='' src="<?php echo $this->coreWebroot ?>/public/images/icons/community.png"/>
                    <?php echo $this->t('Communities') ?>
                </a> (<?php echo $this->escape($this->ncommunities); ?>)
            </li>
            <li><a id="userResults">
                    <img alt='' src='<?php echo $this->coreWebroot ?>/public/images/icons/unknownUser-small.png'/>
                    <?php echo $this->t('Users') ?>
                </a> (<?php echo $this->escape($this->nusers); ?>)
            </li>
        </ul>
    </div>
    <div class="sideElementLast" id="sortTypeLinks">
        <h1><?php echo $this->t('Sort by') ?></h1>
        <ul>
            <li><a id="relevanceSort"><?php echo $this->t('Relevance') ?></a>
            </li>
            <li><a id="viewSort"><?php echo $this->t('Number of views') ?></a>
            </li>
            <li><a id="nameSort"><?php echo $this->t('Name') ?></a></li>
            <li><a id="dateSort"><?php echo $this->t('Date') ?></a></li>
        </ul>
    </div>
</div>
