<?php
/*=========================================================================
 MIDAS Server
 Copyright (c) Kitware SAS. 26 rue Louis Guérin. 69100 Villeurbanne, FRANCE
 All rights reserved.
 More information http://www.kitware.com

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

         http://www.apache.org/licenses/LICENSE-2.0.txt

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
=========================================================================*/
?>
<script type="text/javascript" src="<?php echo $this->coreWebroot?>/public/js/jquery/jquery.form.js" />
<script type="text/javascript" src="<?php echo $this->moduleWebroot?>/public/js/trend/trend.notify.js" />

<link type="text/css" rel="stylesheet" href="<?php echo $this->moduleWebroot?>/public/css/trend/trend.notify.css" />

<form id="thresholdNotifyForm" class="genericForm" method="POST" action="<?php echo $this->webroot?>/tracker/trend/notifysubmit">
  <div><input type="radio" id="noNotify" name="doNotify" value="no" />Do not send me emails for this trend</div>
  <div><input type="radio" id="yesNotify" name="doNotify" value="yes" />Send me an email alert</div>
  <div class="thresholdInfoContainer">
    When submitted value is
    <select name="operator" id="operatorSelect">
      <option value="&gt;">&gt;</option>
      <option value="&lt;">&lt;</option>
      <option value="&gt;=">&gt;=</option>
      <option value="&lt;=">&lt;=</option>
    </select>
    <input type="text" class="thresholdValue" name="value"
    <?php
    if($this->setting)
      {
      echo ' value="'.$this->setting->getValue().'"';
      }
    ?>
    />
  </div>
  <div class="registeredEmail">
  Registered email: <?php echo $this->userDao->getEmail(); ?>
  </div>
  <div class="bottomButtons">
    <input type="submit" value="Save" />
  </div>
  <input type="hidden" name="trendId" value="<?php echo $this->trend->getKey();?>" />
</form>

<div style="display: none;" id="settingInfo">
  <?php
  if($this->setting)
    {
    echo '{"id": "'.$this->setting->getKey().'", "value": '.$this->setting->getValue().', "operator": "'.$this->setting->getComparison().'"}';
    }
  ?>
</div>
