<?php
/*=========================================================================
 MIDAS Server
 Copyright (c) Kitware SAS. 26 rue Louis Guérin. 69100 Villeurbanne, FRANCE
 All rights reserved.
 More information http://www.kitware.com

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

         http://www.apache.org/licenses/LICENSE-2.0.txt

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
=========================================================================*/
?>
<html>
	<title>Midas Platform Visualization</title>

	<script type="text/javascript" src="<?php echo $this->moduleWebroot?>/public/js/webgl/Three.js"></script>
	<script type="text/javascript" src="<?php echo $this->moduleWebroot?>/public/js/webgl/Detector.js"></script>
	<script type="text/javascript" src="<?php echo $this->moduleWebroot?>/public/js/webgl/RequestAnimationFrame.js"></script>
	<script type="text/javascript" src="<?php echo $this->moduleWebroot?>/public/js/webgl/utils.js"></script>
  <script type="text/javascript" src="<?php echo $this->moduleWebroot?>/public/js/webgl/TrackballControlsMidas.js"></script>

  <?php
  echo '<script type="text/javascript" src="' . $this->coreWebroot . '/public/js/layout/jquery.js"></script>';
  echo '<script type="text/javascript" src="' . $this->coreWebroot . '/public/js/layout/jquery-ui.js"></script>';
  ?>
  <script type="text/javascript" src="<?php echo $this->moduleWebroot?>/public/js/webgl/webgl.index.js"></script>
  <link type="text/css" href="<?php echo $this->coreWebroot?>/public/css/layout/jquery-ui.min.css" rel="stylesheet" />
  <link type="text/css" href="<?php echo $this->moduleWebroot?>/public/css/webgl/webgl.index.css" rel="stylesheet" />
</head>

<body>

<button onclick="cameraUp();" id="buttonUp" class="buttonNav"></button>
<button onclick="cameraDown();" id="buttonDown" class="buttonNav"></button>
<button onclick="cameraLeft();" id="buttonLeft" class="buttonNav"></button>
<button onclick="cameraRight();" id="buttonRight" class="buttonNav"></button>
<button onclick="resetCameraPosition(objects3D);" id="buttonReset" class="buttonNav"></button>
<button onclick="zoomIn();" id="buttonPlus" class="buttonNav"></button>
<button onclick="zoomOut();" id="buttonMinus" class="buttonNav"></button>
<div id="info">
	<b>MOVE</b> mouse & press <b>LEFT button:</b> rotate, <b>MIDDLE button:</b> pan , <b>RIGHT button:</b> zoom
</div>

<div id="onliver" style="display:none">
	Over tooltip
</div>

<div id="axesContainer" >
</div>

<div id="container" ></div>

<div id="datacontent" style="display:none"><?php echo $this->data?></div>
</body>
</html>
