<?php
/*=========================================================================
MIDAS Server
Copyright (c) Kitware SAS. 20 rue de la Villette. All rights reserved.
69328 Lyon, FRANCE.

See Copyright.txt for details.
This software is distributed WITHOUT ANY WARRANTY; without even
the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE.  See the above copyright notices for more information.
=========================================================================*/

$this->headScript()->appendFile($this->moduleWebroot . '/public/js/executable/executable.define.js');

?>
<link type="text/css" rel="stylesheet" href="<?php echo $this->moduleWebroot?>/public/css/executable/executable.define.css" />
<div class="viewMain">
     <div class ="genericWrapperTopRight">
         <?php
          echo '<div style="float:right;margin-right:2px;" class="genericBigButton ">';
            echo "<a  href='{$this->webroot}/item/{$this->itemDao->getKey()}'><img style='float:left;margin-right:2px;' alt='' src='{$this->coreWebroot}/public/images/icons/back.png'/>";
            echo $this->t('Back');
            echo "</a>";
          echo '</div>';

        ?>
    </div>

    <?php
          echo '<div  class="genericBigButton ">';
            echo "<a id='addDefinitionLink' ><img style='float:left;margin-right:2px;' alt='' src='{$this->coreWebroot}/public/images/icons/add.png'/>";
            echo $this->t('Add Variable');
            echo "</a>";
          echo '</div>';

        ?>

      <?php
          echo '<div  class="genericBigButton ">';
            echo "<a id='saveDefinitionLink' ><img style='float:left;margin-right:2px;' alt='' src='{$this->coreWebroot}/public/images/icons/upload.png'/>";
            echo $this->t('Save');
            echo "</a>";
          echo '</div>';

        ?>
  <br/>
  <br/>
  <div id="tableContainer">
    <div class="column">


    </div>
  </div>
</div>

<div id="jsonMetadataContent"><?php echo $this->jsonMetadata?></div>








