<?php
/*=========================================================================
 MIDAS Server
 Copyright (c) Kitware SAS. 26 rue Louis Guérin. 69100 Villeurbanne, FRANCE
 All rights reserved.
 More information http://www.kitware.com

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

         http://www.apache.org/licenses/LICENSE-2.0.txt

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
=========================================================================*/

if ($this->isAjax) {
    echo '<script type="text/javascript" src="'.$this->moduleWebroot.'/public/js/executable/executable.define.js"></script>';
} else {
    $this->headScript()->appendFile($this->moduleWebroot.'/public/js/executable/executable.define.js');
}
?>
<link type="text/css" rel="stylesheet"
      href="<?php echo $this->moduleWebroot ?>/public/css/executable/executable.define.css"/>

<div class="viewMain">
    <div class="genericWrapperTopRight">
        <?php
        if (!$this->isAjax) {
            echo '<div style="float:right;margin-right:2px;" class="genericBigButton ">';
            echo "<a  href='{$this->webroot}/item/{$this->escape($this->itemDao->getKey(
            ))}'><img style='float:left;margin-right:2px;' alt='' src='{$this->coreWebroot}/public/images/icons/back.png'/>";
            echo $this->t('Back');
            echo "</a>";
            echo '</div>';
            echo '  <br/><br/>';
        }

        ?>
    </div>

    This page allow you to define the execution options of the item:
    <b><?php echo $this->escape($this->itemDao->getName()); ?></b>.<br/>These option are used to defined how the Midas Platform will use
    the item to create remote processing tasks.
    <br/>
    <br/>

    <div id="tableContainer">
        <div class="column">

        </div>
    </div>

    <?php
    echo '<div  class="genericBigButton ">';
    echo "<a id='addDefinitionLink'><img style='float:left;margin-right:2px;' alt='' src='{$this->coreWebroot}/public/images/icons/add.png'/>";
    echo $this->t('Add an Option');
    echo "</a>";
    echo '</div>';

    ?>

    <?php
    echo '<div  class="genericBigButton" qtip="On save, MIDAS adds a VXML file to the Item.">';
    echo "<a id='saveDefinitionLink'><img style='float:left;margin-right:2px;' alt='' src='{$this->coreWebroot}/public/images/icons/upload.png'/>";
    echo $this->t('Save');
    echo "</a>";
    echo '</div>';

    ?>
</div>

<div id="jsonMetadataContent"><?php echo $this->jsonMetadata ?></div>
<input type="hidden" id="itemIdExecutable" value="<?php echo $this->escape($this->itemDao->getKey()); ?>"/>
