<?php
  $this->headScript()->appendFile($this->webroot.'/public/js/feed/feed.index.js');
?>

<link href="<?php echo $this->webroot?>/public/css/feed/feed.index.css" rel="stylesheet" type="text/css" />

<div class="viewMain">
  <?php echo $this->element('feed')?>
</div>
<div class="viewSideBar">
  <div align="justify" class='sideElementFirst feedNotification'>
MIDAS integrates multimedia server technology with Kitware's open-source data analysis and visualization clients. The server follows open standards for data storage, access and harvesting.
  </div>
    <?php
  if(!empty($this->notifications))
    {
    echo   "<div class='sideElement feedNotification'>
              <h1>Notifications</h1>
            </div>";
    }
    ?>
  <?php 
  if(!empty($this->itemThumbnails))
    {
    echo '<div class="sideElement feedThumbnail">';
    echo '<h1>Thumbnails</h1>';
    foreach($this->itemThumbnails as $item)
      {
      echo "<a href='{$this->webroot}/item/{$item->getKey()}'>";
      echo "<img src='{$this->webroot}/{$item->getThumbnail()}' alt=''/>"; 
      echo "</a>";
      }
    echo '</div>';
    }
    ?>
  <div class="sideElementLast feedStats">
    <h1>Stats</h1>
    <?php
    echo "<ul>";
    echo "  <li>{$this->nUsers} user".(($this->nUsers>1)?'s':'')."</li>";
    echo "  <li>{$this->nCommunities} ".(($this->nCommunities>1)?'communities':'community')."</li>";
    echo "  <li>{$this->nItems} item".(($this->nItems>1)?'s':'')."</li>";
    echo "</ul>";
    ?>
  </div>
</div>




