<?php
/*=========================================================================
MIDAS Server
Copyright (c) Kitware SAS. 20 rue de la Villette. All rights reserved.
69328 Lyon, FRANCE.

See Copyright.txt for details.
This software is distributed WITHOUT ANY WARRANTY; without even
the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE.  See the above copyright notices for more information.
=========================================================================*/

$this->headScript()->appendFile($this->coreWebroot.'/public/js/feed/feed.index.js');
?>

<link href="<?php echo $this->coreWebroot?>/public/css/feed/feed.index.css" rel="stylesheet" type="text/css" />

<div class="viewMain">
  <?php echo $this->element('feed')?>
</div>
<div class="viewSideBar">

    <?php
  if(!empty($this->notifications))
    {
    echo   "<div class='sideElement feedNotification'>
              <h1>Notifications</h1>
            </div>";
    }
    ?>
  <?php 
  if(!empty($this->itemThumbnails))
    {
    echo '<div class="sideElementFirst feedThumbnail">';
    echo '<h1>Thumbnails</h1>';
    foreach($this->itemThumbnails as $item)
      {
      echo "<a href='{$this->webroot}/item/{$item->getKey()}'>";
      echo "<img qtip='".$item->getName()."' src='{$this->webroot}/{$item->getThumbnail()}' alt=''/>"; 
      echo "</a>";
      }
    echo '</div>';
    }
    ?>
  <div class="sideElementLast feedStats">
    <h1>Stats</h1>
    <?php
    echo "<ul>";
    echo "  <li>{$this->nUsers} {$this->t('user')}".(($this->nUsers>1)?'s':'')."</li>";
    echo "  <li>{$this->nCommunities} ".(($this->nCommunities>1)?"{$this->t('communities')}":"{$this->t('community')}")."</li>";
    echo "  <li>{$this->nItems} {$this->t('item')}".(($this->nItems>1)?'s':'')."</li>";
    echo "</ul>";
    ?>
  </div>
</div>




