<?php
/*=========================================================================
 MIDAS Server
 Copyright (c) Kitware SAS. 26 rue Louis Guérin. 69100 Villeurbanne, FRANCE
 All rights reserved.
 More information http://www.kitware.com

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

         http://www.apache.org/licenses/LICENSE-2.0.txt

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
=========================================================================*/

$this->headScript()->appendFile($this->coreWebroot.'/public/js/feed/feed.index.js');
?>

<link href="<?php echo $this->coreWebroot ?>/public/css/feed/feed.index.css" rel="stylesheet" type="text/css"/>

<div class="viewMain">
    <?php echo $this->element('feed') ?>
</div>
<div class="viewSideBar">

    <?php
    if (!empty($this->notifications)) {
        echo "<div class='sideElement feedNotification'>
              <h1>Notifications</h1>
            </div>";
    }
    ?>
    <?php
    if (!empty($this->itemThumbnails)) {
        echo '<div class="sideElementFirst feedThumbnail">';
        echo '<h1>Thumbnails</h1>';
        foreach ($this->itemThumbnails as $item) {
            echo "<a href='{$this->webroot}/item/{$item->getKey()}'>";
            echo "<img qtip='".$item->getName()."' src='{$this->webroot}/item/thumbnail?itemId={$item->getKey(
                )}' alt=''/>";
            echo "</a>";
        }
        echo '</div>';
    }
    ?>
    <div class="sideElementLast feedStats">
        <h1>Stats</h1>
        <?php
        echo "<ul>";
        echo "  <li>{$this->nUsers} {$this->t('user')}".(($this->nUsers > 1) ? 's' : '')."</li>";
        echo "  <li>{$this->nCommunities} ".(($this->nCommunities > 1) ? "{$this->t('communities')}" : "{$this->t(
                'community'
            )}")."</li>";
        echo "  <li>{$this->nItems} {$this->t('item')}".(($this->nItems > 1) ? 's' : '')."</li>";
        echo "</ul>";
        ?>
    </div>
</div>
