<?php
/*=========================================================================
 MIDAS Server
 Copyright (c) Kitware SAS. 26 rue Louis Guérin. 69100 Villeurbanne, FRANCE
 All rights reserved.
 More information http://www.kitware.com

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

         http://www.apache.org/licenses/LICENSE-2.0.txt

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
=========================================================================*/

$this->headScript()->appendFile($this->coreWebroot . '/public/js/jquery/jquery.form.js');
$this->headScript()->appendFile($this->moduleWebroot . '/public/js/config/config.index.js');
?>
<link type="text/css" rel="stylesheet" href="<?php echo $this->moduleWebroot?>/public/css/config/config.index.css" />
<link type="text/css" rel="stylesheet" href="<?php echo $this->coreWebroot?>/public/css/common/common.genericPage.css" />
<div class="viewMain">
     <div class ="genericWrapperTopRight">
         <?php
          echo '<div style="float:right;margin-right:2px;" class="genericBigButton ">';
            echo "<a  href='{$this->webroot}/admin#tabs-modules'><img style='float:left;margin-right:2px;' alt='' src='{$this->coreWebroot}/public/images/icons/back.png'/>";
            echo $this->t('Back');
            echo "</a>";
          echo '</div>';

        ?>
    </div>

    This module requires PIWIK.<br/>
    To install it: <a href="http://piwik.org/docs/installation/" target='_blank'>http://piwik.org/docs/installation/</a><br/><br/>
    This module requires an IPInfoDb API key.<br/>
    To get one, create an account at: <a href="http://www.ipinfodb.com/register.php" target='_blank'>http://www.ipinfodb.com/register.php</a><br/><br/>
    This module requires PHP curl to be enabled on the server.<br/><br/>
     <?php
      echo "
      <form class='genericForm' id='configForm' method='{$this->configForm['method']}'  action='{$this->configForm['action']}'>
      <h3>Statistics Module Configuration:</h3>
            <div>
              <label for='hachoir'>Piwik URL</label>
              {$this->configForm['piwikurl']}
            </div>
            <div>
              <label for='hachoir'>Piwik API Key</label>
              {$this->configForm['piwikapikey']}
            </div>
            <div>
              <label for='hachoir'>Piwik site ID</label>
              {$this->configForm['piwikid']}
            </div>
            <div>
              <label for='hachoir'>IPInfoDB API Key</label>
              {$this->configForm['ipinfodbapikey']}
            </div>
            <div>
              <label for='hachoir'>Send Daily Reports to the Administrators</label>
              {$this->configForm['report']}
            </div>
          <div>
            {$this->configForm['submitConfig']}
          </div>
       </form>";
       ?>

</div>
