<?php 
/*=========================================================================
MIDAS Server
Copyright (c) Kitware SAS. 20 rue de la Villette. All rights reserved.
69328 Lyon, FRANCE.

See Copyright.txt for details.
This software is distributed WITHOUT ANY WARRANTY; without even
the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE.  See the above copyright notices for more information.
=========================================================================*/

$this->headScript()->appendFile($this->coreWebroot . '/public/js/jquery/jquery.form.js');
$this->headScript()->appendFile($this->moduleWebroot . '/public/js/config/config.index.js');
?>
<link type="text/css" rel="stylesheet" href="<?php echo $this->moduleWebroot?>/public/css/config/config.index.css" />
<link type="text/css" rel="stylesheet" href="<?php echo $this->coreWebroot?>/public/css/common/common.genericPage.css" />

<div class="viewMain">

     <div class ="genericWrapperTopRight">
         <?php
          echo '<div style="float:right;margin-right:2px;" class="genericBigButton ">';
            echo "<a  href='{$this->webroot}/admin#tabs-modules'><img style='float:left;margin-right:2px;' alt='' src='{$this->coreWebroot}/public/images/icons/back.png'/>";
            echo $this->t('Back');  
            echo "</a>";
          echo '</div>';
          
        ?>
    </div>
     <?php
      echo "
      <form class='genericForm' id='configForm' method='{$this->configForm['method']}'  action='{$this->configForm['action']}'>
      <h3>Visualize Configuration:</h3>
            <div >
              <label for='customtmp'>Temp directory</label>
              {$this->configForm['customtmp']}<br/>
               (if empty: ".BASE_PATH."/tmp/visualize)<br/><br/>
            </div>
            <div >
              <label for='useparaview'>Use ParaviewWeb server</label>
              {$this->configForm['useparaview']}<br/><br/>
            </div>
            <div >
              <label for='userwebgl'>Enable Webgl</label>
              {$this->configForm['userwebgl']}<br/><br/>
            </div>
            <div >
              <label for='userwebgl'>Use Symlinks (instead of copying files. Only works with samba)</label>
              {$this->configForm['usesymlinks']}<br/><br/>
            </div>
            <div >
              <label for='userwebgl'>PWapp URL</label>
              {$this->configForm['pwapp']}<br/><br/>
            </div>
            <div >
              <label for='userwebgl'>pvbatch location</label>
              {$this->configForm['pvbatch']}<br/><br/>
            </div>
            <div >
              <label for='paraviewworkdir'>ParaviewWeb server Work Dir </label>
              {$this->configForm['paraviewworkdir']}
              <br/>
              (where the paraview server mount the Temp directory)
            </div>
          <div>
            {$this->configForm['submitConfig']}
          </div>
       </form>";
       ?>
    <br/>
    <br/>
    If you want to use symlinks. Please enable "follow symlinks" option in you samba configuration (smb.conf):
    <pre>
    [foo]
       comment = FooComment
       path = /foo
       public = yes
       writable =  no
       printable = no
       follow symlinks = yes
       guest ok = yes
       wide links = yes
       unix extensions = no
    </pre>
</div>






