<?php
/*=========================================================================
 MIDAS Server
 Copyright (c) Kitware SAS. 26 rue Louis Guérin. 69100 Villeurbanne, FRANCE
 All rights reserved.
 More information http://www.kitware.com

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

         http://www.apache.org/licenses/LICENSE-2.0.txt

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
=========================================================================*/

$this->headScript()->appendFile($this->coreWebroot . '/public/js/jquery/jquery.form.js');
$this->headScript()->appendFile($this->moduleWebroot . '/public/js/config/config.index.js');
?>
<link type="text/css" rel="stylesheet" href="<?php echo $this->moduleWebroot?>/public/css/config/config.index.css" />
<link type="text/css" rel="stylesheet" href="<?php echo $this->coreWebroot?>/public/css/common/common.genericPage.css" />

<div class="viewMain">

     <div class ="genericWrapperTopRight">
         <?php
          echo '<div style="float:right;margin-right:2px;" class="genericBigButton ">';
            echo "<a  href='{$this->webroot}/admin#tabs-modules'><img style='float:left;margin-right:2px;' alt='' src='{$this->coreWebroot}/public/images/icons/back.png'/>";
            echo $this->t('Back');
            echo "</a>";
          echo '</div>';

        ?>
    </div>
     <?php
      echo "
      <form class='genericForm' id='configForm' method='{$this->configForm['method']}'  action='{$this->configForm['action']}'>
      <h3>Visualize Configuration:</h3>
            <div >
              <label for='customtmp'>Temp directory</label>
              {$this->configForm['customtmp']}<br/><br/>
            </div>
            <div >
              <label for='useparaview'>Use ParaviewWeb server</label>
              {$this->configForm['useparaview']}<br/><br/>
            </div>
            <div >
              <label for='userwebgl'>Enable WebGL viewer</label>
              {$this->configForm['userwebgl']}<br/><br/>
            </div>
            <div >
              <label for='userwebgl'>Use symlinks instead of copying</label>
              {$this->configForm['usesymlinks']}<br/><br/>
            </div>
            <div >
              <label for='pwapp'>Tomcat Root URL</label>
              {$this->configForm['pwapp']}<br/><br/>
            </div>
            <div >
              <label for='pvbatch'>pvbatch executable location</label>
              {$this->configForm['pvbatch']}<br/><br/>
            </div>
            <div >
              <label for='paraviewworkdir'>ParaviewWeb server Work Dir </label>
              {$this->configForm['paraviewworkdir']}
              <br/><br/>
            </div>
          <div>
            {$this->configForm['submitConfig']}
          </div>
       </form>";
       ?>
<br/>
<p>
  <b>Important note:</b> If you use ParaViewWeb, you must use the Midas Apache server as a proxy for it to prevent
  cross-site scripting issues. Instructions to do so are <a href="http://www.paraview.org/Wiki/ParaViewWeb_with_Apache_as_front-end" target="blank">here</a>.
</p>
</div>
