<?php
/*=========================================================================
 MIDAS Server
 Copyright (c) Kitware SAS. 26 rue Louis Guérin. 69100 Villeurbanne, FRANCE
 All rights reserved.
 More information http://www.kitware.com

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

         http://www.apache.org/licenses/LICENSE-2.0.txt

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
=========================================================================*/

$this->headScript()->appendFile($this->coreWebroot . '/public/js/jquery/jquery.form.js');
$this->headScript()->appendFile($this->moduleWebroot . '/public/js/config/config.index.js');
?>
<link type="text/css" rel="stylesheet" href="<?php echo $this->moduleWebroot?>/public/css/config/config.index.css" />
<link type="text/css" rel="stylesheet" href="<?php echo $this->coreWebroot?>/public/css/common/common.genericPage.css" />
<div class="viewMain">
     <div class ="genericWrapperTopRight">
         <?php
          echo '<div style="float:right;margin-right:2px;" class="genericBigButton ">';
            echo "<a  href='{$this->webroot}/admin#tabs-modules'><img style='float:left;margin-right:2px;' alt='' src='{$this->coreWebroot}/public/images/icons/back.png'/>";
            echo $this->t('Back');
            echo "</a>";
          echo '</div>';

        ?>
    </div>
   <?= $this->t("Don't forget to set up the module. View the documentation from the Help link for more information.") ?>

   <?php
   if(!empty($this->jobs))
     {
     ?>
   <h3>Scheduled Tasks</h3>
   <table>
     <tr>
       <td>
         <b>Name</b>
       </td>
       <td>
         <b>Date</b>
       </td>
       <td>
         <b>Parameters (json)</b>
       </td>
       <td>
         <b>Action</b>
       </td>
     </tr>
     <?php
     foreach($this->jobs as $job)
       {
       ?>
     <tr>
       <td>
         <?php echo $job->getTask()?>
       </td>
       <td>
         <?php echo $job->getFireTime()?>
       </td>
       <td qtip='<?php echo str_replace("'", '"', $job->getParams())?>'>
         <?php echo substr($job->getParams(), 0, 30)?>
       </td>
       <td >
         <a href="<?php echo $this->webroot?>/scheduler/run?id=<?php echo $job->getKey()?>">Run Now</a>
       </td>
     </tr>
     <?
       }?>
   </table>
   <?php
     }
     ?>

      <?php
   if(!empty($this->jobsErrors))
     {
     ?>
   <h3>Last Failed Tasks</h3>
   <table>
     <tr>
       <td>
         <b>Name</b>
       </td>
       <td>
         <b>Date</b>
       </td>
       <td>
         <b>Parameters (json)</b>
       </td>
       <td>
         <b>Logs</b>
       </td>
     </tr>
     <?php
     foreach($this->jobsErrors as $job)
       {
       $logs = $job->getLogs();
       $logContent = '';
       foreach($logs as $log)
         {
         $logContent .= $log->getLog().'<br/>';
         }
       ?>
     <tr>
       <td>
         <?php echo $job->getTask()?>
       </td>
       <td>
         <?php echo $job->getFireTime()?>
       </td>
       <td qtip='<?php echo $job->getParams()?>'>
         <?php echo substr($job->getParams(), 0, 30)?>
       </td>
       <td qtip='<?php echo str_replace("'", '"', $logContent)?>'>
         <?php echo substr($logContent, 0, 30)?>
       </td>
     </tr>
     <?
       }?>
   </table>
   <?php
     }
     ?>

</div>
