<?php
/*=========================================================================
MIDAS Server
Copyright (c) Kitware SAS. 20 rue de la Villette. All rights reserved.
69328 Lyon, FRANCE.

See Copyright.txt for details.
This software is distributed WITHOUT ANY WARRANTY; without even
the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE.  See the above copyright notices for more information.
=========================================================================*/

$this->headScript()->appendFile($this->coreWebroot . '/public/js/jquery/jquery.form.js');
$this->headScript()->appendFile($this->apiWebroot.'/public/js/common/common.ajaxapi.js');
$this->headScript()->appendFile($this->moduleWebroot . '/public/js/config/config.index.js');
?>
<link type="text/css" rel="stylesheet" href="<?php echo $this->moduleWebroot?>/public/css/config/config.index.css" />
<link type="text/css" rel="stylesheet" href="<?php echo $this->coreWebroot?>/public/css/common/common.genericPage.css" />
<div class="viewMain">
     <div class ="genericWrapperTopRight">
         <?php
          echo '<div style="float:right;margin-right:2px;" class="genericBigButton ">';
            echo "<a  href='{$this->webroot}/admin#tabs-modules'><img style='float:left;margin-right:2px;' alt='' src='{$this->coreWebroot}/public/images/icons/back.png'/>";
            echo $this->t('Back');
            echo "</a>";
          echo '</div>';

        ?>
    </div>

    This module requires dcm2xml and storescp from <b>DCMTK</b> to receive DICOM files.<br/>
    To install it: <a href="http://support.dcmtk.org/wiki/dcmtk/howto/start" target="_blank">http://support.dcmtk.org/wiki/dcmtk/howto/start</a><br/><br/>

    This module requires <b>Pydas</b> to upload DICOM files.<br/>
    To install it: <a href="https://github.com/midasplatform/pydas/blob/master/docs/source/intro.rst" target="_blank">https://github.com/midasplatform/pydas/blob/master/docs/source/intro.rst</a><br/><br/>

    <?php
      echo "
      <form class='genericForm' id='configForm' method='{$this->configForm['method']}'  action='{$this->configForm['action']}'>
      <h3>DICOM Uploader Configuration:</h3>
            <div >
              <label for='dcm2xml'>Command to run dcm2xml</label>
              {$this->configForm['dcm2xml']}
            </div>
            <br />
            <div >
              <label for='storescp'>Command to run storescp</label>
              {$this->configForm['storescp']}
            </div >
            <div >
              <label for='storescp_port'>Storescp port</label>
              {$this->configForm['storescp_port']}
            </div >
            <div >
              <label for='storescp_study_timeout'>Storescp study timeout</label>
              {$this->configForm['storescp_study_timeout']}
            </div >
            <br />
            <div id='receptiondir'>
              <label for='receptiondir'>Uploader reception directory</label>
              {$this->configForm['receptiondir']}
            </div>
            <br />
            <div id='pydas_dest_folder'>
              <label for='receptiondir'>Pydas destination folder</label>
              {$this->configForm['pydas_dest_folder']}
            </div>
          <div>
            {$this->configForm['submitConfig']}
          </div>
       </form>";
       ?>
    <br/>
    Check dashboard to verify your current configuration.



    <br/>

</div>
