<?php  
/*=========================================================================
MIDAS Server
Copyright (c) Kitware SAS. 20 rue de la Villette. All rights reserved.
69328 Lyon, FRANCE.

See Copyright.txt for details.
This software is distributed WITHOUT ANY WARRANTY; without even
the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE.  See the above copyright notices for more information.
=========================================================================*/
?>
<link type="text/css" rel="stylesheet" href="<?php echo $this->moduleWebroot?>/public/css/media/media.index.css" />
<link type="text/css" rel="stylesheet" href="<?php echo $this->moduleWebroot?>/public/css/jquery/jquery.player/jplayer.blue.monday.css" />

<?php
echo '<script type="text/javascript" src="' . $this->coreWebroot . '/public/js/layout/jquery.js"></script>';
$this->headScript()->appendFile($this->moduleWebroot . '/public/js/jquery/jquery.jplayer.min.js');
$this->headScript()->appendFile($this->moduleWebroot . '/public/js/media/media.index.js');
?>

    
   <div class="jp-video jp-video-360p">
			<div class="jp-type-single">
				<div id="jquery_jplayer_1" class="jp-jplayer"></div>
				<div id="jp_interface_1" class="jp-interface">
					<div class="jp-video-play"></div>
					<ul class="jp-controls">
						<li><a href="#" class="jp-play" tabindex="1">play</a></li>
						<li><a href="#" class="jp-pause" tabindex="1">pause</a></li>
						<li><a href="#" class="jp-stop" tabindex="1">stop</a></li>
						<li><a href="#" class="jp-mute" tabindex="1">mute</a></li>
						<li><a href="#" class="jp-unmute" tabindex="1">unmute</a></li>
					</ul>
					<div class="jp-progress">
						<div class="jp-seek-bar">
							<div class="jp-play-bar"></div>
						</div>
					</div>
					<div class="jp-volume-bar">
						<div class="jp-volume-bar-value"></div>
					</div>
					<div class="jp-current-time"></div>
					<div class="jp-duration"></div>
				</div>
				<div id="jp_playlist_1" class="jp-playlist">

				</div>
			</div>
		</div>
   
<?php echo $this->headScript() ?>
<div style="display: none;" class="jsonContent">
  <?php echo $this->json?>
</div>
