<?php
/*=========================================================================
 Midas Server
 Copyright Kitware SAS, 26 rue Louis Guérin, 69100 Villeurbanne, France.
 All rights reserved.
 For more information visit http://www.kitware.com/.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

         http://www.apache.org/licenses/LICENSE-2.0.txt

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
=========================================================================*/

$this->declareVars('form', 'pageTitle');
$this->headTitle($this->escape($this->pageTitle));
?>

<div class="viewMain">
    <h1><?php echo $this->escape($this->pageTitle); ?></h1>
    <p>
        If you would like to use this module for extracting zip archives over 2 GB in size, you will need to enter an
        executable unzip command here that will be used for large zip archives because PHP does not support opening zip
        archives over 2 GB in size.
    </p>
    <p>
        The command should be the same as that you would call on the command line to unzip an archive. In the place
        where you would put the path of the file to unzip on the command line, instead put <i>%zip</i>. This will be
        substituted to the actual path of the zip file. If the command also requires an unzip directory to be
        explicitly specified, rather than using the current working directory, add <i>%dir</i> to the command where the
        output directory should be specified. Do not put quotes around the <i>%zip</i> or <i>%dir</i> arguments.
    </p>
    <p>
        This module will still be able to extract zip files under 2 GB in size if you leave the unzip command blank.
    </p>
    <?php echo $this->form; ?>
    <p><a href="<?php echo $this->url(array('controller' => 'admin', 'action' => 'index'), 'default'); ?>#tabs-modules">&laquo; Back to Modules Administration</a></p>
</div>
